### ISSUE TITLE
Odds and Evens odd prompt exception changes and the Five odd Ejection

### ISSUE THREAD

**Issue by Stuurrm** [hanabi/hanabi.github.io#1007]
Changing how known 3s work with prompts in odds and evens to prompting them over playing finesse and over playing any other card with an odd clue on them:

The Odd Prompt Rank Exception states that cards with an odd clue on them are not prompted because they could be an unplayble 5.

However if an odd card was the focus of a single bluff when there were no one-away-from-playable 5s that card will be marked as a 3. Thefore it doesn't make sense to apply that exception to those cards.

Reasoning for playing specifically a known 3 to a prompt.
1. They should not play finesse as prompts come before finesses and it doesn't make sense to apply the exception to known 3s.
2. They should not prompt other possible cards with an odd clue on them to the left of the known 3 as the exception still applies to them.

Example:
https://hanab.live/replay/854594#1
t.1 & 2: An odd clue focusing chop was given to asealr and it got a slot 1 blind play. Therefore this was a 3 bluff and the focused card got marked as such.
t.12: Asealr gets prompted for a b3. They should play their known 3 over their other clued odd cards.

Changing the wording on the Odd Prompt Rank Exception to exclude cards with a color clue on them:

Currently by the wording of the Odd Prompt Rank Exception a card that was previously promptable because it had a color clue on it becomes unpromtable after it receives an odd clue. It very much is beneficial to still be able to prompt these after they receive an odd clue.

Five odd Ejection:

When an odd clue focuses a two-away-from-playable 5 as a play clue it asks the next player to play second finesse position to tell the clue receiver their clued card was a 5.

This follows from same logic as the 5ce and from signal shifting.

In odds and evens very often a problem for the team is unfocusable cards. Because of this a different ejection is very much appreciated and the sacrifice of double bluff targets and potential finesses is worth it. This allows the team to do ejections when a color to the said 5 was blocked or when an odd clue picked up extra cards.

**Comment by newduke** [comment]
+1

**Comment by Zamiell** [comment]
can you submit a pr
