### ISSUE TITLE
Unnecessary Moves with Unknown Trash Off Chop --> Chop Move (Ex.3)

### ISSUE THREAD

**Issue by chennisden** [hanabi/hanabi.github.io#1011]
[Relevant example.](https://hanabi.github.io/docs/level-23#example-3---an-unnecessary-unknown-trash-discharge-with-a-bad-chop-move-ejection)

> All the 2's are played on the stacks.

> Bob sees that this is an Unknown Trash Discharge. He plays his Third Finesse Position. It is a blue 2 and it successfully plays.

These two bullet points contradict each other.

**Comment by Zamiell** [comment]
can you submit a pr

**Comment by chennisden** [comment]
done

**Comment by Zamiell** [comment]
thank you sir
