### ISSUE TITLE
Do we need the Dual-Color 3 Suits conventions page?

### ISSUE THREAD

**Issue by chennisden** [hanabi/hanabi.github.io#1013]
- For vanilla dual-color 3 suits, there is something terribly wrong if you cannot figure out you can invert
- why would you ever play dual-color 3 suits
- when you have 3 dual-color suits, say *Dual-Color + Black (4 Suits)*, inverting does not generalize so cleanly (and is not a good idea).
 
I also think the entire variant is [redundant](https://github.com/Hanabi-Live/hanabi-live/issues/2655)

**Comment by pianoblook** [comment]
> there is something terribly wrong if you cannot figure out you can invert

dang you must be fun at parties

I see no reason to delete the page, or the variant. It's a cute easter egg for those who stumble upon it, especially if they naturally decide to invert.

**Comment by chennisden** [comment]
ok, the first two points are clearly facetious, so i guess i'll state them more seriously.

dual color 3 suit is not pointless when added with other stuff --- black, white, rainbow, even dual color special mix. it's just that 3 suit dual color itself is equivalent to, well, 3 suit

> It's a cute easter egg for those who stumble upon it, **especially if they naturally decide to invert**

yeah, and i think it might be more fun if people found it themselves (instead of likely discovering the variant by seeing the variants conventions). if that's the argument, wouldn't the page be counterproductive towards this?

i mean, sure, this variant and the page existing doesn't make a difference, but considering that Rainbow & Prism (3 Suits) etc are being deleted, wouldn't it make sense to apply the same standard

**Comment by sjdrodge** [comment]
By the way, inverting the clues technically does not render this variant isomorphic to 3 suit. If a player holds all cards of the same suit, then you cannot give the inverted clue without Empty Clues enabled. :D

**Comment by Zamiell** [comment]
long term this won't be an official variant, but you will be able to manually construct it.
for now it sounds like we should keep the convention page
