### ISSUE TITLE
Convention Rework: 5 Pull Tech (5NE and potentially 5NC)

### ISSUE THREAD

**Issue by pianoblook** [hanabi/hanabi.github.io#1015]
TIL I never actually proposed this formally, so here it goes: I say it's high time to modernize 5NDs, using [Precision 5 Tech](https://docs.google.com/document/d/1idE_9n0y34B8-4BGJCtrAqF47pLi7s9sNOQ3UpDUWv8/edit#heading=h.nfoajojqmjv).

There are two ways we could do it, and I'm open to either. Both are logically consistent & intuitive with all our other conventions - one is just *simpler*, at the cost of being a little less informative.
### (a) **FULL** Precision 5-Tech
> *Finesse* if the pulled card is 1-away.
> *Eject* if the pulled card is 2-away.
> *Discharge* if the pulled card is trash.
> *Charm* if the pulled card is 3+-away (usually this works as a _4 Charm_, except for with Null & Brown which could sometimes be 4 or 5).
> The Pulled card should either be [cm]'d or marked [kt], and complete notes should be written.

### (b) 5NE vs 5ND
> *Finesse* if the pulled card is 1-away.
> *Eject* if the pulled card is 2 or more away.
> *Discharge* if the pulled card is trash.
> The Pulled card should either be [cm]'d or marked [kt].

-------

5NE is a pretty old idea. To my knowledge it didn't make the cut in the past because of two reasonable critiques: 
(a) Often you can just 5CE if you want an Ejection instead of Discharge.
(b) H-Group has a dearth of Discharge opportunities in the early game, since Unknown Trash is hard to come by.

Both are fair enough, but I argue the benefits outweigh those concerns:
- This can now be an easy 3-for-1, and helps proactively CM useful 3s and 4s.
- The amount of additional information on the _Pulled_ card is a huge upgrade, compared to needing to have no idea if it's a good card or trash.
- 5CEs can be blocked, and/or can deplete the team's ability to 'use' that 5 clue later to CM the good card to its right.
- UDDs are commonplace now, which at least mitigates the Discharge shortage.
- Just sayin', P5T synergizes really well with Dawn, if that ever is adopted.

**EDIT**: I forgot another huge benefit: if it *DOES* cause a Discharge, this provides [kt] which we all know is busted af (allowing for free sdcms/tocms, protecting Cathy's chop, free Dumptrucks, etc)

**Comment by pianoblook** [comment]
I just want to point out how clean the logic is, btw: Instead of just "discharging because it's WEIRD", the logic becomes clear and intuitive: "the *5 Pulled* card is being given a *Play* signal." 
- So if it's 1-away, just a normal Finesse (usually _Promised_)
- 2-away, it follows the same logic as 5CEs: "Bob shouldn't assume he would have to make multiple consecutive blind-plays"
- unknown trash? well now *that's* a proper Discharge.
- 3-away (4) = 4 Charms are already common

**Comment by GuolinM** [comment]
Do you feel like there's additional bookkeeping required with these? I.e. with something like a 4 charm with rank you just have to notate 4 and eliminate any non 3-away colors at a glance, but when a card came be "2-away" I'm assuming you'd want to figure out what that means for every single color, and write out each rank individually.

**Comment by pianoblook** [comment]
> Do you feel like there's additional bookkeeping required with these?

Depends on which version we go with. It's obviously always beneficial to keep notes, but I think as a community we generally don't expect *perfect* notes. For example in traditional/current 5NDs, we *DO* expect everyone at least mark that the pulled card is "[≥2 away or trash]".

Here's an example of notes I'd expect to be taken, depending on the arrangement:

> No Variant, 3p. r1 & g1 have been played
> On turn 6, Alice clues 5 to Cathy's slot 1, which Bob sees is a *Pull*.
> Bob *Ejects*.

**Simpler Version (E vs D)**: Everyone just writes, `t6 [CM] as any ≥2-away [34]'

**Precision Version (E-D-C)**: Everyone writes, 't6 [CM] as 2-away]'. Unless it's a super casual game, I'd also expect Cathy to write out the options: 't6 [CM] [rg4,ybp3]'

**Comment by Zamiell** [comment]
seems fine to me, which formulation do you prefer

**Comment by pianoblook** [comment]
Happy to go with whichever way feels right to others. My gut feeling is that the added specificity of the 4Cs aren't worth the extra mental overhead. 

"Eject for 2-away, Discharge for unknown trash" is a tried and true concept, so that would be the safe + clean option.
