### ISSUE TITLE
Bomb Double Ignition

### ISSUE THREAD

**Issue by pianoblook** [hanabi/hanabi.github.io#1019]
Long ago, a pioneering convention called _The Distributed Dump Truck_ was created. It came and went, but was revived & remodeled by KPP as a form of _Double Ignition_. Memes aside, we have had immense success with them, particularly in efficiency-demanding variants like tournaments and Clue Starved.

The following is a revised, safer version of the beloved Dump Truck, that **only** uses _Known Trash_. This way, (a) the intention is a lot harder to miss, and (b) it runs zero risk of accidentally losing a good card (instead of the old school 'bomb chop' method)

-------
- A common tactic in advanced Hanabi is giving a _Useless Clue_ that actually gets two cards to blind-play.
- Let's evaluate the logic behind these _Useless Clue Double Ignitions_: Alice is **clearly throwing a clue away**, in a position where everyone can see that she clearly had (at least) one more logical action to perform. Therefore, she must be calling for something Special.
- It turns out there's another kind of situation that fits that exact same logic: **bombing a Known Trash** instead of discarding it.

### Known Trash Dump Truck Double Ignition

- If Alice bombs globally _Known Trash_, this must mean something very special.
- In addition to needlessly causing a Strike, this is obviously an absurd action because she always could have simply discarded it to generate a clue for the team.
- In fact, this is essentially the exact same logic as in _Useless Clues_. To directly rephrase it from above:
> Alice is **clearly throwing a clue away**, in a position where everyone can see that she clearly had (at least) one more logical action to perform. Therefore, she must be calling for something Special.
- We agree that this signals a _Double Ignition_, following the same guidelines (i.e. usually Bob is meant to respond, and the second respondent is usually the last acting person if no one else demonstrates the second blind-play.)

------
While I'm at it, might as well suggest the _Known Trash Dumpster Fire_ as well.

### Known Trash Dumpster Fire (Blazing Dump Truck)

- What if Alice performs what looks like a _Dump Truck Double Ignition_, but Bob can see that no other teammates hold a playable on _First Finesse Position_?
- If Bob were to just play his own _First Finesse_, this will lead to disaster: Cathy will assume she has a play as well.
- What if, though, Bob sees that another teammate *does* have a playable, just deeper in their hand?
- In this case, Bob can trust that Alice is performing a _Dumpster Fire_ (aka a _Blazing Dump Truck_).
- Bob is expected to blind-play the **matching Finesse Position** of the other visible playable.
- In cases where multiple playables are visible, Bob should assume it's the **shallowest** card (i.e. the closest to _First Finesse_).

In-Game Examples (I can dig up plenty more if you want lol)

Clued KT Form:
https://hanab.live/replay/860044#29
< more to come >

Contextual/Stale Chop Form:
https://hanab.live/replay/531393#43
https://hanab.live/replay/538404#22
https://hanab.live/replay/589121#38
https://hanab.live/replay/606754#47
https://hanab.live/replay/858914#37
https://hanab.live/replay/860608#42
https://hanab.live/replay/828451#28

Dumpster Fire:
https://hanab.live/replay/511091#33
https://hanab.live/replay/587770#35
https://hanab.live/replay/855303#29

**Comment by Zamiell** [comment]
firstly, i have some problems with the naming.

that aside, i feel like causing a bomb should probably get 3 or more blind plays.
if we configured the conventions this way, it would be a nice logical separation from the other kinds of *Double Ignition*.

in other words:
useless clue --> 2 blind plays as *Double Ignition*
bombing trash --> 3 blind plays as *Triple Ignition*

**Comment by Zamiell** [comment]
perhaps another formulation (in keeping with how the old DDT worked) is that it should cause N blind plays, where N is equal to the number of players at the table minus 1 (its minus 1 for the person giving the clue)

**Comment by piper0** [comment]
> i feel like causing a bomb should probably get 3 or more blind plays.

This suggests that you feel that spending a bomb is worse or more extreme than spending a clue token. I mostly disagree! 

Both options expend a clue. Spending a clue token removes a clue from your immediately available clues. Spending a bomb removes a clue from your total longterm bank of available clues. In most cases, the former is far more detrimental. 

Another handy feature of bombs is that you can spend them _even when you're out of clue tokens_. 

Bombs really do mostly feel like _Better Clue Tokens_.

The only real advantage that I see for clue tokens over bombs is that spending bombs reduces your margin for error – what if you want to use one of those bombs as a whoopsie token later?

But I don't know... just don't make mistakes. :wink:

(I suppose there's also the danger that you'll inadvertently bomb something useful, but this really shouldn't be an issue if you're taking discard modulation seriously and really making an effort to provide known trash to your friends.)

**Comment by Zamiell** [comment]
i agree that bombs can be used while at 0 clue tokens, but your analysis seems more theoretical than practical.
personally, most of my pickup games (which are a good mix of lower-level and expert) involve either getting 3 strikes, or finishing a game with 2 strikes (which seems to happen regardless of the skill level of the players involved)

**Comment by piper0** [comment]
Acknowledged that whoopsie tokens are more valuable in pickup games, in which you don't know your teammates' play styles as well. Being unfamiliar with your teammates may also impact how comfy you can feel about your chop.

At two strikes, I assume all players begin playing much more carefully. With that in mind, I don't necessarily think that two strikes is _that_ much more dangerous of a game state than zero strikes. If you disagree, we could maybe disallow them at one strike, but that seems complicated. 🤷‍♀️ 

FWIW, I definitely think _Dump Trucks_ and _Dumpster Fires_ should be very high level conventions if they're accepted. Whoopsie tokens are pretty important while you're still learning to navigate new tech, and you can feel much more confident about the trashiness of your chop when your teammates have the required conventional knowledge and game savvy to keep useful cards safe.

**Comment by pianoblook** [comment]
expecting 3 blind-plays definitely drops its overall utility, but you're right that pickup games bomb out a bunch already. 

And sadly, in my experience being at 2 strikes already doesn't seem to be much of a deterrent to most pickup games 💀 I mean, every game that strikes out must have first gotten to 2 strikes first, lol, before someone feels the urge to #yolo the third one, so... it's tough.

A cute compromise, actually, could be to technically define it as 2 blind-plays, *BUT* to add an _Unnecessary_ Form: 
> "if Donald can see that the two cards Alice got from her Dumptruck **could** have been cleanly gotten through a different clue (i.e. a 'normal' double ignition or trash clue, without resorting to causing a strike), Alice was actually expecting a 3rd _Ignition_."

That solves a few issues you both raised:
- Encourages Alices to not resort to them in pickup games without excellent reason
- Cleanly allows the _Double_ form while at zero clues
- Keeps its theoretical integrity as a 2-for-1 at heart (as in, I like that it would stay theoretically sound to say, "Dumptrucks shouldn't be considered _Unnecessary_ while playing in very high trust/high performance games such as tournaments."

**Comment by Zamiell** [comment]
### Bomb Double Ignition

- Normally, when a player has a globally-known trash card in their hand, they can safely discard it.
- In rare cases, a player might decide to intentionally misplay the trash card as a means of communicating a particular slot number as a _Positional Misplay_. This kind of thing almost always happens on either the last round of the game, or the second to last round of the game.
- However, what if a player intentionally misplays a trash card before that point? Wasting a bomb for no reason is "useless" or "pointless" in much the same way that the kinds of clues that cause _Double Ignition_ are. Thus, we define bombing a card in this way should trigger two blind-plays as a _Double Ignition_.

### Bomb Triple Ignition

- Using a clue instead of using a strike is almost always preferable. Thus, players should prefer to use the more-ordinary forms of _Double Ignition_ (like e.g. _Replay Double Ignition_) before doing a _Bomb Double Ignition_.
- If the team can see that a player who initiated a _Bomb Double Ignition_ could have obviously used a more-ordinary form of _Double Ignition_, then this signals an extra message: a _Triple Ignition_.

**Comment by iamwhoiamhahaha** [comment]
Interesting convention. I personally usually do a *Bomb Chop Double Ignition* in the end game while playing in a hypo with myself. It's very useful finishing the game faster lol

**Comment by pianoblook** [comment]
> Interesting convention. I personally usually do a _Bomb Chop Double Ignition_ in the end game while playing in a hypo with myself. It's very useful finishing the game faster lol

Would this be for CMing one player twice, or Bob+Cathy once?

lol I've been wanting to start using _Ambulances_ in KPP, which would be the CM form of the Dumptruck (e.g. if Bob sees it can't be any sort of Ignition, it's a double CM instead.)

**Comment by iamwhoiamhahaha** [comment]
> Would this be for CMing one player twice, or Bob+Cathy once?

We don't chop move things in the end game. Double Ignition takes precedence. It is just my private meme convention
