### ISSUE TITLE
Convention Simplification: Trash Bluff Unnecessary Assumption

### ISSUE THREAD

**Issue by pianoblook** [hanabi/hanabi.github.io#1032]
Zam and I briefly discussed this a few weeks ago, but I forgot about it until earlier today - woops! 

Currently it's often impossible for Bob to know whether or not a _Trash Bluff_ will end up CMing the clue receiver. This desync can lead to headaches - and even bombs. This remains true, and can even get more chaotic, amongst experts, when it becomes a 'leveling game' where everyone needs to start scrolling back through the replay to determine whether or not Bob **should** be able to piece together the truth one way or the other... It's a mess.

So anyway, below is the _Unnecessary Assumption_ Principle, taken from this [doc](https://docs.google.com/document/d/1dLGcc1iZ_NrxC2rcHDlM6pH_Qna_FrIF8zXMJk2nZGw/edit#heading=h.6t144y14pc2m). We've been playing with this for over a year now, and it's been a HUGE help. Simple and powerful.

----------

## Trash Bluff Unnecessary Assumption 

- When a _Trash Bluff_ is performed, we agree that Bob should always assume that Cathy will respond as if it was an [Unnecessary Move](https://hanabi.github.io/docs/level-25/).
- Therefore, if Bob sees that this _Unnecessary_ interpretation would lead to a clearly undesirable outcome, he can know that he’s actually being called to [Signal Shift](https://hanabi.github.io/docs/extras/signal-shifting/) appropriately.
> - If the Unnecessary component would lead to Bad CM, Bob must Eject.
> - If it would lead to an impossible _Trash Push_, Bob must either _Eject_ (as a _TPE_) or _Discharge_ (as a _TPD_).
- Notice how Bob’s Ejection or Discharge **still serves the same purpose as a standard _Finesse_**: the fact that he responds with **any** blind-play immediately identifies the clued card(s) as trash.

NOTE: If multiple 1s are clued, [Junk Discharge](https://hanabi.github.io/docs/extras/discharges/#the-junk-discharge-for-1s) takes precedence unless the unfocused 1 is clearly stale. In Pink variants, [Turnabout Ejection](https://hanabi.github.io/docs/variant-specific/pink#the-turnabout-ejection-for-1s-and-5s) also takes precedence.

### Implications for Cathy
- Since Bob’s response to all Trash Bluffs are now already determined by the nature of the _Unnecessary_ component, it doesn’t actually matter whether or not it actually **was** _Necessary_.
> - Therefore even when a _Necessary Trash Bluff_ occurs, Cathy should still Chop Move (if off-chop) or Trash Push (if on-chop).
- If an Ejection or Discharge does occur, note that Cathy may still be expected to Trash Push, if the trash clue in and of itself was an Unnecessary way to get Bob’s card. [See [Unnecessary Trash Extensions](https://docs.google.com/document/d/1dLGcc1iZ_NrxC2rcHDlM6pH_Qna_FrIF8zXMJk2nZGw/edit#heading=h.r82lc8ijg4nf) below.]

### REASONING: 
Necessary Trash Finesses are very rare, particularly in a world with so many other ways to get cards blind-played. Even in cases where it truly is impossible to get at the moment, it’s still almost never a big deal to just clue/Eject/Discharge it on a later turn. The benefits, on the other hand, are wide and numerous. It erases the annoying desync of whether or not a TCM has occurred; it provides a lot more flexibility to the team; it gives more TOCM opportunities; and it gives a lot of extra Ejection and Discharge opportunities even before all 1s have been played.

**Comment by Zamiell** [comment]
wasn't there an issue for this already in the past?
or am i misremembering

**Comment by pianoblook** [comment]
I thought there was too, back in the #479 post, but I was wrong. Couldn't find any other reference to it, so figured I'd just post it now

**Comment by J-Fricke** [comment]
I find necessary trash finesses often actually. I think it would be better to make trash finesse/bluff default to CM and when introducing the necessary/unnecessary component to then add in when it's not a CM. I think this learning state is better for parity in learners as the CM is desired most of the time when the trash finesse/bluff was given in my experience.

**Comment by pianoblook** [comment]
- Yes @ trash finesse or trash bluff, since they're functionally the same.

- No @ UTDs, though, since Bob couldn't immediately demonstrate _Unnecessariness_ in that case, unlike in _Finesse_ responses. Well unless you wanted to use a [_Slide_](https://docs.google.com/document/d/1Vq0OuPsIApvQmmRjY1jiDWtWLPW0LHxcwXjHsEE5J1A/edit#heading=h.id6uf5mwgatm) mechanic and have Bob _Charm_ as a _UUTDBCMC_, but that sounds unreasonably complicated IMO. As I mentioned in the OP:

> Notice how Bob’s _Ejection_ or _Discharge_ still serves the same purpose as a standard _Finesse_: the fact that he responds with any blind-play immediately identifies the clued card(s) as trash.

@J-Fricke Sure they *could* happen not too uncommonly, but how often do you actually feel *forced* to do them? I'd say maybe 1:500 games for me, since it really takes a rare alignment of negative factors to actually make it the **best** clue to perform. Here are a couple more points I'll add:

1. You can usually just wait: just wait to Eject or Discharge the card in the near future. Or just have the team keep cluing+playing normally and see if a normal _Bluff_ opportunity arises.
2. But sure even when Bob's chop is precarious, a direct clue is blocked, *and* waiting isn't a safe option (which is an extremely rare combination of circumstances), you can still just clue it directly and _Fix_ the bad-touch later. And heck, that'll still end up relieving more pressure from Bob's chop anyway, compared to the 'emergency' trash move lol.

**Comment by Zamiell** [comment]
oh i see.

in general, i like that this proposal removes async information, and i dislike that UUTD continues to contain async information (i.e. it is either a UTD or a UUTDCM, and nobody knows).

maybe we should make UTD always UUTDCM, or we should make UTD never UUTDCM.

**Comment by pianoblook** [comment]
> in general, i like that this proposal removes async information, and i dislike that UUTD continues to contain async information (i.e. it is either a UTD or a UUTDCM, and Bob has no idea).

Yeaaah that is a trickier issue, I dunno how to handle that. It's extra messy because 3rd-finesse spot actually *IS* a lot harder to get, lol (mostly due to less Bluffs & Ignitions, but also since slot 3 is just the hardest slot to focus).

The desync is still annoying for sure though. ¯\_(ツ)_/¯

**Comment by Zamiell** [comment]
can you submit a pr

**Comment by pianoblook** [comment]
Oh, should this be in lvl 25 or Extras?

**Comment by Zamiell** [comment]
probably 14

**Comment by pianoblook** [comment]
I wouldn't be opposed to that, actually, though that would be a pretty radical shift right? Since currently Unnecessary stuff isn't introduced until lvl 25.

**Comment by Zamiell** [comment]
well i think it should just always chop move at level 14

**Comment by pianoblook** [comment]
Another concern would be that Bob wouldn't have access to BCME before max level either. 
Without a way to differentiate, I don't see this change being positive overall.

**Comment by Zamiell** [comment]
i don't think its that complicated, 0 for 1 chop moves would trigger BCME, with 5 save counting as a 0 for 1 as an exception

**Comment by Zamiell** [comment]
status on this?

**Comment by iamwhoiamhahaha** [comment]
does it apply to the variants that usually have blockers like brown and pink?

**Comment by Zamiell** [comment]
i guess i'll do this myself since pianoblook seems not answering

**Comment by Zamiell** [comment]
### Trash Finesses and Trash Bluffs Are Always Unnecessary

- As explained in the previous section, tricky moves can either be _necessary_ or _unnecessary_.
- However, we explicitly agree that _Trash Finesses_ and _Trash Bluffs_ are always treated as being _unnecessary_, regardless of whether it was actually possible to "get" the blind-played card with a normal clue.
- The reason for this special status is to simplify thing a little bit, as _Trash Finesses_ and _Trash Bluffs_ are really common, and it can be a real pain to figure out whether they are actually _necessary_ or not.
