### ISSUE TITLE
delete LPC exception for early game

### ISSUE THREAD

**Issue by Zamiell** [hanabi/hanabi.github.io#1034]
leads to confusion / losses

**Comment by pianoblook** [comment]
Counter suggestion: delete LPCS altogether (outside of brown vars)

**Comment by Zamiell** [comment]
i suspect that might not be a popular decision, as LPC is very commonly used in hard variants

**Comment by iamwhoiamhahaha** [comment]
> Counter suggestion: delete LPCs altogether (outside of brown vars)
1. Increase the required efficiency for hard variants and do not delete LPCs
2. Add a new section for "Very Hard" variants and move LPCs to it
https://github.com/hanabi/hanabi.github.io/issues/880

Reasons: We don't care about BDRs in a variant with extremely high required efficiency

**Comment by Zamiell** [comment]
one of the goals of this issue is to simplify the conventions by deleting an exception, resulting in less total things for people to remember.
splitting the easy/hard variant dichotomy into easy/hard/veryhard runs very counter to that goal.

**Comment by iamwhoiamhahaha** [comment]
the reason why piano proposed to delete LPCs entirely is because of BDRs (for better discard modulation)
we also discussed to delete OPCs in the early game as well
<https://discord.com/channels/140016142600241152/776176933120507964/1034252565459771392>

**Comment by pianoblook** [comment]
> one of the goals of this issue is to simplify the conventions by deleting an exception, resulting in less total things for 

Wouldn't you say LPCs are *already* an exception to a convention (to the Save Principle)? If you want to simplify things, just let people save cards without needing to worry about whether or not it counts as a valid Stalling situation vs Loaded.

**Comment by Zamiell** [comment]
i agree with you that deleting LPC is "more" of a deletion than deleting an exception to LPC, and thus accomplishes my overall goal better.

however, deleting LPC
> might not be a popular decision, as LPC is very commonly used in hard variants

**Comment by argothiel** [comment]
LPC exception should be kept for white, brown, muddy etc. (no LPC in early game).
LPC exception should be removed for hard variants (no early saves in early game).

**Comment by argothiel** [comment]
> Counter suggestion: delete LPCs altogether (outside of brown vars)

Brown, white, muddy etc. use Always Loaded Principle. The early game exception does not apply to them.
LPC exception applies to hard variants and they are useful there - we care more about efficiency than about BDRs.

**Comment by pianoblook** [comment]
> LPC exception applies to hard variants and it is useful there - we generally care more about efficiency than about BDRs

With access to modern conventions, caring more about a 1.25 efficiency than BDRs is, I'd argue, the biggest single setback to winning chances that HGroup faces. The idea to just turn off early game saves is just painful to think about.

I'd support @iamwhoiamhahaha 's suggestion to raise the 1.25 HVR cap.

**Comment by argothiel** [comment]
It's not about 1.25, it's about hard variants. For hard variants we use LPC, we relax DDA stalls and we end early game earlier - all of them increasing the risk of losing for better efficiency, because hard variants are supposed to be hard otherwise.

I don't mind increasing the threshold above 1.25, but if the variant is hard (requires high efficiency), all of these things, including LPC, seem to make sense.

**Comment by Zamiell** [comment]
no longer blocked

**Comment by Zamiell** [comment]
i reassert that LPC exception for early game should be deleted in any variant with >= 1.33 efficiency, as it is one extra thing that is hard to remember and leads to very stupid game losses, with the underlying convention itself not really providing that much value

**Comment by Zamiell** [comment]
i'll close since this is stale.
if someone wants to open a new issue about deleting LPC (now that hard variant threshold is 1.25) you can do that in a new issue
