### ISSUE TITLE
delete Junk Discharge

### ISSUE THREAD

**Issue by Zamiell** [hanabi/hanabi.github.io#1035]
I think it is the same thing as UDD/UTD, so it doesn't need to exist

**Comment by Zamiell** [comment]
@pianoblook

**Comment by pianoblook** [comment]
I guess a rank 1's UDD still promises the unfocused 1 as playable, so yeah they seem indistinguishable now.

I still believe following #805 + keeping Junk Discharge is stronger, but as long as 1s UDD is a thing it can be deleted.
