### ISSUE TITLE
Increasing hard-variant threshold from 1.25 to 1.33

### ISSUE THREAD

**Issue by vEnhance** [hanabi/hanabi.github.io#1036]
Original discussion at https://discord.com/channels/140016142600241152/776176933120507964/1043177462093328404

**Comment by vEnhance** [comment]
(And for the record, I would also support this, 1.25 always felt too low to me.)

**Comment by pianoblook** [comment]
Seemed like there was a lot of support on Discord for this. Fully agree here

**Comment by Zamiell** [comment]
1.5 seems high

**Comment by EhDrone** [comment]
I know IAMJEFF proposed switching to 1.33 instead of 1.5, but will let him type out the reasoning. I agree 1.25 is too low, I am uncertain on 1.33, but do think 1.5 should remain HVR.

**Comment by Zamiell** [comment]
for reference, this page lists the various efficiencies: https://github.com/hanabi/hanabi.github.io/blob/main/misc/efficiency.md

**Comment by EhDrone** [comment]
Thanks for that reference Zamiell - I personally have found 1.33 to not require HVR, but don't play it enough to have a weighted opinion I think. Based on the sheet, my take would be 1.33 is not HVR - but anything higher is (therefore 1.40 and higher is HVR)

**Comment by pianoblook** [comment]
Well, seems like it'll come down to a judgment call. If we can agree 1.25 is too low, and >1.50 is too high, maybe pulling out a few common examples in the gray zone can help anchor our thoughts.

So here's a list of all the existing 3-5p variants between those thresholds:

**Standard**:
5p 4 Suits: 1.33
5p 6S w/ Dark: 1.36
3/4p Double Dark: 1.43

**Gimmicks**:
5p 6S TIIAH: 1.30
5p 5S TIIAH: 1.39
5p 6S Crit 4s: 1.43
5p 6S Up||Down: 1.43

I'm not experienced with 5p TIIAH, lol, but other than that? Personally I would agree w/ ADrone that **>1.40** is a good threshold.

**Comment by DarthGandalf** [comment]
I think it should depend on level.

For someone very experienced 1.50 may be fine, but I wouldn't trust someone who just reached level 10 to play very hard variants optimally (and there are often not enough tools at lower levels for that anyway)

**Comment by EhDrone** [comment]
I for one am against making HVR apply to different efficiencies at different levels.

**Comment by vEnhance** [comment]
I also don't care too much about the exact number as long as it's between 1.33 and 1.50, I just wrote one down. I support the 1.40 threshold from piano and ADRone.

I'd prefer KISS and not making the HVR cutoff depend on level. Actually, after reading this and Stephen's comment ("I'm in the habit of asking my team to turn off HVR before most games"), I wonder if it would be reasonable to explicitly allow overriding? I was thinking we could make it say something along the lines of

> By default, we agree that any variant with required efficiency greater than or equal to 1.40 is a "hard variant".
>
> Depending on the preferences and styles of the players, the team may also agree to consider a variant hard even though it may have less than 1.40 required efficiency. We typically do so for the following: [list from before]

**Comment by iamwhoiamhahaha** [comment]
> I know IAMJEFF proposed switching to 1.33 instead of 1.5, but will let him type out the reasoning.

5p4s is hard imo but it's more about being at low starting pace instead of high required efficiency though.

**Comment by iamwhoiamhahaha** [comment]
Here's the result of the average efficiency an h-group player can achieved in a hard variant (1.25) ending with a perfect score:

![eff](https://user-images.githubusercontent.com/50160641/203196470-05ea0fbc-d957-4862-b809-6e0c0c12fcdc.png)

Sorted by players:
<https://github.com/Aigul9/hanabi-stats/blob/master/output/requests/current_eff_by_player.tsv>

Sorted by same group of players:
<https://github.com/Aigul9/hanabi-stats/blob/master/output/requests/current_eff_by_team.tsv>

Note that the stats are stained by some hat-guessing games, games including my hat-guessing account IAMGUESSING for example

**Comment by Zamiell** [comment]
@iamwhoiamhahaha are you voting for 1.33 or 1.4 as the threshold

**Comment by iamwhoiamhahaha** [comment]
> are you voting for 1.33 or 1.4 as the threshold

1.33. We could change it to 1.40 in the future if it's still too low.

**Comment by Zamiell** [comment]
so then it sounds like we are a little split between raising it to 1.33 or raising it to 1.4

**Comment by iamwhoiamhahaha** [comment]
Here are the variants where the required efficiency is between 1.33 and 1.4:
- 4 Suits 5p - **1.33** (pace: 5)
  - hard because of low starting pace
- 4 Suits (Up or Down) 5p - **1.33** (pace: 5)
  - hard because of low starting pace
- 4 Suits (Clue Starved) 3p - **1.33** (pace: 12)
  - not hard
- 6 Suits w/ 1x 1oE 5p - **1.36** (pace: 10)
  - not hard but 1oE on the bottom of the deck is frustrating
- 5 Suits (Clue Starved) 3p - **1.39** (pace: 17)
  - not that hard

Honestly, I personally am fine with raising it to 1.40. I just feel that not every h-group player is good at playing those 5p variants from my experience. Also, making them "easy variants" means that you have to stall in a dda situation, etc. I don't believe you can easily win a perfect score in *5 Suits (Clue Starved)* 3p with dda on.

**Comment by iamwhoiamhahaha** [comment]
> the average efficiency an h-group player can achieve in a hard variant (1.25) ending with a perfect score: **1.5**

Keep in mind that those games are played with hard variant conventions. The average achieved efficiency would be much smaller if you play them with easy variant conventions, probably below 1.4. Which means raising the limit to 1.4 makes hard variants harder to win a perfect score than before.

**Comment by iamwhoiamhahaha** [comment]
Okay it seems worse than I thought.

The efficiency of getting 15 cards with 10 clues: **1.5**
The efficiency of getting 15 cards with 10 clues plus 1 dda stall:  **1.36**
The efficiency of getting 15 cards with 10 clues plus 2 dda stalls:  **1.25**

Raising the limit to 1.4 is insane. You guys have to think about it.

**Comment by pianoblook** [comment]
Lots of good points from Jeff. One big counterargument is that a lot of people _already_ play non-HVR games pretty aggressively (skipping 5 stalls, reading into LPCs, etc) so it's not like raising the "official" # will suddenly stop people from playing 1.25 or 1.30 variants aggressively anyway. And I don't even mean that's always a bad thing, either: especially in the lower-pace and/or 5p games.

A large raw efficiency requirement is really not that big a deal at max level + decent teamwork (remember all the powerful lategame tools we have: ignitions, pushes/pulls, unnecessary stuff, positionals, and even the slot 1 context plays in the last round). 

**but** I agree with you that we should be careful about setting the bar too high for the broader community. tbh I'll be happy just as long as 1.25 is no longer HVR. So I'll vote 1.33 as well

**Comment by vEnhance** [comment]
I'm indifferent between 1.33 and 1.40 but it sounds like we're leaning towards 1.33 now

**Comment by pianoblook** [comment]
Oh can we also delete the HVR coloring on Mixes that don't actually meet the threshold?
(technically a different decision to agree on)

**Comment by vEnhance** [comment]
OK, it's been a while and I haven't heard any opposition to 1.33 so I'm going to submit a PR for that.

I guess I can also do piano's request from last week while I'm at it

**Comment by Zamiell** [comment]
seems fine
