### ISSUE TITLE
Shout tocm should mean something special

### ISSUE THREAD

**Issue by chennisden** [hanabi/hanabi.github.io#1037]
Fairly often, multiple trashes will be clued as part of a Trash Bluff, and the recipient will already have a playable.

This means they can shout and tocm at the same time. Say slots 1 and 2 are known trash, and Alice discards slot 2 while having a known playable. There are currently two sensible interpretations:

1. Bob double-cms
2. Cathy cms

Since a shout protects all of Bob's cards for a turn, I personally believe that 2 has more utility than 1 --- the cm'ed player should skip over. Moreover, Bob is NOT put into a scream discard situation and may discard.

Either way, we should pick one of these interpretations and run with it.

**Comment by chennisden** [comment]
Example: https://hanab.live/replay/878869#19

(I tried to double cm)

**Comment by iamwhoiamhahaha** [comment]
That is how we play in a 2-player game:
<https://github.com/iamwhoiamhahaha/hanabi/blob/master/2-player/Chop_Move_Guide.md#chop-move-addition-rules>

For 3p+, it is currently undefined whether it signals a double on Bob or a single on Cathy. I'm fine with both.

**Comment by chennisden** [comment]
Me too, I just think it would be good to have it defined one way or another.

Because of BCME/CMI, CMing Cathy might be useful (also allowing Cathy CM just increases flexibility overall), but it would be confusing (it's not actually putting Bob in a shout situation) and the BCME/CMI's actual benefit is very small since if it's late enough in the game to have multiple known trash, BCME/CMI probably isn't going to work anyway.

**Comment by chennisden** [comment]
Ideally the interpretation plays well with Echo Scream Discard too. So maybe double cm is the play, since CMing only Cathy is pointless when Bob has a good card in chop, and you shouldn't shout if Bob has trash on chop to begin with.

**Comment by pianoblook** [comment]
Huh, I'd think this is pretty uncontroversially defined as an OCM on Cathy.

As a comparison, let's say Alice has 3 known trash instead of 2 kt + a playable. Since we agree that Alice discarding the least expected trash = double OCM = Cathy CMs, why should this situation be any different?

**Comment by Zamiell** [comment]
i agree with piano

**Comment by Zamiell** [comment]
chen can you submit a pr to clarify that it is an ocm on cathy
