### ISSUE TITLE
Typo / misunderstanding under Taffy Double Bluff? Rename it? 😄 

### ISSUE THREAD

**Issue by NZadeh** [hanabi/hanabi.github.io#1045]
**Edited**: 

Taffy and Bubblegum are the same. I attempt to convince you of that in the linked PR. Thanks for your time!

-----

**Original**:

Section: https://hanabi.github.io/docs/variant-specific/pink#the-taffy-double-bluff

> Rarely, a player can perform a Taffy Double Bluff by violating Pink Promise on a three-away-from-playable pink card.

The sentences further below actually give examples and explicitly state using "two-away-from-playable", so I think this first one is an outlier/typo.

Furthermore, I don't think the "X-away-from-playability" is the key logical insight here. In my mind, the logic for this move is more akin to the Pestilent Double Bluff, in that Donald would otherwise incorrectly mark their card after the first blind play resolves (as if it were a Bubblegum Bluff).

The thing that makes the Taffy Double Bluff play is that the Bubblegum Bluff would be a lie.
(In contrast, the thing that makes a Taffy [Single] Bluff known is a Bubblegum Bluff and conventional Bluff are impossible.)

~~In fact, I might motion to change the naming of this bluff to something like Pestilent Bubblegum Bluff... :)~~

~~This would naturally extend to situations where e.g. an i3 is clued in Donald's hand with 4, getting Bob to play i1 from slot 4, and forcing Cathy to blind play to "resynchronize" the information (showing that neither Donald nor Bob has the i2 in slot 4 or slot 1 respectively)~~   _EDIT: nevermind, this move is illegal. The docs promise a Finesse._

**Comment by Zamiell** [comment]
can you submit a pr

**Comment by NZadeh** [comment]
Done, please take a look!

**Comment by Zamiell** [comment]
looks like its not done

**Comment by NZadeh** [comment]
Okay, we've got [a winner](https://github.com/hanabi/hanabi.github.io/pull/1060). Now you can take a look for real :)

**Comment by NZadeh** [comment]
also who could have predicted that
> can you submit a pr

would turn into an 8 hour fun-fest with doc reviews and git-wrangling...? 😢 😭

**Comment by NZadeh** [comment]
@Zamiell please let me know if you have any questions or feedback!

**Comment by NZadeh** [comment]
Beep beep :) @Zamiell

**Comment by Zamiell** [comment]
i'll take a look when i get an hour or so of spare time

**Comment by NZadeh** [comment]
Thanks! Feel free to ping me on Discord if something comes up that would benefit from a quicker response.

**Comment by NZadeh** [comment]
@Zamiell friendly reminder. anything I can help with, or anyone else who can review in their spare time?

**Comment by pianoblook** [comment]
'Pestilent' refers to a special situation where the blind-play dangerously matches the clue. Pestilent Bubblegums are a different beast than double Taffies. 

The key logic of what distinguishes a Taffy from a Bubblegum is that the Positional blindplay inherently proves that the card couldn't be the 'promised' rank, so it can never be 'Pestilent' in the sense that it matches. 

A double ( or triple?) Taffy just refers to when the focused card isn't a valid single bluff. It's just the difference between a 3 bluff (valid single) vs 4 bluff (if it's 2+ away)

**Comment by NZadeh** [comment]
Howdy pianoblook!

Sorry, are you writing in response to the actual doc change or the initial "Issue" text?

I think the thinking has evolved since... indeed, there should be no need to mention the word "pestilent" or "taffy". Please take a look at the `Files changed` tab of the [linked PR](https://github.com/hanabi/hanabi.github.io/pull/1060).

Pestilent and Taffy Double (now just Bubblegum Double) are similar in that the motivation is "fixing wrong note", but I agree with you that my initial wording was incorrect.  Indeed, Pestilent Bubblegum Bluffs are impossible -- according to the doc's language -- because we agree that whenever a pink card plays in response to a Bubblegum clue, it is a true Finesse.

(That is, if Alice clues Donald's i3 with a "4", Bob plays slot 4 as i1, and Cathy successfully plays slot 1 as b1, Cathy is _promised_ a playable path to i2 in her hand... .)

A Pestilent Bubblegum Bluff (which doesn't exist) would be if Cathy stopped digging for i2 after playing b1 in the above example, because Donald's notes would be correct (`!i2,i3`) once Cathy blind-plays anything. Does that sound right to you?

**Comment by pianoblook** [comment]
oh dear, no I hadn't seen that sorry. At first glance this doesn't really make sense to me, though maybe I'm just a hanaboomer at this point.

> The difference, if any, is whether the number the pink card could be is actually greater than (Taffy) or less than (Bubblegum) the clue's number.

How Kakashi first proposed it (#342), and my understanding of it through the years, is just that 'Taffy Bluffs' are a specific _type_ of Bubblegum Bluff which, very specifically, do not require additional blind-plays in order to identify that a lie has occurred.

The *only* difference, and thus the reason we decided to commit to a new term for the move, is just to help people remember that Taffies are a special kind of self-resolving bluff. Before they were defined, performing this move would often result in people (either Bob or someone else on the team) thinking they're expected to blind-play more than they needed to.

**Comment by NZadeh** [comment]
Interesting... I wouldn't have expected people to be confused (if the principles of good-touch and "assume lowest possible value" are familiar).  If a 2 touches i3, and b1 plays (on empty stacks): "can this be an i1? no. can it be an i2? no. can it be an i3? yes. can it be an i4? yes*. can it be an i5? yes*. what is the lowest value it can be? i3. the card is an i3."  If this process yields an incorrect note, then more blind plays are required.

_* well not conventionally, but in theory before a convention (or lowest-possible value principle) is assigned._

Typically bluffs (with color) have an implicit "assume lowest possible value" attributed to them. The same goes for Bubblegum.... (or "Taffy" -- which is identical to Bubblegum if you're already doing the above).

The thing about "Taffy" is that the card being clued is a higher value than the clue used to touch it. For "Bubblegum", the card being clued is a lower value than the clue used to touch it. But this is a random property of where the line between Bubblegum and Taffy was drawn. My argument (and doc edit) is that these are one and the same.

The reason for this is that one "fact" about Bubblegum is the card is never the number it is clued with.
So if the card is clued with 2, the options are {3, 4, 5}. If with 3, {2, 4, 5}. If with 4, {2, 3, 5}. If with 5, {2, 3, 4}. So a Taffy bluff is never possible with a 5, just... numerically. And a Bubblegum is impossible with the number 2.

**Comment by jack67889** [comment]
I think it's just a separate convention for historic reasons. See the initial discussion on the bubblegum bluff #193. Emphasising the importance that's put on pink promise and making explicit what's the conventional response to (the atypical) more than 1-away bluff.

**Comment by NZadeh** [comment]
Thanks for your thoughts! I definitely understand there's some historical context, but now I think that context is not helpful for reasoning about the Taffy bluff. I.e. it's extra baggage, not intuitive. It certainly confused me when I started reading about it.

The card being 1-away or not 1-away isn't actually important. As I stated in the previous (edited) comment, it just so happens that a select few number clues on a select few cards happen to have this property that they're more than 1 away... but the whole move follows from the same exact principles. There's nothing new in terms of logic or principles (even if they were "discovered" at separate times).

If you read through the PR's edits, you might find you'll start to agree with me! I'm curious to hear what you think.

**Comment by jack67889** [comment]
Certainly agree with that, keep forgetting what the taffy bluff is about myself. I think it could be a good idea to merge it with bubblegum bluffs and define it as the least-away possible card. But I also think that it's not like normal bluffs (and thus complicating the bubblegums just a bit), those are specifically about 1-away cards. So before the Taffy Bluff convention it was unclear what was promised about the clued card and if it was a finesse or not (since, single, bluffs are in principal only performed on 1-away cards; pink promise is very valuable). See for example a [similar case](https://github.com/hanabi/hanabi.github.io/blob/e2e1460d0ca89765e8145841510d55e4717abcb9/variant-specific/Null.md#the-positional-layered-finesse) for a very old null convention, where the convention was to treat it as a finesse and to keep blind-playing no matter what.

**Comment by NZadeh** [comment]
In the PR, I have a separate section (part 2) explaining that sometimes the card happens to be two-away.

Really, the guiding principle is: "is the note correct?"

If it is, then there's no real reason to keep playing. Everyone is synchronized; no problem.

Perhaps an advanced extension of this is something like the null convention you shared:

_DOESN'T EXIST YET:_
i.e., imagine the note on Cathy or Donald's card isn't correct yet. Cathy looks and sees that Bob actually has all of the cards, and (by not playing, if on Donald, or just waiting, if on her) converts the clue into a finesse.

Alice clues Cathy's i3 with 4. Bob plays slot 4 as b1. Cathy sees that Bob has i1 on slot 5 and i2 on slot 1. Cathy marks her card as i23 and does something unrelated.

Bob later sees that Cathy's note is wrong, so this must be a finesse. Rather than start from slot 1, Bob continues from the positional clue until a pink card is found, then finishes the finesse.

**Comment by NZadeh** [comment]
Would anyone like to continue the discussion on specific points of the PR? I think communicating "at large" without context has made it hard to find concrete disagreement.

E.g. if someone could point to a line of the PR they disagree with, that would be very helpful.

Or a line that you feel was omitted.

Or a suggestion to reorder sections
Etc.

@Zamiell do you have time to take a look?

**Comment by Zamiell** [comment]
yeah ill take a look today

**Comment by Zamiell** [comment]
> I think it could be a good idea to merge it with bubblegum bluffs and define it as the least-away possible card

yeah that seems fine

**Comment by Zamiell** [comment]
ill close this now since the PR was merged

**Comment by NZadeh** [comment]
yep, thanks for the discussion and review!
