### ISSUE TITLE
A potential bug about "Restart Game"

### ISSUE THREAD

**Issue by jk15162428** [hanabi/hanabi.github.io#1046]
I found that there has been a new feature "restart game" which can restart the game or make a new table. 
I encountered this situation in a recent game. I remake a table after one play, and the new joined player cannot "play" in this new remake table.
The situation goes like this:
Alice, Bob and Cathy made a table, they played. After they finished, they remaked a table using "restart game" button, and Donald joined. This table changed the timer, and didn't change the variant. They started the game, but When it's Donald's turn, Donald found that he cannot play. Donald could see that "Current Player" is Donald, but he could not give clue.

I don't know if this is some bug about this new feature or just a problem related to Internet. So I call it "A potention bug". If it cannot be reproduced, feel free to comment and close this issue.

**Comment by vEnhance** [comment]
This should probably be in the hanab-live repo and not the conventions repo, I'll transfer it there now.

**Comment by vEnhance** [comment]
Just kidding, seems I don't have permission. Maybe @Zamiell does, otherwise we could just recreate the issue there manually too.

**Comment by Zamiell** [comment]
you can't transfer issues between orgs

please open issues about the website on the hanab live website repo

**Comment by jk15162428** [comment]
sorry for that, I will repost that.
