### ISSUE TITLE
Ignition discard

### ISSUE THREAD

**Issue by Romain672** [hanabi/hanabi.github.io#1047]
Hi,
Here is a new global term which I believe can be nice to define to refer some propositions to it.
I call it an 'ignition discard'.
**Note that I propose on that post no move which trigger an ignition discard. But on paper, that look really effecient sometime** (sometimes a 6for1, with some known trash, meh chop move, meh elimination notes, but still a 6for1).

Alice do something weird which trigger an ignition discard.
Bob then check all the finesse position of all others players, isole the last trash card between those, and write 'known trash' on it.
Then, after the discard occur, he wrote 'chop move' to the card in finesse position of all players after them and before Alice.
Then, if the discard is useful, he wrote the elimination notes for that card in the right hand.
And that's it.

The discard should happen immediately.

By default, all non-playable cards are assumed to be good.
That mean that if Bob is holding a 3 which is either r3 or y3, Cathy have an r3 in finesse position, and Donald have a b4 in finesse position, then Bob must assume the r3 is a good card to chop move, and so must discard his finesse position which will chop move r3 & b4, note that his 3 is y3. And potentially adding elimination note if Bob's finesse was useful.

By default, if a card is present in more than one hand (in the hands you should check), it's assumed to be potentially trash.
That mean if Cathy have an r3 in finesse position, and Donald have a b4 in finesse position and a r3 in his hand, then r3 is considered trash.
Bob so assume the ignition discard is on Cathy and do something unrelated.
Cathy then discard her finesse position (since b4 is useful), which add elimination notes on r3 on Donald, and chop move his b4.

You can do some 'pass-ignition discard'. If Bob have a play, Cathy have an r3 in finesse position, Donald have a b4 in finesse position, and Alice have another copy of b4, Bob know that from Alice's pov, the ignition discard was for him. So he wrote trash in his finesse position.
But since Bob & Cathy saw that b4 can be discarded in Donald's hand, Bob can instead play, Cathy will do something unrelated (double think of that part, it's really important because confusing), and Donald last to play will discard his finesse position, giving elimination notes to Alice.
The following turn, Bob will discard his finesse position, which will then chop move the old finesse position of Cathy. Potentially adding another elimination note if Bob's finesse was useful.

**Comment by pianoblook** [comment]
Can you provide an example? I am having trouble understanding the idea.

**Comment by Romain672** [comment]
Let's assume it's so good that every red clue should be ignored and trigger an 'Ignition discard' instead. (for a real example, look at 'answering a color bluff by clueing the same color' on discord, in-depth discussion)

Played: r1, y2.
Bob: r4-x-x-x-x
Cathy: g4-x-r4-x-x
Alice clue red to Cathy, conventionnally, that trigger an 'ignition discard'.
Bob look at all other players finesse position (which is only Cathy) and we have g4. g4 is useful, it's not trash, it's not present in another hand from Alice knew about Bob's pov.
So Bob assume the ignition discard is on him. Bob note that his slot 1 is trash.

[skip that part if you don't want 'pass ignition discard':
Furthermore, Alice don't hold a copy of g4, that mean Bob can't make Cathy react to the clue instead.]

So Bob discard his slot 1, it's an useful r4.
So everyone else assume there is another copy of r4 on the board: Cathy wrote r4 in the only possible spot possible.
And Cathy chop move the g4 since Bob could have let Cathy discard it instead.

After that, everyone know the r4, and the chop move of g4.

**Comment by iamwhoiamhahaha** [comment]
I'm having trouble understanding the example as well. Is it the first turn of the game? Isn't it just a *4 Charm* (suboptimal)? If r4 is playable while g4 is not, isn't it just a direct *Play Clue*?

**Comment by Romain672** [comment]
The thing is, I have no move which trigger an ignition discard.
But that look really promessing: if you manage to find a move which trigger an ignition discard (so which is known as a ignition discard for the whole table) you can get at 4 players one trash, two chop move, one elimination note just from the ignition discard, and maybe some value from the clue itself.


Since apparently you want some (real) examples, I will give you one, but it have many downside. It's my 'answering a color bluff by clueing the same color'.
Played: r1.
Alice: b4-x-x-x
Bob: playable-x-x-x
Cathy: r1-b1-b5-x
Donald: b2-r3-x-x
Alice clue blue to Donald. It tell Bob he has a bluff to play in his slot 1.
Bob know it can't be layered since the clue is on b2 and not b3.
Instead Bob decide to clue blue to Cathy.
From Cathy's pov, she can assume many things: either Bob have vision on three b1s, and delay his bluff in purpose to get tempo on b1 ; or Bob want to do an out of position discharge, which would be wild ; or others things... My proposition was to assume it is an ignition discard.
From Donald's pov, the initial clue was b1 on himself which was weird since Alice clued it instead of clueing Bob (Cathy finesse position isn't playable, so stealing the clue to make Bob Cathy isn't an option), and Bob reclued b1. But out of position discharge is illegal, so that make no sense. So Donald can assume an ignition discard too.
From Alice's pov, she got the most information, assuming an ignition discard look fine.
So the ignition discard work.

Cathy then look at the finesse position of others players: it's r3 and b4, she then check if from what Bob knew from her pov they were useful or trash, but no other copy is visible in Donald or Alice's hand. So she assume they are useful. So she note that her slot 1 is trash.
Furthermore, Bob don't hold a copy of r3 or b4, so Cathy can't do a pass-ignition discard to make another one react to the clue.
So Cathy discard her slot 1 as an ignition discard.
This is an useless r1, so no one add elimination notes for r1.
Then everyone note that Donald and Alice finesse position are chop moved.
In the following turn, Bob will play his bluff.
And finally, as an option, since I wanted the move to be the most clear possible, Donald note that is blue is b2 and not b3 because Bob delayed his bluff and so I assumed that couldn't be layered.


Note that this example is really specific, the initial clue on b2 must be on Donald or must be a self color bluff on Bob. And the second clue on b1 must be on Cathy.

The point isn't this move, it's to try to play some with ignition discard, to see how powerful or how bad they are.
I'm proposing just a definition, not any move.

**Comment by Romain672** [comment]
> I'm having trouble understanding the example as well. Is it the first turn of the game? Isn't it just a _4 Charm_ (suboptimal)? If r4 is playable while g4 is not, isn't it just a direct _Play Clue_?

You ignored two sentences, though with that it would be clear D:
"Note that I propose on that post no move which trigger an ignition discard. But on paper, that look really effecient sometime (sometimes a 6for1, with some known trash, meh chop move, meh elimination notes, but still a 6for1)."
"Let's assume it's so good that every red clue should be ignored and trigger an 'Ignition discard' instead. (for a real example, look at 'answering a color bluff by clueing the same color' on discord, in-depth discussion)"

**Comment by argothiel** [comment]
In general, I don't think that ignition discards are a good idea, because they might cause discarding of a useful (or even critical) card.

For example, in your example from Cathy's point of view she might have a red 2 on her slot 1. If she discards it, another r2 might be near the bottom of the deck and the team might lose because of that.

**Comment by Romain672** [comment]
But someone trigger the ignition discard, either from Alice in my first two posts, or either Bob in the third post.
So if there if there is only useful(/playable?) cards between those players, the initial clue(/action) shouldn't be done.
So if the ignition discard doesn't work, nobody should do it.

It's like saying 3-bluffs are bad because Bob could play a non playable 5. You just don't clue 3 in that case.

**Comment by argothiel** [comment]
The difference is that with 3-Bluffs Bob knows that 3-Bluff is happening, it is well defined when Bob should respond with playing his finesse card. And here, you don't define in which situations the ignition discard can happen (as you wrote: "I propose on that post no move which trigger an ignition discard"). Thus, Bob has no way of telling if it's a ignition discard, so he cannot be sure if he's not discarding a critical card.

In your first two posts, how could Bob know that Alice is triggering the ignition discard?
In your third post, how could Cathy know that Bob is triggering the ignition discard?

**Comment by argothiel** [comment]
Ah, okay, I get it now. These were both just abstract examples. Like:
"every red clue causes an _Ignition Discard_" or "every color bluff followed by the same color causes an _Ignition Discard_".

I can agree that this could be a useful concept, but for this to proceed, I believe you'd have to provide at least one proposal what Ignition Discards could actually replace. You know, I could propose that there should exist some types of clue where everybody should play their 1st and 2nd slot, which would be great efficiency, but to determine if it's actually useful, I'd have to offer a clear and simple scenario where this would occur.

**Comment by EhDrone** [comment]
I am thinking perhaps Romaine meant to post this in in-depth-discussion channel instead of as an open issue in the git repository? Without any proposal for a change - it doesn't really belong here. If you are trying to workshop or identify moves where this may be useful, an open discussion on the discord is probably a better place since most people here are viewing comments and issues through the lens of "Here is a change I want to make, do you accept it or not? Discuss!"

**Comment by Romain672** [comment]
I hesitate to do that post and close it immediately.
The point is that if someone come with a good idea on github, and you want to change some part of it, you can refer to this post immediately.

**Comment by Romain672** [comment]
Anyway, I will close that for now.

If anyone come with a move where the initiator got some unknown blind play, feel free to share that post :)
