### ISSUE TITLE
Matryoshka Conventions

### ISSUE THREAD

**Issue by iamwhoiamhahaha** [hanabi/hanabi.github.io#1053]
### Note
- Suits
  - Red: touched by red
  - Yam: touched by red, yellow
  - Geas: touched by red, yellow, green
  - Beatnik: touched by red, yellow, green, blue
  - Plum: touched by red, yellow, green, blue, purple
  - Taupe: touched by red, yellow, green, blue, purple, teal
- Wavelengths
  - Red: longer
  - Yellow
  - Green
  - Blue
  - Purple
  - Teal: shorter (Note that it is not true in Physics)

### Red Chop Move
- Players are allowed to give a red clue to a player who is not locked. It signals a *Chop Move* on that player.
- The rest of the cards which are newly touched by the red clue are treated as "unclued".
- Note that *Matryoshka Tempo Clues* with a red clue (see below) take precedence over *Red Chop Moves*. Which means if the player has received a red clue earlier and all of their cards are currently touched by a red clue. The other players cannot perform a *Red Chop Move* to that player in this situation.

### Matryoshka Tempo Clue
- *Matryoshka Tempo Clues* are similar to *Mud Clues* in a variant with muddy rainbow cards. But unlike *Mud Clues*, red clues correspond to the rightmost slot in "Matryoshka" (while purple clues correspond to the rightmost slot in "Muddy Rainbow"), and so for.
- Similar to how *Tempo Clues* work with pink cards and brown cards, *Matryoshka Tempo Clues* are never *Tempo Clue Chop Moves* or *Double Tempo Clues* - they only promise the one card and that's it.
- For example, in a 4-player game of the "Matryoshka (6 Suits)" variant:
  - Bob's hand: `yam 3, plum 3, red 3, geas 3` (All of them are touched by a 3 clue which has been clued earlier.)
  - If Alice gives a red clue to Bob which touches all the cards in his hand; the focus of the *Tempo Clues* is on geas 3 which is on slot 4.
  - If Alice gives a yellow clue to Bob which touches yam 3, plum 3, and geas 3 in his hand; the focus of the *Tempo Clues* is on plum 3 which is on slot 2. (Note that the focus will be changed in the following section.)
  - If Alice gives a green clue to Bob which touches plum 3 and geas 3; the focus of the *Tempo Clues* is on geas 3 which is on slot 4.
  - If Alice gives a blue clue to Bob which touches only the plum 3; the focus of the *Tempo Clues* is on plum 3 which is on slot 2.
  - If Alice gives a purple clue to Bob which touches only the plum 3; the focus of the *Tempo Clues* is on plum 3 which is on slot 2.
  - In order to *Tempo* the yam 3, Alice is supposed to give a 3 clue in this situation.
- You may be noticing that there is no way to *Tempo* the red 3 in the example above. In order to do that, we need to apply *Redshift Tempo Clues* (see below).
- Rarely, if the clue receiver who is exactly next to the clue giver knows that the focus of card is unlikely to be playable, then the focus shifts left by one slot. (Note that normally, it means a *Reversed Finesse* rather than a *Signal Shifting*.)

### Interaction Between Red Chop Moves and Matryoshka Tempo Clues
- Players are allowed to perform a *Matryoshka Tempo Clue* on a player who just received a *Red Chop Move*. (Note that all the cards which has been newly touched by the *Red Chop Move* are considered to be unclued, except for the *Chop Moved* card.)
- All the cards newly touched by the *Matryoshka Tempo Clue* are also treated as unclued, unless they are focused.
- For example, in a 3-player game of the "Matryoshka (6 Suits)" variant:
  - Yam 1 and plum 1 are played on the stacks. 
  - Cathy's hand: `plum 1, red 3, beatnik 2, yam 2, geas 2` (All of the 2s are touched by a 2 clue which has been clued earlier.)
  - Alice gives a red clue to Cathy. It is a *Red Chop Move* on the red 3. (Don't forget that the plum 1 is treated as unclued.)
  - Bob follows with a yellow clue retouching plum 1, beatnik 2, yam 2, and geas 2. It is a *Matryoshka Tempo Clue* and the focus of the clue is on yam 2.
  - Cathy plays the yam 2 from slot 4.
- Again, you might be noticing that the plum 1 is touched by both the red clue (from the *Red Chop Move*) and the yellow clue (from the *Matryoshka Tempo Clue*). But keep in mind that it is treated as "unclued".

### Redshift Tempo Clue
- Players are allowed to perform a *Redshift Tempo Clue* which specifically identifies a card (and only that card) that has longer wavelengths by negative color information. (Usually performed by a yellow clue to identify a red card.)
- In this situation, the focus of the *Tempo Clue* shifts to the card which has been identified. Note that the focus is not directly touched by the *Tempo Clue*.
- For example, in a 4-player game of the "Matryoshka (6 Suits)" variant:
  - (This is almost exactly the same as the previous example in *Matryoshka Tempo Clue*.)
  -  Bob's hand: `yam 3, plum 3, red 3, geas 3` (All of them are touched by a 3 clue which has been clued earlier.)
  - We know that Alice can easily perform a *Matryoshka Tempo Clue* on each card but red 3 in this example. So how do we *Tempo* the red 3? Now, we may apply *Redshift Tempo Clues*.
  - Alice gives a yellow clue to Bob which touches yam 3, plum 3, and geas 3 in his hand.
  - Bob knows *Matryoshka Tempo Clues*. Which means that the focus of the clue is on the plum 3.
  - However, since the yellow clue specifically identifies the red 3 with negative color information. Bob also knows that *Redshift Tempo Clues* take precedence over *Matryoshka Tempo Clues*.
  - In this situation, the focus of the clue shifts to the red 3. Bob plays the red 3 from slot 3.
- Note that the players can also perform this move by touching a new card. Unlike *Matryoshka Tempo Clues*, any card newly touched by the *Redshift Tempo Clues* are considered as "clued".
- For example, in a 4-player game of the "Matryoshka (6 Suits)" variant:
  - (This is almost exactly the same as the previous example.)
  - Red 2 is played on the stack.
  - Bob's hand: `yam 5, plum 3, red 3, geas 3` (All of 3s are touched by a 3 clue which has been clued earlier.)
  - Alice gives a yellow clue to Bob which newly touches the yam 5. It looks like a *Play Clue* on the yam 5.
  - However, since *Redshift Tempo Clues* take precedence over normal *Play Clue*. The focus shifts to the red 3, which is playable.
  - Bob plays the red 3 and keeps the yam 5 (an unknown card which has been clued with yellow) for the rest of the game.

### Matryoshka Bluffs
- Players can perform a *Bluff* with a color clue, as long as the focus of the clue does not match to the blind-card.
- Yam cards are treated as yellow cards. Geas cards are treated as green cards. And so for.
- For example, in a 4-player game of the "Matryoshka (6 Suits)" variant:
  - Alice gives a yellow clue to Cathy focusing a yam 2.
  - Bob blind-plays his *Finesse Position*. It is a geas 1 and it successfully plays.
  - Cathy knows that geas cards can also be touched by a yellow clue, which looks like a *Finesse*. However, she also knows that *Matryoshka Bluffs* take precedence over *Finesses* since geas cards are treated as green cards.

### Matryoshka Principle
- If the players have a *Free Choice*, they are supposed to give a color clue which specifies the identity of the cards while giving a direct *Play Clue*. (Yellow for yam cards, green for geas cards, and so for.)
- For example, in a 4-player game of the "Matryoshka (6 Suits)" variant:
  - Cathy's hand: `beatnik 1, beatnik 2, yam 4, yam 4`.
  - Alice wants to give a direct *Play Clue* on beatnik 1 and she has a *Free Choice* between a green clue and a blue clue.
  - By *Matryoshka Principle*, Alice is supposed to give a blue clue to specify "beatnik" in this situation.
- Exception: If the player has received a specific type of color clues earlier, we agree that it is better for the team to give the other type of color clues to provide more negative information. In this situation, players are allowed to break *Matryoshka Principle*.

### Redshift Finesse
- If a player breaks the *Matryoshka Principle* and gives a color clue with longer wavelengths, then they are trying to perform a *Redshift Finesse*.
- In this situation, the next player is supposed to blind-play their *Finesse Position* as a ***Known Bluff*** which looks like a true *Finesse*.
- For example, in a 4-player game of the "Matryoshka (6 Suits)" variant:
  - (This is almost exactly the same as the previous example.)
  - Cathy's hand: `beatnik 1, beatnik 2, yam 4, yam 4`.
  - Alice gives a green clue to Cathy.
  - It is weird that Alice gives a green clue rather than a blue clue, which disobeys the *Matryoshka Principle*. She must be trying to communicate something extra.
  - Bob knows that *Redshift Finesses* exist and blind-plays his *Finesse Position*. It is a geas 1 and it successfully plays.
  - Now, it's Cathy's turn. She thinks that it is just a normal *Finesse* and plays her "geas 2". Surprised! It's a beatnik 1 and it successfully plays.
- Note that the players are not allowed to perform a *Gentleman's Discard* if it can be a *Redshift Finesse*.
- How do you distinguish them from normal *Finesses*? The blind-play from a *Redshift Finesse* is always on the bluff seat.

**Comment by iamwhoiamhahaha** [comment]
Note that the main purposes of performing a *Red Chop Move* is not only to protect a random card on *Chop* but also enables the ability to give a following *Tempo Clues* to that player.

**Comment by J-Fricke** [comment]
How to distinguish from Matryoska Tempo (MT) finesse and Redshift tempo? B2 in finesse position yellow clue reveals R3 with Redshift Tempo, but would focus B3 with MT. 

Any reason not to use Extremely Ambiguous for red given how similar it is?

Red CM + Muddy or Rainbow/Omni/Brown Fives/Ones... How do these work?

**Comment by iamwhoiamhahaha** [comment]
> How to distinguish from Matryoska Tempo (MT) finesse and Redshift tempo?

*Redshift Tempo Clues* take precedence over *Matryoshka Tempo Clues*. But we can change that if people feel that it's not that important to tempo a red card.

> Any reason not to use Extremely Ambiguous for red given how similar it is?

I found that *Ejections* are not useful after testing few games. And the main reason is we need to find a way to deal with the problem to tempo a card in the situation where there is a blocking card.

> Red CM + Muddy or Rainbow/Omni/Brown Fives/Ones... How do these work?

Honestly, I haven't thought about them. But I do believe that we are still able to play those variants with these conventions.

**Comment by Zamiell** [comment]
which members of h-group are playing the most Matryoshka in 2023? i need to know which conventions have consensus, and i would like to close out the issue.

**Comment by Zamiell** [comment]
closing this for now
