### ISSUE TITLE
Deck draw card revealed

### ISSUE THREAD

**Issue by J-Fricke** [hanabi/hanabi.github.io#1059]
Unsure what causes this, but I sometimes see this when tabbing back to a game (have seen both when playing and more frequently when watching (probably because more likely tabbing away)
![Screen Shot 2023-01-18 at 11 55 09 AM](https://user-images.githubusercontent.com/5597761/213282177-94411935-4b0f-4004-bebe-05ed301cc5f7.png)
![Screen Shot 2023-01-18 at 11 56 07 AM](https://user-images.githubusercontent.com/5597761/213282192-e315128b-12ee-464d-9694-a4926615a545.png)

This was the game I witnessed this in: https://hanab.live/game/120 see screenshots

**Comment by Zamiell** [comment]
to be clear, the client has no information about what the unknown cards are.
so its just a synchronization bug where the 4y didn't get tweened to the correct location.
in general, this probably isn't something we can fix using the current konva library.

**Comment by Zamiell** [comment]
also this issue was in the wrong repository, this repository is for convention stuff
