### ISSUE TITLE
Add end-game strategies

### ISSUE THREAD

**Issue by ReaverSe3** [hanabi/hanabi.github.io#1064]
The Safety/Declined Positional Discard (Advanced strategy discards & misplays)

For example, in a 2-player game:
- There are 0 clues in the bank.
- Only 1 card is left in the deck.
- Only Red 5 and Blue 5 are left to play
- Alice has known Red 5 on slot 3
- Bob has Blue 5 somewhere
- if Bob hasn't Blue 5 on slot 3, Alice can do positional discard.
- if Bob has Blue 5 on slot 3, Alice can't do anything. She would just play Red 5.
- Therefore, Bob is supposed to play slot 3 as Safety/Declined positional discard.

Note that it works only if Alice has enough time to discard

The Ambiguous Escape Clue (Advanced strategy Play Clues)

First, see the section Ambiguous Tempo Clue

For example, in a 3-player game:
- There are 1 clue in the bank.
- Only 1 card is left in the deck
- Red 4, Red 5, Blue 5 are left to play.
- Bob has two 5's. He doesn't know which is which
- Cathy has Red 4 somewhere
If Alice touches Red 4 with Rank, Bob should play left 5.
If Alice touches Red 4 with color, Bob should play right 5.

Note that it works only if Alice has free choice.

The Index Misplay (Advanced strategy discards & misplays)

https://hanab.live/replay/917220#40
-It's sin_faith's turn.
-He labeled slot1,2,3,4 to index 0,1,2,3

-scharkbite has playable on index 2
-Newduke has playable on index 1
-joelw has playable on index 0
-sin_faith misplayed index 3 as 2+1+0

Not sure this works when sin_faith playable which is critical and unknown where it is.

**Comment by chennisden** [comment]
A real example of where the declined positional discard should have been utilized: https://hanab.live/replay/880106#39

I strongly agree that it should be an explicit convention.

**Comment by str8tsknacker** [comment]
Suggestion: Double (Triple etc...) Positional Discard

If Alice needs to communicate 2 (3,4...) unknown playable cards, she can do it by discarding the slot numbered the sum of the slots of the playables, wrapping around if necessary.

For example, in a 3-player game:
There is 1 card left in the deck and 0 clues in the bank. r4, y5, g5, b4 and p5 are played.
Bob: x r5 x x x
Cathy: x x b5 x x
Neither Bob nor Cathy knows where their 5 is.
Alice can discard slot 5 (2+3) as a Double Positional Discard.
Note that this move only applies to unknown cards.

**Comment by Zamiell** [comment]
> If Alice needs to communicate 2 (3,4...) unknown playable cards, she can do it by discarding the slot numbered the sum of the slots of the playables, wrapping around if necessary.

afaik we deliberately don't do this because its too much like hat guessing, which we consider to be cheating.
the tldr is that if we wanted people blind-playing random slots, then we would just play hat-guessing.

going to close since this hasn't gotten a lot of interest
