### ISSUE TITLE
All of the Special-Five saves

### ISSUE THREAD

**Issue by Stuurrm** [hanabi/hanabi.github.io#1067]
Suggesting to add to the Special-Fives variant specific section the way all of the different Special-Fives are saved. All of them are pretty straight forward except for the pinkish fives (which are already defined) and Muddy-Rainbow-Fives.

Muddy-Rainbow-Fives can be saved in 2 different ways. They can be saved using their own color or they all be saved using red. An argument had arisen during pre game on the subject which prompted this issue to be made.

The benefits of using only red to save Muddy-Rainbow-Fives is that you do not sacrifice the ability to give play clues using the majority of colors. As seen with muddy rainbow this does add to the difficulty but does not really hinder the teams ability to get cards played from chop. The downside of this way of saving is that the clue receiver without context is unable to differentiate their fives and may need to be tempo clued.

The benefits of using the true color to save Muddy-Rainbow-Fives is that the receiver will learn the true color of their 5s allowing them to play it immediatly when it becomes playable. Also it does not lie about the color of the 5 so players will not be confused what color their cards are. The downside of this is every single color clue to chop will have to be treated as saves making it considarably harder for the team to give play clues focusing on chop.

The proposal:
Pink-, Light-Pink and Omni-Fives saved with the rank 2 clue. (as is currently)
Brown-Fives saved with true color. All color clues always loaded. (same as is in Deceptive-Fives)
Muddy-Rainbow-Fives saved with red. Red clues always loaded. Mud clues apply. (treating them exactly like muddy rainbow cards)

**Comment by Zamiell** [comment]
yeah, a little more clarification here can't hurt, can you please submit a PR?

**Comment by Zamiell** [comment]
david submitted a PR and I updated the page a little bit, can you review it to see if it is okay now?

**Comment by Zamiell** [comment]
i updated it now
