### ISSUE TITLE
Remake table resets the password

### ISSUE THREAD

**Issue by Kowalski1337** [hanabi/hanabi.github.io#1070]
When you play in private room with password and use "remake table" option the password resets and you room become public
That's weird..

**Comment by Zamiell** [comment]
please option website issues on the website repository

**Comment by vEnhance** [comment]
It was fixed in https://github.com/Hanabi-Live/hanabi-live/pull/2822 but I think this hasn't reached production yet.

**Comment by Zamiell** [comment]
the website should have the latest code afaik

**Comment by Zamiell** [comment]
i'll restart it now to make sure
