### ISSUE TITLE
Ignitions from Unnecessary Moves not on Bob, instead always on last player

### ISSUE THREAD

**Issue by Stuurrm** [hanabi/hanabi.github.io#1086]
In this post Donald is used to mean the last person able to succesfully react to an ignition / ejection. They might not actually be fourth player from Alice.

**Unnecessary Moves with Known Trash**
If an unnecessary move with known trash was performed on Bob then Cathy should always be the one to ignite or in the double ejection's case Cathy should alwayas eject. The question is should it be this way?

What I have witnessed in practise and have found to work quite well is that the igntion would be on Donald in the same manner as the second ignition from double ignition. It is true that sometimes Bob can be in the dark for a moment if Donald's card has been ignited. This situation can be handled as long as the rest of the team is mindful of this fact. If in doubt Bob can always apply the Occam's Razor. Assume the least amount of plays from bob as possible.

**The Double Ejection**
My thoughts with the double ejection are very similar to the previous case. They should be on Donald instead of always on Cathy.

**"a very good reason"**
This has been left extremely vage. It does not have to be defined as precisely as for example what is considered unnecessary but some guidence I believe should be given and I have heard there might be some differing opinions on this.

Should Bob already having a known playable consired a good reason? Personally yes.

Should Alice being in a bad position to discard? Personally yes, if at least severity 3 stalling situation or in end game and it would be "highly detrimental" to have Alice discard.

Miscallenous desperate situations? Yes, though these are much more context dependant 

Another thing that has been left ambigous in the doc is that if not Bob then who? Again I believe it should be Donald.

**Comment by pianoblook** [comment]
Weird, when did this change? My memory is that it was originally expected to be from Bob+Cathy, but then was changed - I found a couple links to when it was changed in 2021 ( #456 and then #499). 

I suspect most high trust teams are still being sensitive to whether or not it was 'weird' for Alice to trigger a DI, and/or if it's weird for Cathy (or even Bob) to be responding (usually due to tempo or late-game obligations). But I'll skip rambling further on that since you've brought up plenty of good points about it already.

**Comment by Stuurrm** [comment]
Those are very close but not specifically talking about when cluing Bob.

Also I should mention from practise unnecessary moves with known trash are already being played in a way that the blind play does not have to be from Cathy. Though there isn't too much practise from double ejections as they are a new thing.

**Comment by Zamiell** [comment]
> The question is should it be this way?

I'm not sure myself

> "a very good reason"
This has been left extremely vague. It does not have to be defined as precisely as for example what is considered unnecessary but some guidance I believe should be given and I have heard there might be some differing opinions on this.

absolutely agree, this is one of the terrible parts of the doc that i take responsibility for.
this ambiguity leads to lost games.

so, to summarize this issue:
currently, the ignition from an "unnecessary" thing is always on Bob. (it's rarely on cathy if you clue bob, but yeah.)
Sturm proposes that it's always on Donald (or the very last person).

without more support though i don't think we can accept this, sturm do you want to see if any current players who are playing a lot want to comment on this issue?

**Comment by Stuurrm** [comment]
> without more support though i don't think we can accept this, sturm do you want to see if any current players who are playing a lot want to comment on this issue?

I can definetly do that.

**Comment by Zamiell** [comment]
@Stuurrm do you think that all DI should work this way? e.g.

- 5 player game
- end-game
- Alice clues Emily number 1 as a TDI
- Bob sees that Donald+Emily have playables on *Finesse Position*
- Bob discards
- Cathy sees that Donald+Emily have playables on *Finesse Position*
- Cathy discards

**Comment by Stuurrm** [comment]
No, I do not think that. I believe the first part of double ignitions should be on the first person who reasonably should have given the same clue. In that example Bob is expected to react as Alice took time out of their day to give that clue instead of letting a later person give it. Though if Bob for example already had a card to play it would go onto Cathy etc.

**Comment by ranasaria** [comment]
I agree with this proposal. It should always be on Bob and the last person who can fulfill double ignition. Skipping over Bob if they already have a play is also valuable.

**Comment by Zamiell** [comment]
ok i think this has support enough to pass, sturm do you wanna do a PR?

**Comment by Zamiell** [comment]
we discussed this more today after playing game 1078476.

i strongly feel that we should unify the rules around the following 3 moves:

- double ignition
- double ejection
- unnecessary ignitions

TODO: sturm needs to review the PR from sr8, and then post his revised thoughts here

**Comment by Stuurrm** [comment]
I like the changes in str8's pr. Still keeps open the option of forcing a blind play from your Bob if you really want that card while opening up Alice to give more clues when Bob is loaded. The only thing that has to be looked is does Bob have a play if not then last in all cases. I think this a fine compromise between complexity and freedom in, which card gets ignited. It being on the first person who was not occupied is an another option but that would have to cause differenses between if the clue was given to Bob or not and is not neccessary to include in order to keep complexity down.

When it comes to double ignitions it seems that double ignition first blind play has already has gotten an update that if Bob has a play the first ignition moves forward. To make it same as ignition from unnec I would just add then it is going to second last and last.

When it comes to double ejections they could be made to identical to double ignitions though that requires them to become more disconnected from their roots of trash/replay/poke ejections. A reasonable way to do it I would say is:
If not on Bob -> Uses exact same rules as DI for determaning when not on Bob and on whom the blind plays are. Also always double.
If on Bob -> single if neccessary, if not the second blind play uses same rules as DI.
Of course one could be more radical and remove single trash/replay/poke ejections which would allow it to make the exact same as DI.
Additionally I would add to them that 1 away targets do not count for double ignions just straight up or a more context version of it "Could they have clued it as a normal finesse?". The later version is what I have been playing with as the teammates have usually been able to fix together playing a r1 from finesse is very dumb if I could have just finessed them like a normal person. On the other hand I have ignited u1 and u2 with the same clue several times.

**Comment by pianoblook** [comment]
> Of course one could be more radical and just remove single trash/replay/poke ejections which would allow it to be the exact same as DI.

This doesn't seem worth, since we have very limited options for (necessary) ejections during the middlegame. 

That said, this could be a good opportunity to revisit the idea of Blaze Ignitions, way back from #449 . That was back in 2020 and deemed (very justifiably) too fringe to include, but imo times have changed a lot since then. Thoughts? fwiw the KPP team used these pretty regularly (most commonly via Blazing Dumptrucks, aka Dumpster Fires)

**Comment by Zamiell** [comment]
> This doesn't seem worth it, since we have very limited options for (necessary) ejections during the middlegame.

this is my initial reaction as well, Trash Ejection + Replay Rejection + Poke Ejection seem useful enough, while not extremely common they are common enough

**Comment by Stuurrm** [comment]
> This doesn't seem worth it, since we have very limited options for (necessary) ejections during the middlegame.
Absolutely valid. If that is not on the table any better ideas of bringing DE closer to DI other than what I proposed? Though if one wants more ejections on Bob compared to more doubles and does not mind a slightly bigger difference with DI it could always be Bob + last. To be noted is that the only time it takes ejection away from Bob is if they are loaded and they see 2 playables.

**Comment by Zamiell** [comment]
I accepted Sturms PR with some small edits.

i also changed this:

> - The first _Ignition_ **must always be on Bob**, unless Alice had a very good reason to give the clue (i.e. Bob has a known-playable card already).

to this:

> - The first _Ignition_ **must always be on Bob**, unless Bob has a known-playable card already. Then, it would be on the first player without a known-playable card already.

which is a bit more clear IMO (?)

**Comment by Zamiell** [comment]
> If that is not on the table any better ideas of bringing DE closer to DI other than what I proposed?

ok, then since the consensus is that we want to keep TE, then let's forget about double ejections for now, since they are rarely used anyway.

**Comment by Zamiell** [comment]
Ok so with these edits, I believe Double Ignition and Unnecessary blind plays have been as fully united as possible, correct me if I am wrong?

**Comment by Zamiell** [comment]
As a summary of this issue, this is what I am planning on announcing:

- Ignitions are now more strongly defined.
- For _Double Ignitions_:
  - The first _Ignition_ **must always be on Bob**, unless Bob has a known-playable card already. Then, it would be on the first player that does not already have a known-playable card.
  - The second _Ignition_ **must always be on the last player with a playable card**. (This is because the players in the middle will think that the last person is supposed to play, similar to how a normal _Ambiguous Finesse_ works.)
- For _Unnecessary Ignitions_:
  - The _Ignition_ is always on Bob, with two exceptions:
    - If Bob can already play a card on his turn and sees a playable card on someone else's _Finesse Position_, then the _Ignition_ is on the other player with the visible playable card.
    - If Bob was the receiver of the clue and is blind-playing from the clue, then the _Ignition_ is on the last player with a playable card on _Finesse Position_.

**Comment by Stuurrm** [comment]
Looks good to me except:
>         * If Bob can already play a card on his turn and sees a playable card on someone else's _Finesse Position_, then the _Ignition_ is on the other player with the visible playable card.

Namely "the other player" could be made more clear if there are multiple such people.

**Comment by Zamiell** [comment]
updated it to:

>     - If Bob can already play a card on his turn and sees a playable card on someone else's _Finesse Position_, then the _Ignition_ is on the last player with the visible playable card.
