### ISSUE TITLE
Trash Finesse/Bluff in Pink

### ISSUE THREAD

**Issue by str8tsknacker** [hanabi/hanabi.github.io#1088]
The Trash Finesse/Bluff in Pink should promise all touched cards to be trash, not only since that is the more common case but also because another convention exists which promises only the focus to be trash, namely the Unknown Trash Discharge. And it allows for potential TOCMs.

**Comment by Zamiell** [comment]
> not only since that is the more common case

that's debatable, its not more common in my experience

but the other points seem pretty good

**Comment by Zamiell** [comment]
can you submit a PR?

**Comment by Zamiell** [comment]
looks like str8tsknacker isn't responding so ill do it myself
