### ISSUE TITLE
Suggestion for non-optimal gentleman's discards

### ISSUE THREAD

**Issue by benzloeb** [hanabi/hanabi.github.io#1089]
Some gentleman's discards are actively bad because they are such bad tempo that it will slow down cards being played by a full turn cycle. Because this play is bad, I propose that it should cause a blind play similar to an ignition. Note that this should not apply if it is being gentleman's discarded behind other playable cards, or in endgames as tempo is vital. 

Example: 
Stacks: Empty. For this example Alice and Bob somehow know what/where their red cards are. 
Alice: R1 X X X X
Bob:  Y1 X X R2 X
Cathy: R1 X X X X

After Alice discards R1, Bob sees that this discard goes to Cathy and delays his R2 by a full turn cycle. For this reason, he ignition plays his front card. 

This 
Sorry if I get some notation wrong in this proposal, first time ;)

**Comment by Zamiell** [comment]
whether or not it is "bad" is not synchronous, so this isn't well-defined.
furthermore, it is actually common to intentionally perform "bad" gentleman discards for the purposes of trading tempo for negBDR

**Comment by benzloeb** [comment]
I'm not familiar with negBDR or this play pattern. Could you point me in the right direction?

**Comment by Zamiell** [comment]
BDR stands for bottom deck risk, meaning that you can GD to prevent a player with an interesting card discarding for N turns.
in plenty of variants, tempo is not needed at all, especially towards the beginning of the game (and neither is efficiency for that matter), rather minimizing BDR is the number one priority
