### ISSUE TITLE
5 Chop Move vs. 5 Play Clue

### ISSUE THREAD

**Issue by str8tsknacker** [hanabi/hanabi.github.io#1106]
What's currently in the doc is that chop moves are turned off in the endgame, where "endgame" means pace is smaller than the number of players. However, there are situations where pace is very high and a 5cm is nonsensical (eg. all 4s are played). And there are situations (mostly in 5-player hard variants) where, by the doc's endgame definition, it's possible for the endgame to start when there are only a few cards played on the stacks (and many useful cards to cm). I think whether a 5 clue is a cm or a play clue should somehow depend on the number of cards played and I'm interested in your opinions on this because there should be a clear convention to distinguish between them.

**Comment by Zamiell** [comment]
> there should be a clear convention to distinguish between them.
i absolutely agree.

however, i have to close this issue now since nobody has proposed any new ways
