### ISSUE TITLE
New Convention: Trash Stall (Extras/Max Lvl)

### ISSUE THREAD

**Issue by purple-joe** [hanabi/hanabi.github.io#1121]
- If a clue is given which only touches two or more trash cards, and it does not Chop Move or Trash Push any cards, it generally does not convey any meaning. In particular, it cannot ask for any special blind-plays or Chop Moves.
- In such cases, the purpose of the clue is either:
    - to protect the player’s own chop via a stall.
    - to stall in an endgame-related situation.
    - to protect the following player’s chop via a Trash Order Chop Move.
- This also allows for future Shout Discard Chop Moves.
- If a clue that looks like a Trash Stall is given when there was clearly a better clue available, it has the usual H-Group meaning (Chop Move or Trash Push).

**Comment by Zamiell** [comment]
isn't cluing trash like this just a DI? (specifically, a trash double ignition)

**Comment by purple-joe** [comment]
we can delete this, i don't think it's a good convention. I reworked it alot.
