### ISSUE TITLE
alphasorting for variant-specific

### ISSUE THREAD

**Issue by vEnhance** [hanabi/hanabi.github.io#1130]
Currently the page "Variants with No Positive Clues" has slug `no-positive-clues` which causes the alphabetical ordering to be off in the sidebar:

![image](https://github.com/hanabi/hanabi.github.io/assets/3750940/052ddb18-a2a7-4619-ba76-1dac109fb32f)

Should we rename the page title, rename the slug, just change the order in the sidebar, do nothing, something else?

**Comment by Zamiell** [comment]
up to you
