### ISSUE TITLE
ALP Applying to 5's

### ISSUE THREAD

**Issue by Zamiell** [hanabi/hanabi.github.io#1132]
From what I'm reading of the ALP convention, it should apply to 2's and to 5's equally. If we want to change this, then we should discuss it here. (If this was not the ALP author's original intention, then they did not perform the ALP pull request carefully enough.)

Jack summarizes the issue here, so you should reference that before posting: https://github.com/hanabi/hanabi.github.io/pull/1126#issuecomment-1811432657

I think that most people do not assume ALP with 5's, which is why the text of the document historically did not represent this.

**Comment by unsoftcapped3** [comment]
We already had this discussion. You're the one changing things without people coming to a consensus.

**Comment by purple-joe** [comment]
I see several issues with ALP for fives (and, for that matter, twos) the biggest one being - it mekes 5 saves and stalls in the early game harder (which would lead to less clues to do things with). Of course, this doesn't matter in hard variants where 5 stalls are deactivated, but it is relevant to regular Gray and White which are not hard variants.
Also, if someone is loaded but receives a 5 clue one away from chop, is that a 5 cm or a loaded 5 play clue? Same question with pulls in the early score phase - if someone loaded is given a five clue, is it a pull or a finesse/play clue on that five?
Having fives be loaded seems like it would be confusing and restrictive.

As it currently stands, the gray doc and the white doc contradict each other. The gray doc says only 3s and 4s are loaded while the white doc says 2, 3, 4, and 5 are all loaded.

From what I've seen there's been a lot of community support for NOT having ALP apply to fives. I've seen downvoid, yagami, and egroegw speak on this issue.
