### ISSUE TITLE
Trash CM's with pink seem like they don't need pink promise on the trash card

### ISSUE THREAD

**Issue by vEnhance** [hanabi/hanabi.github.io#1134]
https://hanabi.github.io/docs/variant-specific/pink/#pink-promise-with-a-trash-chop-move currently says

> This same convention applies to a Trash Chop Move given with a number clue. In a Trash Chop Move given with a number clue:
> -    The focus of the clue is the trash card that is closest to chop.
> -    Pink Promise applies to the focus of the clue.
> -    Other cards, if any, are not necessarily promised to be anything.

The second line seems overly strong to me, so I posted the following question in Discord #convention-questions:

> Bob's hand unclued, from left to right, is r1 g3 y1 i2 b3
> If all 1's are on stacks, and i2 is on stack, is Alice allowed to clue 1 to Bob as a trash chop move? While it violates pink promise, it shouldn't matter because Bob doesn't really care about i1 vs i2.
> Same question if all 2's are on stack. (In that case, 2 is also permissible as a trash chop move, but I still think 1 is more informative, especially if e.g. Bob's hand has negative-5 info on the trash 1's.)

See https://discord.com/channels/140016142600241152/456214043351580674/1178396657029746798.
The consensus so far seemed to be that we were fine with allowing 1's to trash CM in this way for both questions, as this doesn't conflict with any other conventions and is pretty clear to everyone what's going on.

I'd like to push this into the issue tracker to make sure there's a real consensus here and see if there's support for either deleting this line altogether or weakening it in some way.

**Comment by Zamiell** [comment]
I'll edit this to be more clear:

> - Pink Promise_ applies to the focus of the clue.

-->

> The focus of the clue is promised to be trash.

as timehoodie shows, you can see that this was just an original copy paste of the other section, and wasn't ever meant to be taken literally

**Comment by Zamiell** [comment]
should I close this now?

**Comment by vEnhance** [comment]
yeah seems good, ty
