### ISSUE TITLE
Delete Trash Finesse Exception in Pink

### ISSUE THREAD

**Issue by Zamiell** [hanabi/hanabi.github.io#1139]
Currently, in pink variants, there is the following exception:

### Trash Finesses & Trash Bluffs in Pink

- When a _Trash Finesse_ or a _Trash Bluff_ happens in a normal variant, if more than one card is touched, then all of the touched cards are known to be trash.
- When a _Trash Finesse_ or a _Trash Bluff_ happens in a variant with a pink suit, if more than one card is touched, and the clue was a number clue, it is possible that only the focused card was trash, and that the other cards touched are useful / critical pink cards.
- In this situation, after discarding the focus of the _Trash Finesse_ or _Trash Bluff_, the player should then hold on to the other touched cards.

### Delete It

Many players cannot remember this exception. Since it generates little value, we can simplify the conventions by deleting it.

RE: https://discord.com/channels/140016142600241152/1178396657029746798

**Comment by David707x** [comment]
Fully agree

**Comment by Zamiell** [comment]
oh this is a duplicate of #1088
