### ISSUE TITLE
Remove double tempo clues?

### ISSUE THREAD

**Issue by gw12346** [hanabi/hanabi.github.io#1155]
_Double Tempo Clues_ are not used by the vast majority of H-group. If we remove them, we might say instead that any tempo clue that touches multiple cards is treated as though it touchs only the left-most card. 

Advantages include:
- Can tempo single cards before blockers get drawn
- Rare for both or all cards to be exactly the right playable order

Disadvantages:
- If both or all cards are in the right order, it may take multiple tempo clues to get everything played

**Comment by pianoblook** [comment]
If we turned double tempo off then presumably we'd replace it with a TCCM. They don't really seem that rare though, at least not the kind that act across multiple hands. 

Personally I like it how it is, but maybe someone can put together a convincing argument. Definitely check out the relevant discussion back from #658.

**Comment by kesslermaximilian** [comment]
I think the crux of the point is that some clues might look either way:

Example 1:
- we have some red and blue card, both unknown. rank 2 reveals both as playable
- This is a clear double tempo and I think everybody agrees on that.

Example 2:
- Yellow one is played on the stacks, Bob holds two yellows and gets them reclued.
- Option 1: This could be a double tempo clue on y23 now
- Option 2: Maybe this is a single tempo clue + TCCM

I think there is no point in removing double tempos intrinsically (two units of tempo is valuable), but I can see a point being made to clarify that Example 2 is single tempo + TCCM. At least that is how me (and lots of people I know) have been playing it, but I think it's not what the doc says.

I would be in favor of clarifying this and arguing that if in doubt, single tempo + cm takes precedence over double tempo. But don't remove double tempo clues in itself.

**Comment by kesslermaximilian** [comment]
Also, in the example of holding y23, most of the time you can still just clue rank 3 and get the 'double tempo' unambiguously. Onem ore reason why I should think the color reclue should favor single tempo only.

**Comment by Zamiell** [comment]
> Double Tempo Clues are not used by the vast majority of H-group. 

citation needed lol

**Comment by newduke** [comment]
I believe they are not too common, and  should not (IMO) be given with rank. Color double tempo is valuable in pink in particular because a rank clue will never cause a self prompt.  Rank is useful as a single tempo (+ tccm) and Roger might not know if the leftmost color is blocked. For simplicity rank = single tempo seems best.

**Comment by Egroegw** [comment]
> > Double Tempo Clues are not used by the vast majority of H-group.
> 
> citation needed lol

My sources are Newduke and Cadenza (Wei), who have 20,000 games played between them.

**Comment by gw12346** [comment]
My sources are Newduke and Cadenza (Wei), who have 20,000 games played between them, but pink and omni are variants where double tempo clues given with color are more common relative to other variants.

**Comment by Zamiell** [comment]
[this post](https://github.com/hanabi/hanabi.github.io/issues/658#issuecomment-873621202) still seems like the best defense / the best summary, 2.5 years later
