### ISSUE TITLE
Disallow play-cluing a card that's also on finesse position?

### ISSUE THREAD

**Issue by gw12346** [hanabi/hanabi.github.io#1156]
As Simon writes,

> First turn of the game, Alice clues red to you (Bob) touching one card. You see a red 1 in Cathy's finesse position. Conventions says you should write "r2 if r1 plays, else r1", but you are taking a turn
> - Without knowing if Cathy has a safe action
> - Without knowing what Cathy's finesse position is
> - Without knowing which red cards are now playable 
> 
> As a result, you can't really
> 
> - Clue any red card, as you don't know whether red 2 has been gotten
> - Perform any move that asks for a blind play from Cathy, as you don't know what her finesse position is
> - Let a card ride on Cathy's chop, as she might not have a safe action
>
> Finally, giving something more urgent to Cathy also keeps you in the dark one extra turn.
>
> Players will generally try to read whether it was a finesse or a direct play clue, and I think that conventions should instead state that Bob is allowed to assume it's a finesse and play accordingly...

**Option 1:** The simplest change H-group could make would be to specify at Level 1 that you are not allowed to play-clue a card that also appears on somebody's finesse position (i.e. "if it looks like a finesse it must be"). 

**Option 2:** However, Simon's scenario is less unclear if Bob and Cathy were swapped, so a smaller change would be "if it looks like a _reverse_ finesse it must be", because at least the blind-play (or not) would happen first.

**Comment by pianoblook** [comment]
> I'm pretty sure there's already rules saying not to stomp on a finessed?

Level 2: https://hanabi.github.io/level-2/#stomping-on-a-finesse

At low levels, this isn't a concern. At higher levels, 'Context' should solve it 99.9% of the time.

**Comment by gw12346** [comment]
To be clear, this proposal is not to stop **Bob** cluing Cathy's r1 (either stomping on Alice's finesse or duplicating his own r1, making Cathy think she has r2) in Simon's scenario. Current conventions already prevent this. 

Instead, this proposal is about stopping **Alice** from cluing Bob's r1 if Cathy also has r1 on finesse position. Bob would always know what card he's been clued about, because if anyone else has r1 on finesse position, he's _guaranteed_ to have r2 instead.

For example, back to Simon's scenario, under Option 1, after Alice's clue, Bob doesn't have to consider that his red card might be r1 and Bob is also _guaranteed_ to know what Cathy's finesse position is and whether Cathy has a safe action.

**Comment by kesslermaximilian** [comment]
I agree with piano there, context almost always solves this. Or contrarily: There are legitimate reasons to give such confusing clues (for example, you might want to pick up that nice b4 that bob also holds, even if it means bob thinking "b2" for one round because cathy also holds b1). Good players will just in general be aware of what type of confusion that clue causes - and just not give it if it risks losing that 5 on cathy's chop.

So both options to me seem very unneccessarily restrictive, I (and presumably most players) don't like them.

**Comment by vEnhance** [comment]
I also agree that I think this is too restrictive.

Generally, if such a clue is given, from context Bob will either write "r12" or "technically r12 but probably r2". So this change would only benefit the situations where Bob would write "r12" _and_ the one turn of ambiguity would cause some actual dilemma (i.e. there is some real urgent reason why Bob can't wait one turn to see if r1 plays) _and_ there wasn't any better (or at least similar-value) clue for Alice to give. That seems rare enough that I think the loss of flexibility doesn't justify this trade-off.
