### ISSUE TITLE
Convention Proposals/Clarification: Trash Bluff Ejection & Discharge

### ISSUE THREAD

**Issue by pianoblook** [hanabi/hanabi.github.io#1160]
Now that we've simplified things so that [Trash Finesses Are Always Unnecessary](https://hanabi.github.io/level-25/#trash-finesses-and-trash-bluffs-are-always-unnecessary), there are a couple important scenarios that I think might now currently be undefined. Below are a couple example scenarios, with suggested resolutions/clarifications:

**Example 1: Off Chop Trash**
> Max lvl, 3 player No Variant
> r1, y2, g3 have been played.
> Cathy's hand: `p3, r3, y1, g2`
- Alice clues 1 to Cathy
- Bob knows he's being called to blind-play as a _Trash Bluff_.
- However, Bob can see that since Trash Bluffs are now assumed to be _Unnecessary_, this will always result in Cathy _Chop Moving_ all bad cards, which seems bad.

### Proposal 1: Bad Trash Bluff Ejection
- If a _Trash Bluff_ move is given such that Bob can see that a _Bad Chop Move_ would result, he can therefore trust that a normal _Finesse_ response is not intended.
- Therefore, Bob should _Eject_ instead.
- Everything still resolves immediately; the touched card(s) are still obviously trash (or else Bob wouldn't have responded at all), and all cards to the right can be globally marked as _Known Trash_ as well.

------

**Example 2: On Chop Trash**
> Max lvl, 3 player No Variant
> r1, y2, g3 have been played.
> Cathy's hand: `p3, r3, r5, y1`
- Alice clues 1 to Cathy
- Bob knows he's being called to blind-play as a _Trash Bluff_.
- However, Bob can see that since Trash Bluffs are now assumed to be _Unnecessary_, Cathy would naturally assume this also becomes a _Trash Push_, which would be catastrophic.

### Proposal 2: Trash Bluff Push Ejection & Push Discharge
- If a _Trash Bluff_ move is given such that Bob sees that a _Trash Push_ would naturally result, he can immediately trust that his response should be based on the identity of the (would-be) _Pushed_ card:
> - If the card is playable or 1-away, he can blind-play as a normal _Trash Bluff_.
> - If the card is ≥2-away, he should _Eject_.
> If the card is _Unknown Trash_, he should _Discharge_.
- Everything still resolves immediately, similarly to the _Bad Trash Bluff Ejection_ above.

These are the arrangements folks like kimbi & piper & I played with for years, and it always felt natural & useful. It not only opens up more Ejections & Discharges, but can also allow for immediate _TOCM_ opportunities!

**Comment by Zamiell** [comment]
- con: more complexity
- con: cluing bob's slot 1 card might be blocked, and in such a situation chop moving trash is an acceptable tradeoff. (in a world where _Bad Trash Bluff Ejection_ exists, it might not be possible to get slot 1.)

**Comment by ricardodd2** [comment]
I like proposal 2 as a an addition to advanced level ejection and discharges. It adds options to the players that play with the convention, while not limiting options for players that doesn't (if you would see a trash finesse that pushes a card that would bomb, you simply don't give it). Furthermore it interacts neatly with the currently existing "Trash Push Ejection" and "The Trash Push Discharge".

**Comment by rz-1** [comment]
I like these b/c it adds more options for ejection and discharge. However, I think these make sense for 3 player, but what about 4+ player?
I see a scenario, similar to the example, where Alice clues Donald. Bob plays fp into the trash bluff, and then Cathy ejects/discharges from the BCME/push ejection/push discharge. Could we add a note about the ambiguity (simlar to DI) where Bob must check if Cathy has a playable/1away on 2nd/3rd fp? Or is that getting too complicated?

**Comment by argothiel** [comment]
Yes, this seems intuitive. For 4p it's on Cathy unless it's impossible. My only concern would be about Turnabout Ejection interaction.

**Comment by Stuurrm** [comment]
I quite like these. They do add more complexity but not an improper amount in my opininion. I have seen the opportunity do these already like 10 times so they would quite likely be rather common. Additionally the reason why we now unnecessary assumption is because trash bluffing #1 is almost always not necessary.

**Comment by Zamiell** [comment]
@pianoblook can you do a PR?

**Comment by pianoblook** [comment]
yeah, though I'm unsure about how we want to handle the case where Bob sees a playable in Cathy's slot 2.

Personally I see no reason why Bob shouldn't just Eject immediately - that seems like the simplest agreement, instead of the unnecessary complication of requiring him to assess what Cathy's hand is - but it looks like others have said slot 1 from Bob sounds more intuitive to them? What do we all think?

**Comment by Zamiell** [comment]
it was my understanding that this new convention only applies when all of the cards chop moved are trash.
thus, if the chop moved player has one or more non-trash cards (including playable cards), no special convention applies and it would be a "normal" trash finesse/bluff.

**Comment by pianoblook** [comment]
> mple, where Alice clues Donald. Bob plays fp into the trash bluff, and then Cathy ejects/discharges from the BCME/push ejection/push discharge. Could we add a note about the ambiguity (simlar to DI) where Bob must check if Cathy has a playable/1away on 2nd/3rd fp? Or is that getting too complicated?

^ I was referring to this comment. to write out an example:

- 4p NV, stacks being r1, g3, b3
- Donald's hand = x x r1 g2
- Alice clues 1 to Donald

So this proposal calls on Bob to Eject immediately, since he sees that (a) Donald will always cm, so (b) therefore he can immediately know that this is a form of BCME.
Two others have stated that they think Bob should still just play 1, *if* he sees that Cathy's slot 2 is playable. Personally I think that's adding unnecessary complexity, not to mention unnecessarily greedy - imo Bob should assume the line that requires the least blind-plays, aka simply his own slot 2, rather than his slot 1 + Cathy's s2.

**Comment by ricardodd2** [comment]
In the example piano gave I think Bob playing finesse and Cathy ejecting is more useful. If only Bob ejects the clue is just a 1 for 1+some trash on Donald which doesn't add much more value when a directly play clue can usually be given to Bob. While finesse+ejection is a 2 for one on slots that are not easy to get consecutively. To answer argothiel, turnabout, being a pink convention should take precedence over these imo.

**Comment by Zamiell** [comment]
> Personally I think that's adding unnecessary complexity, not to mention it's greedy - imo Bob should assume the line that requires the least blind-plays

agreed

**Comment by benzloeb** [comment]
The proposed trash push interferes with number ejections. Here are both situations, they look identical from Cathy's POV. 

Number Ejection example. 
Stacks: r1 p2
Alice: Clue Giver
Bob: X X g1 X X
Cathy: X X b1 r1

Proposed Trash Bluff 
Stacks: r1 p2
Alice: Clue Giver
Bob: X X g1 X X
Cathy: X X p2 r1 p1

**Comment by pianoblook** [comment]
> The proposed trash push interferes with number ejections[...]

You mean Trash Bluff Push Discharge interferes with Junk Discharge?

I think it's pretty clear that Junk Discharge would take precedence when multiple 1s are involved - but sure, could be worth noting explicitly. 

The Discharge is also less useful / frequent, I suspect, since the inherent presence of trash 1s makes it pretty common that you could just use color anyway. Ejections, on the other hand, can frequently be quite annoying to find.

**Comment by EhDrone** [comment]
> In the example piano gave I think Bob playing finesse and Cathy ejecting is more useful. If only Bob ejects the clue is just a 1 for 1+some trash on Donald which doesn't add much more value when a directly play clue can usually be given to Bob. While finesse+ejection is a 2 for one on slots that are not easy to get consecutively. To answer argothiel, turnabout, being a pink convention should take precedence over these imo.`

There is nothing wrong with giving a 1 for 1 + some trash on Donald. In most variants, 1 for 1s are more than sufficient - and even variants with ~1.2-1.3 usually dip down to under 1.0 req eff pretty quickly. There is inherent value in knowing trash as a safe discard. It opens opportunities for shout discards, TOCMs, etc.

If it ends up being a higher value clue than just a 1 for 1, great but I am leaning in favor of Occam's and simplicity.

**Comment by benzloeb** [comment]
I wrote the wrong thing. In the first example (reposted below), Cathy would assume it is either a Unknown Trash Discharge or a Unknown Dupe Discharge (which is kinda the same for 1s). 
Number Discharge example.
Stacks: r1 p2
Alice: Clues 1 to Cathy
Bob: X X g1 X X
Cathy: X X b1 r1

If there is only one 1, Bob should discharge, and once he does Cathy should push if it was unnecessary. 
Stacks: r1 p2
Alice: Clues 1 to Cathy
Bob: X X g1 X X
Cathy: X X p3 r1

This still interferes with the proposed changes. The proposed changes would leave Cathy thinking her pushed card is trash. 

> > The proposed trash push interferes with number ejections[...]
> 
> You mean Trash Bluff Push Discharge interferes with Junk Discharge?
> 
> I think it's pretty clear that Junk Discharge would take precedence when multiple 1s are involved - but sure, could be worth noting explicitly.
> 
> The Discharge is also less useful / frequent, I suspect, since the inherent presence of trash 1s makes it pretty common that you could just use color anyway. Ejections, on the other hand, can frequently be quite annoying to find.

**Comment by pianoblook** [comment]
I think you're confused about something, so I'll just lay out all possibilities:

Your (new) first scenario = Alice clues 1; 
- If Bob Discharges, Cathy knows it's a UTD/Junk Discharge
- If Bob plays slot 1, Cathy knows they're all trash, plus Pushes immediately due to the recent 'assume unnecessary' convention.

second (new) scenario = Alice clues 1
- If Bob Discharges, Cathy knows it was a Trash Bluff Discharge, and marks the 'pushed' card as kt.
- If Bob plays slot 1, Cathy knows they're all trash, plus Pushes immediately due to the recent 'assume unnecessary' convention.

Perhaps your concern is if Cathy was to clue the r1 with color..? In which case that's just a normal UTD. But I'm not sure what's conflicting here.

**Comment by benzloeb** [comment]
> I think you're confused about something, so I'll just lay out all possibilities:
> 
> Your (new) first scenario = Alice clues 1;
> 
> * If Bob Discharges, Cathy knows it's a UTD/Junk Discharge
> * If Bob plays slot 1, Cathy knows they're all trash, plus Pushes immediately due to the recent 'assume unnecessary' convention.
> 
> second (new) scenario = Alice clues 1
> 
> * If Bob Discharges, Cathy knows it was a Trash Bluff Discharge, and marks the 'pushed' card as kt.
> * If Bob plays slot 1, Cathy knows they're all trash, plus Pushes immediately due to the recent 'assume unnecessary' convention.
> 
> Perhaps your concern is if Cathy was to clue the r1 with color..? In which case that's just a normal UTD. But I'm not sure what's conflicting here.

I'm keep getting the setups wrong on this, should be good this time. 

Stacks:
R0 G1 B2 Y1 P1

A: X  X  X  X
B: X  X  P2 X
C: X  X  R1 G1
Here you want Cathy to know its a number discharge. 

A: X  X  X  X
B: X  X  P2 X
C: X  B2 B1 G1
Here you want Cathy to know the pushed card is trash. 

My problem is that Cathy can't tell the difference between these 2 scenarios.

**Comment by Stuurrm** [comment]
As with all conventions that interfere with each other you just have to decide which one takes precedence which in this case should probably be UTD/UDD. This means that situation #1 plays exactly as it does now. In situation #2 Alice cannot give that clue which is exactly how it is now.

**Comment by pianoblook** [comment]
> I'm keep getting the setups wrong on this, should be good this time.

We're back to what I already addressed:

> You mean Trash Bluff Push Discharge interferes with Junk Discharge?
> I think it's pretty clear that Junk Discharge would take precedence when multiple 1s are involved - but sure, could be worth noting explicitly.

**Comment by Zamiell** [comment]
piano do you want to do a PR based on this https://github.com/hanabi/hanabi.github.io/issues/1160#issuecomment-1921908522

**Comment by pianoblook** [comment]
Sure, I will this week.
