### ISSUE TITLE
Critical fours

### ISSUE THREAD

**Issue by gw12346** [hanabi/hanabi.github.io#1170]
Given there's no page dedicated to critical fours yet, we could look at creating one.

During pick-up games with Newsun, Wshull, Tailz, and Kernel, our main agreements were
- no _critical color bluffs_ on fours (analogous to "no critical color bluffs on fives")
  - allowing _critical color bluffs_ on fours would let color be a single bluff, while rank would be a double bluff or charm. Better to allow them then?
- fours to be saved with rank instead of color (analogous to "save 5s with rank")
  - Newsun suggested _Florrat saves_ as an exception

**Comment by Zamiell** [comment]
> fours to be saved with rank instead of color (analogous to "save 5s with rank")

yes, that is the existing convention that we have historically used

> no critical color bluffs on fours (analogous to "no critical color bluffs on fives")
allowing critical color bluffs on fours would let color be a single bluff, while rank would be a double bluff or charm. Better to allow them then?

seems fine i guess, do you want to submit a PR?
