### ISSUE TITLE
Delete: 2 Saves Off Chop on the First Turn

### ISSUE THREAD

**Issue by Zamiell** [hanabi/hanabi.github.io#1176]
I don't think people use this convention, so let's delete it.

**Comment by EhDrone** [comment]
Deleting is fine i.m.o - but we could also replace it with a section that outlines how (I think) most people play? I can see people finding this happen late into their hanabi careers since it is rather uncommon and having no clue what to do. Something like:

>No Turn 1 Valid Clues
>Though rare, it is possible to have a turn 1 with no valid clues to gives [No 5s, no unique 2s on chop, no play clues]. When this occurs, we agree it is best to give a clue that causes the 'least' damage with a bomb [or the most 'benefit' with a bomb. This decision is highly contextual based on each individual game - but since any clue given will be interpreted as a play clue, it is up to Alice to choose the best option to bomb. This only applies to turn 1 where Alice has 8 clues and cannot discard. Once the first clue is given, if the game state immediately goes back to 8 clues [Bob discards], it is a standard 8 clue stalling situation.

> Sample of least 'damage'
> Alice sees no valid clues to give on turn 1. Alice sees that Bob has a y4 on chop, and Cathy has a y4 in slot 2. Alice chooses to clue Bob yellow touching his slot 5 causing y4 to bomb immediately. Cathy assumes Alice had no legal clues to give on turn 1 and chose a card to bomb. She is not promised the other copy of y4, but agrees that a random 4 is better to bomb than a 3 in Bobs hand.

> Sample of most 'benefit'
> Alice sees no valid clues to give on turn 1. Alice sees that Bob has a a p4 on finesse position. Alice sees that Cathy's hand is x x r3 b3 y3. Alice clues Cathy 3, touching her 3s. Bob bombs slot 1 (p4) and Cathy assumes Alice had no legal clues to give on turn 1 and chose to make Bob bomb while picking up all of her 3s.



Thoughts?

**Comment by Zamiell** [comment]
agree

**Comment by EhDrone** [comment]
See 
https://github.com/hanabi/hanabi.github.io/pull/1177
https://github.com/hanabi/hanabi.github.io/pull/1178

Moved it to Misc section because it didn't really fit in the 'Save Clues' section to me.
