### ISSUE TITLE
Make trash finesses and trash bluffs cm at Level 14

### ISSUE THREAD

**Issue by gw12346** [hanabi/hanabi.github.io#1187]
Since trash finesses and trash bluffs are now always unnecessary, at max level they always cm. We can streamline their treatment at level 14 and at max level by making them always cm at level 14 as well.

**Comment by J-Fricke** [comment]
Fully support this. At Max level unnecessary can be determined at times and possibly we do no cm. Easier to have everyone on the same page all through out the levels.

**Comment by pianoblook** [comment]
I support this too. It simplifies things nicely, and imo it intuitively ties the concept of "oh someone clued me known trash off chop" = with =  "this is a trash cm".

**Comment by J-Fricke** [comment]
PR: https://github.com/hanabi/hanabi.github.io/pull/1192

**Comment by Zamiell** [comment]
seems fine

**Comment by Zamiell** [comment]
this is completed in Newsun's PR
