### ISSUE TITLE
Delete Shadow Finesse

### ISSUE THREAD

**Issue by Zamiell** [hanabi/hanabi.github.io#1204]
It's too rare and too confusing to bother including in the conventions.
Never personally seen a successful one in all my thousands of games, and had one go wrong today.

**Comment by Zamiell** [comment]
Subsequently, if Shadow Finesse was deleted, I propose we would also delete the Shadow Finesse derivatives, like Reverse Shadow Finesse & Prophetic Finesse.

**Comment by argothiel** [comment]
I saw it once or twice… but never successful either.

**Comment by pianoblook** [comment]
My vote would be to move it to Hard Variant Rules. There's solid preexisting strategic justification for turning them off in low-Efficient vars anyway. 

I'd be more hesitant to throw our Prophetics, but if HGroup is looking to simplify then I guess it could certainly be one of the many defensible items that could appear on the chopping block.

**Comment by Stuurrm** [comment]
Shadows is one of those fun little conventions which have a rather small upside for increased complexity. I do not believe there is much wrong with them conceptually but for the sake of simplicity I would not cry if they went away.

**Comment by EhDrone** [comment]
I agree - I have never actually seen a Shadow performed outside a game specifically with piano / kimbi / piper. I think the concept itself is sound, and maybe could be moved to Hard Conventions (things like clue starved this probably would come up more to eek out efficiency). I am in favor of removing it from the doc or moving it specifically to hard convention section [to again rarely if ever be used :P]

**Comment by benzloeb** [comment]
I've been looking for them more often (I play CS) and I see them fairly infrequently in 4+ player. I'd like to completely overhaul the CS specific conventions, but am still currently testing our new rules. I personally think the entire advanced section is mostly for hard mode, so it doesn't make a huge difference to move it.

**Comment by Zamiell** [comment]
> and maybe could be moved to Hard Conventions

if both myself and adrone have never seen a shadow finesse, then i dont think they are suited for HVR (for the same reason that i want to delete them)

**Comment by NZadeh** [comment]
I will miss them... and maybe continue to try using them. :'(

"Known misplay"

**Comment by winsonnhm** [comment]
> I will miss them... and maybe continue to try using them. :'(
> 
> "Known misplay"

It will be interesting if some members of the community continues to make these "Known misplays" :'(
