### ISSUE TITLE
Trash Chop moving over Saving convention proposition

### ISSUE THREAD

**Issue by benzloeb** [hanabi/hanabi.github.io#1206]
If Alice trash chop moves a card that she could have just clued to save, and it is 1 away from playable, bob plays his front card. When Cathy sees this, she assumes this is a chop move ignition and plays the chop moved card. 

I believe for this convention, the chop moved card must be critical, so everyone knows it could have been saved. 

This convention is very similar to The Declined 5's Finesse, so some generalization might be able to be made. 

Example:
Turn 44
[https://hanab.live/shared-replay/1172478#49](https://hanab.live/shared-replay/1172478#49)
benzloeb clues red to darr, declining yellow as a valid save. Darr sees that yellow was a valid save. (4 wasnt because benzloeb has a unknown 4).

**Comment by argothiel** [comment]
If I were to name it, I would call it "Suboptimal Chop Move", as it's the same mechanism as described in "The Suboptimal Prompt & The Suboptimal Finesse & The Suboptimal Bluff" section:

- If the other copy of a card is in the trash, then the remaining copy is critical and needs to be saved. Critical cards of this nature can be saved with either a color clue or a number clue.
- If both types of clues will only introduce one new card, then it is said that that there is a Free Choice between the two clue types.
- In this situation, the clue type will be chosen that "fills in" other ancillary cards in the hand or gives important negative information.
- If a clue type is chosen that is clearly worse than the other one, then the clue giver must be trying to communicate something extra.
- The means that this innocent-looking Save Clue is really a Play Clue, and all of the in-between cards are called for.
- Note that for a Suboptimal Save Finesse to work, the clue has to be really bad, not just technically suboptimal in some slight way.

**Comment by Zamiell** [comment]
seems fine

**Comment by benzloeb** [comment]
So there is an extension of this idea that Vivarus came up with:
Suboptimal trash chop move discharge
If you trash chop move a critical card that could be save clued that is more than 1 away from playable, you must discharge to avoid conflict with 5 trash chop move ejection.

**Comment by Zamiell** [comment]
discharge is usually reserved for trash, i think it would be an ejection like e.g. 5 pull ejection.
but i think it would be better to intentionally leave that undefined

**Comment by argothiel** [comment]
Can't be an ejection here, because we already have a Bad Chop Move Ejection.

Which maybe should be Bad Chop Move Discharge then...?

**Comment by benzloeb** [comment]
Switching the ejection and discharge would be more intuitive, but I don't think we should. This proposed discharge is very rare because it must be suboptimal with a trash chop move specifically. I don't want to change Bad Chop Move Ejections which I do much more frequently with 5 chop moves.

**Comment by argothiel** [comment]
Maybe a Charm then? 😉

**Comment by benzloeb** [comment]
I only like making it a charm if finesse slot, ejection, and discharge are already defined. In this case discharge isn't so it makes sense to define that first. As far as naming this convention, I'm all ears, I knew the name I gave wasn't great when I gave it.

**Comment by Zamiell** [comment]
@benzloeb can you submit a PR?

**Comment by winsonnhm** [comment]
Does it mean that if you trash chop move a more than 1 away from playable critical, it implies a discharge?

But is it possible that it may bring confusion on
https://hanabi.github.io/level-25/#example-3---an-unnecessary-bad-chop-move-ejection-with-a-trash-push-discharge

In this doc section, the clue receiver will be pushed if Bob proved BCME with an ejection.

With the concept of
https://hanabi.github.io/level-25#trash-finesses-and-trash-bluffs-are-always-unnecessary
and
https://hanabi.github.io/extras/ejections/#the-bad-trash-finesse-ejection--the-bad-trash-bluff-ejection

Is it possible that Bob respected that Cathy will be pushed once BCME is demonstrated (by knowing it is unnecessary by empathy, or context), therefore Bob discharge for the “pushed” card to be marked as trash?

If above case happened, can Cathy successfully deduce if it is a trash push discharge by BCME, or the 2-away critical trash chop move?

**Comment by Zamiell** [comment]
> Does it mean that if you trash chop move a more than 1 away from playable critical, it implies a discharge?

no, to start with we will leave that undefined and treat it as a known mistake

**Comment by ricardodd2** [comment]
Treating it as a true finesse at max level (even if more than 1 away) seems beneficial and not clear enough imo

**Comment by Zamiell** [comment]
its been 3 weeks without benzloeb responding, does anyone else want to take over this PR?
otherwise i will close this issue
