### ISSUE TITLE
Now that Reverse Trash Finesses always chop move, the UFRTF is a duplicate convention

### ISSUE THREAD

**Issue by downvoid** [hanabi/hanabi.github.io#1209]
https://hanabi.github.io/extras/special-finesses#the-unnecessary-forced-reverse-trash-finesse-a-gentlemans-discard-that-looks-like-an-unnecessary-reverse-trash-finesse
https://hanabi.github.io/level-14#the-reverse-trash-finesse

The reverse trash finesse covers both the card being red 2 and the card not being red 2, which is the exact same as the UFRTF, so I think these are duplicate conventions.

**Comment by Zamiell** [comment]
ok i removed it

**Comment by Zamiell** [comment]
for reference, the convention was called "The Unnecessary Forced Reverse Trash Finesse (A Gentleman's Discard That Looks Like an Unnecessary Reverse Trash Finesse)"
