### ISSUE TITLE
Saving dark pink 34 with rank 5

### ISSUE THREAD

**Issue by gw12346** [hanabi/hanabi.github.io#1217]
Grey Pink, Dark Pink, and Dark Omni are a group of variants that generally don't apply pink promise to rank 5 clues. This allows for fake 5 pulls, cms, and saves on i34.

Currently there is an exception: in Dark Pink, pink promise does apply to rank 5 clues touching chop. What if we removed this exception?

1. **Consistency**: in Grey Pink, Dark Pink, and Dark Omni, there'd be a standard method of saving i34. (This also frees up pink to always be a play clue.)
2. **Efficiency**: 5 clues touch the same cards pink clues touch, but can also pick up extra 5s.

**Comment by Zamiell** [comment]
my two cents:

- i think pink promise is more valuable than any extra efficiency gain, for basically the same reasons that we value pink promise in a normal pink variant.
- i find the consistency argument more valuable/important, but still not valuable enough to warrant making the change.

**Comment by gw12346** [comment]
Very fair, and there's a good reason pink promise is one of the most important pink conventions!

Though in Dark Pink, we already ignore pink promise for rank 5 clues on slot 1, slot 2, slot 3, etc., so would it be that much more to also ignore pink promise for rank 5 to chop?

**Comment by Zamiell** [comment]
so the pro argument is that we get "more consistency" for people who commonly play these 3 very-specific variants.
but the con argument is that the convention does not really flow from basic logic.

imagine that you are a new player playing a dark pink game for the first time, without having explicitly read any dark-pink specific conventions.
it just makes intuitive sense that you would save a dark pink 3 with a pink color clue.
subsequently, there would be no first-order reason that "fake 5 saves" would be turned on.
if they were turned on, this would probably be highly surprising to you.

next, you could imagine playing playing dark omni for the first time.
in this situation, if you thought to yourself the question "if i designed the conventions, how would I save a dark omni 3?", you would naturally and intuitively come up with the idea of a "fake 5 save".
so the fact that a "fake 5 save" would be turned on in this variant would probably not be surprising to you.

**Comment by ricardodd2** [comment]
I like the idea of fake 5 saves/2 fake saves in dark pink, but I would not override the conventional way of saving 3 and 4 with pink. Think about it: how often pink is available to focus chop (as play clue) and rank 3/4 is not? Never! Only benefit of removing pink saves is sometimes you may avoid bad touch, but pink promise on 3/4 with pink is a much greater one imo. On the other hand I beleive that the option of fake saving multiple cards with rank 2/5 gaining efficiency is an advantage greater than pink promise requiring multiple clues, especially in dark pink where the team is not worried about bad touching multiple pinks.

**Comment by gw12346** [comment]
Great points, @ricardodd2 ! Yeah, I like the idea in your summary: we already have fake 5 pulls and fake 5 cm's, so why not also fake 5 saves in dark pink? 

Not many people play dark pink (4000 games compared to 400000 novar games), and I'd guess most of those who play dark pink are already comfortable remembering pink promise might not apply to 5s.
