### ISSUE TITLE
Update White to only 3&4 loaded

### ISSUE THREAD

**Issue by J-Fricke** [hanabi/hanabi.github.io#1221]
I find it's way more useful to leave 2 saves available to players than the odd occasion to get a card played from LPC on a rank 2 clue.

**Comment by Zamiell** [comment]
agreed.
i think it is confusing/weird/unintuitive that a rank 5 clue would have an exception but a rank 2 clue would not have an exception.
accepting this issue would solve that problem.

**Comment by english5040** [comment]
yeah, I support this

**Comment by argothiel** [comment]
I agree, playing with 2s not loaded is comfortable enough.

**Comment by english5040** [comment]
Thought I'd share my new thoughts. I've come to really like loaded 2s in white- the chances of a 2 getting stuck and leading to the team losing hand space has anecdotally (sample size ~6 games?) been far more important than extending the early game a turn or two. It only comes up sometimes but when it does, it's very crucial to get tempo on the white 2.

**Comment by ricardodd2** [comment]
I don't minf loaded 2s in white, but it seems that majority prefers playing with only 3 and 4 loaded. I would suggest changing the convention just to avoid confusion when the team forgets to agree on loaded 2s or not
