### ISSUE TITLE
Clarify Always Loaded principle

### ISSUE THREAD

**Issue by english5040** [hanabi/hanabi.github.io#1222]
Clarify the Always Loaded principle: if a specific type of clue, other than clues that are already conventionally a save, always looks like a save if it touches chop, it's AL.

What I'm going for is saying ALP doesn't apply to 5, Dark suit clues, and 4 in Critical Fours, using a unified argument. 2 can be added if we want to make White consistent.

**Comment by Zamiell** [comment]
this is how we play already (?) so I don't think this needs an issue

**Comment by Zamiell** [comment]
do you want to submit a PR?

**Comment by english5040** [comment]
alright, if we're ok with just changing how the convention is phrased then I'll make a PR. I thought that a change to the internal logic that keeps the current behavior would warrant an issue. I was trying to preempt the issue talking about 2 clues in white: according to the logic I gave, 2 would still be a save. In my PR I'll probably make an exception for 2

**Comment by Zamiell** [comment]
yeah making an exception for 2 would indeed warrant a new issue.
but newsun already opened that, see #1221 .
so for now just PR to clarify without changing anything

**Comment by english5040** [comment]
sorry, I meant, the outlined logical principle would have to be phrased as no loaded 5/dark suit/4 but yes to loaded 2s in white. My original phrasing didn't quite work

**Comment by Zamiell** [comment]
do you want to just close this issue then and wait for #1221 to be accepted/denied?

**Comment by english5040** [comment]
I'll temporarily close it
