### ISSUE TITLE
Turnabout Ejection precedence over 5NE

### ISSUE THREAD

**Issue by gw12346** [hanabi/hanabi.github.io#1227]
Specific conventions (turnabout in pink) should take precedence over general conventions (5NE in novar).

**Comment by Zamiell** [comment]
I think this is the way that people currently play.

By the doc it is currently undefined, which means that after a turnabout ejection, you would write notes for both the 5NE case and the turnabout case in the same way that you would write notes for a 4 charm + bubblegum case.

**Comment by ricardodd2** [comment]
I think being in superposition of a playable and a cm on a 2+ away is not feasable so people played with turnabout precedence already. Good to vlarify in the doc.
I'll also suggest adding turnabout inheritance on pink/omni 1s the same way it is done for pink 5s.

**Comment by Zamiell** [comment]
i added this bullet point at the bottom:

> - _Turnabout Ejections_ explicitly have precedence over all other conventions, including _5 Number Ejections_. In other words, if a clue could be a _Turnabout Ejection_, then players are supposed to assume that it is.
