### ISSUE TITLE
Convention Cleanup for 2024

### ISSUE THREAD

**Issue by Zamiell** [hanabi/hanabi.github.io#1230]
(Last thread: https://github.com/hanabi/hanabi.github.io/issues/804)

It is our responsibility to delete conventions that are rarely used, because some players forget about them, and other player's don't, and this causes lost games and desynchronization. See this very important document: https://github.com/hanabi/hanabi.github.io/blob/main/misc/convention-goals.md

For every new convention, we should also delete an old convention to keep the balance, so deleting rarely-used conventions makes space for other moves that will actually have a substantial impact to win-rate.

I propose that the following conventions are rarely-used and should be deleted. If you see a rarely-used convention that should be deleted that I did not include in the list, please bring it up below.

- [The Speed-up Clue](https://hanabi.github.io/extras/fix-clues/#the-speed-up-clue)
- [The Pestilent Finesse](https://hanabi.github.io/extras/special-finesses/#the-pestilent-finesse)
- [The Diseased Clandestine Finesse](https://hanabi.github.io/extras/special-finesses/#the-diseased-clandestine-finesse)
- [Signal Shifting](https://hanabi.github.io/extras/signal-shifting/)

Proposed to be deleted on September 12th (from english):

- [Black Save Bluff](https://hanabi.github.io/variant-specific/black/#the-black-save-bluff)
- [Crazy 3/4 Saves](https://hanabi.github.io/variant-specific/black-rainbow/#crazy-3-saves--crazy-4-saves)

Proposal to be deleted on September 12th (from downvoid)

- [The Time Travel Chop Move (Direct Form)](https://hanabi.github.io/level-17/#the-time-travel-chop-move-direct-form)
- [The Time Travel Chop Move (Blind-Play Form)](https://hanabi.github.io/level-17/#the-time-travel-chop-move-blind-play-form)

**Comment by downvoid** [comment]
isn't the signal shift page just a graph with other conventions? I don't see any new conventions on that page that don't already appear on another page

**Comment by english5040** [comment]
I'd take a look at the Black Save Bluff (I support deleting it as it causes confusion between it and Occupied Play Clues), and also Crazy 3/4 Saves in Black+Rainbow.

**Comment by Zamiell** [comment]
> I'd take a look at the Black Save Bluff (I support deleting it as it causes confusion between it and Occupied Play Clues), and also Crazy 3/4 Saves in Black+Rainbow.

sure, we can delete those.

**Comment by Zamiell** [comment]
updated the OP with the following moves:

- [Black Save Bluff](https://hanabi.github.io/variant-specific/black/#the-black-save-bluff)
- [Crazy 3/4 Saves](https://hanabi.github.io/variant-specific/black-rainbow/#crazy-3-saves--crazy-4-saves)
- [The Time Travel Chop Move (Direct Form)](https://hanabi.github.io/level-17/#the-time-travel-chop-move-direct-form)
- [The Time Travel Chop Move (Blind-Play Form)](https://hanabi.github.io/level-17/#the-time-travel-chop-move-blind-play-form)

**Comment by hm1298** [comment]
I agree that most of these seem to be underused.

I would also caution that the principles underlying Signal Shifting are not underused and in fact may benefit from greater explanation. This is somewhat true of Speed-up Clues as well, but I personally cannot think of a way to do so (and therefore support, by default, removing them). If Signal Shifting is not deleted, I would offer a PR or contribute to another issue focused on clarifying that page

Also, I am wary by default of removing the Time Travel moves from the docs. As a relatively "modern" addition to the doc, they may simply have not had enough time (heh) to reveal their full utility, both in terms of intuition/clarity and strategic benefit. If the majority of modern players find them unhelpful or detrimental, then this point is moot

**Comment by english5040** [comment]
The Time Travel Chop Move is very rare, but that set of conventions is designed with a logical principle in mind (namely, Minimum Clue Value principle, considering the clue to have to have some meaning.) I would be wary of removing it and making things inconsistent.

Maybe it may not deserve to be in its level, due to its rarity- we can move it to the special chop move section? I consider the convention very rare, but not too complex.

**Comment by english5040** [comment]
I'm also wary of removing the discussion for Diseased Clandestine Finesse. Not because I think the convention should stay, but because I want to keep the discussion on a player treating a clue that might be a Pestilent Double Bluff as something else. Defining when a PDB should be treated as something else is important.

**Comment by Zamiell** [comment]
> Defining when a PDB should be treated as something else is important.

I think the point is that by deleting DCF, PDB always takes precedence.

**Comment by argothiel** [comment]
Vote to remove:
* [The Speed-up Clue](https://hanabi.github.io/extras/fix-clues/#the-speed-up-clue)
* [The Pestilent Finesse](https://hanabi.github.io/extras/special-finesses/#the-pestilent-finesse)
* [The Diseased Clandestine Finesse](https://hanabi.github.io/extras/special-finesses/#the-diseased-clandestine-finesse)
* [Signal Shifting](https://hanabi.github.io/extras/signal-shifting/)
* [Black Save Bluff](https://hanabi.github.io/variant-specific/black/#the-black-save-bluff)

Vote to keep:
* [Crazy 3/4 Saves](https://hanabi.github.io/variant-specific/black-rainbow/#crazy-3-saves--crazy-4-saves)
* [The Time Travel Chop Move (Direct Form)](https://hanabi.github.io/level-17/#the-time-travel-chop-move-direct-form)
* [The Time Travel Chop Move (Blind-Play Form)](https://hanabi.github.io/level-17/#the-time-travel-chop-move-blind-play-form)

**Comment by argothiel** [comment]
Some reasoning - I've played in several games when the topic of TTCM and the discussion on what it would mean appeared. That's quite a lot for a "rarely used" convention, other H-group conventions I have never seen or seen it maybe once.

Crazy 3/4 Saves just seems intuitive to me and should be a pretty common issue in Rainbow & Black (although I don't play them that often to notice).

**Comment by Zamiell** [comment]
maybe this is a little late, but I would also like to add the Distribution Finesse to the list of things to delete.

**Comment by Zamiell** [comment]
Conventions voted for deletion:

- The Speed-up Clue
- The Pestilent Finesse
- The Diseased Clandestine Finesse
- Signal Shifting
- Black Save Bluff

Rarely-used conventions voted to be kept:

- Crazy Saves
- All conventions from level 17

**Comment by Zamiell** [comment]
I'll open a separate issue for the Distribution Finesse.
