### ISSUE TITLE
Add hyperlinks to definitions of convention terminology

### ISSUE THREAD

**Issue by kimhanm** [hanabi/hanabi.github.io#1237]
Improve information accessibility for terminology in the convention reference document by linking terms to their definition.

Here is an example of how a new player reading the conventions could be confused.
Suppose one reads the convention for the "White" variant. One stumbles upon the "Always Loaded Principle" and looks it up.
There one reads the word "loaded" and tries to look it up. In the search bar, one only finds references to other variants and the "Loaded Play Clue (in Hard Variants)". But since white is not considered a hard variant, one thinks this is not relevant. And is stuck trying to find the definition of "loaded".

**Comment by Zamiell** [comment]
seems to be closed by #1238
