### ISSUE TITLE
Incomplete sentence in level 3 thing

### ISSUE THREAD

**Issue by downvoid** [hanabi/hanabi.github.io#1241]
https://media.discordapp.net/attachments/140016142600241152/1287888811925307483/image.png?ex=66f32f6c&is=66f1ddec&hm=75c6662cbe02e84cc0a5d31ddedb60ce7fa04a16fb14041037e86c34e7f1c91d&=&format=webp&quality=lossless

**Comment by Zamiell** [comment]
thanks, fixed here https://github.com/hanabi/hanabi.github.io/commit/9ae72d6accee28c8ee8666e64c84bde1881df71f
