### ISSUE TITLE
New form of bubblegum bluff

### ISSUE THREAD

**Issue by Dr-Kakashi** [hanabi/hanabi.github.io#342]
![2020-08-14_16-06-28](https://user-images.githubusercontent.com/48993588/90298844-93fc0480-de48-11ea-9f63-1f4a85f72446.png)
Normally, bubblegum bluffs can only be done with pink cards that are 1 away from playable. 
Here Plus can give 2 to Kimbi touching i3.
Kakashi will play slot 2 to show a bubblegum bluff is occurring.  
Kimbi marks i3 as i2, but wait if it really was i2 then Kakashi would've played slot 1, thus this is not i2.  
If it was i1, then Kakashi would've done nothing. 
Thus this is i3 and the note Kimbi writes on the card.

**Comment by Zamiell** [comment]
seems esoteric.
probably doesn't need its own doc entry unless it becomes very common

**Comment by iamwhoiamhahaha** [comment]
We can call them *Bubblegum 3 Bluffs*

And here's the example:
https://hanab.live/replay/383927

Note that if IAMJEFF blind-play slot 1 right after jeff10 blind-play slot 2, macanek should probably mark his 2 as an i4 as a *Bubblegum 4 Double Bluff* or a b2 if https://github.com/Zamiell/hanabi-conventions/issues/199 is a thing

**Comment by iamwhoiamhahaha** [comment]
https://hanab.live/replay/387021#3

**Comment by iamwhoiamhahaha** [comment]
can this issue be reopened?

**Comment by pianoblook** [comment]
This has been super consistent + not very uncommon if memory serves. I feel like most players comfortable in pink have been playing with this on these days

(I wish it was easier to find old examples of this sort of thing w/o manually going back through replays)

**Comment by Zamiell** [comment]
if players are playing with it, then show 3 examples where it worked and was the best and/or most clear move

**Comment by pianoblook** [comment]
Here are some from my own games:

https://hanab.live/replay/543292#3
https://hanab.live/replay/463259#4
https://hanab.live/replay/387021#3
https://hanab.live/replay/541072#6
https://hanab.live/replay/507080#5
https://hanab.live/replay/463259#4
https://hanab.live/replay/458560#5
https://hanab.live/replay/423742#8 (getting the matching 1 lol)
prompt version: https://hanab.live/replay/474054#3

**Comment by Zamiell** [comment]
good, if no-one else objects in 2 weeks or so, then submit a pr

**Comment by sjdrodge** [comment]
No objection. I don't know if you remember, Zamiel, but when we were originally specifying Bubblegum Bluffs, we decided to outlaw "Bubblegum 3 Bluffs" and just pretend ignorance of the fact that there's an obvious meaning for a 2 clue to an i3 that gets a non-pink blind-play. It's not at all surprising that other players noticed after all :).

**Comment by Dr-Kakashi** [comment]
I think it's misleading to call it Bubblegum 3 bluff. This can work with any of the pink cards.

For Example:
Playfield: i1 is down

Cathy's Hand:
x - x - i4 - x - x

Alice clue's 3 to Cathy only touching i4
Bob blind plays slot 3 

Even though i4 is 2 away, no other cards are promised because Cathy immediately writes i4 on her clued card.

Basically, this can only be performed on an n card with a n-1 clue.
In the original post a i3 (n) was clued with a 2 (n-1) clue
In the example in this post i4 (n) was clued with a 3 (n-1) clue.

**Comment by Zamiell** [comment]
Distant Bluff

**Comment by sjdrodge** [comment]
False Promise Bluff

**Comment by pianoblook** [comment]
Deceptive Bubblegum Bluff?

**Comment by Zamiell** [comment]
as always, i prefer one-word move names for ease of communication

**Comment by iamwhoiamhahaha** [comment]
https://hanab.live/replay/584251
Wittvector went offline during the game btw

**Comment by Zamiell** [comment]
submit a pr

**Comment by sjdrodge** [comment]
Regarding the name of this convention. Let's please please not call it Distant Bluff. That name is misleading at best, and the virtue of being shorter only goes so far.

**Comment by pianoblook** [comment]
Gumshoe Bluff
Chewed Bluff / Stretched Bluff
Bubble Burst/Pop
Bubbly Bluff
Taffy Bluff
Pink Wink

**Comment by Zamiell** [comment]
Taffy Bluff is fine

**Comment by iamwhoiamhahaha** [comment]
i thought kakashi would do that

**Comment by Zamiell** [comment]
i think you should be the one responsible since you asked for the issue to be reopened
also, kakashi has a history of not checking github ever

**Comment by iamwhoiamhahaha** [comment]
i've told him to submit the pr
also, how about the name *Doublegum Bluff*?

**Comment by Zamiell** [comment]
sure

**Comment by Zamiell** [comment]
although since its rhymes its a little confusing

**Comment by Dr-Kakashi** [comment]
Can we come to a consensus on a name? I would really like something that says 2 Away Bubblegum Bluff. I like the creative names so far, but none of them really say it's a Bubblegum Bluff. I guess what I really want is a word that says 2 Away or Away Away in some manner.

**Comment by Zamiell** [comment]
should probably a find a name that doesn't sound like bubblegum

**Comment by Dr-Kakashi** [comment]
How about Distant Bubblegum Bluff. I know Stephen didn't want Distant Bluff and I agree we shouldn't replace any of the words of Bubblegum Bluff. Here we can replace just the word Distant, if someone comes up with a better name. If not, we'll just go with this. I'll give it a few days for brainstorming and then do the pull and close.

**Comment by Dr-Kakashi** [comment]
Below is a rough draft so we can review/edit and I can easily copy and paste when it's time to pull. Also I'm using the example in Bubblegum Bluff changing the pink 2 on slot 5 to pink 3 and moving Bob's Red 1 card to slot 2. I don't know how to generate an image to put in the doc. 

### Distant Bubblegum Bluff

- Similar to a _Bubblegum Bluff_, it is possible to perform a Distant Bubblegum Bluff.
- A Distant Bubblegum Bluff is when a 2 away pink card (n) is clued to initiate a single bluff on slot n-1.
- For Example, in a 3-player game:
      - It is the first turn and nothing is played on the stacks.
      - Alice clues number 2 to Cathy, touching a pink 3 (n=3) on slot 5 
      - Bob knows that Alice is violating _Pink Promise_. This must mean that he is supposed to play his slot 2 card (n-1=2). 
      - Bob blind-plays slot 2 and it is a red 1.
      - Cathy knows that if this was a _3 Bluff_, then Bob would have played his _Finesse Position_. So it cannot be a _3 Bluff_.
      - Thus, Cathy knows that this must be a Bubblegum clue. Since red 1 is not a pink card and Alice was in _Bluff_ Seat for Bob, this must be a _Bubblegum Bluff_.
      - Cathy marks her slot 5 card as the one-away-from-playable pink card, the pink 2, but wait a minute. If it was pink 2, then it would be a Bubblegum Finesse, if it was in any other slot in her hand. In this case, a 2 on slot 5 is just a 2 save, so it shouldn't induce any blind play from Bob from her POV. 
      - Since it is not the pink 2, Cathy marks her slot 5 card as the two-away-from-playable pink card, the pink 3.
- If you want to use other 2 away pink cards, two away pink 4 (n=4) for example, then it should only get a blind play from n-1 = 3 or slot 3.

**Comment by sjdrodge** [comment]
I'll throw my support behind Taffy Bluff.

**Comment by Dr-Kakashi** [comment]
https://github.com/hanabi/hanabi.github.io/pull/731

### Taffy Bluff
- Similar to a Bubblegum Bluff, it is possible to perform a Taffy Bluff.
- A Taffy Bluff is when a 2 away pink card (n) is clued using rank to initiate a single bluff on slot n-1.
- For Example, in a 3-player game:
  - It is the first turn and nothing is played on the stacks.
  - Alice clues number 2 to Cathy, touching a pink 3 (n=3) on slot 5
  - Bob knows that Alice is violating Pink Promise. 
  - If he plays slot 1, then Alice will mark it as the matching 2 and will bomb it.
  - This must mean that he is supposed to play his slot 2 card (n-1=2) as a bubblegum bluff for pink 1.
  - Bob blind-plays slot 2 and it is a red 1.
  - Cathy knows that if this was a 2, Bob would've played slot 1. Thus, it is not a 2 and Cathy knows that this must be a Bubblegum clue. 
  - Since red 1 is not a pink card and Alice was in Bluff Seat for Bob, this must be a Bubblegum Bluff.
  - Cathy marks her slot 5 card as the one-away-from-playable pink card, the pink 2, but wait a minute! If it was pink 2, then it would be a Bubblegum Finesse, if it was in any other slot in her hand. In this case, a 2 on slot 5 is just a 2 save, so it shouldn't induce any blind play from Bob from her POV.
  - Since it is not the pink 2, Cathy marks her slot 5 card as the two-away-from-playable pink card, the pink 3.
  - Because Cathy is able to immediately identify her clued card, the entire table understands that the situation is immediately resolved.
- If you want to use other 2 away pink cards: 
  - Two away pink 4 (n=4) would get a blind play from n-1=3 or slot 3. Pink 4 would be clued with 3.
  - Two away pink 5 (n=5) would get a blind play from n-1=4 or slot 4. Pink 5 would be clued with 4.

**Comment by Zamiell** [comment]
### The Taffy Bluff

- First, see the section on the *[Bubblegum Bluff](#the-bubblegum-bluff)*.
- A *Bubblegum Bluff* is when *Pink Promise* is violated on a *one-away-from-playable* pink card to perform a *Bluff*.
- It is also permissible to violate *Pink Promise* on a *two-away-from-playable* pink card to perform a *Bluff*. This is called a *Taffy Bluff* to distinguish it from the former case.
- For example, in a 3-player game:
  - It is the first turn and nothing is played on the stacks.
  - Alice clues number 2 to Cathy, touching a pink 3 on slot 5. (The pink 3 is *two-away-from-playable*.)
  - Bob knows that Alice is violating *Pink Promise*.
  - If he plays slot 1, then Alice will mark it as the matching 2 and will misplay it.
  - Thus, this must be a *Bubblegum Double Finesse*, meaning that Bob should play the slot that matches the rank that Alice chose.
  - Bob tries to blind-play pink 1 from slot 2, but it is a red 1 instead. It is now revealed to Bob that this was a *Taffy Bluff* instead of a *Bubblegum Double Finesse*.
  - Cathy knows that if her clued card was really a 2, Bob would have played slot 1. Thus, it cannot be a 2. Furthermore, there are no *Ejections* that match this situation, so this must be a *Taffy Bluff* on a pink 3.
- It is also possible to perform a *Taffy Bluff* with cards other than a pink 3. For example:
  - A *two-away-from-playable* pink 4 that is clued with a number 3 clue would cause a blind-play from slot 3.
  - A *two-away-from-playable* pink 5 that is clued with a number 4 clue would cause a blind-play from slot 4.
