### ISSUE TITLE
Convention Expansion: Double Ignition Blaze (with recluing trash)

### ISSUE THREAD

**Issue by pianoblook** [hanabi/hanabi.github.io#449]
As briefly discussed in general-in-depth-discussion today. This is a fusion of a few recognizable conventions:  _Junk Ejection_, _Double Ignition_, and _Blaze Discards_.

It also continues my fervent desire to break the game through the creation of more unambiguous _Ignition_-style clues (such as Blaze Discards & Shadows).

## Double Ignition Blaze ##

- If known trash is reclued, conventionally this signals a clean _Double Ignition (with Known Trash)_
- But what if Bob sees that no other teammate currently has a card on their own _First Finesse Position_ that could be made playable through a single blind-play? (e.g. either directly playable or cleanly cluable one-away from playable)
- In this case, Bob knows that blind-playing as normal would trigger a _Misplay_ due to another player assuming this was a normal _Double Ignition_.
- Therefore, Bob must be called to blind-play from a different Finesse Position.
- If a teammate has a playable or one-away playable on their _Second Finesse Position_, he should therefore play his own _Second Finesse Position_. If not, then he should look at _Third FP_ and so on.
- Much like a normal _Double Ignition_, this blind-play will still "_Ignite_" the teammate's hand...only the card being signaled to play is now in a different slot

**Comment by Jayhui-q** [comment]
Big fan of this! I totally agree that something odd is happening when Bob sees no one has anything on finesse. 

When conceptualizing this are you thinking of all other players besides Cathy as well? That is, should Bob first be thinking about an OOP double ignition depending on how necessary the clue was to win in end-game?

If such a move can only be done on Bob and Cathy, that might save on a lot of confusion.

If the OOP is the first consideration, then there might be many instances where Cathy/Donald/Emily
- have a playable behind one-away-from-playable (though it seems like you are suggesting that left to right takes precedence over playability, not that I am opposed to that!)
- share a finesse position with a playable/one-away from playable, causing some ambiguity on which is desired by Alice

Totally on board if this is only legal on Bob/Cathy. A little hesitant otherwise, and would also need to think more about whether Bob should look at Cathy's hand with the priority flow-chart in mind on what slot to play.

**Comment by pianoblook** [comment]
I'm not actually sure what the current conventions say about Double Ignitions - I assume that Cathy should not usually blind-play in response if she sees that Donald/Emily also has a slot 1, but I might be remembering that wrong.

I'd vote to keep this consistent with whichever way Double Ignitions are currently structured. It's a pretty interesting tradeoff between simplicity vs flexibility.

**Comment by Jayhui-q** [comment]
I believe the current double ignition is only on the very next two players (though when desperate I have a habit of always entertaining it out of position).

I think a relevant conversation is if Cathy has a one-away from playable on finesse but a playable on the ejection slot, should Bob play slot 1 or slot 2? (same logic extends for eject/discharge)

I am totally at a coin flip for which makes more sense, but it seems to me like it is way more likely that a straight finesse could be given if Bob played the connecting card?

This comes into conflict with the default read of a double ignition (two from finesse) but I would be stoked to make it read:
If Cathy's finesse is not directly playable, then Bob should play the matching finesse position of the highest priority unclued card in Cathy's hand 😊

**Comment by pianoblook** [comment]
yeah the distinction I decided on - and this is inspired by Jeff's Double Bluff Ejection proposal - is whether Cathy's one-away card *could* have been cleanly used to finesse:

> But what if Bob sees that no other teammate currently has a card on their own First Finesse Position that could be made playable through a single blind-play? **(e.g. either directly playable or cleanly cluable one-away from playable)**

**Comment by pianoblook** [comment]
There's also a different option, which would be to simplify+combine this with Double Play clues:

- If a clue retouches a  _Known Trash_ **or** a card that was already given a direct _Play Clue_ (e.g. a 1), this is essentially a _Hard Burn_
- Bob should therefore first see if this is a _Double Ignition_ : he checks if Cathy's slot 1 is playable (or 1-away but not cleanly able to be clued itself).
- If he sees this can't be a _Double Ignition_, Bob should instead _Eject_.

The even spicier version of this would be modulating between an Ejection vs Discharge based on whether or not Cathy's slot 1 is trash or a 2+ away, but that's confusing based on our current convention framework for stuff like pushes/pulls

**Comment by iamwhoiamhahaha** [comment]
cool idea

**Comment by pianoblook** [comment]
lol this example works here as well: recluing trash (or really any ignition clue at this point?) can't be a true double ignition, so lel0uch must be called to play slot 3 instead

This *definitely* seems like a nice extra tool for late-game scenarios where you're at 2 strikes (though in this case you can also do a Trash Pull Discharge (cross-posted this in #363 )

<img width="1260" alt="Screen Shot 2020-12-30 at 1 01 07 AM" src="https://user-images.githubusercontent.com/32303453/103333164-e118f580-4a3a-11eb-8f01-3b5580301d43.png">

**Comment by Zamiell** [comment]
seems like a fringe thing.
needs more evidence

**Comment by Zamiell** [comment]
#441 had 8 examples, this issue has 1 example

post more evidence or we must close this

**Comment by pianoblook** [comment]
This is still way too theoretical and rare.

Also directly conflicts with #441. RIPeronis
