### ISSUE TITLE
Trash Push Ejection Examples

### ISSUE THREAD

**Issue by pianoblook** [hanabi/hanabi.github.io#450]
I'll actually try to put in an effort for sharing examples of these. It's one of those things that's just been so intuitive that we just do it without thinking about it

<img width="1246" alt="good trash push ejection (chop card was KT)" src="https://user-images.githubusercontent.com/32303453/103095902-3636b080-45d0-11eb-8a22-c83d1fda79b0.png">
(note - y2 wasn't known or anything; I just took this screenshot retroactively.) Also note that a 5ce would *not* work here because it would look like a prompt + finesse

<img width="1245" alt="Useful TPE" src="https://user-images.githubusercontent.com/32303453/103095908-3931a100-45d0-11eb-97b0-c01ebe58639e.png">
(this is an old game's hypo - in game we just clued my 1 directly and therefore needed to spend another clue saving a copy of m4 soon after)

**Comment by pianoblook** [comment]
<img width="1100" alt="Screen Shot 2020-12-29 at 12 14 45 PM" src="https://user-images.githubusercontent.com/32303453/103301445-7383af80-49cf-11eb-9053-b387d8e1e736.png">

1 to ADrone to get c2 while CMing c4 (and actually I think c4 is the only card left on the board this could be, so it's a clean 2-for-1)

**Comment by Jayhui-q** [comment]
Lovely :)

**Comment by pianoblook** [comment]
5cm doesn't work because it might be a stall w/ context. ejection doesn't work because of blocking cards

<img width="1237" alt="Screen Shot 2020-12-30 at 12 29 11 AM" src="https://user-images.githubusercontent.com/32303453/103331933-1242f700-4a36-11eb-912d-1e05a575f4c9.png">

**Comment by Zamiell** [comment]
### Trash Push Ejection

- First, see the section on the [Trash Push](#the-trash-push).
- Normally, when known trash is touched as the focus of the clue, and the known trash is on chop, it communicates a *Trash Push*.
- However, what if the *Trash Pushed* card is two-or-more-away-from-playable? This would normally be a *Trash Push Double Finesse* on Bob, but that is unlikely.
- Instead, we agree that similar to the rules for *5 Color Ejection*, if the *Trash Pushed* card would require two-or-more-blind-plays from Bob, then he interprets the clue as an *Ejection*.
- After a *Trash Push Ejection*, the clue reciever should *Chop Move* the two-or-more-away-from-playable card.

**Comment by rz-1** [comment]
Doesn't the first example with n5 violate the 2 or more blind plays convention because pianoblook has an already clued brown card in hand?

**Comment by pianoblook** [comment]
Conventionally we never allow for _Layered Trash Pushes_, though - so pianoBob only needs to see that no single blind-play on his part would be able to make n5 **immediately** playable

**Comment by rz-1** [comment]
Would it make more sense to change the 4th point to:

> * Instead, we agree that similar to the rules for _5 Color Ejection_, if the _Trash Pushed_ card would require two-or-more-plays from Bob, then he interprets the clue as an _Ejection_.

**Comment by pianoblook** [comment]
I would agree to change the 4th bullet - it's actually not very similar to 5ce.

maybe something like:

> Instead, since no single play could ever prevent the _Pushed_ card from immediately misplaying, Bob interprets the clue as an Ejection.

**Comment by Zamiell** [comment]
ok i edited it to be that, thanks
