### ISSUE TITLE
Replay Double Ignition, Poke Double Ignition & Ejection Counterparts (Formerly Burn/Exhaust)

### ISSUE THREAD

**Issue by Jayhui-q** [hanabi/hanabi.github.io#460]
_**EDIT: Below is a bunch of thought processes for how it came about. Scroll down to the bottom to see a more concise explication of the move.**_

First of all, massive massive credits go to kevincaseytdk1 for thinking through a lot of this with me and creating much of the groundwork for this idea. This idea tries to unify and simplify other conventions and provide for a simpler, more consistent way to get two unrelated cards off of finesse (as the current double ignition does).

I present to you: 
## The Useless Clue Framework

We define a useless clue to take any of the following forms:
1. A re-clue of globally known trash
2. A clue that focuses on a globally known playable card
3. A re-clue of a non-playable with no additional fill-in information given, and it is not a finesse

An otherwise useless clue, which is not an allowable stall, communicates to the team that there are two blind-plays to be had from finesse (Useless Double Finesse, or UDF)

_________

Notice the unified relationship with existing conventions.
* Notably, the first version of the useless clue is akin to the double ignition (but more specific). 
* The second, unfortunately (or fortunately) conflicts with and rewrites a double play ejection (more on this later). 
* The third is consistent extends the no-information double bluff.

Let’s discuss each of these in turn, and why I think this is a great way to unify the three.

### Form 1: Re-Clue of Globally Known Trash
As Bob, I think a double ignition is notoriously hard to read. This is because I often wonder whether or not Alice really wanted me to eject/discharge and Cathy to blind-play as the unnecessary component. (Such as the conflict listed in the conventions with a bad chop move ejection). Instead, the proposed framework above only permits a re-cluing of trash as a double ignition.

A big value of putting double ignition higher in precedence (over, say BCME) as it currently stands is that sometimes there are not other ways to get two cards from finesse, and more often two cards are wanted from finesse than one card from ejection and one from finesse. However, I think this problem is highly alleviated by the second and third components of the framework, and it becomes very rare to not be able to clearly communicate two blind-plays from finesse in a different way.

### Form 2: Double Play Clue
I think a double play ejection is very curious as it is currently written. While useful, it doesn’t seem consistent with the signal shifting framework, as fix -> play is unique. In fact, it appears every blind-play option from Bob would tell Cathy that it wasn’t simply a fix clue (not just the ejection). 

Moreover, it is not clear what the unnecessary component of a DPE is (it’s not known trash or unknown trash. Does it call for a blind-play or a chop move? I think either way could totally make sense, such as telling Cathy to please please play instead of chopping and reminding her of the playable card). 

There’s also some trouble regarding desynchronization with the DPE. Does Cathy’s knowledge of the known playable involve other player’s hands? Or has Cathy not played in a while and it looks like she doesn’t know? The distinction between a DPE and a tempo clue chop move is sometimes very blurred (perhaps even the ejection looks like a signal shift to suggest the tempo clue chop move was actually on trash). 

Finally, a DPE is almost always a 1 for 1, and every time it is given I scratch my head about the blocking cards in my hand and the context for which this clue was not given just for style. 

### Form 3: A No-Information Clue
A re-clue of a non-playable (that is not a finesse) with no additional fill-in information given, is consistent with the logic of the no-information double bluff as currently written. If Bob does not play a card that matches, then two blind-plays (one more) from finesse are being asked for.

### Summary
In my view, all three of these put together make for a pretty neat and concise framework to approach getting two blind-plays from finesse: give an otherwise useless clue!

Another way of thinking of these clues, is that every clued card carries a state. It is: 
1) Known playable through cards clued or finessed, or 
2) Known trash and will be discarded, or 
3) Assumed good and will be kept in hand. 

A clue that does not correctly change the state of a card, or provide useful information, is deemed useless, and asks for two-blind plays from finesse.

Adopting this framework I think creates clarity and makes for new options. For example, 
* the double ignition (useless clue form 1) would not need to be confined to end-game, and is never confused with an unnecessary bad chop move ejection. 
* A DPE (useless clue form 2) is never read as a bad tempo clue chop move ejection, and causes less bombs when a tempo clue is actually desired (another player needs to have a playable finesse, otherwise it is definitely just desync about the card’s playability). 
* And I also foresee wider adoption of a no-information double bluff (useless clue form 3).

### Out of Order, and the Shadow Split Double Finesse
I don’t think that these finesses need to be in order either (Bob plays immediately, but it doesn’t need Cathy to play), but I am very open to discussion on this. 

For example, if they did not need to be in order, I think there’s a fun way to get three plays from finesse: The Shadow Split Double Finesse, or SDF (credits to Kevin).

If:
* Alice gives a 1-for-1 direct play clue to Bob (or the first of the three players with playables)
* Each player can see that at least two cards are playable from finesse from their perspective
* There exists a useless clue (non-stall) of any form (a re-clue to a 5, for example)
* Then, Cathy (or the second to last player with a playable) should blind-play finesse to ignite the next player’s hand to play, thereby getting three plays. This is the same theory as a Shadow Finesse, but the cards played don’t need to be in the same suit, hence the “split.” 

For example, 
* Bob, Cathy, and Donald all have playable finesses.
* Alice clues Bob’s finesse as a 1-for-1, and Bob plays.
* Cathy can see that Donald’s finesse is playable, sees that an otherwise useless clue could have been given, and scratches her head. She decides to play her finesse to demonstrate to Donald that it is on his finesse as well. 
* Donald completes the round by playing his finesse.

**Comment by pianoblook** [comment]
Well (and I've said this many times before :p)I love the idea of recategorizing a 'Double Play' clue into a Double Ignition. If it was truly a trash Fix, no blind-play would occur anyway.

If Bob can see that the Double Ignition interpretation would cause a bomb, he still _Ejects_ (just like a normal Double Ignition that would otherwise cause a bomb), which preserves a lot of the functionality of normal DPEs anyway.

**Comment by Jayhui-q** [comment]
> If Bob can see that the Double Ignition interpretation would cause a bomb, he still Ejects (just like a normal Double Ignition that would otherwise cause a bomb), which preserves a lot of the functionality of normal DPEs anyway

This one is interesting. My gut initially said that I would prefer this to be off just for simplicity and not having to think about both, but I think this is pretty consistent with the self-color ejection that already exists. 

That is, if a clue from Alice traditionally calls for two consecutive finesse blind-plays, and this is outright not possible without a bomb, then Bob should eject. (Another aside at why I think 4 number ejection makes more sense than charms, but oh well).

**Comment by Zamiell** [comment]
> I think a double play ejection is very curious as it is currently written. While useful, it doesn’t seem consistent with the signal shifting framework, as fix -> play is unique.

that's because signal shifting was invented as a post-hoc justification for the existing ejections/discharges and doesn't map on to all of them.
the "point" of DPE is that we have a readily-available ejection in the cases where 5CE isn't there.
it is the only ejection that is readily-available in a general card configuration

> Moreover, it is not clear what the unnecessary component of a DPE is (it’s not known trash or unknown trash. Does it call for a blind-play or a chop move?

the former

> Does Cathy’s knowledge of the known playable involve other player’s hands? Or has Cathy not played in a while and it looks like she doesn’t know?

i dont understand the question. you are only allowed to DPE on a playable card that is already known to be playable from the perspective of both bob and cathy

> The distinction between a DPE and a tempo clue chop move is sometimes very blurred

i dont think its blurred at all.
if it is known playable, then its a DPE, and if it isn't, then its a TCCM.
simple

> Finally, a DPE is almost always a 1 for 1, and every time it is given I scratch my head about the blocking cards in my hand and the context for which this clue was not given just for style.

Indeed, the point of DPE is not for efficiency purposes, its to get cards that are blocked, which is especially useful in e.g. brown

**Comment by Jayhui-q** [comment]
> that's because signal shifting was invented as a post-hoc justification for the existing ejections/discharges and doesn't map on to all of them equally.
Oh yeah, totally. I just say that to illustrate that, for the DPE there is no connection to the other conventions, and especially the previously existing rule which was simply "if finesse is insufficient, then we agree as a group that [arbitrary slot] is being called for." A finesse actually IS sufficient to stop a trash fix interpretation.

> if it is known playable, then its a DPE, and if it isn't, then its a TCCM
Agreed. These are simply mistakes. The blurred aspect only arrives when all of the other players think that the clue recipient should have had enough context to play it.

> if we wanted/needed more tools to be efficient, then we would delete it and reassign it to a 2-for-1
Yeah, this is totally a tool for efficiency, and the neat thing is that it is a tool that applies throughout the game (rather than just the end-game for double ignitions). The more 2's on the stacks, the harder it is to get two cards played on finesse (as 4 double bluffs are single bluffs).

The other benefit of this is just allowing for unnecessary bad trash chop move ejections in the end-game.

**Comment by Jayhui-q** [comment]
Here are a bunch of examples of times they were used! All of them were done in the past 22 days, since the initial post. 
I personally love this convention -- to me, this added efficiency does not come at the cost of clarity.

**Form 1:**
https://hanab.live/replay/388835#20
https://hanab.live/replay/388933#34

**Form 2:**
https://hanab.live/replay/410980#43
https://hanab.live/replay/392920#46 

**Form 3:**
https://hanab.live/replay/404729#43
https://hanab.live/replay/409143#45
https://hanab.live/replay/413007#45
https://hanab.live/shared-replay/392995#30
https://hanab.live/replay/392920#65
https://hanab.live/replay/388933#5
https://hanab.live/replay/398519#46

**Comment by Zamiell** [comment]
need more input on this from top players

**Comment by Jayhui-q** [comment]
Amusingly, there's some fun fire-themed wordplay that came to me recently and inspired me to draft it up as if it were a convention. (The SDF above would be named the Shadow Burn).

## Burn Ignition

* If a player is not in a [stall situation](https://github.com/Zamiell/hanabi-conventions/blob/master/Reference.md#allowable-stall-clues-stall-table) or [stalling for end-game purposes](https://github.com/Zamiell/hanabi-conventions/blob/master/Reference.md#burning-end-game-stalling), it would be very odd if they give a burn clue.
* The player chose not to discard and generate the team a clue, and is wasting a clue instead of giving a 1-for-1. Indeed, if they are not making a mistake, such a choice must have some other meaning.
* We agree that the intended meaning of the clue is an ignition. Namely, the burn clue _**ignites**_ the hands of the very next player and one other player, asking each of them to play their finesse positions. 
* Clues that call for a Burn Ignition can have three forms:
  1) A re-clue of a known playable through cards already clued or finessed.
  2) A re-clue of known trash.
  3) A re-clue of a non-playable that gives no-additional information.
* Burn Ignitions may not pick up new cards, and a clue is not a burn clue if it makes a previously unplayable card playable.
* For example, in a 3-player game:
  * Red 2 is on the stacks. 
  * Cathy holds a clued red 5 that is clued with 5.
  * Alice re-clues Cathy's 5 with 5.
  * Bob sees that either this must either be a finesse or a burn ignition. 
  * Bob sees that Cathy does not have red 3 on finesse. 
  * Bob marks red 3 and red 4 on his slots 1 and 2 and blind-plays green 1.
  * Cathy, seeing that Bob does not hold more blind-plays to satisfy a finesse, realizes that this is a burn ignition, and blind-plays as well. 
  * Bob removes his notes for red 3 and red 4, as Cathy revealed that it was a burn ignition.
  * This same example applies for re-clues of known playables or known trash, but Bob does not need to look at the cards of other players to determine if it is a finesse or prompt in those cases.
* It is strongly ill-advised to give a burn ignition if there are other means of getting the cards played. For example, the burn ignition is an information-less 2-for-1, while a direct finesse, a sequence of two bluffs, or a double bluff provides additional information and may pick up other good cards.

**Comment by Jayhui-q** [comment]
It only just now clicked to me the power of the statement that @pianoblook stated:

> If Bob can see that the Double Ignition interpretation would cause a bomb, he still Ejects (just like a normal Double Ignition that would otherwise cause a bomb), which preserves a lot of the functionality of normal DPEs anyway.

That is, giving a _Burn Ignition_ which would cause a bomb should actually call for an _Exhaust Ejection_ (or just the Burn Ejection, though I find the softer burn theme to be fun). Totally down to change the naming and the play on words! Here's what it might look like:

### Exhaust Ejection

* Normally, when a player gives a burn clue and they are not allowed to, it triggers a _Burn Ignition_. 
* However, what if the next player can see that a _Burn Ignition_ is impossible? In this situation, they instead intend for an _Ejection_ on the very next player. This is called an _Exhaust Ejection_ because a clue was exhausted without creating an ignition.
* For example, in a 5-player game:
  * All 1's are played on the stacks.
  * Cathy holds a clued 1 that is clued with 1.
  * Alice re-clues Cathy's 1 with red.
  * Bob sees that Alice did not give a legal stall clue, and knows that it can not simply be a burn.
  * Bob sees that no other teammate currently has a card on their _Finesse Position_ that could be made playable through a single blind-play. Thus, if Alice is not making a mistake, the clue isn't a _Burn Ignition_. It is instead an _Exhaust Ejection_.
  * Bob blind-plays his Second Finesse Position. It is a brown 2 and it successfully plays.
* Note that only in special cases can a re-clue of a non-playable cause an _Exhaust Ejection_. This is because Bob needs to be able to show that the clue is not simply a _Finesse_.
  * For example, this can be demonstrated through negative color information (such as through a color re-clue to Bob), an insufficient amount of card slots, or the presence of critical connecting cards in another player's hands.
____

Unfortunately, this creates a look-ahead component, but I think it is _tremendously helpful_ in terms of both added options as well as simplicity. It preserves much of the current functionality of the DPE, creates a new ejection opportunity when there is known trash, and in special circumstances when there is simply an unplayable card. 

These two together would cover many of the fields of:
1) No-Information Double Bluff (Burn Ignition encompasses this)
2) Double Play Ejection (Exhaust Ejection encompasses this)
3) Double Ignition (the extra tool allows some disambiguation for UBCME) 
4) Self Color Double Bluff (mostly covered by Burn Ignition, we would need language in the Burn Ignition for a color clue given to Bob to a non-playable. It's not covered currently because the color clue might actually provide information. This language might be simply a fourth form: "A clear fill-in clue")
5) Self Color Ejection (mostly, as above)

**Comment by Jayhui-q** [comment]
As a small note, unfortunately, the _Exhaust Ejection_ extension directly conflicts with #449.
This is because Cathy (or some other player if out of position) would be called to play her ejection slot as well afterward.

**Comment by rkass** [comment]
I like this a lot. I've always found DPE's rare to find and when they do exist not very useful. Two blind-plays I think are more common and more valuable.

**Comment by Zamiell** [comment]
jerry can you do a pr

**Comment by Zamiell** [comment]
also, does it make more sense to call it Burn Ejection, so that it matches Burn Ignition?

**Comment by pianoblook** [comment]
I'm happy to settle on this over the #449 Blaze idea btw - I'll close that down

**Comment by Jayhui-q** [comment]
> also, does it make more sense to call it Burn Ejection, so that it matches Burn Ignition?

Hmm, good question! I'll think about this for a bit and ask around.

> jerry can you do a pr

Sure thing! I can do it this week.
What would you like me to do with the no-information double bluff? 

Also, for the DPE, is there a place that you would like me to put old conventions?

**Comment by Zamiell** [comment]
> What would you like me to do with the no-information double bluff?

i dont know, can we just leave it the way it is?

i think i would prefer that you:
1) rename *Double Ignition* to *Trash Double Ignition* + make any necessary edits
2) make a new section called *Replay Double Ignition*
3) leave *No Information Double Bluff*

> Also, for the DPE, is there a place that you would like me to put old conventions?

put DPE in deleted_conventions.md

**Comment by Zamiell** [comment]
in TDI the two blind-plays can be on anyone on the team, i imagine that RDI would follow the same rules

**Comment by Zamiell** [comment]
we probably dont need the shadow split, open a separate issue for that if you strongly feel that it is common enough to be widely applicable

**Comment by Jayhui-q** [comment]
> i dont know, can we just leave it the way it is?

Yeah, we can! Asking because the ideas overlap, and it may get a little confusing with the ejection extension.
In addition, a no-information clue that doesn't cause two blind-plays from Finesse could lead to a _Triple Finesse._

> rename Double Ignition to Trash Double Ignition

Good call. 

> make a new section called Replay Double Ignition

I quite like the "burn" connection to "ignite" in terms of the naming. Also, replay doesn't capture the other forms, such as a re-clue of trash.

> in TDI the two blind-plays can be on anyone on the team, i imagine that RDI would follow the same rules, so you can copy paste the relevant bullet point

Yes! However, Bob must blind-play except in rare situations when a non-playable is re-clued.

> we probably dont need the shadow split, open a separate issue for that if you strongly feel that it is common enough to be widely applicable

Oh definitely. I currently have no plans on adding that. I need way more games in where that actually works and is actually optimal.

**Comment by Zamiell** [comment]
> Yeah, we can! Asking because the ideas overlap, and it may get a little confusing with the ejection extension.

conventionally bob would interpret this as a *No-Information Double Finesse* - meaning that there is no associated *Ejection* form of this move, correct me if I am wrong.

> replay doesn't capture the other forms, such as a re-clue of trash.

1) I'm proposing that a re-clue of trash would be a *Trash Double Ignition*, equivalent to Form 1 from your original post.
    - It's named that way because you ignite the cards by cluing trash.
2) I'm proposing that a re-clue of a playable card would be a *Replay Double Ignition*, equivalent to Form 2 from your original post.
    - It's named that way because you ignite the cards by re-cluing a playable card = re-play = replay.
    - I think that "Replay Double Ignition" might be more mnemonic than "Burn Double Ignition" because "Burn" doesn't really capture what is happening.

> Yes! However, Bob must blind-play except in rare situations when a non-playable is re-clued.

RDI is by definition is on playable cards, so your sentence is not computing.

**Comment by Jayhui-q** [comment]
> conventionally bob would interpret this as a No-Information Double Finesse - meaning that there is no associated Ejection form of this move, correct me if I am wrong.

A true finesse will always take precedence over the ejection. 

However, as above,

> Note that only in special cases can a re-clue of a non-playable cause an Exhaust Ejection. This is because Bob needs to be able to show that the clue is not simply a Finesse.
For example, this can be demonstrated through negative color information (such as through a color re-clue to Bob), an insufficient amount of card slots, or the presence of critical connecting cards in another player's hands.


> I'm proposing that a re-clue of trash would be a Trash Double Ignition, equivalent to Form 1 from your original post.
It's named that way because you ignite two cards by cluing trash.

Ah, I see what you mean. The distinction I am making is whether or not a new card is picked up. 

In _Trash Double Ignition_, I find it very distinct because it picks up a new card (known trash). In this proposal, all of the ignitions are explictly a result of not picking up a single card or providing useful information. It is also distinct, because the re-clue of trash is not confined to end-game (whereas interpreting the pick-up of a new card usually requires end-game context). Moreover, in this setting, the trash double ignition would also need to be associated with the ejection component. 

> I think that "Replay Double Ignition" might be more mnemonic than "Burn Double Ignition" because "Burn" doesn't really capture what is happening.

Agree on this if and only if this whole concept only applies to form 2. 
Burn captures all three. If I thought it was only important to rewrite double play ejection as replay ejection then 2/3 of this proposal goes away.

> RDI is by definition is on playable cards, so your sentence is not computing.

Apologies -- I am speaking of Burn ignition which is all three forms.

**Comment by Zamiell** [comment]
> For example, this can be demonstrated through negative color information (such as through a color re-clue to Bob), an insufficient amount of card slots, or the presence of critical connecting cards in another player's hands.

that type of ejection is confusing and seems unlikely to be useful.
do you actually have any examples of that?
above, it only looks like you listed form 1, form 2, and form 3.

**Comment by Jayhui-q** [comment]
> that type of ejection is confusing and seems unlikely to be useful.
do you actually have any examples of that?
above, it only looks like you listed form 1, form 2, and form 3.

Happy to remove it for now, especially given there hasn't been nearly as much time/discussion spent on the ejection extension. 

I can also remove form 3 above then to make everything more consistent, but I do feel fairly strongly that forms 1/2 should be conceptually different and placed differently than with the _Trash Double Ignition_.

**Comment by Zamiell** [comment]
ok lets remove form 3 then

**Comment by Zamiell** [comment]
form 1 and form 2 are so drastically different that i feel like you should give them different names.
one of the whole points of the whole convention framework is that we like to give unique names to everything.
i dont think there are any other existing conventions that have different "forms", because if they do have different forms, we just call them by a different name

**Comment by Zamiell** [comment]
so i think there are 3 moves:

1) *Trash Double Ignition* - brand new trash is introduced
    - has a *Trash Ejection* counterpart when Bob sees that Cathy does not have a playable card
2) *Replay Double Ignition* - playable cards are re-*Play Clued* (no new cards are introduced)
    - has a *Replay Ejection* counterpart when Bob sees that Cathy does not have a playable card 
3) *Tickle Ignition* - globally-known trash cards are re-touched (no new cards are introduced)
    - has a *Tickle Ejection* counterpart when Bob sees that Cathy does not have a playable card

**Comment by Jayhui-q** [comment]
> i feel like you should give them different names.

I hadn't thought of it that way since burns made sense to me as a unified form. However, I see your point about the elegance of distinguishing the two. 

For the third one, I would prefer _Nudge Double Ingition_  or _Poke Double Ignition_  (Nudge > Poke).

**Comment by Zamiell** [comment]
poke seems fine

**Comment by Zamiell** [comment]
in the Replay Ejection section, we need to clarify that it is turned off in the end-game

**Comment by Jayhui-q** [comment]
Sounds good!

**Comment by Jayhui-q** [comment]
Closing after the merge.
