### ISSUE TITLE
Delete Repair Finesse

### ISSUE THREAD

**Issue by Zamiell** [hanabi/hanabi.github.io#480]
bye bye

**Comment by Jayhui-q** [comment]
Agreed.

**Comment by florian-5f3759df** [comment]
Sure. I prefer players being in the mindset that they're expected to help out with a fix clue if something like this occurs, that's a much more robust way of playing. Now it's an easy mistake to forget about [Saving Playable Cards when the Preceding Cards Are Not Promptable](https://github.com/Zamiell/hanabi-conventions/blob/master/Reference.md#saving-playable-cards-when-the-preceding-cards-are-not-promptable) and instead bomb some random card.

Removing this gains clarity and tempo, and costs a tiny amount of efficiency. I think that's currently a good tradeoff. (To be honest, the convention should still happen occasionally in high sensitivity games as an uncodified context read, if the fix interpretation is bad enough, but that's fine.)
