### ISSUE TITLE
Delete Rank Choice Finesse / Rank Choice Bluff

### ISSUE THREAD

**Issue by Zamiell** [hanabi/hanabi.github.io#481]
i invented this shit convention in 2018 and it is a net negative, way to go zamiel

**Comment by padiwik** [comment]
It's great (necessary) in tricky situations where you have few clues and can't afford to give an ambiguous finesse...

Perhaps this has changed with all the new unnecessary moves?

**Comment by Zamiell** [comment]
post examples

**Comment by sjdrodge** [comment]
I'd like to keep the ability to turn save clues into play clues by choosing rank when either choice would be equally good, but I'd happily lose Rank Choice Bluff.

**Comment by Zamiell** [comment]
to be clear, this proposal only deleted rank choice finesse + rank choice bluff, but does not delete https://github.com/Zamiell/hanabi-conventions/blob/master/Reference.md#the-rank-choice-save-finesse
