### ISSUE TITLE
turn off priority when the team is at 2 strikes

### ISSUE THREAD

**Issue by Zamiell** [hanabi/hanabi.github.io#482]
i decree

**Comment by sjdrodge** [comment]
I suggested this in discord, not entirely facetiously, but I'm not convinced this a good idea. Players often tighten up their play once there are 2 strikes, which means priority mistakes are less likely at that point. Also, you often need the extra efficiency particularly badly if you've already had 2 strikes, so this might make it less likely to get a perfect score (though of course we optimize the conventions for highest average score, not highest chance of maximum score).

If we do add this to the convention set, I'd like it to come along with a lot of weasel words.

**Comment by florian-5f3759df** [comment]
Slight disagree. Such a conditional change is extra cognitive load and something players will forget, causing errors.
