### ISSUE TITLE
Delete The Trash Finesse (Weak Form)

### ISSUE THREAD

**Issue by Zamiell** [hanabi/hanabi.github.io#484]

**Comment by Jayhui-q** [comment]
Down for this. 
Have a few related topics that may be worth discussing:

Is this replaced in favor of the Junk Charm? #399 

Alternatively, does this mean that we can/should strengthen [trash touch elimination](https://github.com/Zamiell/hanabi-conventions/blob/master/Reference.md#trash-touch-elimination) to cases where there are more than 1 card missing?

I'm okay if neither is true -- I think removing the weak form trash finesse is good for simplicity, but I do think these are related threads to consider.

**Comment by Zamiell** [comment]
neither is true

**Comment by pianoblook** [comment]
I'd still be in favor of just deleting the Reverse form, since that was the part that was complicating stuff like UDD and Junk Charms.

As for Junk Charms, kipipi has been using them as a Blast now; piper's Charm is far superior as a 1-for-1

**Comment by Zamiell** [comment]
what is pipers charm

**Comment by sjdrodge** [comment]
WFTF is cool but it only consistently works with a tiny subset of players. Fine with saying goodbye.
