### ISSUE TITLE
Clarify Restrictions on 5 Double Pulls

### ISSUE THREAD

**Issue by pianoblook** [hanabi/hanabi.github.io#491]
Based on discussion over in #479 , folks have brought up some important edge-cases concerning 5 Double Pulls that currently aren't addressed in the doc.

It sounds like there's consensus that sometimes a 5DP should not be assumed **if the **5CM could just be deemed as 'optimal'**. I'll toss out the four types of examples based on the types of scenarios brought up:
 
Example A: Avoiding Bad Touch
> 4 player no variant
> b1 has been played
> Donald's hand is b1 x r5 b2
> Alice clues 5 to Donald

Example B: Delayed Playable
> 3 player no variant
> Donald's hand is x x r5 g3
> Bob has green 1 and 2 clued in hand
> Alice clues 5 to Cathy

Example C: Low Clue Count
> 5 player no variant
> All 2s have been played
> 1 clue remaining
> Cathy's hand is x x x [b3]
> Donald's hand is x x r5 b4
> Emily's hand is x x x g5
> Alice clues 5 to Donald

Example D: Duplicate seen elsewhere
> 4 player no variant
> all 1s have been played
> Cathy's hand is x g5 r5 b2
> Donald's hand is x x x b2
> Alice clues 5 to Cathy

---- 

For what it's worth, I do think Example D should work as a Pull, but I included it here in case others disagreed

**Comment by Zamiell** [comment]
example a - should not be a 5db
example b - should not be a 5db
example c - should not be a 5db
example d - assuming cathy cannot clue donald's hand, then it should not be a 5db since elim will get the card for free.
use occam's razor:
- 5db = 2 blind-plays as a 4-for-1
- 5cm = 1 blind-play as a 3-for-1

5cm wins.
on the other hand, if cathy can clue donald's hand, then she will, which ruins the line.
if that is the case, then it would be a 5db.

**Comment by Zamiell** [comment]
- Sometimes, it can be useful to *Chop Move* a playable card. Something is only a *5 Double Pull* if there is not some other good reason for the *Chop Move*. Specifically, the player might want to:
  - Avoid violating *Good Touch Principle*.
  - Save a *Delayed Playable* card that is followed by a critical card.
  - Save two important cards when there are a lot of cards to deal with and the team is low on clues.
  - Get a blind-play from *Elimination* when the duplicate is visible.
