### ISSUE TITLE
Bob's Truth Principle & Cathy's Match Principle

### ISSUE THREAD

**Issue by Zamiell** [hanabi/hanabi.github.io#493]
I suggest renaming
"How to Tell the Difference Between a Finesse and a Bluff (Part 1) - Recognizing Finesses on Other Players"
--> "Bob's Truth Principle (Part 1)"

and
"How to Tell the Difference Between a Finesse and a Bluff (Part 2) - Bluffs Are on "Mismatched" Cards"
--> "Cathy's Match Principle (Part 2)"

This is probably a bit better than the less-verbose "Truth Principle"  / "Match Principle" because it highlights that it is specific to Bob/Cathy

**Comment by Jayhui-q** [comment]
Ooh, I like this! This change makes a lot of sense to me.
