### ISSUE TITLE
Propose mention normal discard order for trash in level 2

### ISSUE THREAD

**Issue by cjwomack** [hanabi/hanabi.github.io#494]
I propose that normal discard order for trash should be mentioned in level 2. The normal order to discard trash is not mentioned until trash order chop moves in level 9. It can sometimes inadvertently get higher level players to move their chop... 

Also I don't see why trash order chop moves can't be moved to level 5 because this is a similar principle as order chop moves. If normal discard order for trash is mentioned in level 2 then I think there should be no problems.

**Comment by Zamiell** [comment]
> It can sometimes inadvertently get higher level players to move their chop

i dont see that as a problem. TOCM is a level 9 convention, so if you are playing a level 2 game, then a high level player interpreting something as a TOCM would be a mistake.

> Also I don't see why trash order chop moves can't be moved to level 5 because this is a similar principle as order chop moves.

because it is not necessary knowledge for beginners. trash is not normally clued in hand

**Comment by cjwomack** [comment]
Actually there was an occasion where higher level players thought it was a trash order chop move... despite playing level 5.

There have been a few occasions where I've played where the 5 is clued on chop with colour or the 5 is in someone else's hand so when the 4 comes up (and obviously the chop isn't coloured with the colour clue) that happens to give several trash cards.

**Comment by pianoblook** [comment]
It can happen, sure, but level ≤8 games should never have to come down to whether or not a TOCM could have occurred. Plenty of higher level conventions *can* be useful but as Zam said, it's not at all necessary.

Caring about the order in which you discard - and **also** constantly tracking the order that all your teammates discard - is a great example of something that can be *really* easily overlooked if you haven't played a whole ton of games already. Therefore, it makes a lot of sense that we don't want teams to try and rely on it until everyone is at least lvl 9.
