### ISSUE TITLE
Convention Proposal:  Licorice Pulls & CMs in Dark Pink/Omni

### ISSUE THREAD

**Issue by pianoblook** [hanabi/hanabi.github.io#496]
We already allow for [Psuedo 5 Saves](https://hanabi.github.io/docs/variant_specific/dark_omni_gray_pink/#pseudo-5-saves) in Gray Pink / Dark Omni, which means we're already used to disregarding _5 Pink Promise_ in these variants. 

This proposal extends this to off-chop 5 rank clues in order to allow for 2-for-1s, either as a CM or Pull. I believe it should also be allowed in normal Dark Pink, unlike Pseudo 5 Saves. We've already done a few successful fake pulls, though I haven't seen any of the 5CMs yet (well, outside of 2p) - they're conceptually the same, though.

I included some maybe-unnecessary language about how this might (rarely) interact with _Bubblegums + Wraparounds_. I know "non-variant-specific conventions always take precedence" anyway, but I figured I'd add this now in case that changes in the future. For now though, with conventions as-written, the "EXCEPTION" bullet points can be ignored.

### Licorice Pulls & Chop Moves (Fake Off-Chop 5s) ###
- If an off-chop Dark Pink, Gray Pink, or Dark Omni card is clued as a 5, this could mean one of several things:
> - If the focused card itself is **Playable**, this is a _Turnabout Ejection_.
> - Otherwise, if the card is exactly one-away from chop, this is acting as a _5CM_.
> - Otherwise, if the team is in _Low Score Phase_ and the card is two or more away from chop, this is a _5 Pull_.
> - If none of the above are true, this is a _Bubblegum Finesse_ of some sort.

- This means the clued player should always ignore _5 Pink Promise_ in situations in which a _5 Pull_ or _5 CM_ is performed.
- This move is Illegal if the clue could just be interpreted as a _5 Stall_. Therefore, the immediate next player can trust that such a clue is *never* a _Stall_ and can react accordingly (e.g. _Discharge_ as a 5ND).

- **EXCEPTION**: If the card is exactly one from playable, **AND** the card being _Pulled_ is not playable (or if the card being _5CM'd_ is trash), this should be respected as a _Promised Bubblegum Finesse_ for exactly the matching card.
- > If the response is a slot 1 blind-play which is **NOT** Pink/Omni, a _5 Pull Finesse_ interpretation takes precedence.

### In Game Examples

https://hanab.live/replay/369669#2

https://hanab.live/replay/368701#4

https://hanab.live/replay/369709#5
(this one needs some context: the y3 was known 3 from a _3 Discharge Shadow_ - but that's a different story

**Comment by pianoblook** [comment]
Also I don't really care about the name lol. Just figured it'd be cute to extend the pink-candy theme of Pink Promise-violating conventions. Licorice is darker though 🤷

**Comment by Zamiell** [comment]
you could probably just call it a *Fake 5 Pull* or a *Fake 5's Chop Move*

**Comment by pianoblook** [comment]
that's fine too

**Comment by Zamiell** [comment]
can you do a pr

**Comment by pianoblook** [comment]
oh wtf I never saw this notification - yeah, will do. sorry bout that!
