### ISSUE TITLE
Unnecessary Ignitions do not need to be from Bob

### ISSUE THREAD

**Issue by Zamiell** [hanabi/hanabi.github.io#499]
Recently, *Double Ignition* has changed such that the two blind-plays do not have to be from Bob and Cathy. They can now be from anyone on the team (e.g. Cathy + Donald).

It probably also makes sense to change *Unnecessary* blind-plays to function in the same way. e.g. An *Unnecessary* blind-play can be from Bob, Cathy, or Donald (instead of just Bob).

**Comment by sjdrodge** [comment]
I approve. Lots of people already playing it this way.

**Comment by florian-5f3759df** [comment]
Agreed, like asked in #456.

**Comment by Zamiell** [comment]
also, i realized that they are ignitions, and should be explicitly called as such
