### ISSUE TITLE
Delete OOP Bluffs

### ISSUE THREAD

**Issue by sjdrodge** [hanabi/hanabi.github.io#506]
OOP Bluffs are kinda bad. When used often, they are even worse. Most of the times I've seen an OOP Bluff attempted it caused at least one bomb. Most of the times I've seen it work, it wasn't even the best available move. I would personally argue for deleting them completely since they provide so little value, but I am aware there's a reasonably large contingent on the site that loves the idea of them.

Therefore, I propose a compromise. Take them off the Learning Path. Move the convention into the Extras section of the Reference document with a large number of warnings about how bad the convention is, and let those who disagree continue to have fun with it.

**Comment by Zamiell** [comment]
https://www.youtube.com/watch?v=chJAc0IujdU

**Comment by Zamiell** [comment]
anyone else have any thoughts? piano/jerry?

- It is more optimal to have a bluff than a layered finesse in the sense that 1 card bluffs are more widely-applicable than promising a true finesse (just purely based on the statistical likelihood across all card permutations). This is the logical justification for oop existing thus far.
- However, oop bluffs are so hard to remember that they often cause bombs in the sense that cathy forgets that OOP exists and assumes a layered finesse.
- Furthermore, players initiating OOP often don't understand the 3 criteria involved. Over and over and over I ask people which of the 3 criteria their OOP bluff satisfies, and they stare blankly back at me like some kind of idiot poodle
- So the main reason for removing OOP is the complexity argument.
- As a side benefit / non benefit, it will be "nice" to have layered finesses working in the card permutations where cathy *actually has the promised card as a Layered Finesse*, but will only play her finesse position and not continue to play cards

**Comment by pianoblook** [comment]
Maybe the criteria could be even stricter? IMO criteria ii and iii are the ones that cause confusion most often, while i (literally having zero clues to mess things up) has never been a problem.

**Comment by Zamiell** [comment]
making the criteria stricter isn't helpful - as i said above, players dont even know what the criteria is to begin with

**Comment by Jayhui-q** [comment]
Hm. I think I agree with removing them. Echoing these two thoughts:

> main reason for removing OOP is the complexity argument

> Most of the times I've seen it work, it wasn't even the best available move.

I have never done an OOP bluff here. Not only are they crazy rare, every time I see an opportunity for one I find it more simple (and often efficient) to use the bluff target for a later round and to eject/discharge the playable card if it leaves finesse (or even use it later as a layered finesse!). I would just discard and hope that I ideally draw the connecting card for a finesse/bluff or have a card in my hand now that Cathy will clue (all of which would be more efficient or important than my OOP Bluff). I think it's easier and smoother for team strategy/cohesion if these clues would be read as a known bluff or layered finesse instead. 

At the very least, I agree with adding language akin to that found in Purge Bluff, such as "In extremely rare situations" and "can only be done in expert games where there is no other possible interpretation for what is happening" would be helpful. 

There is a high threshold (and rightfully so imo) for when it is worth violating the Lie Principle. In my opinion, OOP Bluffs do not usually meet this.

**Comment by florian-5f3759df** [comment]
I would be very happy with deleting them. Actually a different set of conventions, where OOP bluffs are much more often legal, would possibly work. Since illegal possibilities for useful OOP bluffs, if Bob just decides not to react, come up all the time. But that would be a big change with repercussions in other places (I think that's more BGA style, right?).

They're now in an annoying state of it not being natural whether something can be a legal OOP bluff or not, but people having to think for a long time / disagreeing more often than for almost any other convention. Banning them seems like an improvement to me.

(Funnily enough OOP ignitions, ejections, discharges, and blazes are much less error-prone, since there is no 'true' version of those.)

**Comment by Zamiell** [comment]
yes, thats BGA style

**Comment by Zamiell** [comment]
farewell sweet prince
