### ISSUE TITLE
Need to correct links regarding level numbers

### ISSUE THREAD

**Issue by cjwomack** [hanabi/hanabi.github.io#517]
Need to correct links regarding level numbers in some sections in Extras and possibly within levels. (I've done some and hopefully will do the rest some other time but if I don't; this is so others know)

**Comment by cjwomack** [comment]
Also will try to combine the updates into a single PR next time possibly.

**Comment by Zamiell** [comment]
ok thx

**Comment by Zamiell** [comment]
should i close this now?
