### ISSUE TITLE
Typo after level changes

### ISSUE THREAD

**Issue by wjomlex** [hanabi/hanabi.github.io#518]
In Level 1 we say:

```
Interaction With 5 Stalls#
For level 16 players, there is a special interaction between 2 Saves and 5 Stalls.
```

But this should now say (and link to) level 17

**Comment by Zamiell** [comment]
can you submit a pr

**Comment by wjomlex** [comment]
Yeah probably. Lemme dig into files.

**Comment by wjomlex** [comment]
https://github.com/hanabi/hanabi.github.io/pull/519

Dunno how to link PR to issue.

**Comment by wjomlex** [comment]
Ah, I see you need write access to link 'em.
