### ISSUE TITLE
Search bar incorrectly transforms hyphens in URLs to underscores

### ISSUE THREAD

**Issue by angelinahli** [hanabi/hanabi.github.io#520]
When I search for an article using the search bar and click on the article, this always leads to a 'Page Not Found' error for me:

![image](https://user-images.githubusercontent.com/25024154/109408259-ad345080-7955-11eb-9e71-f7e2f82732a4.png)

The reason seems to be that the search bar seems to be transforming hyphens ('-') into underscores ('_'), rendering incorrect URLs. The correct URL in the above example should be: "https://hanabi.github.io/docs/level-6#the-order-chop-move-ocm".

**Comment by Zamiell** [comment]
thats because i changed underscores to hyphens, and it takes the search 24 hours to update, so just wait 24 hours
