### ISSUE TITLE
moving double bluffs higher

### ISSUE THREAD

**Issue by hakha3** [hanabi/hanabi.github.io#564]
I think DBs are harder than ejections/discharges so imo they should be moved after 5tech, especially that [in one of sections](https://hanabi.github.io/docs/level-14#the-4-double-bluff--the-5-double-bluff) it mentions 5CE and 5ND so they should be earlier than 4DB ("_Note that this would only happen if e.g. 5 Color Ejection and 5 Number Discharge would not apply._").
So
Ejections & Discharges -> 14
Elimination -> 15
5 Tech -> 16
Double Bluffs -> 17
Similar order was in previous level system

**Comment by Zamiell** [comment]
lelouch [proposed that double bluffs were easier than ejections](https://discord.com/channels/140016142600241152/776176933120507964/814768770631467038), and i agreed, so that's why it was moved

the section you linked is just a bug, and i will fix that now

**Comment by hakha3** [comment]
another reason to move double bluffs over 5 tech is that people may read 5 double bluff section and think that 5s are being used to cause double bluffs, while from my experience it never happens. I dont remember any 5 double bluff. Potentially I experienced 5 double bluff with cluing 5 which already had clue on it, but thats it

**Comment by Zamiell** [comment]
if noone else has any thoughts then i will close this
