### ISSUE TITLE
Sarcastic discard for pink and brown

### ISSUE THREAD

**Issue by hakha3** [hanabi/hanabi.github.io#611]
Sarcastic discard doesnt promising slot is nice in normal variants where you can later show where discarded card is by showing that others cards are different. But sarcastic discard in variants where each card in that color is indistinguishable has almost no value bc you need to do positional clue anyway if player has already 2 or more cards in that color. You could instead play your card and then fix dupped trash if necessary. So I think it would be beneficial if sarcastic discard for pink, brown, omni worked like prompt on known cards in that color. 
What I mean is that for example if Alice hand is:
x g[3] i2[3] r[3] i4[3]
and Bob sarcastic discarded i2 then Alice doesnt play any card until she knows which of them is pink. Once she knows that which ones are pink, Alice plays left one
It would still be possible to sarcastic discard if promised card is in wrong slot, but it would require immediate fix

**Comment by heff10** [comment]
I considered this in clue-abundant variants like Pink, Rainbow, and Omni (usually two of them together). How would this interact with the blaze convention then?
