### ISSUE TITLE
Unnecessary moves: trash push discharge

### ISSUE THREAD

**Issue by florian-5f3759df** [hanabi/hanabi.github.io#614]
When updating the unnecessary file recently, I made a small mistake and the doc is now inconsistent. But instead of directly making a PR for the change that fixes it and rounds it to one option, I'm making an issue just to be sure. 

There's two kind of unnecessary trash moves:
1. Those where the clue receiver would already play, like a trash pull and trash push. Those are called 'Unnecessary Moves with Known Trash'.

2. Those where Bob's play tells the clue receiver about trash. Those are called 'Unnecessary Moves with Unknown Trash'.

There's two edge cases here, for which it's not instantly clear which kind they are: Trash Push Discharge (TPD) and using trash to do a Bad Chop Move Ejection (BCME). Currently type 1 has an example involving a Trash Push Discharge, because literally taken the clue focus is known trash. Instead, this should be type 2, since Bob's discharge is telling the clue receiver about a trash card. I.e., it's more consistent if the types are about whether Bob's blind play informs the clue receiver that something is trash, not if the literal clue focus is trash.

In the last edit I put a BCME example in type 2, but I neglected to remove the TPD example from type 1 / move it to type 2.

Relevant example (modified from a question of pianoblook):

4 player game, all 3s are played
Bob's hand is r1, g1, b4, y2
Cathy's hand is g4, r4, r3, r1
Alice clues 1s to Cathy
Bob discharges b4
What does Cathy do?

Option A: play g4 on slot 1, simply as an 'Unnecessary' blind-play, because the clue target, r1, was known trash.
Option B: play r4 on slot 2, because Bob's blind play told her about a trash card: r3.

Currently there's an example in the doc of option A, I want to do a quick PR which clarifies that it should be option B - as is already done for BCME.

**Comment by Zamiell** [comment]
b is weird though

**Comment by florian-5f3759df** [comment]
To clarify: If that's consensus, a PR is still needed, but then it's one that puts BCME back to option A. (Since it makes sense to treat BCME and TPD in the same way.)

**Comment by pianoblook** [comment]
I'm a big fan of the move towards simplified + universally applicable Trash interpretations. Option B feels more logically consistent IMO, and also seems more useful.

e.g. if Alice just wanted Bob's slot 3 + Cathy's slot 1, how about just a Unnecessary Trash Push to Bob

**Comment by Zamiell** [comment]
if you both feel b is better, then submit a PR for b
it seems unlikely to ever happen in a game though

**Comment by Lel0uch-H** [comment]
> it seems unlikely to ever happen in a game though

An example from yesterday's game of clue starved 3p:

https://hanab.live/replay/478098#41

<img width="1117" alt="UTPD" src="https://user-images.githubusercontent.com/81278716/112291019-c52d9480-8cb5-11eb-989a-226a34af9214.png">

**Comment by florian-5f3759df** [comment]
> 
> An example from yesterday's game of clue starved 3p:
>

Nice! Although because both y5 and g5 were already chop moved, either the old or new location (= a trash push from r2) would ask for slot 1.

**Comment by Lel0uch-H** [comment]
Well... no because y5 and g5 are chop moved so r2 is the newly known trash which causes the y3 to push.

Although in the given example, slot 1 and the *newly pushed chop* are coinciding so it isn't a counter example for either choice.

**Comment by Zamiell** [comment]
oh right

**Comment by Zamiell** [comment]
looks like the pr is integrated now
