### ISSUE TITLE
Request: Elaborate and add some conventions or (general principles) in the elimination (level 16) section.

### ISSUE THREAD

**Issue by hanabirnoob** [hanabi/hanabi.github.io#617]
There are still a few things that I (and perhaps other players) get confused about that might be good to elaborate on reference document.

Namely:

1. How elimination notes interact with chop moved or already clued cards (for an example, when should you trust that a clued or chop moved card could be the card you're looking for instead of one of your unclued cards). 
2. When should you write elimination notes when other players let someone discard a playable card or 2 that's not in your hand hand. (For an example, when should Alice write elimination notes when Bob, Cathy and Donald let Emily discard a 2.)
3. Play elimination (when should you write elimination notes when a card gets played that wasn't a known playable from your perspective).

**Comment by Zamiell** [comment]
> How elimination notes interact with chop moved or already clued cards (for an example, when should you trust that a clued or chop moved card could be the card you're looking for instead of one of your unclued cards).

there is no special interaction, thus there isn't a section for it in the document

> When should you write elimination notes when other players let someone discard a playable card or 2 that's not in your hand hand. (For an example, when should Alice write elimination notes when Bob, Cathy and Donald let Emily discard a 2.)

ok i will add that

> Play elimination (when should you write elimination notes when a card gets played that wasn't a known playable from your perspective).

that doesn't exist, thus there isn't a section in the doc about that
