### ISSUE TITLE
Learning Path: Estimated Levels Opinion

### ISSUE THREAD

**Issue by heff10** [hanabi/hanabi.github.io#625]
After rereading the convention documents, here is my own opinion of how variants correspond to levels:

No Variant: 1
6/4/3 Suits: 2
White: 4
Black: 5
Rainbow: 5
Pink/Light Pink: 12
Brown: 15
Muddy Rainbow: 17
Omni: 19
Null: 23

The more difficult variants are debatable, but I do believe that Black and Rainbow should be at level 5, as this is when stuff like free choice gets introduced. It also corresponds to the old level 4, which was never edited accordingly. 

I also think that brown should not be played until one knows ejections and discharges, as brown cards can be quite difficult to get.

**Comment by Zamiell** [comment]
who are you?
