### ISSUE TITLE
pink promise on trash cards

### ISSUE THREAD

**Issue by hakha3** [hanabi/hanabi.github.io#627]
Lets just fix in doc that pink promise doesnt apply to trash pink cards and let zamiel rest from arguing that it does

**Comment by padiwik** [comment]
There would probably need to be some kind of "free choice" concept to go with this to figure out if a clue is positional or a regular trash move.

**Comment by hakha3** [comment]
well its almost always trash bluff or UTD. A lot of weird choice is very situational and hard to define

**Comment by florian-5f3759df** [comment]
In principle I think it's a good point, since when the pink isn't done yet, playing positional in this way looks like bubblegum bluff / finesse. But in endgame or after pink is done we do use positionals in practice. So what do you propose as a good dividing line between positional and UTD / trash bluff?

**Comment by pianoblook** [comment]
I've only ever played this as a UTD. Any other alternative seems extremely weird

**Comment by hakha3** [comment]
well positionals generally work the same as always? Positional clues shouldnt care if positional number clue matches or not matches trash pink on which it was clued

**Comment by pianoblook** [comment]
"true Positional" clues don't exist outside of Null or Brown to my understanding.

In Pink variants I'd always just assume this is a Bubblegum bluff, or a 4 charm, or some other game-losing assumption

You'd need to Discharge

**Comment by hakha3** [comment]
well you do positional clues when there would be no wrong assumption

**Comment by jack67889** [comment]
> So what do you propose as a good dividing line between positional and UTD / trash bluff?

I guess: if the focus of the clue is known trash before Bob reacts, breaking pink promise on trash is a positional. Otherwise just clue 1s to indicate a pink card is known trash. (Seems a good general rule, the cases where another number is known trash but 1s are not are very rare.)

**Comment by Lel0uch-H** [comment]
In my experience, the way people are playing is Bob's reaction usually corresponds to what Cathy would write on her pink cards.

Example 1:

All 1s played on stacks. Alice clues i1 as 2 on Cathy. Bob responds as if it were a trash 2 and plays finesse position 1 (trash bluff).

Example 2:

All 1s played on stacks. Alice clues i1 as 4 on Cathy. Bob responds as if it were a trash 4 and plays finesse position 3 (UTD).

Example 3:

All 1s played on stacks, i3 has also been played. Alice clues i3 as 1 on Cathy. Bob responds as if it were a trash 1 and does nothing (TCM on Cathy).

**Comment by timotree3** [comment]
The rule of looking at what Cathy would think after 1. no blind-play and 2. finesse position blind-play and 3. matching-slot blind-play 4. discharge is pretty good but does not match the existing logic for trash bluff vs UTD.

e.g. in a 4 player game
- Played: i2
- Donald has a known i3
- Alice clues 4 to Cathy, touching only a trash i1
- Bob considers what will happen if he doesn't blind-play: Cathy believes the 4 is useful :x:
- Bob considers what will happen if he blind-plays finesse position: Cathy believes the 4 is useful :x:
- Bob considers what will happen if he blind-plays the matching slot: Cathy will know it's pink trash because if it was pink 4 bob would do nothing and if it was pink 5 bob would blind-play slot 4 only after the pink 3 was played. (A sort of "Bubblegum Trash Bluff")
- Bob blind-plays slot 4, which conflicts with what the doc says about UTD vs trash bluff:

> - For a Trash Bluff:
>   - The empathy on the clued card only contains possibilities that are Playable, Delayed Playable, or trash.
>   - Thus, a normal blind-play is enough to prove it is trash.
> - For an Unknown Trash Discharge:
>   - The empathy on the clued card contains one or more possibilities that are useful and currently unplayable.
>   - Thus, something extra is needed to prove it is trash.
> - Other than this, don't use more complicated factors to prefer a Trash Bluff over an Unknown Trash Discharge (like Bob having to wait on some other card).

**Comment by Zamiell** [comment]
i recommend that we stop trying to squeeze extra efficiency out of the pink variant - it is not necessary to win games.
let's stop trying to complicate things by inventing advanced criterions as to when pink promise should apply to trash cards or when it should not apply to trash cards.
that complicates the decision tree, leading to more mistakes and more lost games.
keep it simple, stupid - pink promise always applies to trash cards.

**Comment by Lel0uch-H** [comment]
> In my experience, the way people are playing is Bob's reaction usually corresponds to what Cathy would write on her pink cards.

In game example:

All 1s and 2s have been accounted for. Clueing 3 to melwen needs a blind play from slot 1 to prove that the "3" is trash.

https://hanab.live/replay/487047#35

![Screenshot (3)](https://user-images.githubusercontent.com/81278716/113284422-3baa4200-9307-11eb-9902-cea45418a957.png)

**Comment by hakha3** [comment]
> e.g. in a 4 player game
> 
> * Played: i2
> * Donald has a known i3
> * Alice clues 4 to Cathy, touching only a trash i1

This is just UTD, we shouldnt really consider slot 4

> i recommend that we stop trying to squeeze extra efficiency out of the pink variant - it is not necessary to win games.
let's stop trying to complicate things by inventing advanced criterions as to when pink promise should apply to trash cards and when it should not apply to trash cards.
that complicates the decision tree, leading to more mistakes and more lost games.
keep it simple, stupid - pink promise should always apply to trash cards in the same way that it applies to all other cards.
(which is exactly how we already have it configured.)

I would argue that what I propose (consider it just as trash bluff or UTD) is simple thing, instead of looking if trash has been clued according to pink promise and if it doesnt has some complicated decision tree on what to do then (I say complicated bc after talking with you, I have no clue what do you want to happen in a lot of cases where pink promise on clued cards would be break and then what should Cathy be thinking).

**Comment by timotree3** [comment]
> This is just UTD, we shouldnt really consider slot 4

I agree that it should be UTD, but I'm pointing out that the simple algorithm of looking at the 4 interpretations I listed in decreasing priority does not give the outcome of UTD, but of positional clue, therefore if we want that clue to be a UTD, we need a different algorithm than the one I wrote out.
