### ISSUE TITLE
Proposal: The Ambiguous Prism tempo clue

### ISSUE THREAD

**Issue by Lel0uch-H** [hanabi/hanabi.github.io#648]
Often we are in a situation when the prism card of the same color is drawn by the person holding the non prism card (or vice versa). There are situations where it could be contextually resolved which card is prism and which card is of the true color, but not always. Case in point this game (https://hanab.live/replay/519213):

![Screenshot (21)](https://user-images.githubusercontent.com/81278716/116841396-b7452a80-abf6-11eb-9c81-03d2f4b046df.png)

I propose the following convention to disambiguate the focus of the tempo clue:

If a player has two identical cards (say p5 and i5), the color tempo clue focuses on the right most card, and the rank tempo clue focuses on the left most card.

This is inspired from the brown convention where clueing color on identical brown cards causes the right most one to be played.

### Interaction with tempo clue chop move:

To keep it simple, we can agree to not ever tempo clue chop move from an "Ambiguous Prism tempo clue", primarily because the player who is being tempo'd might draw the connecting card (example: a person holding g3 and i3 might draw g4). Though I am  open to discussion on this in case anyone has more ideas.

[Background: indego and I have been playing with this convention in 2p for a while and we found that it works pretty well. I haven't tried this ever in a multi player game though.]

**Comment by timotree3** [comment]
Seems like a good idea. I've often wanted this convention playing with prism. Using color for the weirdly focused tempo clue makes sense because color reveals that both cards are ambiguous when the cards are previously rank clued, which is more common than color clued with 5's at least. I guess the proposal is just unhelpful is they're previously color clued instead.

How does this convention help with that replay example? If we were to make a convention that helps with that replay example, I would suggest the following:

When a delayed play clue tells you that you have both a prism card and the normal card that is indistinguishable from it and it's important to play a card now (for example because it's the endgame), assume that the immediately playable card was already clued in your hand, otherwise a trash push/pull would have been performed in order to prevent the clue from being delayed.

**Comment by Lel0uch-H** [comment]
In the given replay, Fafrd clues 5 to schark. melwen clues 5 or purple to schark based on which 5 she wants schark to play in this turn.

**Comment by Lel0uch-H** [comment]
> Using color for the weirdly focused tempo clue makes sense because color reveals that both cards are ambiguous when the cards are previously rank clued

Exactly. And clueing rank is unambiguously play left most regardless of prism variant or not.

**Comment by Lel0uch-H** [comment]
>  otherwise a trash push/pull would have been performed in order to prevent the clue from being delayed.

Note that the above game was level 10. I want the convention to be level-neutral.

**Comment by Lel0uch-H** [comment]
> I guess the proposal is just unhelpful if they're previously color clued instead.

In 2p, indego and I always assume play right most on a color reclue (similar to brown) and focus shift for late clue. But of course this would not work for multiplayer and needs further thought.

**Comment by timotree3** [comment]
> In the given replay, Fafrd clues 5 to schark. melwen clues 5 or purple to schark based on which 5 she wants schark to play in this turn.

Oh, my suggestion is for if you need to get the cards known with only 1 clue, so that's a separate proposal from this one and is compatible. If you can spend 2 clues, then even without this proposal it's easy. Fafrd clues 5 to schark and melwen clues 4's to Fafrd as a play slot 4 signal.

**Comment by Lel0uch-H** [comment]
> Fafrd clues 5 to schark and melwen clues 4's to Fafrd as a play slot 4 signal.

Yes, this is the solution we agreed to in the game review, but it won't work in mid-game. This proposal aims to address the focus of tempo clues given at any point during the game.

**Comment by Zamiell** [comment]
this is similar to #445, which was denied because:

> I think the easiest (and cleanest) way to get the rightmost playable 5 is "delay few turns and give the tempo clue on the 5s" (with either color or rank) as a Focus Inversion / Focus Slide. It's really useful in Ambiguous Suits btw.

> it is fairly rare that someone will have both matching 5s. when this happens, it is usually solved in the way jeff describes. furthermore, one could also solve this via a positional bomb. we probably don't need a specific convention to handle this case.

**Comment by Lel0uch-H** [comment]
"delay few turns and give the tempo clue on the 5s" isn't always the option when pace is low. Urgency is needed sometimes.

Furthermore, suppose a player is locked with g4 [i3] [g3] b[5] (assume g4 was just drawn and it is critical). How should we tempo their g3 in a table where a locked hand is unaffordable?

**Comment by timotree3** [comment]
Tempo clues are not mandatory, so waiting doesn't really communicate that the leftmost one isn't playable. This kind of thing (not just 5's) presents a big issue in maybe 1/15 prism games in my experience. I think it's worth having a convention.

**Comment by mmelwen** [comment]
it happens, and i can happen earlier in the game with g3p3. I believe is easy, clear and usefull convention.

**Comment by Indego** [comment]
This tempo clue convention also apply in deceptive-ones & deceptive-fives variants, where there exist cards identical in both color and rank.

**Comment by Zamiell** [comment]
submit a pr

**Comment by Lel0uch-H** [comment]
Sure, allow me to take it up this weekend.

**Comment by Zamiell** [comment]
if you don't finish your PR by Aug 16th, i will close this issue
