### ISSUE TITLE
Adjust game numbers along the learning path to give more practice for harder levels

### ISSUE THREAD

**Issue by vEnhance** [hanabi/hanabi.github.io#657]
Currently, the recommended number of games for level n is 20(n-3), for n ≥ 3. This is on the conservative side, which is fine, because I appreciate the sentiment it is better to not rush the learning process.

However, with that said, I want to propose that we adjust some of the numbers so that the total remains about the same, but more games are speqt towards levels that are more complicated than others. I have *Bluffs* in mind in particular. For a player that is learning, I would rather have them spend 30 games practicing level 7, 8, 9 and 50 games practicing level 10 where bluffs are introduced, rather than 60 + 20 as currently written, because bluffs are really complicated.

I made up the following table, obviously exact numbers are negotiable, just to have something concrete to discuss.

| Level Number        | Level Name              | Main Conventions Learned | #Games
| ------------------- | ----------------------- | ------------------------ | ------------
| [1](https://hanabi.github.io/docs/level-1/)     | Fundamentals            | *[The Early Game](https://hanabi.github.io/docs/level-1/#the-early-game)*, *[5 Stalls](https://hanabi.github.io/docs/level-1/#the-5-stall)*, *[Prompts](https://hanabi.github.io/docs/level-1/#the-prompt)*, *[Finesses](https://hanabi.github.io/docs/level-1/#the-finesse)* |
| [2](https://hanabi.github.io/docs/level-2/)     | Basic Finesses          | *[Double Finesses](https://hanabi.github.io/docs/level-2/#the-double-finesse--triple-finesse--quadruple-finesse)*, *[Reverse Finesses](https://hanabi.github.io/docs/level-2/#the-reverse-finesse)*, *[Self-Finesses](https://hanabi.github.io/docs/level-2/#the-self-finesse)* |
| [3](https://hanabi.github.io/docs/level-3/)     | Basic Strategy          | *[Playing Multiple 1's](https://hanabi.github.io/docs/level-3/#playing-multiple-1s)*, *[The Fix Clue](https://hanabi.github.io/docs/level-3/#the-fix-clue)*, *[Sarcastic Discards](https://hanabi.github.io/docs/level-3/#the-sarcastic-discard)* | 15
| [4](https://hanabi.github.io/docs/level-4/)     | Chop Moves              | *[Trash Chop Moves](https://hanabi.github.io/docs/level-4/#the-trash-chop-move)*, *[5's Chop Moves](https://hanabi.github.io/docs/level-4/#the-5s-chop-move-5cm)* | 25
| [5](https://hanabi.github.io/docs/level-5/)     | Intermediate Finesses   | *[Hidden Finesses](https://hanabi.github.io/docs/level-5/#the-hidden-finesse)*, *[Layered Finesses](https://hanabi.github.io/docs/level-5/#the-layered-finesse)*, *[Clandestine Finesses](https://hanabi.github.io/docs/level-5/#the-clandestine-finesse)*, *[Stacked Finesses](https://hanabi.github.io/docs/level-5/#the-stacked-finesse)*, *[Ambiguous Finesses](https://hanabi.github.io/docs/level-5/#the-ambiguous-finesse)* | 45
| [6](https://hanabi.github.io/docs/level-6/)     | Intermediate Chop Moves | *[Order Chop Moves](https://hanabi.github.io/docs/level-6/#the-order-chop-move-ocm)*, *[Trash Order Chop Moves](https://hanabi.github.io/docs/level-6/#the-trash-order-chop-move-tocm)*, *[Scream Discard Chop Moves](https://hanabi.github.io/docs/level-6/#the-scream-discard-chop-move-sdcm)*, *[Generation Discards](https://hanabi.github.io/docs/level-6/#the-generation-discard)*, *[Tempo Clue Chop Moves](https://hanabi.github.io/docs/level-6/#the-tempo-clue-chop-move)* | 60
| [7](https://hanabi.github.io/docs/level-7/)     | End-Game                | *[Positional Discards](https://hanabi.github.io/docs/level-7/#the-positional-discard-indicating-a-play-with-a-discard)*, *[Positional Misplays](https://hanabi.github.io/docs/level-7/#the-positional-misplay-indicating-a-play-with-a-misplay)* | 80
| [8](https://hanabi.github.io/docs/level-8/)     | Stalling                | *[Double Discard Situations](https://hanabi.github.io/docs/level-8/#double-discard-situations-severity-2-stalling)*, *[Locked Hand Saves](https://hanabi.github.io/docs/level-8/#the-locked-hand-save-lhs)*, *[8 Clue Saves](https://hanabi.github.io/docs/level-8/#the-8-clue-save-8cs)* | 90
| [9](https://hanabi.github.io/docs/level-9/)     | Special Discards        | *[Gentleman's Discards](https://hanabi.github.io/docs/level-9/#the-gentlemans-discard)*, *[Baton Discards](https://hanabi.github.io/docs/level-9/#the-baton-discard)*, *[Sarcastic Finesses](https://hanabi.github.io/docs/level-9/#the-sarcastic-finesse)*, *[Certain Finesses](https://hanabi.github.io/docs/level-9/#the-certain-finesse--the-certain-discard)* | 100
| [10](https://hanabi.github.io/docs/level-10/)   | Bluffs                  | *[Bluffs](https://hanabi.github.io/docs/level-10/#the-bluff)* | 110
| [12](https://hanabi.github.io/docs/level-12/)   | Intermediate Bluffs     | *[3 Bluffs](https://hanabi.github.io/docs/level-12/#the-3-bluff)*, *[Critical 4 Bluffs](https://hanabi.github.io/docs/level-12/#the-critical-4-bluff)* | 120
| [11](https://hanabi.github.io/docs/level-11/)   | Context                 | *[Stale 1's Clues](https://hanabi.github.io/docs/level-11/#the-stale-1s-clue)*, *[Focus Inversion](https://hanabi.github.io/docs/level-11/#focus-inversion)* | 150
| [13](https://hanabi.github.io/docs/level-13/)   | Trash Moves             | *[Trash Bluffs](https://hanabi.github.io/docs/level-13/#the-trash-bluff)*, *[Trash Pushes](https://hanabi.github.io/docs/level-13/#the-trash-push)* | 160
| [14](https://hanabi.github.io/docs/level-14/)   | Double Bluffs           | *[Double Bluffs](https://hanabi.github.io/docs/level-14/#the-double-bluff)*, *[4 Double Bluffs](https://hanabi.github.io/docs/level-14/#the-4-double-bluff--the-5-double-bluff)* | 190
| [15](https://hanabi.github.io/docs/level-15/)   | Ejections & Discharges  | *[5 Color Ejections](https://hanabi.github.io/docs/level-15/#the-5-color-ejection-5ce)*, *[The Unknown Trash Discharge](https://hanabi.github.io/docs/level-15/#the-unknown-trash-discharge-1-for-1-form-utd)* | 220
| [16](https://hanabi.github.io/docs/level-16/)   | Elimination             | *[Elimination](https://hanabi.github.io/docs/level-16/#elimination--elimination-notes)* | 240
| [17](https://hanabi.github.io/docs/level-17/)   | 5 Tech                  | *[Early 5 Chop Moves](https://hanabi.github.io/docs/level-17/#the-early-5s-chop-move)*, *[5 Pulls](https://hanabi.github.io/docs/level-17/#the-5-pull)*, *[5 Number Discharges](https://hanabi.github.io/docs/level-17/#5-number-discharge-5nd)* | 260
| [18](https://hanabi.github.io/docs/level-18/)   | Priority                | *[Priority](https://hanabi.github.io/docs/level-18/#the-priority-prompt--the-priority-finesse)* | 280
| [19](https://hanabi.github.io/docs/level-19/)   | Advanced Moves          | *[Occupied Play Clues](https://hanabi.github.io/docs/level-19/#the-occupied-play-clue--the-occupied-finesse-opc)*, *[Out-of-Order Finesses](https://hanabi.github.io/docs/level-19/#the-out-of-order-finesse)*, *[Suboptimal Finesses](https://hanabi.github.io/docs/level-19/#the-suboptimal-prompt--the-suboptimal-finesse--the-suboptimal-bluff)*, *[The Good Touch Bluff](https://hanabi.github.io/docs/level-19/#the-good-touch-bluff)*, *[The Pestilent Double Bluff](https://hanabi.github.io/docs/level-19/#the-pestilent-double-bluff-pdb)*, *[The No-Information Double Finesse](https://hanabi.github.io/docs/level-19/#the-no-information-double-finesse)* | 320
| [20](https://hanabi.github.io/docs/level-20/)   | Ignition                | *[Trash Double Ignition](https://hanabi.github.io/docs/level-20/#the-trash-double-ignition)*, *[Replay Double Ignition](https://hanabi.github.io/docs/level-20/#the-replay-double-ignition)*, *[Poke Double Ignition](https://hanabi.github.io/docs/level-20/#the-poke-double-ignition)* | 340
| [21](https://hanabi.github.io/docs/level-21/)   | Emergency Discards      | *[Echo Scream Discard Chop Moves](https://hanabi.github.io/docs/level-21/#the-echo-scream-discard-chop-move)* | 360
| [22](https://hanabi.github.io/docs/level-22/)   | Charms & Miscellaneous  | *[4 Charms](https://hanabi.github.io/docs/level-22/#the-4-charm)*, *[Blaze Discards](https://hanabi.github.io/docs/level-22/#the-blaze-discard)*, [*Finesses* with a *Lie Component*](https://hanabi.github.io/docs/level-22/#finesses-with-a-lie-component), *[Hesitation Blind-Plays](https://hanabi.github.io/docs/level-22/#the-hesitation-blind-play)* | 380
| [23](https://hanabi.github.io/docs/level-23/)   | Unnecessary Moves       | *[Unnecessary Moves](https://hanabi.github.io/docs/level-23/#unnecessary-moves)* | 400
| [Extras](extras/) | | n/a                   | Other rarely-used conventions / edge-cases

Note that I flipped the order of level 11 and level 12 because to me it's a bit weird to have something between one-away bluffs and 3 bluffs and critical 4 bluffs. (Honestly, when I teach people, I just teach 10+12 together.)

**Comment by Zamiell** [comment]
i agree with the sentiment, but i am not so sure that it is worth it to micro-manage the numbers too much
1) i'm under the impression that not many people put too much stock in these numbers to begin with, maybe other people can chime in
2) it makes it harder to refactor the levels in case i have to move a level around

**Comment by Zamiell** [comment]
> when I teach people, I just teach 10+12 together

i don't think that you should teach 10 and 12 at the same time.
i think it is important to establish that a bluff is always on a one-away-from-playable card, no exceptions.
a lot of players don't fundamentally understand what a bluff is, then just think its an arbitrary agreement that doesn't flow naturally from finesses.
whereas the only arbitrary thing about a bluff is specifically for 3 bluffs and critical 4 bluffs

**Comment by vEnhance** [comment]
> i agree with the sentiment, but i am not so sure that it is worth it to micro-manage the numbers too much
> 
>     1. i'm under the impression that not many people put too much stock in these numbers to begin with, maybe other people can chime in to state whether or not that is true
> 
>     2. it makes it harder to refactor the levels in case i have to move a level around

That's reasonable. Let's wait a bit to see if anyone else has an opinion, but if not, we can close the issue.

**Comment by Lel0uch-H** [comment]
> i'm under the impression that not many people put too much stock in these numbers to begin with, maybe other people can chime in to state whether or not that is true

I agree that this is not true. I have seen players with 2k+ games still playing at lvl 14, while players with roughly 500 games playing with max lvl conventions.

**Comment by sjdrodge** [comment]
I think the game # recommendations are inherently silly, and if people are paying attention to them, it can really only be to their detriment. People should just be encouraged to move on to the next level when they feel comfortable playing with the level they're currently on.

**Comment by vEnhance** [comment]
> I think the game # recommendations are inherently silly, and if people are paying attention to them, it can really only be to their detriment.

Well if that's the sentiment, perhaps we can just delete them :)

Or something in between, where we just put a few fenceposts at two or three of the most involved levels to the effect of "this level is pretty involved, so make sure you have a firm grasp on the previous levels before starting this one (~N games)" but otherwise not micromanage the path.

Perhaps I'm overfixating on the numbers, but (1) I'm speaking as someone who followed the recommended numbers closely when I was learning because I didn't want to rush the process too much; and (2) based on my experience onboarding a lot of beginners, I don't think I'm completely alone.

I guess it's one of those situations where advice always reaches the wrong audience. The [people who are rushing the process](https://github.com/hanabi/hanabi.github.io/pull/373#issuecomment-716754960) aren't going to listen no matter what's written, and the people who are more patient are the ones who feel reluctant to ignore an explicitly written direction.

**Comment by vEnhance** [comment]
Closing this since the pull request looks ready to merge.
