### ISSUE TITLE
Proposal: Single Scream Chop Move (Blind Playing Chop)

### ISSUE THREAD

**Issue by Dr-Kakashi** [hanabi/hanabi.github.io#663]
Convention Name: Single Scream Chop Move (Blind Playing Chop)

0 Clue Situation: 
We can analyze the 2 situations which can be interpreted as a single cm and then see the ending result:
1. Bombing Chop
     -On Bob's turn, 0 clues and single cm
2. Skip Discard
     -On Bob's turn, 1 clues and single cm

We can agree that it's much better to do the 2nd option.
Bombing chop in this situation would be a double cm to make up for the lost clue.
However, what if there are no cards available to skip discard? 
For this situation, we agree that bombing chop will only cause a single cm.

8 Clue Situation:
There are situations where players are unable to directly save the card, such as in null or even in situations where you can't guarantee that the next player won't discard their chop.
Using null as an example, 5 or blue would just be interpreted as a stall.
Players are unable to discard at 8 clues, so skip discard is not available.
Thus, the next option is to bomb chop, so we can agree that only a single cm is called for, since the next player is unable to discard as they are now at 8 clues.  

Kimbi and I figured this out together. Doing 2p, but I know this can be applied in all player counts.  Though, extremely rare, as the team doesn't generally put their teammates in such a dire situation in 3p+ situations.

**Comment by Zamiell** [comment]
your convention proposal is confusing.

you start by saying "We can analyze the situations", but go on to talk about a "skip discard", which isn't a convention.
and, for the record, the name for the move where you bomb chop is specifically called "The Scream Blind-Play" - let's call things by their official names for clarity of communication.

**Comment by Zamiell** [comment]
The Scream Blind-Play is already a single chop move, so i don't understand what your proposal is supposed to accomplish

**Comment by Zamiell** [comment]
closing since kakashi isn't responding
