### ISSUE TITLE
Turnabout Ejection Clarification

### ISSUE THREAD

**Issue by pianoblook** [hanabi/hanabi.github.io#667]
I think this is how people have been naturally playing already, but I don't think the doc specifies this to be true:

> If a _Turnabout Ejection_ is caused by a 1s clue that newly touched multiple cards, the clued player is expected to treat the remaining (non-focused) cards as if they had been clued as 1s normally.

replay from today that reminded me to make this post: https://hanab.live/replay/543686#1

**Comment by pianoblook** [comment]
Eh, that wording can probably be improved. Point is: players should feel comfortable playing the other 1s (still in the right order, ofc) after the focused 1 gets Signaled as a 5

**Comment by Zamiell** [comment]
can you submit a pr

**Comment by pianoblook** [comment]
Looks like you may have added this yourself, or I'm just a derp and it was already included - in any case, seems like this is all set
