### ISSUE TITLE
Proposal: Focus of trash chop move in a pink variant

### ISSUE THREAD

**Issue by Lel0uch-H** [hanabi/hanabi.github.io#668]
Re-mentioning here what I posted on discord:

> The pink doc defines that "focus of trash bluff/trash push" should be considered as trash while all other cards be considered good touched. I don't see how and why trash chop move should be treated differently.
>In a no variant game, we assume that we are chop moving all cards to the right of the right most trash, so by extension we should also define the focus of trash chop move to be the right most 1. Also allowing for good touch to be promised on the non focus seems to be consistent with how the doc treats trash bluff/trash push.

**Comment by pianoblook** [comment]
As discussed in Discord, I just worry that this could easily lead to common mistakes: if the cluing player, clued player, *or* the next teammate after them forgets this rule - which is basically an 'inversion' of how most trash-focused clues operate - then you'll end up with accidental TOCMs.

I agree it makes sense logically, but I just wonder if the tradeoffs make it an actual net positive

**Comment by Lel0uch-H** [comment]
Closing since it seems nobody is interested.

**Comment by Zamiell** [comment]
agree with piano
