### ISSUE TITLE
Add "Level 0" to "First Principles"

### ISSUE THREAD

**Issue by Cyberbeni** [hanabi/hanabi.github.io#673]
When someone played on other sites before with less structured convention guides and they find hanab.live and hear about the "The Hyphen-ated Conventions" and meet the question "what level are you?", they might think that the basic strategy starts with level 1 (especially since it strongly suggest that this is where you should start: "Level 1 strategies can be learned with no games of Hanabi played. You can either learn them before you play your first game or after you play a few games to learn the basic mechanics. This stuff is mostly a repeat of the beginner's guide, but we go into a bit more detail here.")

I suggest adding "Level 0" to "First Principles" to make it more clear that it should be also read before "Level 1".

**Comment by Zamiell** [comment]
you aren't supposed to read the first principles before level 1

quoting literally what it says in the first principles section:

> Since the principles are a little abstract, they are more useful as a reference than as an actual guide on how to play Hanabi with our group - this is what the beginner's guide is for.

**Comment by Cyberbeni** [comment]
When are you supposed to read First Principles then? Level 3 refers to chop-focus when describing the order of play for multiple 1s, which is explained there. Playing on level 3 with people, you will be expected to respect chop-focus when they give you any clue, not just for 1 clues.

The Beginner's Guide also explains chop focus but level 1 tells you that it's mostly the same but with less details, so it's not worth reading. (And in the situation I mentioned above, you will be most likely arriving to the site at the level 1 page or at least ignore everything else until you find out what these levels mean)

**Comment by Zamiell** [comment]
> When are you supposed to read First Principles then?

you are not ever supposed to read the first principles

> Level 3 refers to chop-focus when describing the order of play for multiple 1s

chop focus is explained in the beginners guide

> Playing on level 3 with people, you will be expected to respect chop-focus when they give you any clue, not just for 1 clues.

if you are playing at level 3 with people, then everyone will know about chop-focus, because all level 3 people have presumably read the beginners guide

> The Beginner's Guide also explains chop focus but level 1 tells you that it's mostly the same but with less details, so it's not worth reading. (And in the situation I mentioned above, you will be most likely arriving to the site at the level 1 page or at least ignore everything else until you find out what these levels mean)

if you are arriving to the site at level 1 instead of the beginners guide, then something has fucked up in the chain of what people are telling your to read, and i would ask you what was the chain of events that resulted in that even happening

**Comment by Cyberbeni** [comment]
I have played on GBA a couple years ago and also read other, less detailed guides about conventions. Then one day I had a sudden urge to play some Hanabi again and since BGA made this game premium, it's pretty much dead there, so I searched for sites that allows playing Hanabi for free, so naturally I found hanab.live, where I was met with questions about knowing the hyphenated conventions and my level in them, so I explained to them that I played like 20-30 games on BGA some time ago and that I haven't known about these specific conventions but I found the site, and saved it for later, and based on the table of contents, I'm around level 3. So then later on I started reading from level 1 and when arriving to the chop-focus mention in level 3, I wanted to search for it, the "basic strategies" section of the results only had level 3 and level 16 in them, so then I just gave up on it for the time. And then later on I was curious what the other 2 menu points before level 1 were and that's when I realized that the First Principles is actually level 0. Level 1 told me that "This stuff is mostly a repeat of the beginner's guide", so naturally I didn't read the beginner's guide, only the part that it specifically told me: "First, see the section on Delayed Play Clues from the beginner's guide."

**Comment by Zamiell** [comment]
i think that your experience is pretty atypical.
most people have read the beginners guide, regardless of whether they are brand new to hanabi or have played on BGA in the past.
i will add a warning to the level 1 section that says to not read it and to instead read the beginners guide
