### ISSUE TITLE
The Sarcastic Clue (Chop move?)

### ISSUE THREAD

**Issue by Romain672** [hanabi/hanabi.github.io#676]
Hi,
Example #A:
3 players, 5 Suits. r1, b1, y1 are on stacks.
Bob's hand: 2-2-x-x-x.
Cathy's hand: x-b2-x-x-x.
Alice clue 2 to Bob (play clue).
Bob clue blue (or 2?) to Cathy.
What happen next?

I believe current interpretation is:
1) Alice has another copy of b2: that clue is a play clue.
2) Bob know somehow the color of his 2 by context, or know it isn't blue: that clue is a play clue.
3) ????

My idea would be to make Cathy chop move in 3), even if it's confusing.
20% of the time, that's an 'early save' without extra info. 80% of the time, that's one play+one save.

Example #B:
4 players, 5 Suits. Start of game.
Bob's hand: x-1-1-x.
Cathy's hand: x-r1-x-x.
Alice clue 1 to Bob (play clue).
Bob clue red (or 1?) to Cathy, instead of playing his slot 2 to ocm Cathy directly. So that should be more than one cm.

This is only the theory now. But I would at least know what you propose to interpret example #A and #B. That look like some kind of clue which can be done all the time.

**Comment by Lel0uch-H** [comment]
A similar convention for 2p is documented well in [IAMJEFF's score hunting guide](https://github.com/iamwhoiamhahaha/hanabi/blob/master/2-player/Score_Hunting_Guide.md#dupe-chop-move-risk-of-duplication-chop-move).

**Comment by Romain672** [comment]
Yeah, that idea came from 2 players.

Was wondering how good/bad/confusing it was with 3+.

**Comment by Dr-Kakashi** [comment]
Yea we call it a [Dupe Chop Move](https://github.com/iamwhoiamhahaha/hanabi/blob/master/2-player/Score_Hunting_Guide.md#dupe-chop-move-risk-of-duplication-chop-move).

If a color or rank clue touches a single card, at the risk of a duplication, then it induces a chop move.

In the example you gave, Cathy can safely sarcastic discard back. However, when rank is used a bomb could happen. I believe it can be used in multiplayer, but haven't seen it happen often as it isn't in the doc.

**Comment by sjdrodge** [comment]
I vote no. I think this is really bad in 3p+.

**Comment by Dr-Kakashi** [comment]
What are the downsides stephen?

**Comment by Zamiell** [comment]
the difference is that in 2p it is symmetrical, but in 3p is it asymmetrical
asymmetrical conventions are usually terrible, which is why this doesn't exist as a move already

**Comment by Lel0uch-H** [comment]
Agree that in multi p games players can find enough context that they are not duping.

**Comment by Romain672** [comment]
And how about limiting that to 1s then (so most of the time only turns 2/3/4/5).
That make the move way rarer though.

**Comment by Zamiell** [comment]
i dont see how limiting it to 1s makes it sync, or makes it "more" sync

**Comment by Romain672** [comment]
Like the 'no context double gentleman's discard' i mean.

**Comment by Zamiell** [comment]
that was deleted yesterday
