### ISSUE TITLE
OOP Shadow Finesse

### ISSUE THREAD

**Issue by Dr-Kakashi** [hanabi/hanabi.github.io#679]
Follows the Shadow Finesse convention. However, the player who needs to demonstrate the shadow is not the immediate next player.

For Example:
Play Field: No Cards Played

Bob's Hand:
R1 - Y - Y - Y
Donald's Hand
X - X - R2 - X

Y in Bob's hand was previously picked up cards. He was 5 saved earlier for example.

Alice clue's red to Bob touching R1.
Bob is unable to show the shadow as his other cards are known not playable. Thus, he knows it's up to Cathy to show the Shadow.
Bob Plays R1
Cathy finds red to Bob odd as Donald's R2 is not blocked by a focused clue to it. Thus Cathy knows this is a Shadow Finesse and it is up to her to demonstrate the shadow. 
Cathy blind plays 3rd finesse position and successfully plays G1
Donald finds the sequence of events odd, but realizes that Cathy only played because of the red clue to Bob. This means that Cathy was showing Donald where the R2 is located through a shadow finesse.
Donald successfully plays R2 from slot 3.

**Comment by pianoblook** [comment]
How is this different than a normal [Reverse Shadow](https://hanabi.github.io/docs/extras/special-finesses/#the-reverse-shadow-finesse)?

> Bob is unable to show the shadow as his other cards are known not playable. 
That would be assuming he was clued 1? If Bob he clued red, then it totally *could* still be a self-shadow finesse; but he needs to check and see if Cathy holds a playable in the matching position. If not, then he should play his own 3rd FP.

**Comment by Zamiell** [comment]
closing since kakashi isn't responding
