### ISSUE TITLE
Delete Bubblegum Wraparound

### ISSUE THREAD

**Issue by timotree3** [hanabi/hanabi.github.io#686]
If slot 1 plays from a 5 clue, nobody will think it's bubblegum wraparound. Slot 1 is way too overloaded with other use cases for it to pretty much ever be unambiguous. I'm not even sure why you would give that clue when you can just give pink. Has anyone ever used it in a game?

**Comment by Indego** [comment]
Here's a game that comes to mind:
https://hanab.live/replay/434934#13
<img width="504" alt="image" src="https://user-images.githubusercontent.com/25340055/124646594-6e944100-dec7-11eb-9b57-2f0e2f87ad76.png">

**Comment by timotree3** [comment]
Has it only ever happened in light pink?

**Comment by iamwhoiamhahaha** [comment]
only useful in light pink i guess (more examples here: https://github.com/hanabi/hanabi.github.io/issues/214)

**Comment by Zamiell** [comment]
so should we delete it or move it to a Light-Pink-specific convention?

**Comment by iamwhoiamhahaha** [comment]
the latter

**Comment by Zamiell** [comment]
submit a pr

**Comment by Zamiell** [comment]
i think tim should do the PR since he's the one who opened the issue

tim if you don't submit a pr by august 18th, I will close this issue
