### ISSUE TITLE
Tempo Clue Restriction

### ISSUE THREAD

**Issue by Zamiell** [hanabi/hanabi.github.io#688]
I propose that the following bullet point is deleted from the *Tempo Clue* section:

> 2) When the clued card is not a 5 and it is "out of order" (meaning that it is impossible for a *Prompt* to get the card played)

Reason: Bad players commonly forget about this rule, and it causes desynchronization / lost games.

**Comment by sjdrodge** [comment]
This bullet point is required in many cases for the team to get a playable before it's discarded.

**Comment by Zamiell** [comment]
Those situations are rare.
In the unlikely scenario where:
1) a *Tempo Clue* is given for this reason
2) and the *Chop Moved* card is trash
Then players can utilize the *Chop Transfer* convention on the trash card, if needed.

**Comment by timotree3** [comment]
Counter offer

2. When the clued card is not promptable AND after the tempo clue is given, the connecting card is clued in the same round.

**Comment by pianoblook** [comment]
This seems really weird to delete. Allowing teammates to give tempo clues can be a valuable tool for discard modulation / handling slightly-spooky situations in which discarding is the only real alternative

**Comment by Zamiell** [comment]
> When the clued card is not promptable AND after the tempo clue is given, the connecting card is clued in the same round.

1) That would be the only "one-round-toggle" convention that we have, which is novel, and thus potentially mistake-inducing.
2) When creating conventions, I usually consider "simplicity" to be the factor that should be weighted most heavily.

**Comment by pianoblook** [comment]
"Bad players" also mess up DDA stalling situations all the time too, but that doesn't mean we should delete it. 

Would raising its Level help alleviate concerns of mistakes?

**Comment by sjdrodge** [comment]
My vote is we neither delete it nor raise its level. This bullet point for TCCM is significantly better than the DTC bullet point, and it would be more confusing, not less confusing, if players find themselves in a situation where their only choices are to cause a bad chop move or let a playable card die.

**Comment by timotree3** [comment]
> This seems really weird to delete. Allowing teammates to give tempo clues can be a valuable tool for discard modulation / handling slightly-spooky situations in which discarding is the only real alternative

I don't think converting ways to permanently save cards into ways to stall is a good tradeoff. 

Alice stalling by giving this kind of tempo clue only pays off and actually lets the team save her chop when she finds something to clue on the next turn AND someone draws a playable with which to bluff with her chop AND there's enough clue tokens to give the bluff. The other benefit is that Bob may not have to give a DDA clue on his turn, but this is usually offset by the fact that Alice has to give a DDA clue after Cathy discards.

If stalling doesn't pay off, then you just have 2 fewer clue tokens than you started with, which makes it much harder to actually have the resources to save the useful cards you care about.

When compared to enabling Alice to permanently save a useful card on Bob's chop, the payoff there seems much more reliable and strong.

**Comment by pianoblook** [comment]
but that argument basically comes down to "when Bob's chop is useful, it's more useful to let it be _Chop Moved_." 

That can't really be debated, lol, but it's ignoring all the instances when you'd prefer it *not* to cause a TCCM.

**Comment by pianoblook** [comment]
Why don't we just make a convention that causes a TCCM anytime you do an off-chop 1-for-1 play clue? 

Here's why it would be good:
> "Alice stalling by giving this kind of 1-for-1 only pays off and actually lets the team save her chop when she finds something to clue on the next turn AND someone draws a playable with which to bluff with her chop AND there's enough clue tokens to give the bluff. The other benefit is that Bob may not have to give a DDA clue on his turn, but this is usually offset by the fact that Alice has to give a DDA clue after Cathy discards[...]"

/s of course

**Comment by Zamiell** [comment]
> Allowing teammates to give tempo clues can be a valuable tool for discard modulation / handling slightly-spooky situations in which discarding is the only real alternative

I agree with you that the loss of *Discard Modulation* is the biggest con of removing the bullet point.
More on this later.

> "Bad players" also mess up DDA stalling situations all the time too, but that doesn't mean we should delete it.

Apples and oranges.

1) The complexity tradeoff for DDA seems to be worth it.
I think of it as high risk, high reward - lots of mistakes, but also lots of value.
2) The complexity tradeoff for this convention is probably not worth it.
I think of it as high risk, low reward - lots of mistakes in return for a small amount of discard modulation in very specific circumstances.

> Would raising its Level help alleviate concerns of mistakes?

No, because levels don't correspond to skill level. They correspond to number of games and/or experience. (The two are correlated, but distinct.) Besides, having extra tempo clue rules in a different level isn't a great way to structure the conventions.

> it would be more confusing, not less confusing, if players find themselves in a situation where their only choices are to cause a bad chop move or let a playable card die.

When a critical card is on chop, it must be saved. If both a color clue and a number clue would violate *Good Touch Principle*, then you have to pick one and violate it anyway. This is a concept that is explicitly outlined in the beginners guide:

> This is called Save Principle and it is the most important principle of them all. You are allowed to break any other principle or rule in order to prevent a card in this list from being discarded!

Thus, I expect beginners to be familiar with this concept. And I would certainly expect a level 6 player to be familiar with this concept (which is the level that the *Tempo Clue Chop Move* is contained within). If players are commonly forced to touch trash cards in order to not let important/playable cards die, then I don't think it is very confusing to *Chop Move* a trash card in order to not let important/playable cards die.

> When compared to enabling Alice to permanently save a useful card on Bob's chop, the payoff there seems much more reliable and strong.

Tim's post above analyzes whether or not a *Tempo Clue* is better than a X units of *Discard Modulation*. There's pros and cons for each side and Tim does a good job of advocating for the *Tempo Clue* side.

I'd like to point out something different though. Even if you disagree with Tim that the benefits of more *Tempo Clues* are not worth it, I think it would be fair to classify this convention reconfiguration as a "side-grade". If we stay more-or-less the same along the axis of **convention value**, but we move lower down the axis of **convention complexity**, then I think that's a *great deal for us as a group*.

Let's not underestimate the value of reducing complexity for the group:

> Doodles — 06/19/2021
Okay, you know what. I'm for it. We should delete half the convention document.

> pianoblook (he/they) — 06/09/2021
I'm going to commit to doubling down on pushing others to keep things simple

**Comment by timotree3** [comment]
> but that argument basically comes down to "when Bob's chop is useful, it's more useful to let it be Chop Moved."
> 
> That can't really be debated, lol, but it's ignoring all the instances when you'd prefer it not to cause a TCCM.

I wasn't ignoring those instances.. I was detailing them.

**Comment by iamwhoiamhahaha** [comment]
https://hanab.live/shared/585320
two examples in this game: turn 14 and 26 (but probably doesn't apply to ambiguous)

**Comment by vEnhance** [comment]
> Reason: Bad players commonly forget about this rule, and it causes desynchronization / lost games.

I have to say that off my head, I don't remember this rule being a particularly common source of error.

In particular re beginners, my memory is that they're told in Level 1 to not give tempo clues, so when they see a tempo clue later, it spooks them out and they open hanabi.github.io. Usually for the clue receiver the out-of-order case is pretty clear because they have positive information on the other card.

**Comment by Lel0uch-H** [comment]
I agree with the majority opinion. The status quo is good, and I don't particularly recall it being as frequent a source of error as @Zamiell is mentioning it to be. The analogy with DDA is pretty apt too, bad players messing up a convention does not make it a candidate for deletion.

**Comment by Zamiell** [comment]
stephen/piano are my arguments convincing?

**Comment by pianoblook** [comment]
I agree with your premise that lower complexity conventions are generally better, but I can't say I'm convinced that this reconfiguration in particular would be less complicated. Especially when factoring in the amount of readjusting everyone would need to do anyway. 

I personally believe this is actively less valuable of a convention too, so that's my stance

**Comment by sjdrodge** [comment]
My position is unchanged. I think this makes the TCCM convention worse for almost no gain.
