### ISSUE TITLE
Convention Proposal: 2 Charm

### ISSUE THREAD

**Issue by Dr-Kakashi** [hanabi/hanabi.github.io#689]
Just an extension of 4 Charm, 2 Charm can be done in reversed suit variants.

**Comment by pianoblook** [comment]
example attempted by Flori: https://hanab.live/replay/544724#4

**Comment by Zamiell** [comment]
@Dr-Kakashi submit a pr

**Comment by Dr-Kakashi** [comment]
https://github.com/Dr-Kakashi/hanabi.github.io/pull/1
https://github.com/Dr-Kakashi/hanabi.github.io/pull/2

Is this right? Also, I apologize for doing 2 pull requests as I didn't realize it also works in Reversed Variants.

**Comment by Zamiell** [comment]
not quite, you did a PR to your own fork, not to this repository

**Comment by Zamiell** [comment]
like, if you click on the "pull requests" tab on the top of this page, you can see that there are 2 prs to this repo, one is by lelouch and one is by piano
