### ISSUE TITLE
Convention Extension: OOP Pink Fake Finesse Truth

### ISSUE THREAD

**Issue by pianoblook** [hanabi/hanabi.github.io#690]
<img width="1236" alt="OOP Fake Pink Finesse = Real" src="https://user-images.githubusercontent.com/32303453/125198311-6b82b300-e22f-11eb-8fcc-dc2f73b25aef.png">

Tried something naughty and undefined just now for science, and think it's pretty cool

- Since Alice is jumping ahead to clue Donald, you could argue that this is just a _Fake Finesse_ targeted on Bob.
- But since Bob sees that Cathy's w1 blind-play would match the w2 also being clued, it should be understood as a _true Finesse_ on w2.
- After pink 1 plays Donald will understand what must have happened

**Comment by iamwhoiamhahaha** [comment]
*Pink Fake True Finesses* 😂

**Comment by Zamiell** [comment]
so kim plays slot 1 instead of slot 2 because we define bubblegum OOP stuff as illegal?

**Comment by pianoblook** [comment]
well no the Pink 1 being clued a 2 is just a standard [Fake Finesse](https://hanabi.github.io/docs/variant-specific/pink/#the-pink-fake-prompt--the-pink-fake-finesse).

The proposed extension is that since the w2 that's *also* being clued matches the w1 on kimbi's finesse, possum should defer and therefore make it the Truth. After Kakashi plays pink 1, he'll realize the other 2 must be white

**Comment by timotree3** [comment]
To clarify, bubblegum does not apply when a playable pink card is focused, instead it's either turnabout or a fake play clue.

**Comment by timotree3** [comment]
There's a related case here https://hanab.live/replay/507108#15

I was thinking if timo clues 4's to squirrel, even though it could be a fake play clue as b4, that would be risky since if someone draws b4 we would lose the game, so maybe the team interprets it as a play clue on the white 4 (the 4 that is actually touched by the clue).

**Comment by pianoblook** [comment]
> There's a related case here https://hanab.live/replay/507108#15

That's a nice one! 

IMO in pink suit games you should just always make notes for both options after a rank clue finesse occurs, and therefore not be allowed to GD. Seems like a natural extension of turning on fake finesses

**Comment by Zamiell** [comment]
this move seems like an edge-case that stands a good chance at working "automatically" in the rare case that it comes up in a game.
thus, it might not be worth cluttering the document with.

**Comment by pianoblook** [comment]
I'd like to think that's true. I'll keep an eye out for other opportunities and see if they play out correctly.

imo it'd be worth adding a line in the Fake Finesse section about it - e.g.:

> "In some rare cases, _Fake Finesse_ can be performed _Out of Position_: if a second newly touched card is seen to connect with a card already on another player's *Finesse Position*, the immediate next player should **not** react, thus making the underlying *Finesse* also *True*."

**Comment by Zamiell** [comment]
can you submit a pr

**Comment by Zamiell** [comment]
piano if you don't submit a PR by august 18th, then i will close this issue

**Comment by pianoblook** [comment]
I added a line in the other PR, so this should be good to go
