### ISSUE TITLE
beginner/2-save-question-3

### ISSUE THREAD

**Issue by DrAnax** [hanabi/hanabi.github.io#695]
https://hanabi.github.io/docs/beginner/2-save-question-3

I am not entirely sure this is a good question for beginners, given that Green 2 is playable and Alice can always clue Green to Bob.

Perhaps Green 1 should be removed from the play stacks?

**Comment by Zamiell** [comment]
sure, submit a pr that does that and removes the line about duping the g1s

**Comment by Zamiell** [comment]
this is done now, thanks
