### ISSUE TITLE
beginner/clue-interpretation-question-1

### ISSUE THREAD

**Issue by DrAnax** [hanabi/hanabi.github.io#696]
https://hanabi.github.io/docs/beginner/clue-interpretation-question-1

Tricky answer; Bob's hand could be  xx B3 xx G3 G5

  - Alice sees that Bob has nothing to do
  - Alice cannot clue 3 to Bob; that would focus B3
  - Alice cannot clue 5 to Bob; that would put G3 on chop

Therefore, it is possible for Alice to clue Green to Bob with the given cards.

Solution; make it a four player game, put Cathy's cards to Donald, put Bob's cards to Cathy.

rel: https://hanabi.github.io/docs/beginner/critical-save-question-2

Maybe it should be noted that if Bob had Cathy's cards then Alice would clue purple to Bob to save all his cards.

**Comment by Zamiell** [comment]
> Tricky answer; Bob's hand could be xx B3 xx G3 G5

if that were the case, Cathy and Alice would work together to give two clues in succession.
therefore, what you are proposing is impossible

> Solution; make it a four player game, put Cathy's cards to Donald, put Bob's cards to Cathy.

i'm fine with that if you want to submit a PR

> Maybe it should be noted that if Bob had Cathy's cards then Alice would clue purple to Bob to save all his cards.

no, again that is impossible.
two players will always work together to clue the cards without *Lying* about the identity of the cards
