### ISSUE TITLE
Clarification: The assymetric chop move dilemma

### ISSUE THREAD

**Issue by Lel0uch-H** [hanabi/hanabi.github.io#717]
When an assymetric chop move occurs (like an early game 5s chop move or from an unnecessary trash move), the player for which it is assymetric for (referred to as Alice from now) sometimes needs to clue the player on whom the (potential) chop move occurred (referred to as Bob from now).

In such a situation, how should the clue focus be evaluated is currently undefined. I propose that Alice should assume the trash move to be necessary by default, and the clue given from Alice should be evaluated as if the CM does not exist. This also adds the utility of allowing us to have two different kinds of play clue focii on Bob; Alice can play clue a card pre-CM while any other player can focus post-CM.

**Comment by timotree3** [comment]
What if Alice knows the cards are CMed but not everybody knows she knows? Does Bob have to pretend Alice doesn't know even if the CM is common knowledge between the two of them?

**Comment by Zamiell** [comment]
> In such a situation, how should the clue focus be evaluated is currently undefined.

i dont think it is undefined.
by default you assume that no chop move has occurred, because of occam's razor

**Comment by Lel0uch-H** [comment]
> by default you assume that no chop move has occurred, because of occam's razor

In certain cases it is possible for Alice to know. Example, all but one 1 is down, and Alice is trash bluffed for a 1. Thus she would know that it is unnecessary.

**Comment by Zamiell** [comment]
the fraction of cases where Alice can know seems extremely low, <5%

**Comment by Lel0uch-H** [comment]
Ok so seems like @Zamiell agrees that we should assume no-CM by default. What I am suggesting is we just add the default assumption to the doc because it currently does not exist.

**Comment by Zamiell** [comment]
can you submit a pr

**Comment by Lel0uch-H** [comment]
Ok I will do that.

**Comment by Zamiell** [comment]
lelouch if you don't submit a PR by august 17th then i will close this issue
