### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by NumerateClutter** [hanabi/hanabi.github.io#721]
Level 17, under "The Early 5's Chop Move". The text "additional rules" links to "https://hanabi.github.io/docs/extras/miscellaneous.md#interaction-with-5-rank-clues" but the link is broken (".md" needs to be removed for "https://hanabi.github.io/docs/extras/miscellaneous") _and_ the linked section seems to be removed.

I'd fix it, but it seems like there's some kind of processing going on to remove ".md" but missed this case -- not sure if this is a bug or because the linked section is missing

**Comment by Zamiell** [comment]
1) we have an automated link checker, so it should have caught this, ill have to look into why
2) .md does not need to be removed; just look at every other link in the repository, they all have .md

**Comment by NumerateClutter** [comment]
What I mean is that on https://hanabi.github.io, the links do not end with ".md" (I understand that in the repo they do). I presume the ".md" is stripped somewhere in the process. It seems that step didn't happen for this link

**Comment by Zamiell** [comment]
looks like its just because it uses the full url path

**Comment by Zamiell** [comment]
see https://github.com/hanabi/hanabi.github.io/commit/43bbb9c6c8030005010faef8771cbc7d3cf2f58e
