### ISSUE TITLE
Clarification: Precedence between inverted priority and potential bad touch

### ISSUE THREAD

**Issue by Lel0uch-H** [hanabi/hanabi.github.io#724]
Alice has r4 and g3 to play.

Bob has an unknown red card in hand.

Alice plays g3, does Bob assume inverted priority finesse for g4? Or that his red card is bad touched and not r5?

**Comment by Zamiell** [comment]
that is intentionally undefined and depends on the game state.
in many variants, duplicating cards is necessary, so if bob has any doubt, he should relax and not assume the-super-rare-inverted-priority-finesse
