### ISSUE TITLE
Clarification on muddy rainbow saves

### ISSUE THREAD

**Issue by Aigul9** [hanabi/hanabi.github.io#725]
https://hanabi.github.io/docs/variant-specific/muddy-rainbow-cocoa-rainbow/#muddy-rainbow-saves
needs to be clarified that muddy rainbows should be saved with critical color, and if not possible, only then use red.

**Comment by Zamiell** [comment]
submit a PR

**Comment by Zamiell** [comment]
valetta if you don't submit a PR by august 23rd then i will close this issue
