### ISSUE TITLE
Convention Proposal: The Always Loaded Principle

### ISSUE THREAD

**Issue by Lel0uch-H** [hanabi/hanabi.github.io#730]
There has been a lot of confusion regarding White Loaded play clues. Similarly, in gray/dark prism/etc. variants we say that "dark prism 3 and 4 saves are loaded" but do not specify the behavior about what to do when a non-dark prism 3 or 4 is early saved.

I believe the goal of such conventions is just to have tempo on cards where it would be impossible to, otherwise. But having such discrete rules for such variants fails the goal of simplicity and uniformity.

I suggest we cut the jargon and just define it as "all rank saves are to be treated as loaded play clues in a variant where any rank clue to chop _usually_ looks like a save" (and maybe even the counterpart of this rule for color clues for variants like Brown-Fives let's say, but that is a topic for another PR). This just looks clean from an aesthetic standpoint and would not cause any disagreement in game about clue interpretation.

**Comment by dobi815** [comment]
This is how we have been playing I think. What would it take to firm this up? Should just make a PR?

1. I don't see any downsides to treating a 3 or 4 on chop for a critical 3 or 4 additionally as a play clue regardless of whether its from the special suit or regular suit. So definitely yes.

2. The absence of this convention results in special casing for when the clue receiver could potentially interpret the clue as a play (and thus contextual use of that in higher levels). Its more confusing than less.

**Comment by Zamiell** [comment]
> But having such discrete rules for such variants fails the goal of simplicity and uniformity.

could not agree more. a well written issue, and you have my support

**Comment by Zamiell** [comment]
> This is how we have been playing I think. What would it take to firm this up? Should just make a PR?

read [convention-changes.md](https://github.com/hanabi/hanabi.github.io/blob/main/misc/convention-changes.md) to see what the process is

**Comment by Lel0uch-H** [comment]
I have expanded the scope of the issue to talk about both such rank and color clues.

**Comment by Zamiell** [comment]
@Lel0uch-H shouldn't your PR have also deleted some other sections in the doc?
