### ISSUE TITLE
Early Game Revision: Allow Tempo Clues

### ISSUE THREAD

**Issue by pianoblook** [hanabi/hanabi.github.io#738]
We were discussing when tempo clues should and should not CM in a review just now, and I was completely floored to see that the lvl 8 [Stalling Table](https://hanabi.github.io/docs/level-8/#allowable-stall-clues-stall-table) explicitly DISALLOWS tempo clues to be given in Early Game:

> For example:
It is the Early Game (severity 1).
Alice does not have any normal Play Clues or Save Clues to give (precedence 1).
Alice does not have any 5 Stalls to give (precedence 2).
Thus, Alice is not allowed to perform a Tempo Clue (precedence 3), or anything below that. She must discard.

That just seems incredibly bad, lol. Why wouldn't we want to allow tempo clues?

I suspect this might just be super outdated, since I'm 100% certain that experienced players very regularly will give tempo clues in early game. Now, I *do* agree that they shouldn't be **required** to give, if all other clues have been exhausted, but that's very different than how it's worded now.

**Comment by Lel0uch-H** [comment]
Uhhhhh, I think the idea is that tempo clues are not mandatory clues to give to *stall the early game*, i.e., tempo clues in the early game would cause a tccm if the conditions are satisfied. In other words, if we add tempo clues as a "valid stall clue for early game", we're basically turning off all tccm in the early game which sounds pretty bad.

**Comment by Lel0uch-H** [comment]
It might be worth noting that similar to the remainder of the game, tempo clues would not CM if the conditions are not satisfied (basically for unpromptable cards) so I don't understand why we need another section in the stall table in the early game part to make them "allowed". What am I missing?

**Comment by sjdrodge** [comment]
What Lel said. There's no difference in interpreting Tempo Clues between the Early Game and non-stalling situations in the Mid-Game.

**Comment by pianoblook** [comment]
So to make sure we're all on the same page, see if I'm understanding correctly: y'all are saying that (a) tempo clues should not be **required** in the early game, but (b) tempo clues should be **allowed** in early game. And such a tempo clue should *not* automatically be treated as a tccm unless normal tccm conditions apply?

That's at least how I assume(d) the conventions are structured. But the stalling table disagrees: it explicitly disallows giving tempo clues: 
> "Thus, Alice is **not allowed** to perform a Tempo Clue (precedence 3), or anything below that. **She must discard.**

**Comment by sjdrodge** [comment]
Yeah, this is just unfortunate wording. TCCMs can be given as normal.

**Comment by Zamiell** [comment]
Alice is not allowed to perform a Tempo Clue, but she is allowed to perform a Tempo Clue Chop Move. Maybe thats where your confusion is?

**Comment by sjdrodge** [comment]
That is not quite right either. A Tempo Clue that doesn't meet the TCCM requirements is still allowed (e.g. a Double Tempo Clue).

**Comment by Zamiell** [comment]
Yes, that's correct. I'll change the doc to say `Alice is not allowed to perform a "normal" Tempo Clue"

**Comment by pianoblook** [comment]
So it sounds like I actually do disagree with your interpretations then. I propose that Alice *should* be **allowed** to give a "normal" Tempo Clue if she so chooses, but it's not required

**Comment by Zamiell** [comment]
Pro: More discard modulation.
Con: Not able to give *Tempo Clue Chop* moves anymore in the *Early Game*.

Cons seem to outweigh the pros here.
