### ISSUE TITLE
Rename Tempo Clue

### ISSUE THREAD

**Issue by Zamiell** [hanabi/hanabi.github.io#740]
The fact that Piano is confused in issue #738 means that I've failed to name the moves correctly.
I propose that terminology is changed as follows.
If you have better ideas for names, I'm open to suggestions.

<br />

## Move A

*Move A* is defined as a *Tempo Clue* that meets one or more of the 5 conditions contained in this section of the doc: https://hanabi.github.io/docs/level-6/#the-tempo-clue

*Move A* never causes a *Chop Move*, because it meets one of the 5 exceptions.

I propose that move be called a *Cadence Clue*.

<br />

## Move B

*Move B* is defined as a *Tempo Clue* that does **not** meet the 5 conditions contained in this section of the doc: https://hanabi.github.io/docs/level-6/#the-tempo-clue

*Move B* never causes a *Chop Move*, because even though it does not meet one of the 5 exceptions, it is always performed in a stalling situation where "normal" *Tempo Clues* are allowed.

I propose that move be called a *Pulse Clue*.

<br />

## Move C

*Move C* is defined as a *Tempo Clue* that that does **not** meet the 5 conditions contained in this section of the doc: https://hanabi.github.io/docs/level-6/#the-tempo-clue

*Move C* always causes a *Chop Move*, because it does not meet any of the 5 exceptions and it is not given in a stalling situation.

I propose that Move C is called a *Tempo Clue Chop Move*. (It retains the old name.)

Edit - New proposal below.

**Comment by sjdrodge** [comment]
Oh god, please no. Just change the wording to make it clear that in the Early Game, Tempo Clues are not allowed to be given as Stalls and will be interpreted as normal (i.e. may cause a CM).

**Comment by Lel0uch-H** [comment]
Agree with @sjdrodge. Don't solve a problem with a sword that can be solved with a knife.

**Comment by Zamiell** [comment]
What about simply defining a *Cadence Clue* for the 5 conditions, and then leaving everything else the way it is?

**Comment by Zamiell** [comment]
I think that gets a lot of value.

**Comment by pianoblook** [comment]
agreed that all of this seems super confusing. The definition of a Tempo Clue seems crystal clear; my proposal in #738 was simply suggesting that we allow for Tempo Clues to be given in early game that meet condition #2 in the list:
> When the clued card is not a 5 and it is "out of order" (meaning that it is impossible for a Prompt to get the card played)

i.e. it seems absurd to me that we explicitly disallow such a clue to be given in certain early games (without promising an additional chop move).

**Comment by Zamiell** [comment]
*Cadence Clues* are not disallowed in the *Early Game* - that's probably where your confusion is coming from.

**Comment by pianoblook** [comment]
The doc disagrees. If we agree that what you're calling a 'Cadence Clue' is currently a form of Tempo Clue, then the doc explicitly says that is illegal:

> Thus, Alice is not allowed to perform a "normal" Tempo Clue (precedence 3), or anything below that. She must discard.

Maybe the word 'normal' is doing a lot of work here in a way that's confusing? I dunno. To be clear I opened this issue because I was playing a lvl 16ish(?) game this morning and we lost because the teammates both wrote tccm notes after a Tempo-Clue-that-met-condition-(ii)-from-the-table was given

**Comment by Zamiell** [comment]
Yes, the word "normal" is doing a lot of work here, which is why I opened this issue. =)

**Comment by pianoblook** [comment]
So it seems a lot simpler to just delete that phrase from the doc. The problem solves itself

**Comment by Zamiell** [comment]
I added it precisely because you were confused. If I remove it it will just go back to the way it was yesterday, and people will still presumably still be confused in the future.

**Comment by pianoblook** [comment]
To clarify, my teammates were not only confused, but they wrote TCCM notes when they should not have. Though admittedly now I'm becoming increasingly confused as these threads continue.

Like, what is a "normal" vs "abnormal" single tempo clue? Tempo Clues seem very well defined: the concept of a "normal Tempo Clue" seems to only appear in this context, and thus seems very confusing

**Comment by Zamiell** [comment]
In this context, a "normal" *Tempo Clue* is defined as a *Pulse Clue*.

**Comment by pianoblook** [comment]
Why not just say, "players are not required to give *Tempo Clues* in the *Early Game*" and be done with it? 

By setting the language to saying they are "**NOT** allowed", it makes it seem as if you...lol, can't give Tempo Clues.

basically I guess it sounds like you're setting up an unnecessary double-negative, yeah? Like, if what you're calling "normal" tempo clues are only the kind that are given in Stalling Situations, then that feels a lot more like a...less normal Tempo Clue, lol.

**Comment by Zamiell** [comment]
> Why not just say, "players are not required to give Tempo Clues in the Early Game" and be done with it?

The point of a precedence table is that defining at points in time that you are allowed to do things, and points in time where you are not allowed to do things. The sentence "players are not required to give Tempo Clues in the Early Game" does not belong in a section talking about a stall table - it instead belongs in a section about Tempo Clues.

**Comment by pianoblook** [comment]
to put it another way...I guess when I think of "normal", I think of non-weird situations, i.e. non-Stalling situations. 

To define "Tempo Clues that are only allowable in Stalling Situations" as being *normal* seems strange. 

In a "normal" situation (non-Stalling/non-Emergency), we allow Tempo Clues even in Early Game: it simply might TCCM  if it doesn't match any of the 5 conditions. Right?

**Comment by Zamiell** [comment]
See the chart here: https://github.com/hanabi/hanabi.github.io/blob/main/docs/level-8.md

- At severity 0, we can see that there is a ❌ in the column called "Tempo Clues", therefore they are not allowed. In this context, *Tempo Clues* really means *Pulse Clues*.
- At severity 1, we can see that there is a ❌ in the column called "Tempo Clues", therefore they are not allowed. In this context, *Tempo Clues* really means *Pulse Clues*.

Does that answer your question?

**Comment by pianoblook** [comment]
I mean I continue to understand everything you're saying - I'm just disagreeing with how it's being worded. As evidenced by my teammates chop moving from a tempo clue in the early game, I'm arguing that the current wording is confusing.

If I was trying to learn about tempo clues and early game, and I looked at that chart, it's pretty clearly displaying to me that I'm **never** allowed to give Tempo Clues unless I'm in Double Discard or higher.

But that's just not true. You absolutely **are** allowed to give Tempo Clues, but they just may or may not additionally cause a _Tempo Clue Chop Move_, as defined elsewhere in the doc. So nothing of value is lost by just deleting that whole phrase.

**Comment by Zamiell** [comment]
> If I was trying to learn about tempo clues and early game, and I looked at that chart, it's pretty clearly displaying to me that I'm never allowed to give Tempo Clues unless I'm in Double Discard or higher.

I agree, which is why I am proposing that certain types of *Tempo Clues* are renamed, which will subsequently make the *Allowable Stall Table* crystal-clear for everyone involved.

**Comment by Zamiell** [comment]
> So nothing of value is lost by just deleting that whole phrase.

What specifically are you proposing is deleted? Row 3 of the table? We (obviously) can't delete the whole row.

**Comment by pianoblook** [comment]
Well it looks as though that sort of clue - a tempo clue that would *normally* cause a tccm but doesn't because it's a stalling situation - is already defined in level 6: 

> [...] However, in the following special circumstances, Tempo Clues have enough value to justify giving them:
[...]
> v. When the clue giver is in a situation that requires them to stall (e.g. the player is Locked, etc.)

So such a Tempo Clue is already defined as being NOT normal: it's a _Stalling_ clue

**Comment by Zamiell** [comment]
I think you have it exactly opposite. A *Tempo Clue* that meets one or more of the five criteria is not a stalling clue. It is instead defined as a "normal" *Play Clue* on a card and is treated identically no matter which column of the table you are in.

**Comment by Zamiell** [comment]
What is your actionable suggestion? To rename "Tempo Clue" to "Stalling Tempo Clue"? That's potentially confusing and not very precise. Historically, when we get into this situation, we just come up with a better one-word names so that we can be laser-specific with exactly what we are talking about without having to use any qualifying words.

**Comment by pianoblook** [comment]
> What specifically are you proposing is deleted? Row 3 of the table? We (obviously) can't delete the whole row.

maybe just rename Row 3 to, like, "_Tempo Clue Stall_"? that way it's clear that it's referring to (v.) of the Tempo Clue section.

> A Tempo Clue that meets one or more of the five criteria is not a stalling clue. It is instead defined as a "normal" Play Clue

The possibility of being a "stalling clue" is already defined as **being** one of the five forms of Tempo Clues that don't cause a tccm. And the Chart should, imo, help outline *when* Condition (v) is met.

**Comment by Zamiell** [comment]
> maybe just rename Row 3 to, like, "Allowable Tempo Clue Stall"? that way it's clear that it's referring to (v.) of the Tempo Clue section.

Looks like I preempted this above. =p

**Comment by pianoblook** [comment]
oh nice. maybe we're in agreement then?

**Comment by Zamiell** [comment]
Do you agree with my last post?

**Comment by pianoblook** [comment]
Hmm, I agree that there's probably value in defining it as something distinct I guess. Dunno if making a new unrelated-sounding term is helpful, though: I feel like something like a "Tempo Stall" might be more descriptive than something catchy-but-unrelated like "Pulse"

**Comment by Zamiell** [comment]
I chose "Pulse" because its a synonym of "Tempo", and because pulse describes an action happening to a single entity (i.e. there are not two cards involved, the only point is to make the single card pulse)

**Comment by pianoblook** [comment]
mm, that's the wrong definition of Tempo being synonymized (lol is that word)

<img width="599" alt="Screen Shot 2021-08-22 at 5 40 26 PM" src="https://user-images.githubusercontent.com/32303453/130370824-d33caa47-ff59-4ca2-9a84-97f3e30e36db.png">

**Comment by Zamiell** [comment]
In an abstract way, the intention of a *Pulse Clue* is to "cause action", or "activate". This is exactly what an object does when it pulses, so I think it is a good match.

Do you like *Activation Clue* better?

**Comment by Zamiell** [comment]
I don't think *Activation Clue* is as good because it is longer to say, and it doesn't communicate (as much) that we are only operating on a single entity.

**Comment by pianoblook** [comment]
Personally my vote would still just go for something with the word Tempo Clue in it - I don't think shorter is better if it comes at the cost of clarity. _Tempo Stall Clue_ or _Stalling Tempo Clue_ both seem to hit the nail on the head 🤷 

Hmm...would it technically work to just classify it as a type of "Fill-In"? Calling it a "Tempo Fill-In" might just work; the table would still reflect that a fill-in that gives immediate tempo would still take precedence over a fill-in of some other random card.

**Comment by Zamiell** [comment]
Tempo Fill-In clue doesn't make sense because then you would have to rename Fill-In clues to something else in order to disambiguate it

**Comment by timotree3** [comment]
I feel like introducing new vocabulary for this hurts more than it helps. Players can only remember so much vocabulary. The confusion came from the following passage

> For example:
> - It is the Early Game (severity 1).
> - Alice does not have any normal Play Clues or Save Clues to give (precedence 1).
> - Alice does not have any 5 Stalls to give (precedence 2).
> - Thus, Alice is not allowed to perform a "normal" Tempo Clue (precedence 3), or anything below that. She must discard.

I suggest you simply change it to


> For example:
> - It is the Early Game (severity 1).
> - Alice does not have any normal Play Clues or Save Clues to give (precedence 1).
> - Alice does not have any 5 Stalls to give (precedence 2).
> - Alice does have a Tempo Clue to give (precedence 3) but Tempo Clues are not a valid stall in the Early Game. So if Alice gives the clue, it will be interpreted as normal and may trigger a Tempo Clue Chop Move.

**Comment by timotree3** [comment]
If the part about discarding is important

> For example:
> - It is the Early Game (severity 1).
> - Alice does not have any normal Play Clues or Save Clues to give (precedence 1).
> - Alice does not have any 5 Stalls to give (precedence 2).
> - Alice does have a Tempo Clue to give (precedence 3) but Tempo Clues are not a valid stall in the Early Game. So if Alice gives the clue, it will be interpreted as normal and may trigger a Tempo Clue Chop Move.
> - If Alice does not want to give a Tempo Clue Chop Move, she must discard.

**Comment by florian-5f3759df** [comment]
I agree that removing circumstance number v from the current Tempo Clue description, and then splitting off the stalling variant, makes sense. (Circumstance i-iv all depend on the hands/cards themselves, while v depends on the game state in a different way, so they conceptually feel different.)

Of these, I'd like the current Tempo Clue (without circumstance v) to keep its name. The stalling variant could have a new one, although some permutation of the words Tempo Stall Clue seems easiest to remember, so I think that would make sense.

If is has to be a new name, maybe Ritenuto Stall Clue / Lento Stall Clue? (Although maybe after Chiaroscuro Pink sadly no longer exists, the taste for Italian words on the site has diminished.) Or maybe Syncopated Clue or Off-Beat Clue, kind of associating delay/stall with tempo in the musical sense.

**Comment by Zamiell** [comment]
I've updated the doc now with roughly what Tim outlined. Thanks Tim.

However, the passage is *still* unclear because we haven't established a clear distinction between *Stalling Tempo Clues* and *Tempo Clues* that meet one of the 5 criteria. So I think more work needs to be done.

Again, I'll propose the following (new) dichotomy:

1. *Stalling Tempo Clues*
2. *Cadence Clues*
3. *Tempo Clue Chop Moves*

With this dichotomy, a *Cadence Clue* is distinct from a *Tempo Clue*, so the stalling table becomes extremely clear.

**Comment by sjdrodge** [comment]
I really think the clearest model is as follows. A Tempo Clue refers to any clue which causes cards to play earlier but doesn't get any new cards in the process. A Tempo Clue Chop Move occurs any time a Tempo Clue is given under circumstances where it's not considered a "good enough" clue. Being in a stalling situation of high enough severity is one of the circumstances where a Tempo Clue is "good enough" to not cause a Chop Move.

We should simply focus on communicating this clearly in the document. New terminology and concepts are not required and I think they just serve to confuse the issue.

**Comment by Zamiell** [comment]
Here's a draft, I think this is ultra clear and the way to go.
If you guys really don't like "Cadence Clue", then offer another clarifying word to tack on to "Tempo Clue" like "Stalling Tempo Clue" is.

<br />

### The Tempo Clue

- *Tempo Clues* are defined as clues that "get" no new cards. The purpose of a *Tempo Clue* is to get 1 or more cards played that **already** had a clue on them.
  - If a clue is given to a card that is **already** known to be playable, then that would **not** count as a *Tempo Clue*. It would instead be a *Burn Clue* (i.e. a clue that accomplishes nothing).
- As explained in the beginner's guide, we do not typically perform *Tempo Clues*, because they do not meet *[Minimum Clue Value Principle](first-principles.md#2-minimum-clue-value-principle)*.
- When a *Tempo Clue* touches multiple cards, the focus is on the left-most card.
  - The exception is if one of the cards was previously *Chop Moved*. In that case, the focus is on the left-most *Chop Moved* card.
- If a *Tempo Clue* touches multiple cards, it typically means that all the touched cards are playable. See the *Double Tempo Clue* section below.

#### The Cadence Clue (A Valuable Tempo Clue)

- In some special situations, *Tempo Clues* have enough value to justify giving them:
  1. When it gets two or more clued cards to play
  1. When the clued card is not a 5 and it is "out of order" (meaning that it is impossible for a *Prompt* to get the card played)
  1. When the clued card was *Chop Moved* and it is now playable
  1. When playing the clued card would "unlock" someone's hand (see the section on *Locked Hands* later on)
- If a *Tempo Clue* is given in any of these situations, it is called a *Cadence Clue*.
- *Cadence Clues* can be given at any time. They don't have any special rules associated with them and they are treated in exactly the same way a "normal" *Play Clue* is.

#### The Stalling Tempo Clue (A Non-Valuable Tempo Clue)

- If a player gives a *Tempo Clue* that does **not** meet one of the 5 criteria of a *Cadence Clue*, it is treated differently and given a different name.
- Sometimes, players are in "stalling situations" where it would be illegal for them to discard (like when they have a hand that is completely clued). In some specific stalling situations, it is okay to give a *Tempo Clue* that doesn't meet the criteria for a *Cadence Clue*. This is called a *Stalling Tempo Clue*. Since everyone sees that the player giving the clue was in a stalling situation, they can understand what is going on.
- For level 8 players, see the *[Allowable Stall Clues](level-8.md#allowable-stall-clues-stall-table)* section. If you are lower than level 8, the details are not important right now.
- Obviously, players are only allowed to give a *Stalling Tempo Clue* in a valid stalling situation. If a player gives a *Tempo Clue* that does not meet the criteria for a *Cadence Clue* in an otherwise ordinary situation, then they must be intending to send a deeper message. See the *Tempo Clue Chop Moves* section below.

<br />

**Comment by pianoblook** [comment]
> 1. Stalling Tempo Clues - Tempo Clues that don't meet any of the criteria and are done in a valid stalling situation
2. Tempo Clue Chop Moves - Tempo Clues that don't meet any of the criteria and are not done in a valid stalling situation
3. Cadence Clues - Tempo Clues that do meet one or more criteria

The thing is that #2 and #3 are redundant: as Floriman and I mentioned, being "a valid stalling situation" **is already** one of the five criteria outlined. So this can be drastically simplified:

> 1. Tempo Clue Chop Moves - Tempo Clues that don't meet any of the criteria
> 2. Tempo Clues - Tempo Clues that do meet any of the criteria

**Comment by Zamiell** [comment]
They are not redundant with respect to the stalling table, because some *Tempo Clues* are legal at level 1 and some *Tempo Clues* are not legal at level 1. Breaking it into 3 moves solves this problem.

**Comment by vEnhance** [comment]
I like the three-move division actually. The old (v) feels different from (i)-(iv) to me and more generally I think it's nice to split the business-as-usual-no-reaction-needed tempo clues from the oh-crap-i'm-locked kind of tempo clues. I'm okay with one extra word.

I'm curious how people feel about "Tempo Clue Stall" rather than "Stalling Tempo Clue". I think it fits better with the existing "5 Stall" (and is shorter).

I also suggest we flip the order of Tempo Clue Stall / Stalling Tempo Clue and Double Tempo Clue in the Level 6 doc now, since DTC is a special case of Cadence Clue. (And maybe we might as well mention explicitly that DTC is a special case of Cadence now that we have a new word.)
