### ISSUE TITLE
Rename Shallow Discard/Misplay

### ISSUE THREAD

**Issue by jack67889** [hanabi/hanabi.github.io#748]
When a teammate does an odd discard or even misplays, nothing related to ‘shallow’ seems to come to mind. By now I’ve already heard many times that people think it’s a nonsense name. Some time ago in a review, we had trouble discussing the situation, because people couldn’t think of the name of the convention. So we discussed better names and arrived at more descriptive ones:

Odd Discard
Even Misplay

**Comment by jack67889** [comment]
My initial concern was obviously with using non-descriptive names. But merging it with positional discard/misplay seems also fine with me. 

Side note would be that quite a considerable amount of players treat a positional misplay not as asking for an even amount of blind-plays, but as a sort of unnecessary positional in the first place (in cases where you can't discard non-chop safely, but you can bomb). Maybe it's good to clarify that if we don't go for the odd/even names, but merge the text.

**Comment by Zamiell** [comment]
changed it to Triple Positional Discard and Quadruple Positional Discard
