### ISSUE TITLE
[convention proposal] Pink Shifting

### ISSUE THREAD

**Issue by pianoblook** [hanabi/hanabi.github.io#751]
Just wrote a doc about this, link [here](https://docs.google.com/document/d/1jnJqxCNXC4m1iLxt2IbtjrqR7MxMnVp2mjiO_CQ6o5Q/edit?usp=sharing). But below is the main chunk of it:

------

> This proposal is an expansion of available Signal Shifts in Pink. Specifically, I argue that any rank clue can be used to trigger a Pink Shift, as long as it resolves immediately and unambiguously.

### Pink Shifting [with Pink Lies]
- I propose that certain Signal Shifts can be performed by violating Pink Promise with nearly ANY Rank clue (with few exceptions)
- These Shifts include _4 Charms, Turnabouts (for 5s)_, and _3 Discharges (at Dawn)_.
- The key is that the true identity of the focused card will be immediately determined based solely on which Finesse Position is blind-played - the actual clue that was used almost never makes a difference in this determination.
- In the rare cases in which the card’s identity would still be ambiguous after the blind-play, Pink Shifting is not permitted.

> Example 4 Charm
3-player game, Pink 5 Suits. Turn 1.
Cathy’s hand is [r3 i4 b2 g5 g3]
Alice clues 2 to Cathy.
Since i4 would require 3 blind-plays (or ‘2 or more’ if using Dawn), Bob should not respect the possibility of this being a _Bubblegum (Triple) Finesse_.
Further, he knows that if he were to simply blind-play slot 2, Cathy would incorrectly mark her card as i3 (as a _Taffy Bluff_).
Therefore, Bob Charms as a _Pink Shift_. As a result, the focused card is unambiguously promised as exactly i4.

**Comment by pianoblook** [comment]
btw obviously the 3 Discharge part doesn't apply unless you're using Dawn, but everything else works cleanly either way. 

In fact this proposal becomes much simpler to describe if you don't consider the Dawn case. The two main proposals here are:

(a) Expanded 4 Charms (using a Pink Lie)
(b) Expanded Turnabouts on i5s (using any non-Taffy rank)

**Comment by pianoblook** [comment]
https://hanab.live/shared-replay/632923#3

**Comment by Zamiell** [comment]
looks like this is stale, unless anyone else has more to say about it?

**Comment by pianoblook** [comment]
it's a cute idea, but probably fairly niche + error-prone
