### ISSUE TITLE
Convention rework: Trash bluff discard order and Junk 1s discharge

### ISSUE THREAD

**Issue by Lel0uch-M** [hanabi/hanabi.github.io#753]
The trash bluff section says this:

> In the case where multiple cards are clued as part of a Trash Bluff, all of the touched cards are considered to be trash. However, the focus of the clue should be discarded first.

The Junk 1s discharge says this:

> This situation cannot call for a Trash Finesse or Trash Bluff, because those moves promise that all of the ancillary touched cards are also trash (which is untrue in this case). Since playing slot 1 won't work, we agree that this should call for a Discharge. As a result, the clued player will know to only mark the focused 1 as trash and play the other 1 as normal.

The idea of "discarding focus of trash bluff since non focus could be good" has become obsolete, since the former statement existed only because earlier non-focused 1s could still be good, which is no longer the case after the inception of the junk 1s discharge.

Advantage: makes the doc consistent in terms of trash discard order and allows more opportunities for TOCM.

Disadvantage: none that I can think of.

**Comment by Zamiell** [comment]
@Lel0uch-M can you submit a pr?

**Comment by Lel0uch-H** [comment]
Yes, I will.
