### ISSUE TITLE
4 Charm Change

### ISSUE THREAD

**Issue by Zamiell** [hanabi/hanabi.github.io#755]
In a 4-player game:
- Red 1 is played on the stacks.
- Alice clues blue to Donald, touching a blue 4 as a *Play Clue*. (Blue 4 is currently three-away-from-playable.)
- Bob sees that Cathy has a red 3 on her *Finesse Position*.

Here, the conventions state that Bob should assume a *4 Double Bluff* over a *4 Charm*. In this case, Bob will play exactly red 2, and Cathy will play red 3.

I propose that this convention is changed. As long as Cathy's *Finesse Position* card is two-away-from-playable, Bob should assume a *4 Charm* over a *4 Double Bluff*.

Reason: It is extremely difficult to see that a *4 Double Bluff* will work in this situation when you are Bob. Players in our group commonly make this mistake, leading to many lost games. Specifically, I made this mistake 3 days ago, and I saw this exact same mistake from two other high-level group members in a single 4 hour session today.

As far as optimality is concerned, I do not think that choosing one side or the other results in a meaningful difference in EV. Thus, we should configure the conventions in whichever way will allow for the least amount of mistakes.

**Comment by Zamiell** [comment]
i discussed this with kimbi, kyle, and others last week (i forgot exactly who), all seemed to be in favor for it

**Comment by Dr-Kakashi** [comment]
I'm not in favor of this proposal.

I'm making the assumption that it's the fault of the clue giver that missed seeing Cathy hold a 1 away card on finesse position that connects to the 4 clue. 

Specifically, this situation would only happen if the 4 matches the 1 that has already been played on the table. Or another way to say the same thing is: we aren't allowed to 4 charm with 4's that are 2 away. 

I think a nuance that would be lost: 
Conditions: 
1. Cathy can see Donald holding a 4 (that is 3 away and a valid 4 charm target) 
2. Bob has a playable card on slot 4

Alice decides to 1 for 1 the card on slot 4 in Bob's hand. Cathy would immediately know she has a card that is 1 away on slot 1.

**Comment by Zamiell** [comment]
> I'm making the assumption that it's the fault of the clue giver that missed seeing Cathy hold a 1 away card on finesse position that connects to the 4 clue.

not quite.
it could be alice making a mistake, or it could be bob making a mistake

**Comment by Zamiell** [comment]
**4 Charm** (change) (by Zamiel)

- *4 Charms* now take precendence over *Double Bluffs* in the specific case where Bob sees that Cathy has a *one-away-from-playable* card on her *Finesse Position*.
- For example, in a 4-player game:
  - Red 1 is played on the stacks.
  - Alice clues blue to Donald, touching a blue 4 as a *Play Clue*. (Blue 4 is currently three-away-from-playable.)
  - Bob sees that Cathy has a red 3 on her *Finesse Position*.
  - If Bob has exactly a red 2 on his *Finesse Position*, then he knows that Alice's clue would work as a *4's Double Bluff*.
  - However, since the red 3 on Cathy's *Finesse Position* is *one-away-from-playable*, Bob knows that *4 Charms* take precedence over this interpretation.
  - Bob blind-plays his *Fourth Finesse Finesse* card. It is a red 2 and successfully plays on the stacks.
- *Double Bluffs* take precedence over *4 Charms* when Cathy has a directly playable card on her *Finesse Position*. (This is unchanged from how it worked before.)
- For example, in a 4-player game, similar to the previous example:
  - Red 1 is played on the stacks.
  - Alice clues blue to Donald, touching a blue 4 as a *Play Clue*. (Blue 4 is currently three-away-from-playable.)
  - Bob sees that Cathy has a green 1 on her *Finesse Position*.
  - If Bob has any playable card other than green 1 on his *Finesse Position*, then Alice's clue will work as a *4's Double Bluff*.
  - Bob knows that in this situation, *Double Bluffs* take precedence over *4 Charms*, so he blind-plays his *Finesse Position* card. It is a yellow 1 and it successfully plays on the stacks.
  - Cathy blind-plays her *Finesse Position* card. It is a green 1 and it successfully plays on the stacks.

**Comment by Dr-Kakashi** [comment]
I'm still against this. 

Think about all the cases where Cathy has a 1 away card from playable on slot 1 and Bob has the matching card on slot 1. 

I find it hard to believe that Charms happen more frequently than those cases. Even though charms are a single blind play. There are more dual blind plays from slot 1 on both Bob and Cathy. 

Yes, Charms are best early on. Probably the strongest in the starting hand, but as the game progresses, Charms happen exponentially less. Not only are 3 away 4's less likely to be available, but the heatmap of playable cards are towards the left of the player's hand as the game progresses. 

Not many playable cards even reach the Charm slot as the game progresses.

**Comment by Zamiell** [comment]
you seem to be arguing from a place of "if we changed the conventions, we could squeeze out more efficiency and better scores overall".
i'm arguing from a place of "i'm tiring of losing games to getting 3 strikes over and over and over again, let's change the conventions to make it less efficient and get worse scores so that normal people who don't dedicate their entire lives to hanabi can get through a game without making a mistake".

**Comment by Dr-Kakashi** [comment]
> "i'm tiring of losing games to getting 3 strikes over and over and over again, let's change the conventions to make it less efficient and get worse scores in return for making normal people who don't dedicate their entire lives to hanabi get through a game without making a mistake".

Is this argument even valid? Saying "normal" people is just generalizing and being subjective. What level players are we talking about here? What is a normal player to you?

I agree with you in the fact that there are few Hanabi "masters" who are willing to put the time and dedication to push the limits of the game. Players simply make mistakes, learn from them, and grow. I don't see why it would be better to intentionally make the conventions "less efficient and get worse scores" in order to compensate for mistakes made by the players with fewer experience.

**Comment by Dr-Kakashi** [comment]
> you seem to be arguing from a place of "if we changed the conventions, we could squeeze out more efficiency and get better scores overall".

I'm really not speaking from this place that you mentioned. If we did 1,000 games and count up charms vs 4 double bluffs, where Cathy had a playable on slot 2. I'm sure it would show what I'm explaining here, where Charms exponentially decreases in # as the game goes on, whereas the opposite would occur with the 4 double bluffs. I'm NOT speaking from a Charms have a 2 for 1 vs 4 double bluffs 3 for 1 efficiency, point of view.

**Comment by pianoblook** [comment]
fwiw I'm with Kakashi on this strategically, in the more general case, but only outside of Dawn. After the first couple rounds I'd agree that it's simpler *and* more likely to be a double bluff than a charm.

But as for what agreement would actually lead to lower strike rate, I have no idea

**Comment by hakha3** [comment]
I dont have that many games under my belt but it feels to me that bc 4 charm is only about 3 away 4s distinction between the 2 is mostly about first rounds where there are more 4 charms than 4 DB.

**Comment by Zamiell** [comment]
> I don't see why it would be better to intentionally make the conventions "less efficient and get worse scores" in order to compensate for mistakes made by the players with fewer experience.

it's "better" because we want to strike a compromise between getting good scores, having the conventions be easy to play with, and having fun.
see convention-goals.md for more info on this
