### ISSUE TITLE
Always Loaded Principle should delete other sections?

### ISSUE THREAD

**Issue by Zamiell** [hanabi/hanabi.github.io#759]
@Lel0uch-H

**Comment by Lel0uch-H** [comment]
I two possible options for how we could go about it

- Keep the older sections for some time while people become aware of this principle, and then remove the older ones.
- Delete them right away, but give an explanation in #convention-announcements that the older sections are being subsumed.

**Comment by Zamiell** [comment]
always loaded principle will be announced during the next round on announcements, e.g. in 1-2 weeks

in the meantime can you submit a pr that deletes the relevant sections
