### ISSUE TITLE
Move 5 stall’s to Level 2 (not level 1)

### ISSUE THREAD

**Issue by vEnhance** [hanabi/hanabi.github.io#762]
For newcoming players I think this is one less thing to worry about at first, and the *need* to 5-stall in No Variant at Level 1 is not that drastic.

**Comment by Zamiell** [comment]
i agree, does anyone else care

**Comment by pianoblook** [comment]
I'd be fine with this too. There's certainly plenty to focus on in level 1 already.

I guess the only counterargument would be that 5 stalls are pretty natural feeling for beginners, and it could therefore be weird to not mention them until later. But w/e they'll get to level 2 soon enough anyway, huh?

**Comment by Zamiell** [comment]
thinking about this more, i think that 5 stalls + prompts + finesses should go to a new level 2, and then the old level 2 can become level 3, and every else moves up a level

evan what do you think about that?

**Comment by vEnhance** [comment]
I think my inclination is to keep prompts and finesses at level 1. In my (admittedly limited) experience dragging in new players, I think the most important thing they need to learn is that all of our play clues are *promises* --- if someone promises g4 is playable, but the stack is only up to g2, then you have g3. That's something I'd want a new player to internalize as soon as possible.

Whereas the 5 stall is just one extra thing that needs explaining and doesn't contribute much to level 1 play (and people don't tend to stay at level 1 for very long).

**Comment by Zamiell** [comment]
ok

can you do a PR moving 5 stall to level 2
