### ISSUE TITLE
Define notion of promise

### ISSUE THREAD

**Issue by vEnhance** [hanabi/hanabi.github.io#763]
see e.g. https://discord.com/channels/140016142600241152/456214043351580674/753279265709228042

Since many of our moves promise a card of some sort, I think it may be useful to introduce the word "promise" early. That way prio finesse is philosophically no different than a normal finesse, say -- both of them are promises that some intermediate card is ready to be played.

I remain agnostic on whether fibs count as promises or not :P

**Comment by Zamiell** [comment]
defining the term *Promise* with respect to a connecting card conflicts with the already-existing *Pink Promise* convention
