### ISSUE TITLE
Delete Unnecessary Trash Chop Move

### ISSUE THREAD

**Issue by pianoblook** [hanabi/hanabi.github.io#767]
We've let this ambiguity linger for a while now, so I guess it's as good a time as any to address the issue again.

**Current Problem**: _Unnecessary Trash CMs_ are indistinguishable from _Chop Move Ignitions_.

**Proposal**: Delete _UCMs_, and thus let _CM Ignitions_ always take precedence.

This was already proposed back in the [UCM Principles ](https://docs.google.com/document/d/1Y9SSdwKZjjvkG4E80T8SNoRawkYdf14zNw204EuURiU/edit#heading=h.6i74y656u0uw) doc (#479). As evidence/argument for this change, I'll quote the most relevant passage from the doc + add a few highlights for quick reading:

> [Proposal]: _Unnecessary Trash CMs_ are now restricted to only playables
We hesitate to even call this a downside, because frankly **the ambiguity of Unnecessary Trash CMs (UTCM) as written are quite frustrating and therefore are very rarely performed**. That said, it is true that we would no longer be allowed to UTCM a non-playable critical. Here are a few reasons for why this doesn’t concern us:
> - In many cases, clever players can already **just use Rank Choice or other Suboptimal save on a critical card** to trigger a blind-play, without resorting to UTCM.
> - The blind-play component only occurs in situations where the card(s) could have been easily saved already, so **eliminating this edge-case feels like a very inconsequential loss**.
> - For the low cost of disallowing these cases, **we get a huge amount of added clarity and tempo**. Since this move would now always be a clear and immediate 2-for-1, we strongly believe that narrowing its scope will result in an increase in usage and appeal.

**Comment by EhDrone** [comment]
I also think this is a good idea.

**Comment by mmelwen** [comment]
I thought it was already deleted and replaced with playful ignition. The only trash cm that should work after playful is official i believe is the Unnecessary trash finesse cm where the trash was unknown Bob plays specifically 
r1 on the stacks and all other 2's are down
r2 x x x x 
x x x 2 5
now Alice clues 2 and r2 plays the 5 is cmed correct ?

**Comment by Zamiell** [comment]
> r1 on the stacks and all other 2's are down
r2 x x x x
x x x 2 5
now Alice clues 2 and r2 plays

that looks like a *Trash Finesse*.
after the red 2 is played, no further actions need to be taken by the team.
whether or not Cathy's slot 5 card is *Chop Moved* or not entirely depends on the rest of Bob's hand, making it *Unnecessary* or not

**Comment by mmelwen** [comment]
yes but if r2 was down before the clue was given then Cathy should play slot 5

**Comment by pianoblook** [comment]
There's a huge difference there, mel:
- if a *known* trash is clued off-chop which then gets a blind-play, it converts from to CM --> Play(ful).
- if a *play* clue turns out to have been a _Trash Finesse/Bluff_, then it converts from a play --> CM

**Comment by mmelwen** [comment]
I thought was already deleted as Mango pointed out!!

**Comment by gnarama** [comment]
I believe UTC should ultimately take precedence over the pull, for a variety of reasons.
1) Most of our play/save rules are built upon the principle that if something can either be a save or a play, we interpret it as a save until given additional information. This would remain in line with that train of thought. Additionally, while I acknowledge that cm'd cards often require another clue to 'get', this will often result in the end net-result, but with less stringency.
2) The case where the known trash chop moves a 5(or 5s) and another card to its right shouldn't convert to a pull on the 5. 
3) The case where we cm multiple cards of matching rank and/or color doesn't require a blind play. For example, R3 is critical, and 1 is clued to xx1R4R3. doesnt require r4 to blind play. xx1Y3R3 is similar.
4)The most common use I've seen of cluing know trash has been to cm 5s very early in a game while getting additional plays. Anecdotally, it seems the current convention captures the most useful scenario of it.
There are other cases, and I'm sure some could be made for CMI as well.  In general, it truly seems to me that the CMI is just a less flexible form of UTCM, which gets efficiency in some number of cases.
Piano has noted that it seems to be 'greedy' to want to get a slot 1 play along with a cm that we could directly clued. I noted that a similar argument could be said for the ignition. However, I think the general sentiment doesn't hold up. Both of the conventions are there for the almost explicit purpose of increasing efficiency (and tempo, in regards to the ignition). Efficiency isn't greedy, it's a required component of the game.

**Comment by florian-5f3759df** [comment]
Since I was involved in helping with some versions of the unnecessary stuff, I'd just like to concur: I also agree with deleting this move and updating the doc in the relevant section (i.e., deleting the unnecessary chop move and perhaps adding a clarifying link to the chop move ignition).

**Comment by Zamiell** [comment]
> I believe UTCM should ultimately take precedence over the pull, for a variety of reasons.

are you in favor of deleting chop move ignitions entirely them? or do you want to keep them around in [some edge case where UTCM would not apply]?

**Comment by pianoblook** [comment]
> 1. Most of our play/save rules are built upon the principle that if something can either be a save or a play, we interpret it as a save until given additional information. This would remain in line with that train of thought. 

Sure: when ambiguity exists, you should basically always assume a Save. This change would erase the ambiguity completely, though, and therefore let players safely + immediately trust playability.

> 2. The case where the known trash chop moves a 5(or 5s) and another card to its right shouldn't convert to a pull on the 5.

I've never seen a _Unnecessary Declined 5CM TCM_, and would be surprised if anyone's ever noticed the opportunity, let alone pulled it off. Such a rare situation shouldn't really factor into this decision imo.

> 3. The case where we cm multiple cards of matching rank and/or color doesn't require a blind play. For example, R3 is critical, and 1 is clued to xx1R4R3. doesnt require r4 to blind play. xx1Y3R3 is similar.

This is a solid point. I would counter that in a subset of these scenarios you could still get Bob's slot 1 while also 'getting' the critical on chop by simply doing a Suboptimal Save (e.g. 3 in your first example and red in your second)., but of course that's unfortunate *if* the secondary card would therefore be left in danger. m
More importantly and generally, though, I'll also point out that this sort of dilemma would **only** arise in cases where the 2+ cards could be saved normally anyway (hence it being 'Unnecessary'). So this is never an argument about increased *safety*, but rather about increased *efficiency*. Since the 'lost opportunity' of a 3-for-1 in this case still results in a 2-for-1 save, I don't see it as a significant loss.

> 4. The most common use I've seen of cluing know trash has been to cm 5s very early in a game while getting additional plays. Anecdotally, it seems the current convention captures the most useful scenario of it.
Once again I've literally never seen this occur, and I don't really see why it ever should *need* to occur outside of 1:10,000 anomalies. Just clue the 5 normally. Or clue or bluff Bob's card and let someone else clue the 5.

>    n general, it truly seems to me that the CMI is just a less flexible form of UTCM, which gets tempo in some number of cases.
Yes, they are less flexible but more compact + immediately understandable. In basically any convention you can think of there will always be a tradeoff between **flexibility** and **information**. For example we could make bluffs a lot more "flexible" and frequent if we allowed all 4s to be valid single bluff targets. But then we start diluting their *impact*. 

So to be very clear, yes I am staunchly in favor of **restricting the scope** of this style of clue, precisely because - I claim, at least - that it drastically *increases* their effectiveness. 

My claim is that the gain in tempo and information of favoring the Ignitions far outweigh the much more watered down "CM or playable" interpretation.

> Piano has noted that it seems to be 'greedy' to want to get a slot 1 play along with a cm that we could directly clued. I noted that a similar argument could be said for the ignition.

The point I was getting at gets back to the frequency-vs-impact argument above. On a macro scale, intentionally disallowing UTCM interpretations means decreasing the number of fancy 2+-for-1 clues on average, instead favoring the **less* common Ignition interpretation. Hence, prioritizing CM Ignitions will be a comparative net loss of raw Efficiency, in favor of clarity & tempo.

**Comment by gnarama** [comment]
"I've never seen a Unnecessary Declined 5CM TCM, and would be surprised if anyone's ever noticed the opportunity, let alone pulled it off. Such a rare situation shouldn't really factor into this decision imo."
I've both seen it and performed it. And I honestly don't understand why you'd be surprised it was 'pulled off'. Using KT to cm a 5 meets the most basic of the definitions and it seems easy to pull off. 
I've also seen the other things occur, which you are happy to discount, so I doubt we will get far in this discussion.

**Comment by Zamiell** [comment]
kyle, how do you feel about this convention change on the axis of possible-player-mistakes?
this is the axis I most care about.

in other words, since both conventions are complicated and error prone, do you think that players would have an easier time navigating *Unnecessaryness*? or navigating ignitions?

it strikes me that *Chop Move Ingitions* are always fully-synchronous, while *Unnecessary Trash Chop Moves* are asynchronous. (is this correct?)

**Comment by Zamiell** [comment]
ok given that kyle is not responding i guess i'll vote in favor of this although i think kyle's concern is valid and i am not fully convinced either way

**Comment by Zamiell** [comment]
I added this to the doc:

```
- Note that performing a *Unnecessary Trash Chop Moves* is explicitly illegal, since that move would be indistinguishable from *Chop Move Ignition*.
```

**Comment by Zamiell** [comment]
besides adding that and deleting example 2 in the first section, i don't believe any other changes to the doc are necessary
