### ISSUE TITLE
Move Finesse with a Lie Component to Advanced Strategies - Special Finesses

### ISSUE THREAD

**Issue by SL765** [hanabi/hanabi.github.io#769]
Coming from #766, it seems NV games at lv22 don't need the Finesses with Lie Components which in its current state is fairly limited in use and adds a lot of complexity for little gain. Might as well move it to extras and refer to it when relevant. It's not rarely used, but it might be rarely used correctly.

**Comment by Zamiell** [comment]
seems fine

**Comment by Zamiell** [comment]
can you submit a PR
