### ISSUE TITLE
Fix Clue Assumption for (Light) Pink, (Muddy) Rainbow, Omni, and Hard Variants

### ISSUE THREAD

**Issue by SL765** [hanabi/hanabi.github.io#770]
Coming from #766.

First, see [The Continuation Clue (Touching Both Inside and Outside a Layer)](https://hanabi.github.io/docs/extras/play-clues#the-continuation-clue-touching-both-inside-and-outside-a-layer).

Sometimes, a player will decide their best action is to give a _Finesse with a Lie Component_, expecting to give a _Fix Clue_ later.

However, in variants with _Pink_, _Rainbow_, and/or _Omni_ suits, _Fix Clues_ can often become difficult, if not impossible to give, as drawing a card of these suits means that at least half of the clues given to the blind-player will touch the newly drawn card, and be interpreted as a _Continuation Clue_.

As an exception, a clue given to a player who is playing into a _Layered Finesse_ is also considered a _Fix Clue_ if:

1. It would touch all Pink, Rainbow, or Omni cards, and;
2. It renders the card they were going to blind play impossible to be what it would've played as,

regardless of whether it touches cards outside of the original layer or not. 

The clue receiver should assume Good Touch Principle on the newly clued cards, but not make assumptions about the playability of them, and resume the _Layered Finesse_ from the remaining cards in the original layer that could still be the card they were finessed for.

If the _Fix Clue_ is a rank clue, and the card that was stopped from blind-playing was later revealed as a _Pink/Omni_ card. The clue receiver should mark that card as that rank, following **Pink Fix Promise**.

Hard Variant: Any clue that interrupts an ongoing layered finesse is a fix regardless of the existence of these suits, and the section above applies.

Couple things not covered:
Pink/Rainbow/Omni/Deceptive 1s/5s, Dual Color suits and Synesthesia.

Special 5s might be better off with this assumption since you can pick up extra cards from fixes, 1s will probably just end up picking up more trash.

DC: The only full blockers are cards of the same suit unless ambig+DC so no.

Syn: yikes.

**Comment by Zamiell** [comment]
this is kind of self-evident / obvious, but if you want to create a PR that lays it out explicitly, then you can.
should probably submit a PR for the other issue first though

**Comment by Zamiell** [comment]
closing since a pr was not submitted
