### ISSUE TITLE
Taffy 5 Ejection

### ISSUE THREAD

**Issue by Dr-Kakashi** [hanabi/hanabi.github.io#771]
I've been thinking the past few days about the Taffy Triple Bluff. We've been moving towards having fewer blind plays with players having a clearer idea of what cards they hold (I.e. deleting triple bluffs or even moving away from double bluffs). I was thinking, why don't we apply this to the pink 5? 

Suggestion: 
Pink clue to 5 is just a 5CE
Rank clue using 1, 3, or 4 that touches pink 5 as the focus now follows the rules of 5CE 
- It is highly unlikely that a Taffy Triple Bluff is occurring
- If players want to play with Taffy Triple Bluff at the same time as this convention, then the next player needs to look at the next 2 players to see if they both have a playable card on slot 1 to confirm a Taffy Triple Bluff is occurring. If impossible, then revert to Taffy 5 Ejection

This will delete Taffy Triple Bluff. I wrote this post in Haste, so if you guys can think of any conflicts with our current conventions, it would be most appreciated.

Review of Conflicts:
- 5CE 
     - Color clue is not used, so no conflict
- Trash Push Ejection 
     - Cannot use known trash clues on pink 5
- The Bad Chop Move Ejection 
     - Cannot use known trash clues on pink 5
- The Rank Choice Ejection 
     - Potential Conflict, resolution: you are unable to clue rank 2 on pink 5, if it is on chop slot
     - If pink 5 is playable and 5 is given to pink 5, it works as a Rank Choice Ejection
- Trash Ejection
     - Cannot use known trash clues on pink 5
- Replay Ejection (Not possible)
- Poke Ejection (Not possible)
- Self Color Ejection 
     - Recluing 5 without giving any extra information should just cause an ejection with no conflicts
- 5 Pull
     - Currently Reviewing 5 pull ejection/discharge, but I don't see it in the doc. Actually, this reminds me. Have we not formally approved 5 Pull Ejection's or Discharge's? lol 🤣
- Discharges
     - Shouldn't be considered as the next player will always eject with this convention

**Comment by pianoblook** [comment]
I'd definitely be in favor of this. I'd proposed a more general form of this (_'Pink Shifting'_) before in #751 but that was probably too big of an overhaul to ever hope to get passed.

I don't see any way this could conflict with anything else, other than if you clue it as a 2 --> looks like a normal Taffy Bluff for i3

**Comment by Dr-Kakashi** [comment]
Thanks for the input. I didn't consider Taffy Bluff for i3. 

Combining that with the conflict with Rank Choice Ejection, that means you can use rank 1, 3, or 4 on i5 to cause an ejection if this passes. 

That's still quite good compared to not having the convention. There's also the potential bonus of picking up other cards as well.

**Comment by Zamiell** [comment]
post examples of it actually being used in games, theorycrafted moves with little applicability have no place in the doc
