### ISSUE TITLE
Rename "Critical 4 Bluff" to "Critical Color Bluff"

### ISSUE THREAD

**Issue by Romain672** [hanabi/hanabi.github.io#777]
Confusing to me.
So potentially confusing for more people.

**Comment by pianoblook** [comment]
> its important that move names are as short as possible, or else they lose their utility as concept handles

How about 'Critical Color Bluff' then?

But meh, the concept itself is confusing/unintuitive so renaming it can only go so far. If folks don't want to screw it up it's probably more an issue with how it's being taught/presented. 🤷

**Comment by Lel0uch-H** [comment]
+1 for "Critical Color Bluff". Name covers crit 2-away 2s in UOD variants too.

**Comment by mangopie1** [comment]
The only place to use "critical color bluff" is 4. Naming without number is weird.
How about just "4 color bluff" ? Similar to "5 color ejection". We lost the critical word which might be important, but just like "5 color ejection", we don't name it "2-away 5 color ejection"

Having say that, I don't feel critical 4 bluff is confusing without color. Rank is normally reserved/look like a for 4 double bluff. So intuitively it can only be initiated with color.

**Comment by Ibot02** [comment]
> Having say that, I don't feel critical 4 bluff is confusing without color. Rank is normally reserved/look like a for 4 double bluff. So intuitively it can only be initiated with color.
Since double bluff are level 14 while single bluffs using critical 4s with color are level 12, this reasoning is not available to players just learning about intermediate bluffs - who'd also be the most likely to be confused about it requiring color in the first place.

**Comment by Zamiell** [comment]
in summary, it seems that right now the options are between:
1) calling it "Critical Color Bluff" as piano suggests
2) leaving it the way it is

i will rename the issue accordingly

**Comment by Zamiell** [comment]
Critical Color Bluff does seem like a better name, but on the other hand, there are inertia costs that we have to paid with a rename.

mango seems to be against, does anyone else care strongly either way?

**Comment by sjdrodge** [comment]
+1 for Critical Color Bluff

**Comment by mangopie1** [comment]
I did a review earlier this week, and the newbie thinks that "Critical 4 Bluff" can be done by rank. So I am not strongly against changing.

A small concern.
Someone may think that "Critical Color Bluff" can be done on 5s. As 5 is critical. (note that 5ce is lvl 15, introduced later than crit 4 bluff)

**Comment by Ibot02** [comment]
> Someone may think that "Critical Color Bluff" can be done on 5s. As 5 is critical.

The current description for the Critical 4 Bluff already specifies the other copy must be in the discard pile (as opposed to saying there is only one copy left), so 5s would be excluded the same way dark suits are by that language, though it could probably be explicitly mentioned that this excludes 5s in the level 12 text.

There might also be confusion about whether 2-away critical 3s in Up or Down are valid single bluff targets (since 3-Bluffs are turned off there), if it is changed to Critical Color Bluff.
