### ISSUE TITLE
Turn off Safety Charms in Easy Variants

### ISSUE THREAD

**Issue by pianoblook** [hanabi/hanabi.github.io#779]
Title. 

As long as efficiency isn't a big concern, Alice may simply want to leave the 5 available as a _Stall_ for someone to give and thus help extend early game. 

Since 5 stalls are off in HVR anyway, though, the utility of declining a Pull goes way down (and thus Safety Charms become much more appealing).

Granted there can obviously still be reasons to decline a Pull even in HVR, but they're more edge-casey. I'd still consider the context before deciding to _Charm_ in HVRs, but in general think they're still good in Early Game. (For example, perhaps Alice wants to leave the 5 available to be used as a 5cm, if Cathy's chop is a useful 3 or something).

**Comment by Zamiell** [comment]
can't say ive ever performed a safety charm for any reason, so I don't have much to contribute here

**Comment by mangopie1** [comment]
How about deleting safety charm completely? I only seen once in my hanabi career. But perhaps just the group I play with didn't spot that opportunity.
Given that we have 4 charm, and now it takes priority over 4db. There are more reason of not using safety charm. It is often nice to use 5 is 5 pull or 5 cm or 5 stall.

**Comment by Zamiell** [comment]
> How about deleting safety charm completely?

i think safety charm is indeed a candidate for deletion, if it is the case that high-level hyphenated players are not using it regularly, but i will defer to people who have been playing a lot of games recently (e.g. melwen)

**Comment by pianoblook** [comment]
I'd be fine with it dying personally. Don't think it's a net positive for any variant / situation that matters. If someone wants to delve into deleted conventions and use it for personal use in a tournament or something, that seems more reasonable anyway.

**Comment by mmelwen** [comment]
Is not a convention that is often used so I dont think that it matters too much, personally I prefer piano's 5tech that gives more information about the 5 pulled card and also allows you to get different slots

**Comment by Zamiell** [comment]
closing this in favor of #803
