### ISSUE TITLE
Deceptives-Fives & White (3/4/5 Suits) should save with number

### ISSUE THREAD

**Issue by Romain672** [hanabi/hanabi.github.io#782]
Title.
From the actual doc, there is no special section for it.

**Comment by Zamiell** [comment]
can you submit a pr

**Comment by Romain672** [comment]
How you want to do it?
I can
 - add an exception to the 'deceptive fives' page and assume saving with number is then obvious
 - add an exception to the 'deceptive fives' page, and add a section for number saves
 - add an exception to the 'deceptive fives' page, and add a new page for it
 - add a new page for it and assume it will have priority on the other page

**Comment by Zamiell** [comment]
isn't this kind of obvious? do players really need to be told to save deception 5's with number 3 and number 4?

**Comment by Romain672** [comment]
Okay, I will just add an exception to the deceptives fives page.
