### ISSUE TITLE
Chop Transfer should not chop move if the card was going to be bombed (in the pov of the clue's giver)

### ISSUE THREAD

**Issue by Romain672** [hanabi/hanabi.github.io#789]
Title.
https://hanabi.github.io/docs/extras/chop-moves#the-chop-transfer

**Comment by Zamiell** [comment]
we already decided against this, see <https://hanabi.github.io/docs/level-6#blind-playing-chop-moved-cards>

**Comment by Romain672** [comment]
ok ty, I added a link in pull requests.
