### ISSUE TITLE
Add levels while creating tables

### ISSUE THREAD

**Issue by HelanaAsh** [hanabi/hanabi.github.io#795]
I would usually like to be inclusive and play with people at all levels, I am a human after all and am sometimes in mood for advanced levels. Since I am also an **extremely nice** person, I usually hate to say "sorry we are playing level x", or "can you find another table?". So I create a passworded table and wait for my friends who play at similar levels to join, but after waiting for an hour I realize, I have no friends. So here is a dilemma for me, I want to play at x levels, but adding the name in the title dont always work because reading so many words is very hard. Can we create tables with levels as an option in the settings, so we set the expectations straight?

Thanks!

**Comment by Zamiell** [comment]
issues about the website belong in the [website repository](https://github.com/Zamiell/hanabi-live), not in the repository about the hyphen-ated group
