### ISSUE TITLE
Seperate advanced strategies into levels

### ISSUE THREAD

**Issue by Romain672** [hanabi/hanabi.github.io#796]
Hi, follow up of this post: https://github.com/hanabi/hanabi.github.io/issues/785

So it look like the solution we are going to is to add a level into '[xx]' for each advanced strategies. If we assume Dawn will take level 24, they will be levels 25/26/27/28/29...

There is 76 advanced conventions.

I did a document which regroup every convention and their complexity/rarity/if it's optionnal/if it's logical: https://docs.google.com/spreadsheets/d/1_vHH3kfHOsUA3Esj9hMrpn7V2jb8I_MSgxwASOk-bLU/edit#gid=0

**Comment by Romain672** [comment]
From that doc, we can see the most important convention with the criteria I decided:
 - [Saving Playable Cards when the Preceding Cards Are Not Promptable](https://hanabi.github.io/docs/extras/save-clues/#saving-playable-cards-when-the-preceding-cards-are-not-promptable)
 - [Chop transfer](https://hanabi.github.io/docs/extras/chop-moves/#the-chop-transfer)
 - [Elimination Rewrite](https://hanabi.github.io/docs/extras/miscellaneous/#the-elimination-rewrite-for-1s)
 - [2 Saves off first turn 3 players](https://hanabi.github.io/docs/extras/save-clues/#2-saves-off-chop-on-the-first-turn)
 - [4 Charm](https://hanabi.github.io/docs/extras/charms/#the-4-charm)
 - [Speed up](https://hanabi.github.io/docs/extras/fix-clues/#the-speed-up-clue)
 - [Assymetric chop move dilemma](https://hanabi.github.io/docs/extras/chop-moves/#the-asymmetric-chop-move-dilemma)

And here is what could take the second level:
 - [Double ocm](https://hanabi.github.io/docs/extras/chop-moves/#double-order-chop-move-for-3-player-games)
 - [Certain finesse clandestine exception](https://hanabi.github.io/docs/extras/special-finesses/#the-certain-finesse-clandestine-exception)
 - [Trash pull](https://hanabi.github.io/docs/extras/pushes-pulls/#the-trash-pull)
 - [Negative blind play](https://hanabi.github.io/docs/extras/miscellaneous/#the-negative-blind-play)
 - [Hesitation chop move](https://hanabi.github.io/docs/extras/chop-moves/#the-hesitation-chop-move-from-a-misplay)
 - [Self color bluff](https://hanabi.github.io/docs/extras/special-bluffs/#self-color-bluffs-1-for-1-form-scb)

**Comment by Romain672** [comment]
From it, it look like there is too much moves which are too rare, but not optional and logical like the 'negative blind play'.
It's pretty hard to rank it correctly D:

**Comment by Zamiell** [comment]
In case it hasn't been pointed out already, levels are currently scoped in order of complexity from 1 to 23.
This is why we chose the "Unnecessary Moves" to be level 23 specifically, because those are things that cause a huge amount of bombs, even in games with experienced players.
By adding a level 24 with arbitrary moves that are *lower* in complexity than *Unnecessary Moves*, it breaks the level to complexity relationship, which is a non-zero harm on the overall system.

**Comment by Romain672** [comment]
It's a problem of the actual document: you got something prett hard (level 23), and then what follow is things of any levels.

I was thinking of adding a section with 'logical moves', but that make the search function way harder to use.

I guess the only problem is level 23.
So:
 - stop the doc at level 22
 - put [23] to some logical moves which follow those 22 levels
 - put [24] to some logical moves which follow those 22 levels
 - put [25] to Unecessary moves (but in the advanced section)

**Comment by Zamiell** [comment]
i think if you are putting a prefix on moves like "[24]", it would make more sense to organize the document by putting them on a page called "level 24 conventions"

**Comment by Romain672** [comment]
Yeah true, in the advanced sections (if that still exist), you could still put some links into those if needed.

**Comment by Zamiell** [comment]
it sounds like what you want is to just rename the section called "Play Clues" into "Level 24 - Play Clues", rename the section called "Save Clues" into "Level 25 - Save Clues", and so on.

doing that this does not address the concern that i brought up in my original post in this thread

**Comment by Zamiell** [comment]
furthermore, if you arbitrarily selected a subset of individual conventions from each section (e.g. "Play Clues", "Save Clues", and so on) to comprise a theoretical level 24, that would equally not address the concern that i brought up in my original post in this thread

**Comment by Romain672** [comment]
> furthermore, if you instead arbitrarily selected a subset of individual conventions from each section (e.g. "Play Clues", "Save Clues", and so on) to comprise a theoretical level 24, that would equally not address the concern that i brought up in my original post in this thread

Yeah, it was exactly that. I solve a problem (level 23 hard than some others sections), by adding another one which seem to be better.

**Comment by Romain672** [comment]
So melwen and myself seem to agree on the fact to separate advanced strategies into two parts.
What are other's thoughs about it?

**Comment by Zamiell** [comment]
i'm against it, for the same reasons why we originally created the "extras" section in the first place and for the reasons i outlined above
