### ISSUE TITLE
Hat guess on Turn 1

### ISSUE THREAD

**Issue by Dr-Kakashi** [hanabi/hanabi.github.io#798]
So I was busy with the Dawn proposal and realized something. Why don't we just have Alice give a Hat guessing clue on Turn 1 of the game? The rest of the game will be played the hyphenated way. We can call this the hat guessing phase lol. This would cover all the wants of starting the game that dawn proposed. Tool belt to get any slot, tempo, etc.

**Comment by Zamiell** [comment]
we explicitly don't use hat guessing because it makes the game too easy

**Comment by iamwhoiamhahaha** [comment]
how many times kakashi proposed something and they got closed immediately 🤣🤣🤣
