### ISSUE TITLE
Saves Muddy Rainbow Cards with Green Clues

### ISSUE THREAD

**Issue by iamwhoiamhahaha** [hanabi/hanabi.github.io#799]
We used to save 5s with red clues in Muddy-Rainbow-Fives & Prism, but I think it's better to save with green or blue because it's pretty annoying to touch a trash prism 1 while saving with a red clue. Green seems more valuable than blue because 3s are usually better than 4s.

**Comment by iamwhoiamhahaha** [comment]
Same as Muddy Rainbow & Prism

**Comment by iamwhoiamhahaha** [comment]
Maybe we could just redefine the Save Clues in Muddy Rainbow to solve the problems at the same time. Now I propose that we save muddy rainbow cards with rightmost color. Or always green (the third color).

**Comment by iamwhoiamhahaha** [comment]
Oh darn I just realized we don't have green color clue in 3 suits; also, it is not the third color in 4 suits lol

**Comment by mangopie1** [comment]
Right most colour make more sense.

As if we are also playing dark variant, current convention state that we should use that colour instead, and it also happens to be the rightmost too.

**Comment by pianoblook** [comment]
makes sense to me. 

And I like Mango's point about reclue value. Since statistically the most common mud save will be on m2, the most common _Mud Tempo_ color will also therefore be green. therefore green reclue will have the least chance of wrong-focusing a new card

**Comment by Zamiell** [comment]
> Now I propose that we save muddy rainbow cards with rightmost color. 

no, because the rightmost color changes from variant to variant, and it is already hard enough to remember that a red color clue to chop is a save clue (this is the source of many mistakes)

> Or always green (the third color).

as you said above, this isn't an option because green isn't available in every variant

**Comment by EhDrone** [comment]
I agree keeping it simple with a static red is better than every variant needing to recall that a different color is save.

**Comment by mmelwen** [comment]
I propose to save it with something is already critical as a color eg. If y4 is discarded we can save with yellow. Before that we can use the right most. Is silly to have all colours to be a rainbow save. That means that after a rainbow card is discarded we can not give chop focus play clues

**Comment by Zamiell** [comment]
> I propose to save it with something is already critical as a color eg. If y4 is discarded we can save with yellow. Before that we can use the right most. Is silly to have all colours to be a rainbow save. That means that after a rainbow card is discarded we can not give chop focus play clues

that's subtly different than what jeff is advocating for, since his example applies only to e.g. m2/m5, but your suggestion applies to e.g. a critical m3.
please put your proposition in a new thread

**Comment by mmelwen** [comment]
We can save m2/M5 with a color already in discard pile

**Comment by Zamiell** [comment]
the point of muddy rainbow saves is that there is no color that is critical yet, and we must save m2/m5.
the point of this thread is to discuss what color that should be.
your proposition is outside of this and thus doesn't belong in this thread

**Comment by T-Hoodie** [comment]
If you combine muddy rainbow cards with e.g. pink or brown, we explicitely do not want this right most color to be used as a save clue for the muddys. 
Switching the color for the save clue in the middle of a game can also become confusing in my opinion. But if you're interested we can try this in a couple of games melwen.
I would stick with red as the general muddy save clue for now, but slightly adjusting save clues for specific variant combinations  is not uncommon. So doing it for games with muddy cards and prism cards is fine imo, just state so in the pre game lobby.

**Comment by Zamiell** [comment]
> So doing it for games with muddy cards and prism cards is fine imo, just state so in the pre game lobby.

well said time, i am putting my weight behind this as well

**Comment by hakha3** [comment]
agree with hoodie
