### ISSUE TITLE
Clarification: 4 Charms

### ISSUE THREAD

**Issue by Dr-Kakashi** [hanabi/hanabi.github.io#800]
As I understand it, 4 charms are specifically used on 3 away 4's.

However, in the advanced doc, you can use 2 away 4's if Cathy is holding a 1 away card on slot 1.

I'm sort of confused because doesn't this mean that it's implied that we can always do 2 away 4's even if Cathy doesn't have a 1 away card on slot 1?

Let's say Cathy has a 2 away card on slot 1. 2 away 4 is clued either in Bob's hand or Cathy's hand. Bob is now in a situation where he should blind play 2 cards from slot 1 and slot 2 Or he should blind play slot 4 as a single-blind play.

Since our whole convention set is based on playing the fewest blind plays possible. Doesn't this mean Bob should charm slot 4?

**Comment by Zamiell** [comment]
> However, in the advanced doc, you can use 2 away 4's if Cathy is holding a 1 away card on slot 1.

quote and link the specific passage that says this

**Comment by Dr-Kakashi** [comment]
https://hanabi.github.io/docs/extras/charms/#interaction-with-double-bluffs-where-cathy-has-a-one-away-from-playable-card

Double Bluffs do not have precedence in the situation where Bob sees that Cathy has a one-away-from-playable card on her Finesse Position. Here, it is technically possible that Bob will blind-play the exact card that makes Cathy's Finesse Position playable. But since this is so unlikely, we agree that players in this situation should revert to a 4 Charm interpretation.

**Comment by Zamiell** [comment]
the text you just pasted contains nothing about using two-away-from-playable 4's about the target of a 4 Charm

**Comment by Dr-Kakashi** [comment]
I see, so it must be a 3 away 4 because that's defined in the 4 charm section. Thanks for clarifying

**Comment by Zamiell** [comment]
> our whole convention set is based on playing the fewest blind plays possible

we agree that *4 Charms* violate this principle (*Occam's Razor*) because we want to preserve the ability to perform *Finesses*.
not every convention has to satisfy *Occam's Razor* (although it does make playing with our conventions more difficult)
