### ISSUE TITLE
Variant-Specific Conventions Should Take Precedence 

### ISSUE THREAD

**Issue by iamwhoiamhahaha** [hanabi/hanabi.github.io#802]
I don't see the point of this bullet:

> In general, non-variant-specific conventions take precedence over variant-specific conventions, unless explicitly mentioned otherwise.
https://hanabi.github.io/docs/variant-specific#precedence-of-variant-specific-conventions

Why non-variant-specific conventions take precedence over variant-specific conventions?

The issue https://github.com/hanabi/hanabi.github.io/issues/801 reminds me of the issue https://github.com/hanabi/hanabi.github.io/issues/684#issuecomment-874533445. I still don't understand why non-variant-specific conventions should take precedence.

If it's true, then we should never call variant-specific conventions "variant-specific". I'm fine with deleting all the current variant-specific conventions, because they never take precedence.

For example, the [*Tempo Clues*](https://hanabi.github.io/docs/level-6/#the-tempo-clue) (focusing left) should take precedence over [*Brown Tempo Clues*](https://hanabi.github.io/docs/variant-specific/brown/#brown-tempo-clues) (focusing right) because there's no such a clarification for brown (as *Brown Precedence*) like what we already have in pink with [*Pink Precedence*](https://hanabi.github.io/docs/variant-specific/pink/#pink-precedence).

**Comment by Zamiell** [comment]
i think the section is there for historical reasons since we wanted 4 charm to have precedence over bubblegum X

**Comment by Zamiell** [comment]
i'll delete the section then

/accept

**Comment by Zamiell** [comment]
lelouch writes:

> There is one minor corner case: when all 1s are not down, Alice clues 1 to Cathy and Bob blind plays slot 1. I think in this particular case, trash bluff should still take precedence over bubblegum finesse/bluff. 

@Lel0uch-H do you want to do a pr for this to add it somewhere

**Comment by Lel0uch-H** [comment]
Yes, I'll add it to the pink variant specific conventions page. Give me a week.
