### ISSUE TITLE
Convention Revival: Reinstate Bad Touch Bluff (for 1's)

### ISSUE THREAD

**Issue by pianoblook** [hanabi/hanabi.github.io#805]
I've been sitting several possible convention changes to propose, but had been planning to wait until after doing the 170-game analysis to get a better sense of what mistakes & shortcomings tend to be most prevalent in community games at the moment.
That said, this one just came up in conversation, so I'll just post it now!

-----

UDDs were recently expanded to include Rank clues, and all the _Bad Touch Finesse_ conventions (i.e. duplicate cards getting clued w/ rank) were immediately deleted. But I'd like to argue that _Bad Touch Finesse (for 1's)_ is a uniquely different case, and should be reinstated (or rather, they shouldn't have been deleted without a discussion first).

- The big difference is that a blind-play in response to a 1s clue is very uniquely different than one resulting from a 2/3/4 clue. Unlike other numbers, **ANY** blind-play occurring in response to a 1's clue is sufficient to recalibrate the team.
- To state the obvious, this is because 1s are all playable to begin with, and therefore any blind-play response is nonsensical unless something _weird_ is happening: trash must be involved. By contrast, take dupe 3s as an example: a slot 1 blind-play would be *insufficient* to communicate that dupes were involved and that one should be discarded
- We usually agree that _Discharges_ only occur when the bad touch component **would not be recognizable if the response was from slot 1**. Hence the "Unknown" condition. 
- This is precisely how _Trash Finesses/Bluffs_ function; we all agree that as long as a slot 1 blind-play would be sufficient to identify the clued card(s) as trash, Bob should treat this as a _Trash Finesse/Bluff_ rather than a _Discharge_.
- _Bad Touch Finesses (w/ 1's)_ have worked well historically, and were always quite powerful when they did so.

Speaking strategically, there are some big benefits as well:
1. This will usually result in more options for Alice; if she wanted a _Discharge_, she could probably just do a color clue instead, which would clearly be a _UDD_.
2. The classic: 1st position blind-plays are more common than 3rd position
3. Since the 1s will be presumed as both trash, this gives the clued player more power to _TOCM_.

**Comment by Zamiell** [comment]
> doing the 170-game analysis to get a better sense of what mistakes & shortcomings tend to be most prevalent in community games at the moment

that sounds very interesting

**Comment by Zamiell** [comment]
Let's first state the obvious:
Even when the *Bad Touch Finesse (For 1s)* was an "official" convention, it were super-rarely used and not very useful, because in general, it is much better to perform a normal old *Bluff* and get an actual 2-for-1 instead of a 1-for-1.

Thus, we need to carefully consider whether or not bringing it back is actually helpful in a meaningful way.

> We usually agree that Discharges only occur when the bad touch component would not be recognizable if the response was from slot 1. Hence the "Unknown" condition.

This is essentially arguing:
"When this kind of clue happens, players will intuitively play slot 1, based on the other convention of only playing slot 3 if slot 1 won't work."

One could equally argue:
"When this kind of clue happens, players will intuitively play slot 3, based on the other convention of UTD/UDD already working this way."

Which of these is more relevant? That's the question that I am most interested in, because it informs us on how to configure the conventions to produce less bombs.

**Comment by hakha3** [comment]
Afaik this convention is used only in first rounds. You are making now a point that 
> The classic: 1st position blind-plays are more common than 3rd position
While also (from what I know) suggest dawn to give more options to get cards from other than finesse slots ;)

> We usually agree that Discharges only occur when the bad touch component would not be recognizable if the response was from slot 1. Hence the "Unknown" condition.
I agree with Zamiel, that now with UDD around I think when people see duped card clued they dont think "hmm is playing slot 1 enough", but just straight think about UDD. And reinstating that convention sounds rather confusing to me

**Comment by iamwhoiamhahaha** [comment]
Might be tangential.
https://hanab.live/replay/695306#3
Blind-playing slot 1 is enough to tell me that I have green 1 on slot 3. Based on this idea, I think *Prophetic Discharge* should always be a *Prophetic Finesse* and it can be done with either a color clue or a rank clue.
(Notes that I blind-play slot 1 is kinda unrelated to the green clue. I just felt that I had to blind-play something when lel0uch deferred playing into the 5ce and performed this weird move.)

**Comment by pianoblook** [comment]
> Even when the Bad Touch Finesse (For 1s) was an "official" convention, it was super-rarely used and not very useful, because in general, it is much better to perform a normal old Bluff,

While I agree that bluffs are often a better choice, I'd push back against using that fact as an inherent weakness of this convention. Don't forget this clue is still a clean 2-for-1, with some sometimes-relevant benefits (better tempo on 1s + TOCM power). More powerful tools = more options to deal with specific boards.

It also didn't seem rare to me; though admittedly I would often do it in reverse (clue dupe 1s to Bob, he plays one, then Cathy blind-plays).

> One could equally argue:
"When this kind of clue happens, players will intuitively play slot 3, based on the other conventions of UTD/UDD already working this way."
"...Which of these two statements is more relevant / more correct?"

A few points.
1) Trash bluffs are introduced earlier than UTDs, for good reason. _Discharges_ are not an "intuitive" invention; they are built out of the logical process of **needing** to not respond with a normal blind-play. If we're teaching it otherwise then that's a failure of the teachers. 
2) As a good example, many lvl 15s (and above) will screw up 5CEs because they forget that it is *not* just a blanket rule of "color to 5 = Eject!"; whether or not it's _intuitive_ to Alice or Bob doesn't matter; we build these conventions to follow fairly solid reason and consistency, and we expect Alice & Bob to think critically about what response will actually make sense. By your reasoning about intuitive responses, we should just ban _True Color Finesses on one-away 5s_ and instead agree that Bob should always _Eject_. (also in case it wasn't clear, please lord let's not do that.)
3) I read back through the entry for _UTD_, and thought the summary seemed relevant here:
> For a Trash Bluff:
- The empathy on the clued card only contains possibilities that are **Playable, Delayed Playable, or trash.**
  -  Thus, **a normal blind-play is enough** to prove it is trash.
- For an Unknown Trash Discharge:
  - The empathy on the clued card contains one or more possibilities that are **useful and currently unplayable.**
  - Thus, **something extra is needed** to prove it is trash.
 
> Afaik this convention is used only in first rounds. 
Most commonly, yes, but not by definition.

> [[while suggesting...] dawn to give more options to get cards from other than finesse slots ;)
lol well funnily enough this tool becomes even *more* useful _at Dawn_, since the overall deprioritization of slot 1 makes more slot 1 blind-plays more valuable

**Comment by T-Hoodie** [comment]
Bluff or Discharge? I'll argue for a Charm instead :P
So if we clue mutliple 1s at some later point in the game, a blind play is required to resolve the situation: Finesse position to make all of them trash (Trash Bluff), Discharge position to make the focused card trash and the other cards good (UTD), and a Charm to make the focus good and the other cards trash (Junk Ones Charm).
Clueing dupes means that not both of them are trash, so playing finesse position seems unintuitive to me. As Zamiel already mentioned, there are also oftentimes better ways to get good efficieny with a playable 1 on finesse position.
Now I am wondering discharge or charm? If you have free choice, there is an obvious indication that you could have used color for a discharge, and the requested card is the charm position. And for simplicity reasons, i would just generalize this, and say its always a charm and not only if there was a free choice available.
How does this hold up if not just two, but three identical cards are being touched? Charm position works perfectly well again, whereas a discharge would promise the wrong thing here.
Maybe two interesting examples: Turn 1 of the game, Cathys hand is r1 r1 g1 y5  and Alice clues 1 to Cathy. Playing slot 4 makes it a play on g1 (focus rightmost)  and dupe on the other cards - great. What if Cathys hand were r1 g1 r1 y5 instead? Well then its a discharge: the focus is trash, the rest good.
So overall, using it as a charm seems like the best option to me.

**Comment by pianoblook** [comment]
[Junk Charm](https://hanabi.github.io/docs/extras/charms/#the-junk-charm-for-1s) is already a thing

**Comment by pianoblook** [comment]
oh I see.

lol, that is certainly a funny option then.

But personally I still disagree with the argument that slot 3 is "better" than slot 1.

If it's truly a strategic consideration of wanting more Discharges, may I suggest a certain open proposal? ;) (#589)

**Comment by pianoblook** [comment]
> Might be tangential.
> https://hanab.live/replay/695306#3
> Blind-playing slot 1 is enough to tell me that I have green 1 on slot 3. Based on this idea, I think _Prophetic Discharge_ should always be a _Prophetic Finesse_ and it can be done with either a color clue or a rank clue.

Yeah that makes sense; I suppose even with color a slot 1 is still enough to clear things up, as long as the clued player would have zero chance of accidentally just marking it as g23. If we wanted to combine the two I wouldn't be opposed, although on a personal level I like having them both from a strategic perspective (since often there would be free choice).

I guess the original ideas was that rank would be more trash-bluffy and color is more UTD-y, just as it would naturally be if the 1s were in the same hand (or so I thought before dupe 1s trash bluff was deleted, lolol).

**Comment by HelanaAsh** [comment]
Yes please, in favor of reviving this convention for all the reasons Piano mentioned.

**Comment by TheDaniMan** [comment]
This is really a starting hand convention, meaning that slot 3 is more likely to be playable than usual and there are fewer ways to get slot 3 than later in the game. So functionally I would prefer a discharge.
I don't have a strong preference for which convention is more consistent with the others, but I think the answer should be the same as in this case:
If all 1s (and no 2s) are down on the stacks and two identical 2s are clued by number, is that a bluff or a discharge?

**Comment by pianoblook** [comment]
Speaking of bad 2s, I'd be curious what people think about this situation:
<img width="1146" alt="Screen Shot 2022-01-18 at 3 08 54 PM" src="https://user-images.githubusercontent.com/32303453/150010909-66e0c70b-b62a-4655-901f-352b1ac5112f.png">

If Cathy clues 2s to Bob, what should happen?

Here's hoping this would still work as a _True Bad Touch Finesse_ rather than a UDD.

**Comment by Zamiell** [comment]
> Which of these two statements is more relevant / more correct?

from what I can gather, piano thinks #1 is more correct, and hakha thinks #2 is more correct.
does anyone else have any opinions on which is more correct?

**Comment by TheDaniMan** [comment]
I think it's a matter of convention, and if all bad touch bluffs are replaced by UDD then this calls for a discharge, which does have cases like this as a substantial downside.
I will note however that if g2 is known then this is just cluing the final 2 with no actual bad touch, and should just be treated as a play clue because something about the clue is suspicious (in this case, it's clearly not a save).

**Comment by Zamiell** [comment]
> If all 1s (and no 2s) are down on the stacks and two identical 2s are clued by number, is that a bluff or a discharge?

feels like discharge to me

**Comment by Zamiell** [comment]
for: piano + helana
against: hakha + dani
n/a: jeff, hoodie

so far it sounds like we don't have consensus.

personally, I think 2 identical 2s clued by number after all the 1s are down should be a discharge, so it stands to reason that the 1s clue should work in the same way.
furthermore, besides 5ND there is no first round discharges

**Comment by Zamiell** [comment]
again i am mostly (only?) concerned with reducing mistakes, so i am for whatever convention configuration you think results in that happening the most
