### ISSUE TITLE
Intermediate/Advanced Principle Suggestion: Expected Utility of Lines

### ISSUE THREAD

**Issue by pianoblook** [hanabi/hanabi.github.io#815]
I've been working on a doc with suggested convention changes when tackling _Winstreaks_ / truly trying to _Maximize_ win chance, and just finished this section. I realized, though, that this perhaps might be universal enough to add to the official convention guide as an advanced 'Principle'.

This version is now a second draft, but I'd be very happy to revise the text, e.g. coming up with a better example scenario. This should give you the idea I'm going for, at least.

----
**Expected Utility Principle**
- When deciding on what action to take, it's important to try and approximate each option's **[expected utility](https://en.wikipedia.org/wiki/Expected_utility_hypothesis)**, taking into account possible misinterpretations and their resulting outcomes. (Expected utility is a term commonly used in game theory, and "serves as a reference guide for decisions when the payoff is uncertain".) 
- For example, say Alice is in _DDA_ and considering two options: a one-off-chop _5 Stall_, or a 1-for-1 to Donald that falls under _Finesse Position Exception_. Although in many cases it may seem simple to give the _5 Stall_ without a second thought, this would be a mistake without first properly considering **all** possible direct outcomes - not just the 'correct' one. Alice should ask questions such as the following:
  - What’s the likelihood that Bob might react as a _BCME_? And if he does, what effect would it have on the game?
  - What’s the likelihood that Cathy mistakenly _5CMs_ (and what effect would it have on the game)?
  - Assuming no one makes one of those mistakes, how much better is the _5 Stall_ in theory than the 1-for-1 play clue?
  - How is the game going overall? How much would these mistakes impact the long-term chances for winning the game?
- In the above example, all of these factors should play an important part in calculating what Alice deems to be the best **practical** decision. Let’s expand on the above example with a potential scenario:
 > A) Alice noticed Bob definitely forgot about _DDA_ earlier this game, but is generally a very experienced player. Alice’s best guess is that there’s a ~30% chance he’ll not notice _DDA_. She is 99%+ confident, though, that he would never assume a BCME as long as he **does** realize it was a _DDA Stall._ Bob’s slot 2 card is trash, and the team is at 0 strikes.
> B) Cathy is known as an extremely strong player, so there's a very low chance she'd not notice the _DDA_. That said, Alice also knows that mistaking _5 Stalls_ for _5CMs_ is a common error in general. Taken together, she thinks there could still be a ~5-10% chance of this occurring (unless Bob does indeed _Eject_, of course, in which case Cathy will understand what happened.) If Cathy does _CM_, her next card is a noncritical 4.
> C) Alice sees that after the _5 Stall_, Cathy will have a nice 3 Bluff on Bob to get the playable card on Donald’s finesse.
- In the above example, after reflecting on all this information, Alice can now make a more informed decision. She chooses to perform the _5 Stall_, since (a) there is an obvious benefit to leaving the playable unclued, (b) even though there is a relatively high risk of Bob _Ejecting_, it would at least immediately resynchronize the team, and not cause any huge loss.
- As a parting exercise, what if Bob’s slot 2 is a 5, but his risk of bombing is only 5%? 2%?
  - Would your decision change if this was the 10th game of a _Gauntlet_? Why or why not? What other factors may be relevant?

**Comment by Zamiell** [comment]
at the risk of sounding reductive, this is just a more complicated / more formal / more verbose / game-theoretic / better explained *Clarity Principle* right?

**Comment by pianoblook** [comment]
hmm, it's kind of a cousin, maybe? It's interesting because it actually sometimes would go *against* clarity principle. 

Like in the example above, _Clarity Principle_ would say to just give the simpler clue. But if Alice does her due diligence and determines that it's a worthwhile risk, I'd (personally) support her going for it. I think a key difference is that she'd still be taking accountability for the added risk.

That said, this is definitely very formal & verbose at the moment, haha.
