### ISSUE TITLE
split up level 6 into a new level 7

### ISSUE THREAD

**Issue by Zamiell** [hanabi/hanabi.github.io#817]
re: 42

**Comment by DarthGandalf** [comment]
> re: 42

interesting description. What does that mean?

**Comment by Zamiell** [comment]
it means some idiot has an id of 42 instead of a normal name and this was his idea

**Comment by NumerateClutter** [comment]
Context: https://discord.com/channels/140016142600241152/456214043351580674/930549134711197737

**Comment by DarthGandalf** [comment]
Maybe you shouldn't call people idiots for choice of their nickname?

**Comment by Romain672** [comment]
I'm biaised since I'm from bga but:

I looked at the early section, and the 'tempo clue' part at level 6 look so much not logical with others sections around.
Next really 'illogicals' things are at level 12&15 imo.

So I would agree with putting the 'chop move' part as far as level 12.

**Comment by Zamiell** [comment]
> They may just like using the alias 42 as a Hitchhiker’s Guide allusion.

i'm aware of that, but my personal opinion is that you are an idiot if you intentionally choose an id that is so obviously unfunctional.
feel free to disagree with me, i'm not super interested in arguing about it

> So I would agree with putting the 'chop move' part as far as level 12.

that's a more drastic change that wasn't really being considered here

**Comment by jchernus** [comment]
As someone who was also stuck on Level 6 for a while (and happens to be a teacher), I too was quite surprised about the 'heaviness' of it, especially in comparison to the levels preceding/following it. I would like to add a +1 to the original intent of this ticket to split up Level Six, or perhaps move some things around.

**Comment by Zamiell** [comment]
I guess i'll do this myself at some point, so I'll leave this issue open

**Comment by vEnhance** [comment]
You know, at some point, should we just write a script that takes an integer n and then shifts all levels >= n up by 1

**Comment by Zamiell** [comment]
probably yes :)

**Comment by T-Hoodie** [comment]
My preferred solution would be:
Rename level 4 to Basic Chop Moves

Reorganize level 6 to include Gentleman Discards, Scream Discard Chop Move and Generation Discards. Rename to Unexpected Discards.

Move Positional Discard from level 7 to level 9.
Move Positional Misplays from level 7 to level 19 (not often used anyway imo)
Move No-Information Double Finesse from level 19 to level 20 (Ignition)

Reorganize level 7 to include Ones Order Chop Move, Trash Order Chop Move and Tempo Clue Chop Move, and rename to Advanced Chop Moves.

Level 9 now includes Baton Discards, Sarcastic Finesses, Certain Finesses and Postional Discards. Keep the name special discards.

This keeps most of the current structure intact, something i would prefer.

**Comment by vEnhance** [comment]
> Rename level 4 to Basic Chop Moves

It's already named that :) except it's out of date in the Learning Path. I'll send in a PR for that now.

>  Move Positional Misplays from level 7 to level 19 (not often used anyway imo)

Would support this even generally speaking.

> Reorganize level 7 ... to Advanced Chop Moves.

Right now the [current level 7 page](https://hanabi.github.io/docs/level-7) has a bunch of end-game theory (e.g. Distribution Clue), so you'd have to move that somewhere else as well.

**Comment by T-Hoodie** [comment]
> It's already named that :) except it's out of date in the Learning Path. I'll send in a PR for that now.

Thank you :)

>Right now the [current level 7 page](https://hanabi.github.io/docs/level-7) has a bunch of end-game theory (e.g. Distribution Clue), so you'd have to move that somewhere else as well.

You are correct, I didn't check it properly. I'll look into it more thoroughly, get some input from others, and then will come back with a better alternative.

**Comment by Zamiell** [comment]
@vEnhance do you wanna use your magic script for this now?

**Comment by T-Hoodie** [comment]
I do have some suggestions that might make this redundant, coming this week. Maybe wait for now.
