### ISSUE TITLE
Lower tempo clue stall in stall chart

### ISSUE THREAD

**Issue by TheDaniMan** [hanabi/hanabi.github.io#823]
Single tempo clues are usually really bad. The card usually plays eventually for contextual reasons. If I'm not mistaken, everyone I've asked agrees that locked hand saves are better than tempo clues. My main reasons are that having someone discard trash instead of playing a tempo'd card is rarely bad, and they might play anyways for contextual and possibly asymmetric reasons.
I propose something like this: good* tempo clues stay in precedence 1. LHS/8CS go up to precedence 3 (and are optional). bad* tempo clues go to precedence 4. Fill-in clues and hard burn go down to 5 and 6.
Functionally, the consequence of this change is that LHS/8CS become permitted when there is a tempo clue to give, but on the flipside you can no longer play your clued cards just because you see that the cluer had a tempo clue to give. Since LHS/8CS are optional anyway the renumbering doesn't mathematically do anything to fill-ins and hard burns.

*A good tempo clue is one which is either a 'valuable tempo clue' as listed in the conventions, or is a tccm that works, or one that has a reasonable chance of speeding up an unlock. A bad tempo clue is one which is not good.

**Comment by Zamiell** [comment]
i think the reason it is currently structured in the way that it currently is is to ensure synchronicity.
with this change, you introducing asymmetry.

For example, in a 4-player game:
- Alice is *Locked*.
- Alice has the option between:
  - Giving a *Tempo Clue* to Bob (to get a red 2 to play).
  - Giving a *Locked Hand Save* to Cathy (to save a blue 3).
  - Per Dani's modified stall chart, Alice knows that she is expected to perform the LHS clue instead of a *Tempo Clue*.
  - Knowing this, Alice intentionally performs a *Tempo Clue* on Bob.
  - Bob sees that Alice should have performed the LHS clue, so he knows that this ordinary *Tempo Clue* must be something deeper - a *Tempo Clue Chop Move*.
  - Bob marks his chop as being *Chop Moved* and plays his red 2.
  - Cathy has no idea that this has happened. From Cathy's perspective, the *Tempo Clue* on the red 2 was the only clue that Alice had available, so Cathy is not surprised in the slightest.
  - Cathy gives a clue and the team is now desynchronized. They go on to lose the game.

**Comment by TheDaniMan** [comment]
For this interaction in particular, since locked hand saves are optional, I don't think a tempo clue chop move can ever be inferred on the basis of an available locked hand save, and lowering the priority of tempo clues below something optional shouldn't have a bearing on this.
This is, however, already a quirk in the conventions as they currently are - a tempo clue might be taken as a tempo clue chop move due to the possibility of a 5-stall or a play clue in Cathy's hand.

Perhaps this should be a separate issue, but one way of fixing this is that tempo clue chop moves should be made illegal from a locked or 8 clue player, unless at least two other players have a clueable playable card (perhaps an identical card) or clueable 5 stall. Then if a single tempo clue is given, all players will either see no playable card / 5 stall and assume a 'bad' tempo clue, or see at least one playable / 5 and assume they must have something and so it is a synchronous chop move. This is most consistent with what is best practice anyway.

Or we could just outlaw tempo clue chop moves from locked / 8 clue players because they're somewhat confusing.

**Comment by Zamiell** [comment]
> For this interaction in particular, since locked hand saves are optional, I don't think a tempo clue chop move can ever be inferred on the basis of an available locked hand save, and lowering the priority of tempo clues below something optional shouldn't have a bearing on this.

ok, then i was mistaken

> Perhaps this should be a separate issue, but one way of fixing this is that tempo clue chop moves should be made illegal from a locked or 8 clue player, unless at least two other players have a clueable playable card (perhaps an identical card) or clueable 5 stall.

maybe just simplify it to never TCCM regardless of anything

**Comment by Zamiell** [comment]
![image](https://user-images.githubusercontent.com/5511220/151603948-4443c33f-706b-4e31-a719-0c94812dc1ac.png)

so i think in this screenshot you want to change `3` to `4 (tied)`

that doesn't work because then people are unable to distinguish between fill-in clues and tempo clues, since they would become tied

(and we can't put LHS above fill-in clues because that isn't sync)

**Comment by Zamiell** [comment]
> 1. LHS/8CS go up to precedence 3 (and are optional)

that doesn't make sense, they can't be both optional and level 3

**Comment by Zamiell** [comment]
> *A good tempo clue is one which is either a 'valuable tempo clue' as listed in the conventions, or is a tccm that works, or one that has a reasonable chance of speeding up an unlock. A bad tempo clue is one which is not good.

i don't want to introduce more definitions for the stalling table, that increases complexity and creates more vectors for mistakes

**Comment by TheDaniMan** [comment]
I think I see what the issue is; I had the wrong idea of how LHS/8CS work. I was under the impression that they are optional in the sense that a locked player can choose to perform hard burn over LHS/8CS (if there are no fill-in clues available), and I agree that the situation becomes too confusing just with the change that I proposed. So let me repropose the following:
1) LHS/8CS become optional (i.e. if the locked player wishes, he can just skip them and do lower numbered things on the chart instead).
2) LHS/8CS-> 3 (tied), single tempo clue -> 4, fill-in clue -> 5, hard burn -> 6.

**Comment by Zamiell** [comment]
> LHS/8CS become optional (i.e. if the locked player wishes, he can just skip them and do lower numbered things on the chart instead).

there's only one lowered-number thing on the chart, which is *Hard Burn*, right?

**Comment by Zamiell** [comment]
when you say the words "single tempo clue", do you really mean a "non-important tempo clue"?

**Comment by TheDaniMan** [comment]
Yes, one that shouldn't logically have priority #1.

**Comment by Zamiell** [comment]
the problem is that non-important tempo clues are async, right?

**Comment by TheDaniMan** [comment]
You are right, and I see this blocks resolution of this issue. Perhaps tempo clues in stalling situations deserve some consideration of their own first, I'll see if I have some reasonable ideas.
By the way, regarding optionality of LHS/8CS, there can often be a good reason to not want to do these; consider a 4 player game. no green cards and no red cards are played on the stacks or discarded, other suits are finished. Alice is locked. Bob's hand is unclued g3, unclued r4, and fully known r5g5. Cathy's hand is r4 followed by trash, and Donald's hand is all trash.
Here, Alice can basically either LHS r4 on Bob or hard burn, but it should always be preferable to hard burn, and unfortunately the reasons for that can be asynchronous.

**Comment by Zamiell** [comment]
the way we play in practice is that you can decline to LHS/8CS to hard burn if you want, but only if there are no fill in clues available.
it's hard to represent that on the chart, so i haven't bothered

**Comment by TheDaniMan** [comment]
I see, so then really it's just asynchronicity of tempo clues. I'm gonna close this, and perhaps I'll open an issue about tempo clues, in which case I might bring up the idea there.
