### ISSUE TITLE
Delete The Trash Push Inverted Finesse

### ISSUE THREAD

**Issue by TheDaniMan** [hanabi/hanabi.github.io#824]
I don't think I've ever seen it used.

On the other hand, it sometimes hinders the ability of unnecessary trash pushes to get the card on the next player. In this case, the next player usually just says "he could've clued the inverted finessed card directly, so I'm supposed to play", and then the inverted finesse doesn't play anyway. So truly the most this convention is is useless overhead.

**Comment by Eliclax** [comment]
I've seen this used.  In any case, personally it seems logical that Bob in fact should *not* play from such a clue, because it's supposed to be on the last (i.e. Donald).

**Comment by Zamiell** [comment]
im fine with deleting it

**Comment by TheDaniMan** [comment]
Actually, I had one game today where it was very close to being useful, in that the inverted finesse would have been layered. But I personally don't think it's worth the conventional overhead.
