### ISSUE TITLE
Expanding the scope of Pestilent double bluff to the following case

### ISSUE THREAD

**Issue by Lel0uch-H** [hanabi/hanabi.github.io#834]
I think this is not a convention change, just a clarification in the doc towards how I've seen PDBs already working.

Relevant quotes from discord:

max, variant : rainbow 4p
Alice touches Donald's single card with green
Bob blind plays his finesse position. it is m1
Cathy blind plays his finesse position. it is b1
What is correct note of Donald? (Assume that we don't need to consider other cards)
I guess m3,m4,g2 but not sure g4 is possible?

g3 is also possible FWIW

Another example:

Only r1 is played on stacks. 

Alice clues b3 with rank 3 on Donald. Bob blind plays r2. What does Cathy do?

**Comment by pianoblook** [comment]
Looks like just an oversight in the PDB section. There's no reason why the following line has to exist:

> However, unlike a normal Double Bluff, a Pestilent Double Bluff is initiated by cluing a one-away-from-playable card (instead of a two-or-more-away-from-playable card).

**Comment by Zamiell** [comment]
can you submit a pr

**Comment by Lel0uch-H** [comment]
TheDaniMan's issue pertaining to double bluffs is supposed to subsume this. So I'm not submitting a PR before I see the reception of his.

**Comment by Zamiell** [comment]
k

**Comment by Zamiell** [comment]
@Lel0uch-H the pr is accepted now
