### ISSUE TITLE
Rename and rearrange Level 2

### ISSUE THREAD

**Issue by DrAnax** [hanabi/hanabi.github.io#841]
Level 2 is entitled as "Basic Finesses". The subtitle reads "Special Moves" and the text starts with the "5 Stall"

Proposal:

- Rename Level 2 to "Basic Moves"
- Rename the subtitle to "Finesses and Stalls"
- Move "5 Stall" after the last finesse (The Self Finesse)

**Comment by Zamiell** [comment]
sure, but name it Stalls and Finesses

**Comment by DrAnax** [comment]
Should I rearrange the subsections?

**Comment by Zamiell** [comment]
no, I think stalls should come first before finesses
