### ISSUE TITLE
"The Reverse Shadow Finesse" does not word clearly what is actually "reversed", nor how to resolve ambiguity.

### ISSUE THREAD

**Issue by PabloJ-1** [hanabi/hanabi.github.io#843]
On the [Reverse Shadow Finesse](https://hanabi.github.io/docs/extras/special-finesses/#the-reverse-shadow-finesse), could you please make a bullet point about what is supposed to be "reversed" ? In normal finesses, a reverse finesse has the clued card before the blind play. It seems like that is not what we mean by reverse in a shadow finesse.
I guess it is that the shadow and the clued card are reversed. Making it explicit would be nice.

Is it related to which player needs to play the shadow in case it is ambiguous ? 
It seems like if all players before the shadow target have a shadow, it would be the last person before the shadow target that is required to blind play. If that is the intended way, please state it.

**Comment by pianoblook** [comment]
My understanding is that 'Reverse' refers more generally to any time that a blind-play occurs 'behind' the player being clued. So if Bob is being clued, but a blind-play that's related to that clue is only going to occur after Bob's turn, then it's a _Reverse_ form of that action.

+ Ambiguous shadows are illegal, afaik

**Comment by ZakisanGithub** [comment]
I agree with Pianoblook's explanation and just want to add that in my interpretation, the notion of 'reverse' highlights additional interpretation burden on the clue receiver. Namely, to realize that the move might be happening without previously being 'alerted' of it by a blind play.

**Comment by Zamiell** [comment]
if you dont think the doc is clear enough can you submit a pr
