### ISSUE TITLE
give a name to the rule where you dont have to clue the person behind you in the early game

### ISSUE THREAD

**Issue by Zamiell** [hanabi/hanabi.github.io#849]

**Comment by NumerateClutter** [comment]
This isn’t strictly true, is it? I think there’s an exception from the guide principle

A: x x x x x
B: r1 r2 x x r5
C: x r3 x x b5

Alice clues red to Cathy; Bob blind plays r1. Alice sees r5 on Bob’s chop, so she expects Cathy to clue 5 to Bob before discarding.

**Comment by Zamiell** [comment]
please ask convention questions in #convention-questions

**Comment by mangopie1** [comment]
Permission to discard exception (PDE)

**Comment by Zamiell** [comment]
> Permission to discard exception (PDE)

could shorten it to Permission Exception, or Permission Discard

**Comment by mmelwen** [comment]
PTD permission to discard, is also useful when you focus invert from context

**Comment by Zamiell** [comment]
PTD it is

**Comment by Zamiell** [comment]
i also made a new section for FPE
