### ISSUE TITLE
[End-game] Not playing a non-5

### ISSUE THREAD

**Issue by Romain672** [hanabi/hanabi.github.io#851]
Hi, feel free to do edits here: https://docs.google.com/document/d/1KSs3s1La4V4Go-_t-Y07gs40KJOoVXoXMrtXeXmXcd0/edit

 ### Generating Final non-5 non-play 

  * First read Final card non-play. ( #850 )
  * When a player is holding a playable card (and in most cases if it's his single playable) which can be played during the last turn, and if not playing the card would make the team be able to stall enough turns to increase the max score, he is allowed to **discard** or to do a  **Generating Final non-5 non-play** stall clue with Rank.
  * Remember that playing a 5 is never worst than discarding (outside of variants which don’t give a clue back with a play of a 5)
  * For example, in a 3-player game:
      
    * There is exactly 2 cards on the deck left, 0 clue are available, and Red 5, yellow 5, green 4, blue 4 and purple 3 are played on stacks.
    * Alice is holding the purple 4
    * Bob is holding the purple 5.
    * Cathy is holding the green 5 and the blue 5.
    * Alice should normally plays her purple 4 since it's playable. But here, playing it would force Bob to start last turn.
    * Furthermore, not playing her non5 card would let players be able to stall one more turn, and here that would make Cathy be able to start the last turn which is great since she got two plays
    * Alice discards
    * Bob clue 5 to Cathy as a stall clue thanks to the clue generated by Alice
    * Cathy plays green 5
    * Alice plays purple 4
    * Bob plays purple 5
    * Cathy plays blue 5

**Comment by Romain672** [comment]
#850

**Comment by TheDaniMan** [comment]
I think both this and #850 are best handled by adding a section in the doc called "challenge problems", along the lines of the examples in the beginner doc but intended for players who have already gone through all or most of the conventions. I really like this example in particular, and I was myself thinking of making a few problems about which notes to put on cards for double bluffs and perhaps a few other things when I get the chance.
