### ISSUE TITLE
UTD when 2 slots available + next player know the next playable card?

### ISSUE THREAD

**Issue by Romain672** [hanabi/hanabi.github.io#866]
https://hanab.live/replay/713250#7 (Romain give red to Helana)
https://hanab.live/replay/713250#40

When a red clue in a trash focused card is done, and when the next red card to play is globally known, and when the next player only got 1 or 2 slots available, playing slot 1 tell to the players that card is trash.

In first example, aitch could assume r3+r4+r5+r2, but he doesn't have enough slot.
In second example, Romain could assume y4+y3+y5, but he got negative yellow in his second finesse position.

I was wondering for when it's not obvious what to do, if we could add a 2+ blind play rule to assume a trash bluff over the missing cards.

This look like a pretty commun clue in Odds & Evens.

**Comment by Romain672** [comment]
Note the default interpretation should be discharge for simplicity I believe.
But on this case, when discharge isn't available, trash bluff look the one.

**Comment by Zamiell** [comment]
in the generic case, this is already defined as OOP discharge
we can't have one player play 2 cards because that would break lie principle
