### ISSUE TITLE
True End Game

### ISSUE THREAD

**Issue by Dr-Kakashi** [hanabi/hanabi.github.io#869]
I think it's time for us to define the true end game. 

We have it defined in the doc that when pace turns yellow, end game has started.

However, the true end game starts when one of the following conditions has occurred:
1. All cards that need to be gotten are touched.
2. All cards that need to be gotten are visible.
3. The only cards that need to be gotten are playable. 

This means that the end game will start differently for each player. It's up to the players to be aware when end game starts. This is an important concept because positional plays are very useful during end game. When a positional play is performed, it immediately tells the team that we are now in the end game and all the players on the team will be able to clarify which cards they are holding, touched and/or chop moved.

**Comment by Zamiell** [comment]
positional plays prior to the end-game are indistinguishable from a mistake

**Comment by Romain672** [comment]
Kakashi the problem with it is that if you try to get an unknown r5, from the person holding r5, she will not known that all cards that need to be gotten are visible.


Here is what I would suggest:
2. All cards that need to be gotten are visible, except for one suit.

That mean in a 5 suits game, if r2, y4, g3, b4, p5 are played, the true end game start if the first person who should blind play from the move you try to do sees per example y5, g4, g5, b5.

That would help to start to define #848 too.

**Comment by Romain672** [comment]
Played: all but r5 & b5. 0 clue left. 2 cards in deck.
Bob's hand: x-r5-b5-x

From my new definition, it's not end game yet from Bob's pov, which is bad.
Of course, Alice discarding slot 2 is obviously good here. But that show a weakness to it.

**Comment by Romain672** [comment]
Problem is that the positionnal discard/missplay should be done when you either lack of clue, or someone got two many blinds plays.
The first one is globally known, so it's easy to interpret.

The second is usually unknown to that person.
So my question is, with those three hands and r5 playable:
1) Bob: x-r5-x-x
2) Bob: x-r5-b5-x
3) Bob: x-r5-b5-g5
How can you make Bob play anyway and not assume a mistake?

**Comment by Dr-Kakashi** [comment]
> positional plays prior to the end-game are indistinguishable from a mistake

Mistakes do happen, but it would only apply to a situation where the player misplays a card. In that case, it's up to the players to figure out what went wrong. This applies to all of our conventions, not just this specific scenario. It would be wrong to say a mistake from an unrelated situation to affect a different convention. 

There are positional plays where you discard the slot called for. When that is done it is globally known as not a mistake. 

> Kakashi the problem with it is that if you try to get an unknown r5, from the person holding r5, she will not known that all cards that need to be gotten are visible.

That's the point of positional plays. They not only tell the location of the next playable card, but all the players at the table immediately write elimination notes for the missing cards, as the end game has now started. 

> 2. All cards that need to be gotten are visible, except for one suit.

This would conflict with your stall proposal as now players are unaware of being in a stalling situation or a true end game situation. My definition of true end game here is that everything is visible. 

> How can you make Bob play anyway and not assume a mistake?

I'm not sure what you are stating in this post. If Alice positional discards for playable R5, then Bob needs to respect that and blind play the slot called for. This is extremely valuable in your situation because with 2 cards left in the deck, now Bob knows that the last card in the deck is not B5. However, that's irrelevant since Alice has now generated a clue for the team to clue B5 directly.
