### ISSUE TITLE
Rename Ambiguous Prism tempo clue and expand its scope

### ISSUE THREAD

**Issue by Lel0uch-H** [hanabi/hanabi.github.io#877]
Let's rename it to something not specific to prism. Some suggestions (feel free to suggest more):
 - Ambiguous Tempo clue
 - Special Color Tempo clue

Let's expand its scope to any and all such variants where 2 cards can be undistinguishable using both rank and color clues including but not limited to:
 - Prism
 - Ambiguous
 - Very Ambiguous
 - Deceptive-Ones
 - Deceptive-Fives
 - Odds & Evens
 - Dual-Color (in some cases?)

**Comment by Zamiell** [comment]
seems fine

**Comment by TheDaniMan** [comment]
I would prefer that this is reserved for indistinguishable cards, so not dual-color.

**Comment by Zamiell** [comment]
> I would prefer that this is reserved for indistinguishable cards, so not dual-color.

same

**Comment by Zamiell** [comment]
submit a pr

**Comment by Zamiell** [comment]
looks like lelouch doesn't want to submit a PR for this, does anyone else?

**Comment by Zamiell** [comment]
dani said he would take care of it, so i will assign it to him

**Comment by argothiel** [comment]
If Bob has one-away from playable in his layer, Cathy should play her finesse, right?

**Comment by TheDaniMan** [comment]
Assuming you're talking about the null kick conventions I put in the same PR, the standard patch finesse rules should apply; given that known patch finesses are considered illegal, Cathy should still eject.
For this convention in particular, Cathy should eject for another reason: if her front card was playable, then Bob would take the clue as a double ignition.

**Comment by Zamiell** [comment]
done, thanks dani
