### ISSUE TITLE
Conventions for Clue Starved

### ISSUE THREAD

**Issue by mmelwen** [hanabi/hanabi.github.io#880]
I believe that 

- occupied 1 for 1 off chop, is the card is not leading to someone else's hand should cm 
- occupied tempo clues, even if they are out of order should cm as well

None of us give this kind of clues if the chop is not important at least in 1.56

**Comment by Lel0uch-H** [comment]
Just play sieve for clue starved.

**Comment by iamwhoiamhahaha** [comment]
here's the example i did yesterday: https://hanab.live/replay/723723#17

**Comment by TheDaniMan** [comment]
Perhaps it is worth defining "very hard variants" and defining some type of clue that should additionally signify a chop move. I think the following variants should qualify:
-any variant with two dark suits
-any variant with both a dark suit and a null suit, or any variant with the dark null suit, or null-fives & any dark suit, or up or down & null
-any clue starved variant
-5 suit variants with a dark suit when played with five players.

**Comment by Zamiell** [comment]
i'm not opposed to creating a "Very Hard" conventions section to the doc.
i think it should have a more simple definition though, e.g. "any variant equal to or greater than 1.55 require efficiency"

**Comment by Zamiell** [comment]
submit a pr for a "Very Hard" conventions section

**Comment by Zamiell** [comment]
closing since noone submitted a pr
