### ISSUE TITLE
Change interaction of 5 rank clues with chop moves

### ISSUE THREAD

**Issue by TheDaniMan** [hanabi/hanabi.github.io#881]
I propose that _outside of low score phrase_, a 5 clue one-off-chop is never a chop move ignition nor a chop move ejection, and is instead interpreted either as a weird chop move that does not get a response from Bob, or a finesse/bluff/double bluff with rank, respectively.

Suppose that Cathy has a 5 one-off-chop and a trash card on chop. As the conventions are currently written, a 5 clue to a 5 that is one-off-chop is always chop move stuff (if it is not a loaded play clue), which renders a finesse or bluff with a rank clue very difficult. Also, if any other card in Cathy's hand is trash of the same color as the 5, a color clue to the 5 will not be possible, and the 5 will necessarily be clued as a save. In these situations this change would often end up saving clue. The change also enables double bluffs with a 5 rank clue, but I'll admit that this is less significant.

Since chop move ejection with 5 is rarely useful outside of low score phase, I think the main downside is the loss of chop move ignition. I haven't done the analysis on which of the scenario above and chop move ignition happen more often, but I suspect it is the former.

I will also add that if the game is not going extremely well and the clue count is low, which is the case where this matters the most, the benefit of not having to spend a clue on a save is increased, whereas chop move ignition might just be turned off anyways due to being viewed as necessary in order to save all the cards.

**Comment by Zamiell** [comment]
sounds like the TLDR is:
- turn efficiency dial up
- turn flexibility dial down

we don't need any more efficiency in order to win games.
are you proposing this as a hard variant only convention, or something?
