### ISSUE TITLE
Precedence between self 4-charm vs finesse vs 4DB is unclear in some cases

### ISSUE THREAD

**Issue by Lel0uch-H** [hanabi/hanabi.github.io#884]
In a 3-player game on the first turn, Alice clues a single 4 with rank 4 on Bob's slot 1.

- Case 1: Cathy has a playable 1 on finesse
- Case 2: Cathy has a (non-brown/muddy) 2 or on finesse
- Case 3: Cathy has a (non-brown/muddy) 3 or on finesse
- Case 4: Cathy has a muddy/brown 2 on finesse
- Case 5: Cathy has a 4 or 5 on finesse

Here are the possible interpretations:

- Case 1: finesse
- Case 2: 4DB OR self 4-charm OR finesse
- Case 3: self 4-charm OR finesse
- Case 4: 4DB OR self 4-charm
- Case 5: self 4-charm OR finesse

**Comment by iamwhoiamhahaha** [comment]
imo
Case 1: finesse OR **delayed 4 double bluff** (if Bob plays a 1 after Cathy blind-plays) 😎
Case 2: 4 double bluff
Case 3: self 4 charm
Case 4: 4 double bluff
Case 5: self 4 charm

**Comment by mmelwen** [comment]
i had the impression that 4db is not with 1 away, so imo

- Case 1: finesse
- Case 2: self 4-charm
- Case 3: self 4-charm
- Case 4: self 4-charm
- Case 5: self 4-charm

**Comment by mangopie1** [comment]
I would explicitly say self-4 charm is illegal and go for the finesse or 4db interpretation. 

Due to the fact self 4 charm is calling for slot 5, which is focusable for 3 players.

**Comment by timotree3** [comment]
Agreed with mangopie. I find the idea of Self-Charm/Eject/Discharge very strange, because the point of those Ejections/Discharges/Charms is to prove something to the clue receiver. In the case of a Self- move, it's not proving anything that the clue receiver didn't already know

**Comment by EhDrone** [comment]
I am inclined to agree w/ mango and timo - the odds that Alice is choosing this complicated line when the odds that Alice cannot clue Bob's slot 5 directly is incredible rare, and to me seems more likely to be a finesse or 4db if Cathy plays.

Just because a self 4-charm would be a cool thing to do conceptually, it doesn't seem practically relevant outside of rare edge cases where I think a normal 4db or finesse is equally if not more likely to be occurring.

**Comment by Zamiell** [comment]
@Lel0uch-H you didn't specify whether or not the cards match, which makes a big difference

**Comment by Zamiell** [comment]
what exactly needs to be PRed?

**Comment by Zamiell** [comment]
also you never responded to my last comment
