### ISSUE TITLE
Occupied 5-Pull over 5-cm

### ISSUE THREAD

**Issue by Romain672** [hanabi/hanabi.github.io#886]
This proposition came from this discussion: https://discord.com/channels/140016142600241152/943350066868015117
The idea is that any card pulled from an occupied 5-pull got normal meaning, as if it was the focus of the clue. It happen only if not on Bob, and if the previous player to the 5 could have done the same clue.

Alice: (g1)-x-x-x
Bob: x-x-x-x
Cathy: x-x-5-y1
Alice clue 5 to Cathy as an occupied 5-Pull

Alice: (g1)-x-x-x
Bob: y1-x-x-x
Cathy: x-x-5-y2
Alice clue 5 to Cathy as an occupied finesse 5-Pull

Counter-example:
Alice: (g1)-x-x-x
Bob: x-x-(2)-(2)
Cathy: x-x-5-y2
Alice clue 5 to Cathy, but here it's just a 5-cm, since Alice should save y2.

.

Here is from discord:"
Alice: (g1)-x-x-x
Bob: r1-x-x-x
Cathy: w-x-x-x
Donald: x-x-5-z
Then:
1) z=r2: Bob plays r1. Cathy don't answer. Donald plays r2
2) z=r1: Bob don't answer. Cathy don't interfere. Donald plays r1
3) z=y1: Bob don't answer. Cathy don't interfere. Donald plays y1
4) z=y2, w=y1: Bob plays r1 to tell Donald it's playable. Cathy plays y1. Donald plays y2: https://hanab.live/replay/580771#30
5) z=y2, w=b1: Bob plays, expecting y1. Cathy plays, expecting y1. Donald bomb y2."

**Comment by Lel0uch-H** [comment]
Not in favor. There can be good reasons for an occupied Alice to 5cm a card on Cathy, eg. being phantom playable through Bob's hand.

**Comment by Romain672** [comment]
> Not in favor. There can be good reasons for an occupied Alice to 5cm a card on Cathy, eg. being phantom playable through Bob's hand.

Doesn't the same logic apply for occupied play clue?

**Comment by mangopie1** [comment]
Occupied 5 pull (First example) clash with the CM ignition. It is calling for Bob to blind play.

Occupied 5 pull finesse seems interesting. For 2s, indeed Bob could have save the same cards. For 5cm a 3s, it might have the issue that Lel mentioned. Need to think more about that.

**Comment by iamwhoiamhahaha** [comment]
@Romain672 you forgot to mention *Occupied 5 Pull* can only be done in hard variants

**Comment by pianoblook** [comment]
> Doesn't the same logic apply for occupied play clue?

Yeah, and OPC's are terrible too (outside of *maaybe* brown)

**Comment by Romain672** [comment]
> @Romain672 you forgot to mention _Occupied 5 Pull_ can only be done in hard variants. And Alice can never perform such a move on Bob for it just looks like a 5cm.

I mean since I don't see the difference with OPC atm, I just did my own proposition.
And yeah it's what I wroted.

**Comment by Romain672** [comment]
> Occupied 5 pull (First example) clash with the CM ignition. It is calling for Bob to blind play.

Uh right, is it bad though?
That clue is a 2 for 1 instead of letting Bob charm it.

**Comment by Lel0uch-H** [comment]
OPC is one of the most error-prone conventions already. I would not like any more extensions of the idea.

**Comment by Lel0uch-H** [comment]
https://hanab.live/replay/729734#11

frosty cm's y4 because it is good to put n2 on finesse. Sturm does not have any good bluff targets.
