### ISSUE TITLE
Scream discard at 2 or more clues

### ISSUE THREAD

**Issue by Lel0uch-H** [hanabi/hanabi.github.io#889]
The doc explicitly states that a scream discard is performed when the team is at 1 or less clues, while it might not always be true in practice.

Example: 

- https://hanab.live/replay/507083#9
  - t8: Lel0uch discards r4
  - t9: BraydonM has a play and sees r4 followed by k3 on chop
  - The only way to save melwen's hand is to scream
- https://hanab.live/replay/728797#10
  - t10: Lel0uch sees m2 on indego's chop follow by a playable p3 and a critical 5.
  - The only way to save indego's hand is to scream

**Comment by Zamiell** [comment]
> The only way to save indego's hand is to scream

questionable decision, because you could be discarding a 5 and losing the game, and there are 2 copies of muddy rainbow 2

**Comment by Zamiell** [comment]
> The only way to save melwen's hand is to scream

this is an edge case that is obvious to everyone at the table, the doc probably does not need to document this

**Comment by Lel0uch-H** [comment]
https://hanab.live/replay/728797#6

t6: indego gives me a clandestine finesse with nothing else to do on the board from her perspective. Hence I cannot have a 5 on chop.

**Comment by Zamiell** [comment]
```
- In extremely rare situations, *Scream Discards* can also be performed if the team is at more than 2 clues and it is the only way to win the game. However, these situations are usually obvious when they are happening.
```
i think it is negative EV to add this to the doc.
it doesn't really help anybody
