### ISSUE TITLE
Chinese Localization problem

### ISSUE THREAD

**Issue by jk15162428** [hanabi/hanabi.github.io#904]
Nicely done with the very detailed attention, since there are so many Hanabi players who stick around but don't know how to effectively play together, I'd like to translate some of the basic parts into Chinese (the original planning is from the beginning to Level 5/6 around, if I have time to do more, I will stick to it). If you are interested in that, welcome to contact back!

**Comment by Zamiell** [comment]
see https://github.com/hanabi/hanabi.github.io/issues/674

**Comment by jk15162428** [comment]
Oh yes, thanks for replying, so I'm allowed to make a website of mine to set the Chinese version of it, as long as I point back to this original one right? Thx!

**Comment by Zamiell** [comment]
yes
