### ISSUE TITLE
Level 11 Duplication Responsibility part example correctness

### ISSUE THREAD

**Issue by jk15162428** [hanabi/hanabi.github.io#910]
https://hanabi.github.io/docs/level-11#duplication-responsibility
In this part, example 4, it says "Bob has 2 unknown blue cards. No blue cards have been played yet, so from Bob's perspective, each blue card has a 1/5 chance of being the blue 2." I think the probability 1/5 is wrong. A suit and a rank contains 10 cards in total, we remove one b2, we still have 9 cards for each. So the probability of each blue card in Bob hands has 1/9 chance of being b2, in total 2/9 for Bob to have b2. Cathy also has 2/9 probability to have b2.

Example 5, each blue card in Bob's hand should have 1/9 probability to be b2, in total 2/9. For Cathy, 1/4 is correct.

**Comment by Zamiell** [comment]
can you submit a pr

**Comment by jk15162428** [comment]
Yeah. Making this an issue just wants to check the accuracy. I will submit a pr later. I'm playing now.
