### ISSUE TITLE
Using the browser back button sometimes leads to a wrong link

### ISSUE THREAD

**Issue by nickm2402** [hanabi/hanabi.github.io#917]
Hey,

I ran into a 404 in the docs. 

This is somewhat specific. Here is how to reproduce the issue:

1. Go to https://hanabi.github.io/docs/learning-path/ 
2. In the sidebar, click somewhere else, for example on "How to Join Games"
3. Go back using your browser's back button
4. In the Intro section of the Learning Path page, click on the link to the beginners guide (it leads to https://hanabi.github.io/docs/learning-path/beginner which is wrong)
5. 404

This only happens if https://hanabi.github.io/docs/learning-path/ has the last forward slash. The issue doesn't happen when you start at https://hanabi.github.io/docs/learning-path 

You get to https://hanabi.github.io/docs/learning-path/ (including the forwarf slash at the end) if you click on "Learning Path" on the main page (https://hanabi.github.io/). That is what happened to me and how I ran into that issue.

I don't know if this affects anything else. The other links on the learning path page work just fine. Browser doesn't seem to matter. I tried Chrome, Firefox and Brave.

Unfortunately I don't have the ability to fix this and create a PR. It's just a small thing but maybe someone else wants to look into it and fix it.

**Comment by Zamiell** [comment]
i followed the 4 steps you outlined and i didn't get a 404
can you clarify

**Comment by Zamiell** [comment]
closing since he isn't responding

**Comment by Zamiell** [comment]
oh i think i see the problem, its because the link was "beginner" instead of "beginner.md", it should be fixed now after the website redeploys

thanks for reporting
