### ISSUE TITLE
Redefine Permission to Discard in the Early Game

### ISSUE THREAD

**Issue by EhDrone** [hanabi/hanabi.github.io#918]
Hoping to invoke some additional input / discussion from here:

Currently, PTD is defined as such:

Permission to Discard (PTD)
- Normally, you have to "extinguish" every Play Clue and Save Clue before ending the Early Game.
- However, there are several exceptions, which are listed in the [Extinguishing Every Clue](https://hanabi.github.io/docs/level-8/#extinguishing-every-clue) section.
- The most important exception is that you are not required to clue the hand of the player who came directly before you. Players in this situation can clue the previous player if they want, or they can discard if they want - it's up to them.
- This is because if Alice does not see any Play Clues or Save Clues for Bob to give, then Alice is implicitly giving Bob Permission to Discard (or PTD for short).

I have seen this definition in many games to justify a player discarding to end the early game (in my opinion) extremely prematurely.

--Sample Game-- 
Turn 5, Stack: r1, y0, g0, b1, p0
Clues: 6
Alice: x p2 (b)2 x g5 <- Blue clued by Donald after b1 is played [So play clue on b2]
Bob: x x g2 p3
Cathy: x x y4 g4
Donald: x x x x 
Assumption - all 'x' are non-5, non-playable, non-critical.

Alice has blue 3 to play, and sees nothing to clue in Cathy nor Donalds hand. Alice plays b3 on her turn. 

Per the existing definition, Bob has permission to discard and can choose to discard if they want. I would claim that Bob has permission to discard from Alice, but not from Donald and Cathy, since both players could see that Bob will have a 5 save to give on his turn. Even though Bob, per the doc, can choose to discard - I think that in the above example it would always be a mistake. Of course there will be edge cases where there is an emergency situation and Bob needs to discard - but permission to discard wouldn't be necessary in those situations anyway.

A second example that comes up somewhat frequently:

Turn X: Stack: r2, y2, g3, b1, p0
Clues: 2

Alice: x x x x
Bob: r1, r3, x x g5
Cathy: r2, x x r4
Donald: x x x r1 ---> alternatively, Donald has x x x b4 so chop is not trash, but not playable.

I would argue a valid and good line to lead the team down would be Alice clues 3 to Bob. Bob does not know yellow 3 or red 3 - so Bob plays and it is red 3. Cathy has 1 clue left, and now may choose to discard or save Bob's 5. I think that because Bob's 5 was in-hand when Donald and Alice took their turns, it is fair to rely on Cathy to give a save clue. The reason I gave an alternative Donald hand is that if Donald's chop is trash, it is 'more' likely Cathy saves the 5 - but if it is a non-playable, non-critical unique card - Cathy may feel inclined to take the first discard to try and modulate Donald's discard.

Ultimately - I propose that Permission to Discard to end the early game should be updated to reflect that Bob can choose to give a play or stall clue to a freshly drawn card in Alice's hand, but play / save clues that existed prior to Alice's most recent turn would still be required.

There is always a chance that Alice draws a blocking card (y3 on chop, y2 on stacks, Alice plays b1 and draws the other y3), but often enough there are critical cards or 5s in Alice's hand that can be used as save or stall clues that all players can see are available, and intend to leave for Bob to get - and then Bob ignores it because PTD and loses a potentially playable card.

Finally - if there is a consensus that Bob should still be allowed to discard with PTD from solely Alice's turn, then I hope we can find verbiage to update the doc to state that while Bob is allowed to discard - it is recommended [though not required] that Bob still give the play or save clue unless there are emergency circumstances.

**Comment by Zamiell** [comment]
> I would claim that Bob has permission to discard from Alice, but not from Donald and Cathy, since both players could see that Bob will have a 5 save to give on his turn.

right, but can you be more specific?
what card be okay to discard from Alice's perspective, but not okay to discard from Cathy/Donald's perspective?

the only thing I can think of in this hypothetical is blue 3, which is known to be playable by Cathy/Donald, but not Alice

**Comment by Zamiell** [comment]
contrast that with:

By having the convention where Bob only requires permission to discard from Alice (instead of from Alice + Cathy + Donald), the advantage is:
1) calculating when it is okay to discard becomes much simpler
2) it empowers Bob to aggressively discard if he determines that that is best for the team
3) the risk of discarding an asynchronously playable card is extremely low

**Comment by EhDrone** [comment]
I think that's an accurate summary, but it extends beyond conceptually. One of the goals of the early game is to delay discarding as long as possible to touch as many good cards as we can in part to reduce the risk that we lose the deal due to a bottom deck card. 

Even if Bob's chop is not asynchronously playable, it could still be a useful card that stalling the early game by even 1 more turn would allow to become playable due to Alice's potential play. It happens very frequently that a player discard a 3 when the 1 is played, and then draws the 2 that would make it playable.

**Comment by EhDrone** [comment]
> By having the convention where Bob only requires permission to discard from Alice (instead of from Alice + Cathy + Donald), the advantage is:
The points you mentioned I think are valid - but I think some players take the freedom too far and justify the choice by the definition in the doc. 

How about a smaller step to make easy of calculating PTD simpler - by stating that if Alice has something to save on **chop** [A 5 or a critical card - - 2 saves can become dubious if Cathy or Donald have the other copy], or an existing 5 to stall with prior to Alice's hand then Bob must give the save clue.

**Comment by Zamiell** [comment]
> I would argue a valid and good line to lead the team down would be Alice clues 3 to Bob. Bob does not know yellow 3 or red 3 - so Bob plays and it is red 3. Cathy has 1 clue left, and now may choose to discard or save Bob's 5. I think that because Bob's 5 was in-hand when Donald and Alice took their turns, it is fair to rely on Cathy to give a save clue.

yes, this is the (unwritten) way that we already play.
PTD does not always apply.
if you think that this should be codified as an additional rule, then we could do that (at the risk of adding more complexity), you could type out a proposal

**Comment by Zamiell** [comment]
> I propose that Permission to Discard to end the early game should be updated to reflect that Bob can choose to give a play or stall clue to a freshly drawn card in Alice's hand, but play / save clues that existed prior to Alice's most recent turn would still be required.

seems reasonable, but adds more complexity, is harder to calculate, so I am ambivalent

**Comment by Zamiell** [comment]
> There is always a chance that Alice draws a blocking card (y3 on chop, y2 on stacks, Alice plays b1 and draws the other y3), but often enough there are critical cards or 5s in Alice's hand that can be used as save or stall clues that all players can see are available, and intend to leave for Bob to get - and then Bob ignores it because PTD and loses a potentially playable card.

yeah thats rare enough to ignore for the purposes of this

**Comment by Zamiell** [comment]
> Even if Bob's chop is not asynchronously playable, it could still be a useful card that stalling the early game by even 1 more turn would allow to become playable due to Alice's potential play.

well that isn't relevant.
forcing bob to take an action instead of allowing bob to take the better of two options from his perspective is always strictly worse.
otherwise we could just simplify the conventions and remove the "PTD" clause from the doc entirely, which would subsequently always force bob to clue alice no matter what

**Comment by EhDrone** [comment]
> yes, this is the (unwritten) way that we already play.

Ultimately I agree that it is how **some** of us play this way -- but I have seen multiple members of the community who have either discarded when I was expecting the save clue to come out to Alice from Bob, or have argued after that a certain line was bad because Bob has PTD.

I think adding some sort of statement (even if it's a soft "While Bob does have PTD - we still recommend Bob give any save or play clues in Alice's hand to extend the early game), but I am curious on seeing a consensus here to hopefully point more to if the added complexity seems worth codifying it into the document.

**Comment by pianoblook** [comment]
I'm a strong supporter of adding explicit language that discourages this kind of aggressive discarding. Obviously there are some cases where discarding can be deemed as better for the team, but IMO it should be more of an "opt-out" decision (consciously deciding to go _against_ the conventional agreements) rather than an "opt-in" (i.e. the 'unwritten agreement' to extend early game despite PTD)

**Comment by Zamiell** [comment]
> The points you mentioned I think are valid - but I think some players take the freedom too far and justify the choice by the definition in the doc.

ok, then maybe an explicit convention is needed

> How about a smaller step to make ease of calculating PTD simpler - by stating that if Alice has something to save on chop [A 5 or a critical card - - 2 saves can become dubious if Cathy or Donald have the other copy], or an existing 5 to stall with prior to Alice's hand then Bob must give the save clue.

it is unclear for me to gage which of the following is more complicated:

1) "you have PTD if previous player sees nothing for you to do + has non-fresh cluable cards"
2) "you have PTD if previous player sees nothing for you to do + has savable chop"

feels around the same complexity /shrug

**Comment by Zamiell** [comment]
either way, it is an "exception to an exception" or whatever

**Comment by EhDrone** [comment]
I'll leave this issue open for a bit and just collect some more input from other folks who want to provide and then I will type up an actual proposal for change if it seems to be the consensus. I can type out options for both versions and see which seems less complex or more useful.

**Comment by Zamiell** [comment]
ok, i'd be open to either, seems like most would as well, as this falls into the realm of "documenting how we already play" more than "new convention"

**Comment by Zamiell** [comment]
> I'm a strong supporter of adding explicit language that discourages this kind of aggressive discarding.

ok, which one these two do you prefer?

**Comment by Zamiell** [comment]
> It's somewhat relevant. In my opinion, the true permission to discard is related to Alice playing a card and freshly drawing a playable card or a 5 to do a 5 stall with. Since no one on the team could have expected or predicted Alice's new card would be cluable for Bob, Bob should not ever have to take that card into account to determine if he should discard or clue it.

i 100% agree with this, I just think that this case is more rare than the very-standard case of Bob seeing that Cathy has a red 3 on chop with a red 1 already played, and Bob has an unknown card on his own chop.
in this hypothetical, regardless of what alice drew on her last turn, it is probabilistically very likely that bob has a more desirable discard than the red 3

**Comment by pianoblook** [comment]
lol I also think both are reasonable + would be interested in hearing more folks chime in. Option 2 (being expected to give a chop clue) seems like the simpler option I guess

**Comment by Zamiell** [comment]
will close for now
