### ISSUE TITLE
Levels and variants

### ISSUE THREAD

**Issue by weshuu** [hanabi/hanabi.github.io#924]
For any level that (in the general opinion of the group) enables the play of additional variants that could not be played well before, those variants should be listed in the regular page of that level. Furthermore, variant specific conventions that come with that level should also be listed in the main document of that level.

For example, on the pink variant page:

https://hanabi.github.io/docs/variant-specific/pink#level-8---basic-pink-principles

There are pink conventions associated with levels 8, 9, 10, 12, and 19.

However, on the regular pages for those levels, there is no indication of the pink variant. For example, level 8:

https://hanabi.github.io/docs/level-8

The word "pink" doesn't come up once.

It would be good to know, as we progress through the regular levels, which variants become playable at each level, and which of those variants need special conventions.

**Comment by Zamiell** [comment]
1) the doc does not prescribe a specific mapping of levels to variants, beyond what is listed here: https://hanabi.github.io/docs/learning-path#variant-summary
note that this table is a merely a suggestion.

2) the reason that pink has levels on it is purely a sorting mechanism to split up conventions into chunks based on complexity.
in other words, it is an organizational strategy that helps make the page more coherent.
by no means does pink get "unlocked" upon reaching a certain level - you probably shouldn't be playing pink at all unless you are an expert already.

3) i'm pretty sure it says this on the learning guide page, but in general we recommend that players do not play any variants at all besides no variant & rainbow until they have mastered every single level.

hopefully that clarifies things, you can submit a doc if you feel that the doc needs to be improved in this regard
