### ISSUE TITLE
Skipping over dark suits on mud clues should only apply to null

### ISSUE THREAD

**Issue by newduke** [hanabi/hanabi.github.io#925]
The reason we skip over dark suits in null color positionals does not apply to mud clues.  For a mud clue, all colors are available (sans blockers), so there is no particular difficulty in finding a suitable suit. However, if rightmost clues are the most valuable, then dark suits are actually the best, because there are fewer blockers.

**Comment by Zamiell** [comment]
sounds fine to me

**Comment by Zamiell** [comment]
i will close this once the pr is merged
