### ISSUE TITLE
Red Fix Clue in Omni-One's

### ISSUE THREAD

**Issue by Dr-Kakashi** [hanabi/hanabi.github.io#926]
https://hanab.live/shared-replay/778112#19
![Red Fix Clue](https://user-images.githubusercontent.com/48993588/170148445-6c1cb1ca-89b1-4340-a176-d5902c7ef7fc.jpg)

In Omni-One's variants, Newduke and I have found several issues:
1.  Once an omni one is picked up, it's nearly impossible to tell your teammate their 1 is trash
2. The team has to work around unclued Omni 1's 
3.  The team is forced into a difficult situation where the Omni 1 must be focused or touched, during stall situations

I made the proposal that we should pick a color to signal that the card that's in the player's hand is a trash omni. 
For example, red.

Proposal:
Have 1 color (red) be designated at the start of the game as the signal that the focus is trash. 
This means that red tempo clues are turned off and you must clue red cards with rank to get them to play. 

2 Situations for when this clue can be given:

1. The card touched with red must have been previously touched. 
2. There is context to know the newly touched red card is not playable.

**Comment by Zamiell** [comment]
seems fine, does anyone else care

**Comment by EhDrone** [comment]
Seems like a fine solution to fixing omni-1s. I would agree that focused left-most as a fix clue seems simplest unless anyone has a reason to do something else.

**Comment by Romain672** [comment]
When only two colors are available, fixing with red has an high cost.

**Comment by iamwhoiamhahaha** [comment]
I don't think we need a *Fix Clue* in *Omni-Ones & Colorless Suit (3 Suits)*

**Comment by Romain672** [comment]
How about doing that only if not all cards are taken.
That mean if you have 3 colors, and reclue 3 cards, then red is for the leftmost card.
If you have 3 colors and reclue 2 cards, then red is for (leftmost?) trash.
If you have 4 colors and reclue 4 cards, then red is for leftmost
If you have 4 colors and reclue 3 cards, then red is for (leftmost?) trash.
...

**Comment by Romain672** [comment]
Or, if you push my idea to the maximum and allow others colors for fix:
You first determine how many cards the clue can be positionnal for.
Then you start by the rightmosts colors, and associate one color per card to make them playable (muddy positionnals).
Then with the remaining colors, you start with the leftmosts colors, and you associate one color per card to make them trash.
Then with the remaining colors, you warparound the rightmost colors.
Per example, with 2 cards and 5 colors: (purple is play rightmost, blue is play leftmost) & (red is discard leftmost, yellow is discard rightmost) & (green is play rightmost).

**Comment by iamwhoiamhahaha** [comment]
*Mud Clues* came into my mind when I saw this proposal at the first glance. However, I realized that defining a better form of *Omni-One Fix Clues* and killing the ability to perform a *Mud Clue* is probably not a good idea.

**Comment by Romain672** [comment]
> _Mud Clues_ came into my mind when I saw this proposal at the first glance. However, I realized that defining a better form of _Omni-One Fix Clues_ and killing the ability to perform a _Mud Clue_ is probably not a good idea.

I added two lines about context on my last post. That's exactly what you are already doing with red.
And if you are doing it with red for the leftmost, I don't see the reason why not goes further if you have enough colors.

**Comment by EhDrone** [comment]
A massive goal of the conventions is to keep overhead to a minimum. I haven't given it really any thought - so whether your proposal is optimal or not I haven't thought about - but just reading it seemed overly complicated and massively prone to error, let alone taking away most tempo clues if one is needed.

It seems like if we laid out some complicated "how many colors are available, some mean play, some mean discard, some wrap if available or not" convention list specifically for Omni-One's the mental cost massively outweighs the benefit of the convention.

Considering this was raised because there seemed to be an issue specifically with telling people about trash 1s in the Omni-Ones variant, I don't see a need to develop a solution that branches out into what other possible cards are trash or playable, as they seem extremely rare to ever occur.

**Comment by Zamiell** [comment]
I agree with ADrone. Simple conventions are great!

Kakshi can you do a PR for a simple red-fix clue convention?

**Comment by Zamiell** [comment]
dani do you want to do this

**Comment by NZadeh** [comment]
I guess this is still outstanding... but have we considered dedicating something like a pink (rank) tempo clue to touch good _1s_, and a _Mud Clue_ to identify bad _1s_? Then you have the full power of either for play and for fix...  and both are blocked by the same thing.

(If the discussion was just about trashing unclued 1s, then perhaps red is a reasonable clue to dedicate to trash duty, and cluing trash omni 1s with red can be a priority.)
