### ISSUE TITLE
Positional clue vs double ignition

### ISSUE THREAD

**Issue by Dr-Kakashi** [hanabi/hanabi.github.io#927]
![2022-05-25_02-34-27](https://user-images.githubusercontent.com/48993588/170231604-bfd0fe18-22ca-4163-996f-8d84d4ba93c4.png)

Had an issue in our game that probably needs clarification in the doc

For variants that require positional clues. If the positional clue gets a single-blind play, it is immediately resolved and should never be interpreted as a double ignition. 

2 reasons: 
1. We should interpret the clue that gives the fewest blind plays 1 blind play (positional) vs 2 blind plays (ignition).
2. There may not be another way to get the card to play other than a positional clue

**Comment by Zamiell** [comment]
ping

**Comment by Zamiell** [comment]
closing since kakashi doesn't seem to care
