### ISSUE TITLE
Level quizzes

### ISSUE THREAD

**Issue by weshuu** [hanabi/hanabi.github.io#930]
It would be good to, for each level's document (and the variant specific ones), have a quiz to test the reader's knowledge.

**Comment by GuolinM** [comment]
+1, I'd be interested in helping in the quiz writing effort

**Comment by Zamiell** [comment]
sure, just submit a pr

**Comment by Zamiell** [comment]
https://github.com/hanabi/hanabi.github.io/blob/main/README.md

**Comment by Zamiell** [comment]
closing this for now
