### ISSUE TITLE
Clarification on Taffy Double Bluff

### ISSUE THREAD

**Issue by Dr-Kakashi** [hanabi/hanabi.github.io#938]
https://hanabi.github.io/docs/variant-specific/pink/#the-taffy-double-bluff

Rarely, a player can perform a Taffy Double Bluff by violating Pink Promise on a two-away-from-playable pink card.

This needs to be changed to: 
Rarely, a player can perform a Taffy Double Bluff by violating Pink Promise on a **three**-away-from-playable pink card.

**Comment by Zamiell** [comment]
can you submit a PR?
