### ISSUE TITLE
Convention Proposals: Dupe Tech Theory

### ISSUE THREAD

**Issue by pianoblook** [hanabi/hanabi.github.io#947]
Hello, it's been a while!

I'm excited to share this doc we've been working on refining the past few weeks: here's the full [doc](https://docs.google.com/document/d/1zhFHjb2ChoLEIKn71bd8yKFczy0kn3hStrydRQ_m4NE/edit?usp=sharing)! Our hope is that normalizing - and standardizing - these kinds of actions can be tremendously advantageous for saving random cards. 

I won't *unnecessarily dupe* all the details here, but I'll list the proposed conventions for discussion's sake.

**1. Duplicitous Value Clue & Duplicitous Blind-Plays**
- this would include a *DELETION* of a current convention, the "bluff that causes a blind-play of a known dupe"
 
**2. Assisted Trash Chop Moves (ATCM)**

**3. Time Travel Trash Chop Move** (TTTCM)**

**4. Uncanny Dupe CM**

**5. Unknown Dupe Bad Chop Move Ejection**

Along with a few corollaries / hybrids:

- Dupe Tempo Clue Principle (sometimes TCCMing)

- Uncanny ATCM

- Dupe Clue Compositions (various forms)

---

And finally, it felt only natural to reintroduce our plea to reinstate *Bad Touch Bluffs for 1's and 2's*  (as brought up in #805 )

**Comment by iamwhoiamhahaha** [comment]
I like them! The doc is long but the concept is simple

**Comment by pianoblook** [comment]
Long for sure, lol - we wanted to make sure that we properly laid out the justification / proposed theory behind everything. For one thing that's to help justify the reasonings, but also to promote future exploration as well.

(but if anyone wants to just skip right to the conventions, lol, you can ignore the first 3 pages. Conventions start [here](https://docs.google.com/document/d/1zhFHjb2ChoLEIKn71bd8yKFczy0kn3hStrydRQ_m4NE/edit#heading=h.icnid363co9s)

**Comment by GuolinM** [comment]
🔥🔥🔥

To give perspective from a non-max level player, I feel like many of these are quite intuitive when already playing with bluffs. At the very least, we've already been erring on the side of not promising additional blind plays on duplicitous bluffs/ejections that touch untouchable 3's or 4's (in the absence of the [max level dupe bluff convention](https://hanabi.github.io/docs/extras/special-finesses/#the-bluff-that-causes-a-blind-play-of-a-known-dupe-dupe-bluffs--bluff-dupes) convention

**Comment by Zamiell** [comment]
i haven't had time to look at this.
are you proposing that all of these be added at once?
would it just be better to introduce one at a time?

**Comment by pianoblook** [comment]
> are you proposing that all of these be added at once?
> would it just be better to introduce one at a time?

Most of them are pretty similar + simple, so they'd all be natural inclusions imo. But if I had to weigh their merits:

- The Assisted TCM & Time Travel TCM are slam-dunks.
- The Duplicitous moves are great too, we just need to remember to delete the current [dupe bluff layered finesse](https://hanabi.github.io/docs/extras/special-finesses/#the-bluff-that-causes-a-blind-play-of-a-known-dupe-dupe-bluffs--bluff-dupes) convention
- There **are** two conventions that we marked [Advanced] - the two '_Uncanny_' moves. I could definitely see holding off on adding those to the doc, at least until the community has a chance to get familiar with using the rest of the suite. 
- As for the 'Miscellaneous' section at the end, those are a bit independent from the rest - I can make a separate issue for the _Unknown Dupe BCME_, which just leaves the #805 issue which can also be debated separately.

**Comment by Zamiell** [comment]
ok, can you submit a PR for The Assisted TCM & Time Travel TCM + Duplicitous moves + delete dupe bluff layered finesse

**Comment by pianoblook** [comment]
will do

**Comment by pianoblook** [comment]
Oh actually, before I submit anything I'd be curious what others think about proper Leveling for these moves. I'll share my opinions below, but invite you to form your own opinion before reading on :p


- Duplicitous Moves: lvl 13, since these are basically an inverted form of _Trash Bluff_ logic. Instead of *cluing* a useless card to *play* a good one, you *play* a useless card to *touch* other good one(s).

- Time Travel CMs: 13 or 19. 

- If/when we introduce _Uncanny_ moves, those would 100% be 23. (I chose the word 'Uncanny' as a nod to Unnecessariness).
  

Alternatively - and I kinda hate that I'm suggesting this - we could use these as an excuse to expand levels, lol. 'Dupe Tech' could be a reasonable level 14, in between Trash Moves and Double Bluffs.

**Comment by Zamiell** [comment]
> we could use these as an excuse to expand levels, 'Dupe Tech' could be a reasonable level 14

that seems like the best option

**Comment by T-Hoodie** [comment]
Why does ATCM chop move Cathy and not Bob?
It seems more intuitive to me that it chop moves Bob; and chop moves Cathy only if it was unnecessary (just like normal trash clues)

**Comment by pianoblook** [comment]
> Why does ATCM chop move Cathy and not Bob? It seems more intuitive to me that it chop moves Bob; and chop moves Cathy only if it was unnecessary (just like normal trash clues)

The final ATCM interpretation was unanimously agreed upon by everyone I [surveyed](https://docs.google.com/presentation/d/1is8dcBil7bxgSx-P7zG6ifKq5gLVWgN_YFkLb5TNqOk/edit?usp=sharing) as a CM on Cathy - sounds like you've changed your mind since then?

I'll share my fave explanations some of the surveyed players gave (responding to scenario 3):

1)
> - It signals a Chop Move on Donald (bluffing a duped card is always treated as Unnecessary).
> - If Donald's Chop is trash, Cathy is supposed to eject as a BCME.

2)
> if she is ready to spend an extra clue to get no new card[, from] Donald's POV, this means the 1 clue was important somehow to Alice, which means Donald must treat this as unnecessary trash bluff, and he should cm all cards to the right of the trash

3) 
> Reasoning is the purpose of the clue is not to get b2 (which can be gotten form GD), but to give kt to Donald. Alternative interpretation is layered trash finesse, but cm is good enough imo.

TBF, though, it's also possible to CM Bob at the same time, but that falls under the [Advanced] form ([Uncanny Assisted TCM)](https://docs.google.com/document/d/1zhFHjb2ChoLEIKn71bd8yKFczy0kn3hStrydRQ_m4NE/edit#heading=h.1zl905b3fnw6)

**Comment by T-Hoodie** [comment]
When you asked about the survey, it was still an undefined clue. Also it was clearly unnec in the example, so interpreting only the unnec part seemed the most straightforward to me, because doing undefined things is always scary.

The thing about ATCM is, it gives two player a safe action now: Bob has a play he didnt have before, and Cathy has a discard she didnt have before. So which part was important to the clue giver: That Bob has a safe action, or Cathy, or both? It's not obvious imo. Its just obvious that Cathy should probably cm if it was unnecessary.

**Comment by T-Hoodie** [comment]
Also since Dupe Tech is potentially conflicting with other trash moves, we need to clarify which takes precedence:
e.g. [r2], [y2] on the stacks, Donald has known [r3] in hand.
Alice clues 3 to Cathy, touching r[3]. Is Bob supposed to do nothing, and Alice chop moves? Or is Bob supposed to discharge?
I would argue the ambiguity means Bob has to play slot 3, because Bob could have given the same clue if the team only wants the cm on Cathy. Therefore other trash moves take precedence if the action is not taken from Bluff seat.

If you agree with this, then consequently the Dupe Tech should be introduced after the UTD in the doc. Otherwise players would learn the Dupe Tech like above - only to learn shortly afterwards that those clues no longer work the same way because UTD now takes precedence.

**Comment by pianoblook** [comment]
I agree, based on current/historical playstyles I think Bob would be expected to respond in such a case. Which means it's better for both conventions to be lvl ≥16 (after UTD). 

That's helpful for introducing all the Duplicitous + TT conventions, too, because those have UTD versions as well!

**Comment by vEnhance** [comment]
Closing since #1016 is merged
