### ISSUE TITLE
Bad Chop Move Ejection Trash Definition

### ISSUE THREAD

**Issue by omegaxisJC** [hanabi/hanabi.github.io#954]
Not very common but sometimes people might consider chopmoving a duplicate for redistribution purposes.  However other players can interpret this clue as either a BCME or the card in their hand as not the CMd card.

Was wondering if we can specifically label BCME in the convention docs in terms of trash as cards that can no longer be played at all, instead of cards just "trash", as some people interpret that as cards that are not already in people's clued or CMd cards.

**Comment by Zamiell** [comment]
I agree with this.

since noone else seems to have an opinion, can you submit a PR?

**Comment by pianoblook** [comment]
Agreed - plenty of reasons to preserve a dupe

**Comment by Zamiell** [comment]
i added this:

```
- Note that sometimes, players perform _Chop Moves_ on the other copy of currently clued cards. This can be useful for distribution purposes, meaning that everyone will have a card to play on the final round of the game. For this reason, a _Bad Chop Move Ejection_ can only be triggered when chop moving cards that have been played already.
```
