### ISSUE TITLE
Summary of the conventions

### ISSUE THREAD

**Issue by Romain672** [hanabi/hanabi.github.io#959]
Hi,
How about creating a page 'summary' which would take most conventions, and wrote one line/~10 words to explain it.
It would be for players who know at 80/90% the conventions, and just need a quick refresh to know what to answer/what a specific clue would do?

**Comment by Romain672** [comment]
Like, if you open the page, and search for '5-pull', you will get some quick summary to what happen depending of which card clued.
Actually, if you search for '5-pull' on the doc, you will get like 50 lines of 5 differents conventions. Then need to scroll down to check what you need exactly.

**Comment by Zamiell** [comment]
ok, you can submit a pr

**Comment by Romain672** [comment]
Okay I will do it.
If anyone want to help I started it here: https://docs.google.com/spreadsheets/d/1LECCSBMPYOTKugRKxk69iqRG7fF43-tIJkU4cVSufMQ/edit#gid=0

It will became a page at the end.
Feel free to do any modification for clarity, I just wrote the first sentence I got, I didn't double checked anything, I will do it later.

**Comment by Romain672** [comment]
Since I got no answer, here is where I'm at, without the excel document:
https://textup.fr/643899Me
I really would want some early feedbacks though.

**Comment by Zamiell** [comment]
seems fine

**Comment by Romain672** [comment]
Just add my text into a new page. There still need to do everything else (like doing the links between the page per example), if anyone else can do it: #990

**Comment by Zamiell** [comment]
i'm not a big fan of this since whenever we shuffle the levels around, or add new conventions, or change anything, we have to also change the summary

**Comment by Zamiell** [comment]
which is more maintenance work for me

**Comment by Romain672** [comment]
I guess there should be javascript or similar to get the Titles of sections added and removed automatiquely?
But that's a lot of extra work.

**Comment by Zamiell** [comment]
ok i will close this for now
