### ISSUE TITLE
Level 18: add unknown cards first

### ISSUE THREAD

**Issue by Romain672** [hanabi/hanabi.github.io#964]
https://github.com/hanabi/hanabi.github.io/pull/961
https://hanabi.github.io/docs/level-18/
Hi,
I was wondering there if you could add 'unknown cards' to the table and remove the 'priority finesse'?

**Comment by iamwhoiamhahaha** [comment]
I personally would play into a *Priority Finesse/Bluff* if my teammate plays an unknown card over a known card with the same rank.

```
| 2 | Cards that lead into clued cards in someone else's hand | Otherwise, the team would lose _Tempo_.                |
| 3 | Cards that lead into the player's own hand              | It is bad for a suit to be "held up" on one player.    |
| 4 | 5's                                                     | Playing a 5 gets the team a free clue.                 |
| 5 | The lower rank card                                     | The smaller stacks are more important to fill up.      |
| 6 | Unknown card                                            | Gaining information about an unknown card is valuable. |
| 7 | The left-most card                                      | The left-most card is more likely to be good.          |
```

**Comment by Zamiell** [comment]
what jeff said seems reasonable, so i added that to the doc.
it's a bit confusing though because 6 only wins over 7 if all of the criteria from the section marked as "Special Case" apply.
so remember to always follow the rules of that section
