### ISSUE TITLE
Negative 5's tempo clue

### ISSUE THREAD

**Issue by weshuu** [hanabi/hanabi.github.io#967]
Currently, this page:

https://hanabi.github.io/docs/extras/play-clues

reads:

"Since Negative 5's Tempo Clues only get one card played, they are also Tempo Clue Chop Moves like most other Tempo Clue."

Negative 5's Tempo Clues might occasionally get more than one card played. Suppose you have three 5s in your hand, and of the 5s you can't already see, all but one is playable. If one of your cards is the unplayable color, a clue of that color gets the other two to play.

The page does not make clear whether such a clue should *also* be a chop move on your remaining card. (My feeling is "no" given the efficiency benefits of such a clue.)

**Comment by Zamiell** [comment]
I updated the page to say this:

```
- If a _Negative 5's Tempo Clues_ only gets one card played, then it would also be a _Tempo Clue Chop Move_.
```

thanks
