### ISSUE TITLE
Minor language fix in the beginner's guide

### ISSUE THREAD

**Issue by asimov-io** [hanabi/hanabi.github.io#991]
In https://hanabi.github.io/docs/beginner/clue-interpretation#clue-interpretation-algorithm, it says "Is it a Play Clue or a Save Clue or could it be both ?".
"Both" means that it is a Play Clue and a Save Clue all at once. Here we should say: "or could it be either ?" to indicate that the question still remains. Alternatively, we could say "or could it be any one of them ?". Or completely change it and say "or can we still not know which one it is ?".

**Comment by Zamiell** [comment]
> "Both" means that it is a Play Clue and a Save Clue all at once.

that is the intent of the language.
we think of it similar to e.g. https://en.wikipedia.org/wiki/Quantum_superposition

**Comment by asimov-io** [comment]
But just after that, "Chop clues can be either a Play Clue or a Save Clue" is written. You wouldn't write "both" there.
And in step 3: "Based on whether it is a Play Clue or Save Clue, record all of the possibilities as a card note", it's made clear that it can't be both types at once (whether … or).
But it's not really indicated here that all possibilities in case of a Play *and* all possibilities in case of a Save should be written (i can easily read it as "if it's a Play, record all possibilities for a Playable card, and if it's a Save record all possibilities for a Saved card" but we don't know what to do if it's both/we don't know which it is).

I agree that it's tricky to explain it well before going into detail as it is done in level 3 (https://hanabi.github.io/docs/level-3#information-lock-principle) or in level 5 (https://hanabi.github.io/docs/level-5#schr%C3%B6dingers-cat-principle).

I suggest: "Record (as a *card note*) all possible identities for a Playable card (if it could be a Play Clue) AND all possible identities for a Saved card (if it could be a Save Clue)."

**Comment by Zamiell** [comment]
can you submit a pr

**Comment by asimov-io** [comment]
Will do later today !
