### ISSUE TITLE
Delete The Out-of-Order Corollary

### ISSUE THREAD

**Issue by TheDaniMan** [hanabi/hanabi.github.io#994]
It's not a good convention; sometimes the other cards can be prompted after a bluff, and the receiving player could just have a hand where it's obvious that a fix was not intended. Also, people don't usually play with this.

https://hanabi.github.io/docs/level-19#the-out-of-order-corollary

**Comment by Zamiell** [comment]
i like this convention, and i think that in general, people should assume truth more often, and assuming OOO is a tiny part of that
