### ISSUE TITLE
Rename 'Self color bluff' into 'Self color known bluff'

### ISSUE THREAD

**Issue by Romain672** [hanabi/hanabi.github.io#998]
Hi, it's me again for those kind of rename.
It can look useless, but per example from bga's forum Blacktango said:
"I guess the "bluff" part of this technique’s name doesn't suit me, and didn’t help me to understand it.
Maybe I would call it "self canceling reverse" or "anti reverse" instead, or something like that, because no one is bluffed here."

https://boardgamearena.com/forum/viewtopic.php?t=27148 : but it's a very long discussion.

**Comment by Romain672** [comment]
Personnally, I'm unsure of the rename here.
The 'self' component with the 'color' part should already tell a bluff is impossible, so that could be enough.

I think maybe the discussion is more about what we want for the title of the moves to do.
It should be something short, which tell what the move is about.
And this proposition make it longer, but precise more something (obvious when you know it, but not obvious when you does not).

I'm curious how many moves should be rename if this one is renamed.

**Comment by Romain672** [comment]
This move is a category of move not defined which play not to answer the clue, but to prevent someone else to bomb from that clue. Or at least it's how I see it.
Of course, if no one has to answer the clue, you still need to think if the clue was useless/not good enough or not. And sometimes you can play from it, but for me it's another step.
And both of this point isn't defined for me.

**Comment by jack67889** [comment]
If Bob doesn't play, Cathy will still play into the finesse, just like a normal bluff. You also have variants like white-ones, where you can do an unknown scb. So the naming seems, categorial, on point to me.

**Comment by Romain672** [comment]
In white-ones, it's just a 'bluff' for me. Even if it is with a color which is rare, everything about the bluff apply.

"If Bob doesn't play, Cathy will still play into the finesse, just like a normal bluff." => But the move isn't about Cathy but about Bob.

**Comment by argothiel** [comment]
Embarrassingly, I must admit it also took me a while to understand that this is a known bluff when I first read about this concept. If it were a Self Color Known Bluff, the concept would probably be clearer to me.

**Comment by Romain672** [comment]
I was trying to find pages to define my new term of 'playing an unrelated card as a known bluff to prevent someone else to bomb his card'.
There is lots of situations which are really similar but isn't yet in that definition.
So it look weird to define it.

Here is the three cases I find, but maybe I'm missing more:
Trash bluff: https://hanabi.github.io/docs/level-13/#the-trash-bluff
Self color bluff: https://hanabi.github.io/docs/extras/special-bluffs/#self-color-bluffs-1-for-1-form-scb
Pestilent double bluff: https://hanabi.github.io/docs/level-14#the-pestilent-double-bluff-pdb
Known Pass bluff but it isn't defined

**Comment by Zamiell** [comment]
> if the name serves the purpose of understanding the concept, or does it exist so that we can refer to it during our analysis.

both

i prefer the shorter name for the latter reason
